Создана форма Добавить аудиторию
Students-of-the-city-of-Kostroma/Student-timetable pull request #102
Opened 2019-02-25 18:57 UTC by KudelinRoman

Ветка task-79

2019-02-26 17:07 UTC, YuriSilenok commented on LibOfTimetableOfClasses/CAuditor.cs
> +                    if ((string)table.Rows[i]["Number"] != mAuditor.Number && (string)table.Rows[i]["Building"] != mAuditor.Building)
По условиям Вы должны настроить табуляцию в качестве отступов, найдите письмо с описанием того как сделать это. Выставьте последнюю фигурную скобку в этом файле снова, тогда у вас заменяться отступы на табуляцию.

2019-02-26 17:08 UTC, YuriSilenok commented on TimetableOfClasses/AddTeacher.Designer.cs
> +            this.button1.Size = new System.Drawing.Size(47, 71);
Почему был изменен этот файл?

2019-02-26 17:45 UTC, YuriSilenok commented on TimetableOfClasses/Auditor.cs
> +        private void DataGridAuditor_CellContentClick(object sender, DataGridViewCellEventArgs e)
Зачем был добавлен этот метод?

2019-02-26 17:47 UTC, YuriSilenok commented on TimetableOfClasses/Auditor.Designer.cs
> +            this.ClientSize = new System.Drawing.Size(497, 308);
Почему изменился размер формы?

2019-02-26 17:51 UTC, YuriSilenok commented on TimetableOfClasses/Auditor.cs
> +            DataGridAuditor.AutoGenerateColumns = false;
Почему были добавлены эти две строки?

2019-02-26 17:57 UTC, YuriSilenok requested changes
Здравствуйте.
- Вы не указали в описании запроса на слияние ссылку на задачу
- Не все файлы относящиеся к форме Добавить аудиторию были добавлены в коммит.

2019-02-26 18:31 UTC, KudelinRoman commented
Здравствуйте.
Их не надо было добавлять в коммит?
Спасибо.
Куделин Роман.
17-ИСбо-2б.

вт, 26 февр. 2019 г. в 20:57, Юрий Силенок <notifications@github.com>:

> *@YuriSilenok* requested changes on this pull request.
>
> Здравствуйте.
>
>    - Вы не указали в описании запроса на слияние ссылку на задачу
>    - Вы все файлы относящиеся к форме Добавить аудиторию были добавлены в
>    коммит.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/102#pullrequestreview-208114683>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AtIND0JgFAhCNsQ7Ff4eH0_0zLVNoocmks5vRXWKgaJpZM4bQjVb>
> .
>

2019-02-27 18:02 UTC, YuriSilenok commented
Здравствуйте.

Кого их?

Спасибо.

2019-02-28 21:15 UTC, KudelinRoman commented
Здравствуйте.
" Кого их?"
Все файлы относящиеся к форме Добавить аудиторию.
Спасибо.
Куделин Роман.
17-ИСбо-2б.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.ru
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

ср, 27 февр. 2019 г. в 21:02, Юрий Силенок <notifications@github.com>:

> Здравствуйте.
>
> Кого их?
>
> Спасибо.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/102#issuecomment-467967024>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AtIND_BPxbelCgEPMZjjSzI2Eff06VCOks5vRshIgaJpZM4bQjVb>
> .
>

2019-03-01 19:49 UTC, YuriSilenok commented
Здравствуйте.
- Зайдите в запрос в слияние, посмотрите как выглядит Ваше письмо
- Есть файлы которые Вы не должны были добавлять
- Есть файлы которые должны были добавиться.
Итог. Есть много вопросов по коду и общие вопросы. Пожалуйста, задавайте вопросы более конкретнее. Проверьте Ваш репозиторий командой `git status`. убедитесь что все нужные файлы были добавлены.
Спасибо.

2019-03-03 18:38 UTC, YuriSilenok requested changes
Здравствуйте, обратите внимание на существующие вопросы.

2019-03-03 18:38 UTC, YuriSilenok commented on LibOfTimetableOfClasses/CAuditor.cs
> +        public override bool Delete(Model model)
Зачем Вы реализовали этот  метод?

2019-03-04 20:07 UTC, KudelinRoman commented
Здравствуйте.
Мне нужно создавать новый запрос?
Спасибо.
Куделин Роман.
17-ИСбо-2б.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.ru
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

пн, 4 мар. 2019 г. в 17:33, Буров Илья <notifications@github.com>:

> Closed #102
> <https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/102>
> .
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/102#event-2178064434>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AtIND7i84N8ed0hSnGGUl_q4Ccj4_B7wks5vTS6-gaJpZM4bQjVb>
> .
>

2019-03-05 07:07 UTC, YuriSilenok commented
Нет, еще есть возможность открыть этот запрос.

2019-03-05 07:52 UTC, KudelinRoman commented on LibOfTimetableOfClasses/CAuditor.cs
> +        public override bool Delete(Model model)
Я не реализовывал этот метод.

2019-03-05 18:01 UTC, YuriSilenok commented on LibOfTimetableOfClasses/CAuditor.cs
> +        public override bool Delete(Model model)
Но тем не менее он у Вас появился. 
Я думаю это результат того что вы копировали файл из ветки Testing но не из того коммита, откуда была пущена Ваша ветка. То есть, уже кто-то реализовал и слили изменения в ветку Testing. Вам нужно это затереть новым коммитом. Что у Вас получается всегда можете увидеть на вкладке **[Files changed](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/102/files)**

2019-03-08 19:21 UTC, KudelinRoman commented on LibOfTimetableOfClasses/CAuditor.cs
> +        public override bool Delete(Model model)
Здравствуйте, я затер этот метод.

2019-03-09 10:46 UTC, YuriSilenok commented
Здравствуйте.
Так как работа у Вас продвигается не быстро, то параллельно Вам было сделано много коммитов, это привело к тому что уже непонятно где чьи изменения.
Для того что бы решить эту проблему, вам нужно выполнить перемещение вашей ветки к последнему коммиту ветки Testing.
Для этого Вам нужно выполнить несколько команд и решить возникающие проблемы.
```
git pull
git checkout task-79
git  rebase Testing
git status
```
Вы увидите файлы  с пометкой **both modidied:** . На скрине в синем прямоугольнике.
В этих файлах существуют конфликты. Красной стрелкой показана стадия переноса ветки.
Вам нужно решить конфликты, проверить что ничего не сломалось и закомитить.
После чего Вы продолжаете перенос ветки командой `git rebase --continue`
Когда перенос будет закончен и Вы убедились что в проекте ничего не сломалось, нужно отправить изменения на удаленный репозиторий. 
Я не уверен что об этом получу автоматическое уведомление, так что следите за временем моего ответа после вашей заливки.
![image](https://user-images.githubusercontent.com/14871471/54070406-c4fa0200-4270-11e9-868f-aad648247ec7.png)

2019-03-09 22:02 UTC, KudelinRoman commented
Здравствуйте, у меня возникла проблема
![image](https://user-images.githubusercontent.com/47320335/54077764-3025f180-42ce-11e9-8704-48ed1d5c3945.png)
Как решать конфликты?
Просто использовать команду git add?

2019-03-12 10:10 UTC, YuriSilenok commented
Точно так же как Вы это делали в ЛР02

2019-03-17 13:35 UTC, KudelinRoman commented
Здравствуйте.
я решил конфликты.
Спасибо.
Куделин Роман,
17-ИСбо-2б.

вт, 12 мар. 2019 г. в 13:10, Юрий Силенок <notifications@github.com>:

> Точно так же как Вы это делали в ЛР02
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/102#issuecomment-471937265>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AtIND0iZNoGsOpj517uxCHNocPlLTqC5ks5vV30sgaJpZM4bQjVb>
> .
>

2019-03-20 19:55 UTC, YuriSilenok commented on TimetableOfClasses/TimetableOfClasses.csproj
> -</Project>
В этом месте была испорчена конфигурация проекта

2019-03-20 19:56 UTC, YuriSilenok requested changes
решение конфликта выполнена с ошибками.

2019-03-21 19:19 UTC, KudelinRoman commented
Что теперь делать? 
Всё заново?

2019-03-25 21:14 UTC, KudelinRoman commented on TimetableOfClasses/TimetableOfClasses.csproj
> -</Project>
Здравствуйте. Что теперь делать? Как это можно исправить?

2019-04-01 13:51 UTC, YuriSilenok commented on TimetableOfClasses/TimetableOfClasses.csproj
> -</Project>
@KudelinRoman Вам нужно руками исправить этот файл и сделать коммит в вашей ветке.

2019-04-02 20:07 UTC, KudelinRoman commented
Здравствуйте, я исправил этот файл.
Теперь всё работает.
Спасибо.

2019-04-05 08:09 UTC, YuriSilenok commented
Об исправлениях можно не писать, система оповещает о каждом номом коммите после мой проверки.

2019-04-05 08:14 UTC, YuriSilenok approved these changes
Приступайте к решению конфликта

2019-04-05 18:46 UTC, KudelinRoman commented
Здравствуйте, я разрешил конфликты.
Там присутствуют ошибки в классе "CHEI"
Данный класс я не трогал.
От куда появились ошибки не знаю.
Спасибо.

2019-04-06 14:29 UTC, YuriSilenok commented
Здравствуйте,
Предоставьте скрин ошибок. 
Спасибо.

2019-04-06 18:22 UTC, KudelinRoman commented
Здравствуйте.
Скрин ошибок ветки task-79:
![image](https://user-images.githubusercontent.com/47320335/55673524-b32c6e80-58b1-11e9-9392-e6f631551de5.png)
В ветке Testing так же имеются две эти ошибки 
Скрин: 
![image](https://user-images.githubusercontent.com/47320335/55673550-07cfe980-58b2-11e9-96c8-7aef726778cf.png)
Спасибо.

2019-04-08 04:11 UTC, YuriSilenok commented
Покажите Вашу ветку Testing как на мое скрине.
Не забудьте выполнить командку git pull, Пока вы делаете свою задачу, в ветке Testing могут добавляться и другие коммиты.
![image](https://user-images.githubusercontent.com/14871471/55698075-e7488200-59cc-11e9-9600-ae90eaa47bb8.png)

2019-04-08 17:00 UTC, YuriSilenok commented
Я нашел то, о чем Вы говорили, исправления применил.

2019-04-08 17:05 UTC, YuriSilenok commented
Что бы получить исправления этого файла вам нужно выполнить несколько команд

```
git checkout task-79
git checkout Testing LibOfTimetableOfClasses/CHEI.cs
```
После этого нужно сделать коммит и выгрузить изменения

2019-04-08 20:12 UTC, KudelinRoman commented
Здравствуйте, я выполнил эти команды затем разрешил возникшие конфликты.
Спасибо.

2019-04-09 04:52 UTC, YuriSilenok commented
Кнопка добавить закрывает данные таблицы.
![image](https://user-images.githubusercontent.com/14871471/55774058-46c19300-5a9c-11e9-9d62-19363d402f79.png)
Посмотрите как это сделано в других формах.
![image](https://user-images.githubusercontent.com/14871471/55774097-71abe700-5a9c-11e9-9046-465d793e4d35.png)

2019-04-12 20:15 UTC, KudelinRoman commented
Здравствуйте, я исправил.
Спасибо.

2019-04-19 19:29 UTC, KudelinRoman commented
Здравствуйте @YuriSilenok, мне приступать к разрешению конфликтов? 
Если да то какие изменения оставлять? Которые были в моей ветке или в ветке тестинг?

2019-04-23 17:51 UTC, closed without merging

2019-04-23 18:50 UTC, YuriSilenok commented
@Parallusion нужно добавить комментарий о причине закрытия запроса на слияние

2019-04-24 06:16 UTC, Parallusion commented
Эта задача уже реализована в спринте.