Исправиk сбои в автотестах расположенных в файле UT_Update_CTeacher
Students-of-the-city-of-Kostroma/Student-timetable pull request #1063
Opened 2019-06-09 23:13 UTC by DenisSavelev

#1036

2019-06-11 12:40 UTC, YuriSilenok requested changes
Автотесты не соответсву тестовым сценариям.

2019-06-19 09:16 UTC, DenisSavelev commented
> Автотесты не соответсву тестовым сценариям.

Возможно исправил

2019-06-19 11:16 UTC, YuriSilenok requested changes
Посмотрите на замечания и вопросы

2019-06-19 11:16 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +		public string degree(string a, string b)
комментарий для метода

2019-06-19 11:16 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +		public string Title(string a, string b)
комментарий для метода

2019-06-19 11:16 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
>  		{
комментарий для метода ///

2019-06-19 11:16 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
>  		public void Task_247_1()//изменение когда атрибуты не повторяются (ФИО изменить не возможно)
Перенести комментарии в шаблон ///

2019-06-19 11:16 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
>  			RefData.CTeacher.Insert(tcher1);
Добавить проверки возврощаемого результата для методов Insert

2019-06-19 11:16 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +			bool expected = false;
Почему изменился ожидаемый результат?

2019-06-19 11:16 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +			bool expected = false;
Почему изменился ожидаемый результат?

2019-06-19 11:16 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
>  			RefData.CTeacher.Insert(tcher1);
Добавить проверки возврощаемого результата для методов Insert

2019-06-20 09:42 UTC, DenisSavelev commented
> Посмотрите на замечания и вопросы

Исправил

2019-06-20 14:12 UTC, YuriSilenok reviewed
Смотрите на замечания

2019-06-20 14:12 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +            RefData.CAcademicDegree.Insert(ma);
Нужна проверка на то, что добавление было удачным

2019-06-20 14:12 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +            return ma.Reduction;
Нужна проверка на то, что добавление было удачным

2019-06-20 14:12 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +            RefData.CTeacher.Insert(tcher);
Нужна проверка на то, что добавление было удачным

2019-06-20 14:12 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +            RefData.CTeacher.Insert(tcher1);
Нужна проверка на то, что добавление было удачным

2019-06-20 14:12 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +    [TestClass]
в качестве отступов используются пробелы, должна табуляция.

2019-06-20 22:57 UTC, DenisSavelev commented
> Смотрите на замечания

Исправил

2019-06-20 22:57 UTC, DenisSavelev commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +    [TestClass]
Возможно, в 321 аудитории не настроен Visual Studio

2019-06-21 13:52 UTC, DenisSavelev commented
> Смотрите на замечания

Какие сроки есть на выполнение этой задачи?

2019-06-21 20:13 UTC, YuriSilenok reviewed
Одно замечание, в остальном нормально

2019-06-21 20:13 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +			bool actual2 = RefData.CTeacher.Insert(tcher1);
Тест должен прерываться сразу, если ожидаемый результат не совпадает с фактическим результатом.
`Assert.AreEqual(expected, actual1);`

2019-06-21 20:14 UTC, DenisSavelev commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +			bool actual2 = RefData.CTeacher.Insert(tcher1);
Не совсем понял, что исправить

2019-06-21 20:20 UTC, DenisSavelev commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +			bool actual2 = RefData.CTeacher.Insert(tcher1);
> Тест должен прерываться сразу, если ожидаемый результат не совпадает с фактическим результатом.
> `Assert.AreEqual(expected, actual1);`

Возможно понял, сначала проверка на добавление?

2019-06-21 20:27 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +			bool actual2 = RefData.CTeacher.Insert(tcher1);
тест сам прервется, главное вызывать метод AreEqual сразу после получения фактического результата.

2019-06-21 20:29 UTC, DenisSavelev commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +			bool actual2 = RefData.CTeacher.Insert(tcher1);
> тест сам прервется, главное вызывать метод AreEqual сразу после получения фактического результата.

Я залил изменения

2019-06-21 20:29 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +			bool actual2 = RefData.CTeacher.Insert(tcher1);
почти, но не так:
- инсерт
- проверка 
- инсерт
- проверка

2019-06-21 20:30 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +			bool actual2 = RefData.CTeacher.Insert(tcher1);
а у вас 
- инсерт
- инсерт
- проверка
- проверка

2019-06-21 20:31 UTC, YuriSilenok reviewed
почти

2019-06-21 20:33 UTC, DenisSavelev commented
> почти

Исправлено

2019-06-21 20:36 UTC, YuriSilenok approved these changes
мерж и удаление ветки

2019-06-21 20:36 UTC, merged

2019-06-21 20:38 UTC, DenisSavelev commented
> мерж и удаление ветки

Выполнено