Исправлен сбой в автотесте расположенном в файле UT_Delete_CGroup
Students-of-the-city-of-Kostroma/Student-timetable pull request #1076
Opened 2019-06-10 09:11 UTC by DariaMann

[#1065](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/1065)

2019-06-11 12:34 UTC, YuriSilenok requested changes
- настроить идентификацию коммитов
- настроить отступы на табуляцию
- сбои UnitTestOfTimetableOfClasses.UT_Deleted_CTeacher.Task_248_1() воспроизводится

2019-06-12 18:50 UTC, DariaMann commented
Здравствуйте, @YuriSilenok 

К проблеме "сбои UnitTestOfTimetableOfClasses.UT_Deleted_CTeacher.Task_248_1() воспроизводится"
Почему вы указали UT_Deleted_CTeacher если данный таск относится к UT_Deleted_CGroup?

Спасибо.

2019-06-18 11:22 UTC, YuriSilenok requested changes
Ответил устно

2019-06-26 13:48 UTC, YuriSilenok commented
Если активности не будет в течении 7 дней, запрос будет закрыт а задача снята.

2019-07-03 14:12 UTC, YuriSilenok commented
запрос закрыт по неактивности

2019-07-03 14:12 UTC, closed without merging