Исправлены сбои в тестах расположенных в файле UT_Update_CGroup
Students-of-the-city-of-Kostroma/Student-timetable pull request #1079
Opened 2019-06-10 09:17 UTC by MaximTrapeznikov

#1066

2019-06-11 12:32 UTC, YuriSilenok requested changes
- настроить идентификацию коммитов
- настроить отступы на табуляцию

2019-06-12 11:32 UTC, MaximTrapeznikov commented
Здравствуйте, @YuriSilenok .

Сценарии исправлены.

Спасибо.

2019-06-12 14:52 UTC, YuriSilenok requested changes
- номера автотестов не совпадают с номерами тестами в таблице сценариев
- перенести комментарии в правильный формат /// при этом описание автотестах должно совпадать с описанием тестового сценария из таблицы

2019-06-14 16:57 UTC, YuriSilenok requested changes
- Тестовые сценарии не обновлены в соответсвии с автотестами. Текущий прекондишен перенести перенести в шаги, а то, что добавили Вы, записать в прекондишен.

2019-06-18 12:00 UTC, MaximTrapeznikov commented
https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1079#pullrequestreview-250017052
[Исправлено](https://docs.google.com/spreadsheets/d/113wjRI9iZ3VcwojsnDKf15tTzlalq_Lynckp6ReCelw/edit#gid=0)

2019-06-18 13:51 UTC, YuriSilenok requested changes
Появились сбои в автотестах

2019-06-26 13:48 UTC, YuriSilenok commented
Если активности не будет в течении 7 дней, запрос будет закрыт а задача снята.

2019-07-03 14:15 UTC, YuriSilenok commented
запросм закрыт по неактивности

2019-07-03 14:15 UTC, closed without merging