Исправлен сбой в автотесте UnitTestOfTimetableOfClasses.UT_Delete_CEnclosures.task_395_1()
Students-of-the-city-of-Kostroma/Student-timetable pull request #1081
Opened 2019-06-10 09:32 UTC by bormolei

#1007

2019-06-11 12:29 UTC, YuriSilenok requested changes
- настроить и заменить отсупы на табуляцию
- настроить идентификацию gitgub

2019-06-18 11:48 UTC, YuriSilenok reviewed
ответил устно

2019-06-18 12:08 UTC, YuriSilenok approved these changes

2019-06-18 17:02 UTC, YuriSilenok commented
мне все же кажется что вы скопировали часть файлов и теперь у вас конфликты между одинаковыми участками кода.
Обратите внимание на комментарий в основной задаче.

2019-06-18 17:03 UTC, YuriSilenok reviewed
мне все же кажется что вы скопировали часть файлов и теперь у вас конфликты между одинаковыми участками кода.
Обратите внимание на комментарий в основной задаче.

2019-06-26 13:49 UTC, YuriSilenok commented
Если активности не будет в течении 7 дней, запрос будет закрыт а задача снята.

2019-07-01 16:15 UTC, bormolei commented
Добрый день.


Прошу дополнительное время по данному заданию
<https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1081>,
т.к. у меня возникли проблемы с ноутбуком (полетел HDD)

Спасибо.

Комаров Виктор.


ср, 26 июн. 2019 г. в 16:49, Юрий Силенок <notifications@github.com>:

> Если активности не будет в течении 7 дней, запрос будет закрыт а задача
> снята.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1081?email_source=notifications&email_token=ALD6STNKVVC2M7OOVRVTRVLP4NXVRA5CNFSM4HWR4QK2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYTSVWA#issuecomment-505883352>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALD6STJ35OHKLUCOGUWBGXTP4NXVRANCNFSM4HWR4QKQ>
> .
>

2019-07-01 16:32 UTC, YuriSilenok commented
Комментарий так же является активностью.

2019-07-08 05:36 UTC, YuriSilenok commented
Если активности не будет в течении 7 дней, запрос будет закрыт а задача снята

2019-07-17 12:19 UTC, YuriSilenok commented
запрос закрыт

2019-07-17 12:19 UTC, closed without merging