В справочнике Дисциплина можно ввести одинаковое количество символов в полях Полное название и Краткое название
Students-of-the-city-of-Kostroma/Student-timetable pull request #1094
Opened 2019-06-18 07:31 UTC by Proffet78

#1038

2019-06-18 10:35 UTC, YuriSilenok requested changes
Изменения не соответствуют заданию

2019-06-18 10:35 UTC, YuriSilenok commented on TimetableOfClasses/AddDiscipline.cs
> +			bool itsupdate = false;
зачем эта переменная?

2019-06-18 10:35 UTC, YuriSilenok commented on TimetableOfClasses/AddDiscipline.cs
> +		bool itsupdate = false;
зачем эта переменная?

2019-06-18 10:35 UTC, YuriSilenok commented on TimetableOfClasses/AddDiscipline.cs
> +			itsupdate = true;
зачем эта переменная?

2019-06-18 10:35 UTC, YuriSilenok commented on TimetableOfClasses/AddDiscipline.cs
> +	{
Добавлен пробел, зачем?

2019-06-26 13:47 UTC, YuriSilenok commented
Если активности не будет в течении 7 дней, запрос будет закрыт а задача снята.

2019-07-01 19:09 UTC, halfer4444 commented
@YuriSilenok  Я rebase'нул ветку task-1038 на основе Testing с последующим решением конфликтов, исправил баг, но залить в удаленный репозиторий мои изменения не могу. Возникает ошибка, пишет что-то типа "ваша ветка очень старая".

2019-07-02 06:51 UTC, YuriSilenok commented
> Я rebase'нул ветку task-1038 на основе Testing

Как-то двояко можно понять. Можно немного конкретнее, какой командой вы сделали rebase ?

> Возникает ошибка, пишет что-то типа "ваша ветка очень старая".

Допустим rebase Вы сделали правильно, и вам гит написал что Ваш локальный репозиторий устарел, вы пробовали получить последние изменения командой git pull?

2019-07-02 14:23 UTC, halfer4444 commented
@YuriSilenok  Делал rebase потому что нет в этой ветке mDiscipline.Fullname и mDiscipline.Shortname
![1](https://user-images.githubusercontent.com/52164390/60520469-1f224580-9cee-11e9-9142-f862b0f86945.jpg)

2019-07-02 15:43 UTC, YuriSilenok commented
- на данный момент ветка task-1038 пущена от ветки 17-ISbo-2b. Это не правильно, она должна быть пущена от ветки Testing. Для это потребуется команда rebase. Думаю в ветке Testing все будет.
- запрос на слияние вкетки task-1038 осуществляться в ветку Testing.  Измените это в текущем запросе.

2019-07-02 16:19 UTC, closed without merging

2019-07-02 16:28 UTC, halfer4444 commented
Pull request был закрыт всвязи с необходимостью пересоздания ветки

2019-07-02 16:52 UTC, YuriSilenok commented
запрос закрыт для пересоздания ветки от правильной ветки