Создал справочник "Учебная неделя"
Students-of-the-city-of-Kostroma/Student-timetable pull request #1100
Opened 2019-06-20 18:30 UTC by DemiKor

#798

2019-06-21 17:30 UTC, YuriSilenok reviewed
Пару мест вызвали вопросы

2019-06-21 17:30 UTC, YuriSilenok commented on LibOfTimetableOfClasses/RefData.cs
> -#pragma warning restore IDE0044 // Добавить модификатор только для чтения
Почему эти строки были удалены?

2019-06-21 17:30 UTC, YuriSilenok commented on TimetableOfClasses/AddStudyWeek.cs
> +		/// Здесь должны быть комментарии
Напишите их

2019-06-23 08:22 UTC, DemiKor commented on LibOfTimetableOfClasses/RefData.cs
> -#pragma warning restore IDE0044 // Добавить модификатор только для чтения
Сверху продублировано то же самое

2019-06-23 08:24 UTC, DemiKor reviewed
код ревью

2019-06-23 08:25 UTC, DemiKor commented on TimetableOfClasses/AddStudyWeek.cs
> +		/// Здесь должны быть комментарии
Ненужный кусок кода, удалил

2019-06-23 12:28 UTC, YuriSilenok commented on LibOfTimetableOfClasses/RefData.cs
> -#pragma warning restore IDE0044 // Добавить модификатор только для чтения
Не верно. Одни начинают игнорировать сообщения. Другие завершают игнорировать сообщение. Обратно внимание на третье слово.

2019-06-23 18:15 UTC, DemiKor reviewed
Поправки

2019-06-23 18:15 UTC, DemiKor commented on LibOfTimetableOfClasses/RefData.cs
> -#pragma warning restore IDE0044 // Добавить модификатор только для чтения
Вернул обратно

2019-06-23 18:38 UTC, YuriSilenok approved these changes
мержите, основную задачу на меня.

2019-06-23 18:39 UTC, YuriSilenok requested changes
нет

2019-06-23 18:39 UTC, YuriSilenok commented
у вас в азуре ошибки

2019-06-23 18:40 UTC, YuriSilenok commented
![image](https://user-images.githubusercontent.com/14871471/59980500-890c6200-95ff-11e9-860f-13dbfab28a34.png)

2019-06-24 13:14 UTC, YuriSilenok requested changes
В остальном все хорошо.
Запустить проект и проверить отображение формы пока не могу.
Возможно завтра будет ресурс на это.
Пожалуйста, пока поправьте отступ в комментарии.

2019-06-24 13:14 UTC, YuriSilenok commented on LibOfTimetableOfClasses/CHEI.cs
>  	public class CHEI : Controller, IController
Поправить отступы

2019-06-24 19:52 UTC, DemiKor reviewed
Подправил отступы

2019-06-26 12:21 UTC, YuriSilenok reviewed
Не смог открыть Вашу форму, в меню српавочнике нет такого пункта.
![image](https://user-images.githubusercontent.com/14871471/60179281-657b2e80-982e-11e9-994a-d5f9930909fb.png)

2019-06-27 20:46 UTC, DemiKor commented
Добавил

2019-06-28 07:05 UTC, YuriSilenok submitted a review, later dismissed
У Вас незначительные замечания,
можете приступать к слиянию.

2019-06-28 07:05 UTC, YuriSilenok commented on TimetableOfClasses/Start.cs
> +    }
Пробелы
![image](https://user-images.githubusercontent.com/14871471/60322559-d5a1c580-9990-11e9-9922-339d8a5a5a26.png)

2019-06-28 07:05 UTC, YuriSilenok commented on LibOfTimetableOfClasses/CHEI.cs
> + 	/// </summary>
первый символ в этих двух строках, пробел
![image](https://user-images.githubusercontent.com/14871471/60322461-95424780-9990-11e9-9dba-7f56804e2727.png)

2019-06-29 08:41 UTC, DemiKor reviewed
убрал пробелы

2019-06-30 20:07 UTC, YuriSilenok approved these changes

2019-07-01 06:30 UTC, merged

2020-06-25 13:08 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-26 05:06 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-27 05:06 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-27 05:13 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-28 05:05 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-28 05:13 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-29 05:06 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-29 05:14 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-30 05:05 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-01 05:06 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-02 05:05 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-03 05:04 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-03 13:16 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-04 05:03 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-05 05:03 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 05:03 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 13:03 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 14:23 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 15:25 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 15:27 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 15:49 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-07 05:03 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-08 05:03 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-09 05:03 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-10 05:03 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-11 05:03 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-11 06:17 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче