Task 998
Students-of-the-city-of-Kostroma/Student-timetable pull request #1106
Opened 2019-06-25 08:57 UTC by ZEUS4942

Вот ссылка на основной таск.
https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/998

2019-06-26 12:17 UTC, YuriSilenok requested changes
- Ваша ветка должна была пойти от ветки Testing. Она у Вас пущена от master
- название запроса на слияние должно соответсвовать названию основного таска, с тем отличием, что отвечает на просто что сделано (в прошедшем времени)
- название транслитом не допускаются. В ветке тестинг уже существует форма с именем Characteristic

Что делать?

- Закрыть этот запрос.
- [удалить Вашу ветку](https://www.shellhacks.com/ru/git-delete-branch-local-remote/) и создать новую от ветки Testing.

2019-06-27 10:55 UTC, ZEUS4942 commented
Объясните пожалуйста по поводу Charakteristik. Не понял этот пункт.

2019-06-27 11:00 UTC, closed without merging

2019-06-27 11:38 UTC, ZEUS4942 commented
И ещё вопрос.
Если я создаю ветку task-998 от ветки Testing, то я не могу изменять Windows form-ы.
и как тогда мне быть?

2019-06-27 12:32 UTC, YuriSilenok commented
Впервые слдышу о таком ограничении.

2020-06-25 13:08 UTC, YuriSilenok commented
Пожалуйста, измените заголовок на более детальный

2020-06-26 05:06 UTC, YuriSilenok commented
Пожалуйста, измените заголовок на более детальный

2020-06-27 05:06 UTC, YuriSilenok commented
Пожалуйста, измените заголовок на более детальный

2020-06-27 05:13 UTC, YuriSilenok commented
Пожалуйста, измените заголовок на более детальный

2020-06-28 05:05 UTC, YuriSilenok commented
Пожалуйста, измените заголовок на более детальный

2020-06-28 05:13 UTC, YuriSilenok commented
Пожалуйста, измените заголовок на более детальный

2020-06-29 05:06 UTC, YuriSilenok commented
Пожалуйста, измените заголовок на более детальный

2020-06-29 05:14 UTC, YuriSilenok commented
Пожалуйста, измените заголовок на более детальный

2020-06-30 05:05 UTC, YuriSilenok commented
Пожалуйста, измените заголовок на более детальный

2020-07-01 05:05 UTC, YuriSilenok commented
Пожалуйста, измените заголовок на более детальный

2020-07-02 05:05 UTC, YuriSilenok commented
Пожалуйста, измените заголовок на более детальный

2020-07-03 05:04 UTC, YuriSilenok commented
Пожалуйста, измените заголовок на более детальный

2020-07-03 13:16 UTC, YuriSilenok commented
Пожалуйста, измените заголовок на более детальный

2020-07-04 05:03 UTC, YuriSilenok commented
Пожалуйста, измените заголовок на более детальный

2020-07-05 05:03 UTC, YuriSilenok commented
Пожалуйста, измените заголовок на более детальный

2020-07-06 05:03 UTC, YuriSilenok commented
Пожалуйста, измените заголовок на более детальный

2020-07-06 13:03 UTC, YuriSilenok commented
Пожалуйста, измените заголовок на более детальный

2020-07-06 14:23 UTC, YuriSilenok commented
Пожалуйста, измените заголовок на более детальный

2020-07-06 15:25 UTC, YuriSilenok commented
Пожалуйста, измените заголовок на более детальный

2020-07-06 15:27 UTC, YuriSilenok commented
Пожалуйста, измените заголовок на более детальный

2020-07-06 15:49 UTC, YuriSilenok commented
Пожалуйста, измените заголовок на более детальный

2020-07-07 05:03 UTC, YuriSilenok commented
Пожалуйста, измените заголовок на более детальный

2020-07-08 05:03 UTC, YuriSilenok commented
Пожалуйста, измените заголовок на более детальный

2020-07-09 05:03 UTC, YuriSilenok commented
Пожалуйста, измените заголовок на более детальный

2020-07-10 05:03 UTC, YuriSilenok commented
Пожалуйста, измените заголовок на более детальный

2020-07-11 05:03 UTC, YuriSilenok commented
Пожалуйста, измените заголовок на более детальный

2020-07-11 06:17 UTC, YuriSilenok commented
Пожалуйста, измените заголовок на более детальный

2020-07-11 10:44 UTC, YuriSilenok commented
Пожалуйста, измените заголовок на более детальный