Исправлена ошибка, когда в справочнике "Ученая степень" можно добавить "Краткое название" длиннее "Полное название"
Students-of-the-city-of-Kostroma/Student-timetable pull request #1112
Opened 2019-06-27 09:02 UTC by litdex

#1047

2019-06-27 12:31 UTC, YuriSilenok requested changes
Есть замечания

2019-06-27 12:31 UTC, YuriSilenok commented on TimetableOfClasses/AcademicDegree.cs
> +        private void DG_AcademicDegree_CellContentClick(object sender, DataGridViewCellEventArgs e)
с какой целью добавлен этот метод?

2019-06-27 12:31 UTC, YuriSilenok commented on TimetableOfClasses/AddAcademicDegree.cs
> +                        if (FullName.Text.Length >= Reduction.Text.Length)
настройте сизуал студию на табуляцию в качестве отсупов. Заменить пробелы на табуляцию.

2019-06-27 12:56 UTC, litdex commented
@YuriSilenok исправлено

2019-06-27 13:26 UTC, YuriSilenok reviewed
стнова пробелы

2019-06-27 13:26 UTC, YuriSilenok commented on TimetableOfClasses/AcademicDegree.Designer.cs
> +            this.DG_AcademicDegree = new System.Windows.Forms.DataGridView();
Пробелы заменить на табуляцию

2019-06-27 13:26 UTC, YuriSilenok commented on TimetableOfClasses/AcademicDegree.cs
> +    }
пробелы заменить на табуляцию, пожалуйста настройе VS, она сама все сделает

2019-06-27 13:26 UTC, YuriSilenok commented on TimetableOfClasses/AddAcademicDegree.cs
> +				    if (FullName.Text.Length != 0)
пробелы заменить на табуляцию, настройе студию, она сама замнит как надо.

2019-06-27 16:33 UTC, litdex commented
@YuriSilenok исправил

2019-06-28 06:13 UTC, YuriSilenok approved these changes
Заканчивайте

2019-06-28 06:53 UTC, merged