Создана форма Параметры. Вкладка Звонки
Students-of-the-city-of-Kostroma/Student-timetable pull request #1113
Opened 2019-06-27 17:41 UTC by ZEUS4942

[Вот](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/tree/task-998) ссылка

2019-06-28 06:24 UTC, YuriSilenok requested changes
Обратите внимание на замечания

2019-06-28 06:24 UTC, YuriSilenok commented on TimetableOfClasses/Characteristic.cs
> +        {
У студии в качестве отсупов должна быть настроена табуляция.
Необходимо настроить и заменить.
![image](https://user-images.githubusercontent.com/14871471/60321587-4c898f00-998e-11e9-9f52-b5e8918198ca.png)

2019-06-28 06:24 UTC, YuriSilenok commented on TimetableOfClasses/Characteristic.cs
> +        }
Убрать пустые методы

2019-06-28 06:24 UTC, YuriSilenok commented on TimetableOfClasses/Nastroiki.cs
> +﻿using System;
удалить этот файл.

2019-06-28 06:26 UTC, YuriSilenok commented
> [Вот](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/tree/task-998) ссылка

Это не ссылка на такст, а ссылка на ветку

2019-06-28 11:35 UTC, YuriSilenok commented
@ZEUS4942 почему вы закрыли запрос на слияние?

2019-06-28 11:37 UTC, ZEUS4942 commented
Я сейчас создам новый, правильный.


>Пятница, 28 июня 2019, 14:35 +03:00 от Юрий Силенок <notifications@github.com>:
>
>@ZEUS4942 почему вы закрыли запрос на слияние?
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Сергей Исаков

2019-06-28 11:37 UTC, YuriSilenok commented
что в нем нельзя исправить?

2019-06-28 11:38 UTC, YuriSilenok commented
Не понимаю, зачем создавать новый запрос?

2019-06-28 11:38 UTC, ZEUS4942 commented
Я стараюсь разобраться во всех тонкостях github, но пока не разобрался.
 


>Пятница, 28 июня 2019, 14:37 +03:00 от Юрий Силенок <notifications@github.com>:
>
>что в нем нельзя исправить?
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Сергей Исаков

2019-06-28 11:39 UTC, YuriSilenok commented
Вопросы задавать не восбранятеся.
Спрашивайте.

2019-06-28 11:44 UTC, ZEUS4942 commented
Я и так часто задаю вопросы, мне уже неудобно.
Стараюсь сам разобраться. 
>Пятница, 28 июня 2019, 14:39 +03:00 от Юрий Силенок <notifications@github.com>:
>
>Вопросы задавать не восбранятеся.
>Спрашивайте.
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Сергей Исаков

2019-06-28 11:55 UTC, YuriSilenok commented
https://ru.wikipedia.org/wiki/Agile_Manifesto

- Люди и взаимодействие важнее процессов и инструментов.
- Работающий продукт важнее исчерпывающей документации.
- Сотрудничество с заказчиком важнее согласования условий контракта.
- Готовность к изменениям важнее следования первоначальному плану.

У вас должна быть активна кнопка Reopen and comment
Нажмите ее.
если вы не можете найти ответ по вопросу, спрашивайте, на хорошо поставленный вопрос я всегда отвечу

2019-06-28 12:03 UTC, ZEUS4942 commented
Я снова открыл этот запрос, но не понимаю, как показать свои изменения.
Ведь ветку я заново залил.
И теперь она правильная.

2019-06-28 12:05 UTC, YuriSilenok commented
Давайте решать задачи по мере их поступления.

У Вас есть второй коммит, у него тоже настройки не очень ожидаемы.
Вы знаете как посмотреть значения user.name и user.email ?

2019-06-28 12:05 UTC, ZEUS4942 commented
Не знаю.

2019-06-28 12:10 UTC, ZEUS4942 commented
Уже узнал, разобрался.

2019-06-28 12:10 UTC, YuriSilenok commented
На вкладке [Commits](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1113/commits) можно посмотреть ваши коммиты в контексте текущего запроса. Их может быть сколько угодно, при этом в запросе автоматически добавляется об этом информация. Это позволят несколько раз проверять один запрос не создавая новый.

2019-06-28 12:13 UTC, ZEUS4942 commented
Получается, мне просто нужно добавить новый комит, чтобы показать, что я исправил ошибки?

2019-06-28 12:13 UTC, YuriSilenok commented
я бы даже сказал что есть что изменять что бы коммит не был пустым

2019-06-28 12:14 UTC, YuriSilenok commented on TimetableOfClasses/Characteristic.Designer.cs
> +            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Characteristic));
В этом файле неправильные оступы

2019-06-28 12:31 UTC, ZEUS4942 commented
Теперь вижу, что тут отмечаются коммиты.

2019-06-28 12:32 UTC, YuriSilenok commented
И третий коммит мимо, опять инкогнито, вы настроили параметры о которых я говорил?

2019-06-28 12:38 UTC, ZEUS4942 commented
Вот теперь настроил.
Прошу прощения, не сразу понял.
Теперь мне нужно создать новый коммит?

2019-06-28 12:48 UTC, YuriSilenok commented on TimetableOfClasses/Characteristic.Designer.cs
> +    }
Да, давайте 4 коммит, вот здесь пробелы осталсь
![image](https://user-images.githubusercontent.com/14871471/60343254-9a20ee80-99c4-11e9-8af5-09d3352ed938.png)

2019-06-28 12:49 UTC, ZEUS4942 commented on TimetableOfClasses/Characteristic.Designer.cs
> +    }
у меня появилась одна проблема
мне пишет:
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   TimetableOfClasses/Characteristic.Designer.cs
        modified:   TimetableOfClasses/Characteristic.cs
        deleted:    TimetableOfClasses/Nastroiki.cs
        deleted:    TimetableOfClasses/Nastroiki.designer.cs
        deleted:    TimetableOfClasses/Nastroiki.resx

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   TimetableOfClasses/Characteristic.Designer.cs

2019-06-28 12:51 UTC, YuriSilenok commented on TimetableOfClasses/Characteristic.Designer.cs
> +    }
Пожалуйста, бросайте скрин git bush
Кроме ошибки которую вы скопировали, нужно понимать преыдущие действия и состояние репзитория при этой ошибке.

2019-06-28 12:52 UTC, ZEUS4942 commented on TimetableOfClasses/Characteristic.Designer.cs
> +    }
![image](https://user-images.githubusercontent.com/38218577/60343483-bc167300-99bc-11e9-818a-e297a2ddbdec.png)

2019-06-28 12:55 UTC, YuriSilenok commented on TimetableOfClasses/Characteristic.Designer.cs
> +    }
Не вижу никакой проблемы.
зеленым гит выделяет те файлы которые были приготовлены к комиту.
красным, те файлы которые не попали в стадию готов к коммиту.
соответсвенно измененый файл который выделен красным вам нужно добавить git add а потом выполнить коммит и толкнуть изменения

2019-06-28 12:57 UTC, ZEUS4942 commented on TimetableOfClasses/Characteristic.Designer.cs
> +    }
не выходит:
![image](https://user-images.githubusercontent.com/38218577/60343704-5c6c9780-99bd-11e9-9f50-44c696046ae3.png)

2019-06-28 13:00 UTC, YuriSilenok commented on TimetableOfClasses/Characteristic.Designer.cs
> +    }
сделайте сначало коммит потом git add .

2019-06-28 13:02 UTC, YuriSilenok commented on TimetableOfClasses/Characteristic.Designer.cs
> +    }
Сработало

2019-06-28 13:03 UTC, YuriSilenok commented on TimetableOfClasses/Characteristic.Designer.cs
> +    }
У Вас один git bush открыт?

2019-06-29 11:34 UTC, ZEUS4942 commented on TimetableOfClasses/Characteristic.Designer.cs
> +    }
Простите, не смог ответить, на военную кафедру уехал.
Да открыт один git bush.
Делаю git commit и всё равно выдаёт это.

2019-06-29 11:44 UTC, ZEUS4942 commented
Исправил и всё залил.

2019-06-30 20:37 UTC, YuriSilenok commented
Мне кажется вы не проверяли свои действия. У вас синтаксические Ош бки в проекте и тип ошибки, маркеры мерж конфликте. Эту информацию можно посмотреть на вкладке Checks
![Screenshot_20190701-003504](https://user-images.githubusercontent.com/14871471/60401858-6ac2db00-9b98-11e9-89b0-13b8308e6c40.jpg)

2019-06-30 20:38 UTC, YuriSilenok requested changes
Синтаксические ошибки

2019-07-02 04:39 UTC, ZEUS4942 commented
Если я что не понимаю, подскажите пожалуйста.

2019-07-02 07:38 UTC, YuriSilenok reviewed
Ссылка в описании запроса на сляиние не указывает на задачу из-за которой началась активность.
Почему она указывает на ветку?

2019-07-02 07:40 UTC, YuriSilenok reviewed
Поправить привязку таблицы
![image](https://user-images.githubusercontent.com/14871471/60493573-229dd880-9cbe-11e9-817b-2a07485a2ad3.png)

2019-07-02 07:41 UTC, YuriSilenok requested changes
Стобец № судя по скрину не должен быть редактируемым

2019-07-02 07:42 UTC, YuriSilenok requested changes
скрол откуда-то появился у таблицы

2019-07-03 19:33 UTC, ZEUS4942 commented
Вопрос возник.
Так как в таблице есть данные, их нужно загружать из отдельного файла или пока просто оставить форму?

2019-07-03 19:47 UTC, YuriSilenok commented
Только форма, для данных будет разрабатывать контроллер и модель

2019-07-03 19:54 UTC, ZEUS4942 commented
Тогда надеюсь всё исправил.

2019-07-03 20:31 UTC, ZEUS4942 commented
Ссылку тоже поменял.

2019-07-04 05:14 UTC, YuriSilenok requested changes
Пока не могу проверить эту форму, но есть вопросы

2019-07-04 05:14 UTC, YuriSilenok commented on TimetableOfClasses/Characteristic.cs
> +
Пустой метод, зачем он?

2019-07-04 17:29 UTC, ZEUS4942 commented
Простите, не заметил этот пустой метод.

2019-07-04 19:30 UTC, ZEUS4942 commented on TimetableOfClasses/Characteristic.cs
> +
А если вообще про сам метод, то он описывает то событие, которое возникает при щелчке по содержимому ячейки.

2019-07-05 07:36 UTC, YuriSilenok commented on TimetableOfClasses/Characteristic.cs
> +
да, это для события клика по содержимому таблицы, зачем он здесчь?

2019-07-05 07:37 UTC, YuriSilenok commented on TimetableOfClasses/Characteristic.cs
> +
увидел в комментарии что убрали

2019-07-05 07:38 UTC, YuriSilenok commented on TimetableOfClasses/Characteristic.cs
> +
кстати, вопрос решенным помечает тот, кто его поднял, так же и с багами.

2019-07-05 07:48 UTC, YuriSilenok reviewed
Приступайте к слиянию

2019-07-05 07:49 UTC, YuriSilenok approved these changes

2019-07-05 11:36 UTC, merged