Создана форма Параметры. Вкладка Даты
Students-of-the-city-of-Kostroma/Student-timetable pull request #1115
Opened 2019-06-27 19:36 UTC by PUDGE44

Вот ссылка на [task](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/tree/task-518)

2019-06-28 06:30 UTC, YuriSilenok commented
> Вот ссылка на [task](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/tree/task-518)

это ссылка не на таск, а на ветку. что бы поставить ссылку на таск нужно написать #НомерТаска или как обычную ссылку, но на issue

2019-06-28 06:34 UTC, YuriSilenok requested changes
замечания по коду

2019-06-28 06:34 UTC, YuriSilenok commented on TimetableOfClasses/Characteristic.cs
> +        private void Changes_Enter(object sender, EventArgs e)
настроить студию на отступы в качестве табуляции

2019-06-28 06:34 UTC, YuriSilenok commented on TimetableOfClasses/Characteristic.cs
> +        }
удалить пустые методы

2019-07-05 07:52 UTC, YuriSilenok commented
если в течении 7 дней по этому запросу не будет активности, запрос будет закрыт, а задача снята.

2019-07-05 21:54 UTC, PUDGE44 commented
Исправил все ошибки

2019-07-08 19:59 UTC, YuriSilenok commented
В целом по коду замечаний нет.
пока я проверяю форму, решите образовавшийся мержконфликт.
![image](https://user-images.githubusercontent.com/14871471/60838723-0d500f00-a1d4-11e9-9b23-ca3385d31023.png)

2019-07-08 20:28 UTC, PUDGE44 commented
А вы не подскажете, как разрешить эти конфликты? Что-то не могу разобраться

2019-07-09 04:28 UTC, YuriSilenok commented
![image](https://user-images.githubusercontent.com/14871471/60859322-d81adf80-a21a-11e9-88f2-0adab9be7ddb.png)
Конфликт бывают когда в двух ветках в одном и том же месте происходят изменения.
Нужно решить, из какой ветки должен остаться правильный результат, иногда может быть правильный результат в обоих ветках.
см. ЛР02

2019-07-09 04:31 UTC, YuriSilenok reviewed
У вас для поля Максимальный номер семестра не работают кнопки увеличения или уменьшения значения и нет дефолтного значения

2019-07-09 09:49 UTC, YuriSilenok commented on TimetableOfClasses/Characteristic.cs
> +
зачем этот пустой метод?

2019-07-09 09:49 UTC, YuriSilenok reviewed
Неопознаный код

2019-07-09 12:34 UTC, YuriSilenok reviewed
- зачем эти файлы:
- TimetableOfClasses/Characteristic.Designer_BACKUP_1914.cs
- TimetableOfClasses/Characteristic.Designer_BASE_1914.cs
- TimetableOfClasses/Characteristic.Designer_LOCAL_1914.cs
- TimetableOfClasses/Characteristic.Designer_REMOTE_1914.cs

2019-07-09 12:34 UTC, YuriSilenok commented on TimetableOfClasses/TimetableOfClasses.csproj
> +      <SubType>Designer</SubType>
подозрительное место, разобраться почему это было добавлено студией или в процессе решения конфликта.

2019-07-09 13:19 UTC, PUDGE44 commented on TimetableOfClasses/TimetableOfClasses.csproj
> +      <SubType>Designer</SubType>
Не могу найти, почему это добавляется, но, как я понял, это ненужная строчка, и без неё всё будет так же. Мне удалить её?

2019-07-09 13:21 UTC, YuriSilenok commented on TimetableOfClasses/TimetableOfClasses.csproj
> +      <SubType>Designer</SubType>
попробуй удалить, пересобери проект. если строка будет автоматически добавляться, значит так и доллжно быть

2019-07-09 13:23 UTC, YuriSilenok commented on TimetableOfClasses/Characteristic.resx
> +  </metadata>
Еще непонятно добавленные строки, они дублируют предыдущие.
![image](https://user-images.githubusercontent.com/14871471/60891325-c3b00480-a265-11e9-95cc-616f8626952b.png)

2019-07-09 13:33 UTC, PUDGE44 commented on TimetableOfClasses/TimetableOfClasses.csproj
> +      <SubType>Designer</SubType>
Строка добавляется автоматически.

2019-07-09 13:33 UTC, YuriSilenok commented on TimetableOfClasses/TimetableOfClasses.csproj
> +      <SubType>Designer</SubType>
ok

2019-07-09 13:34 UTC, YuriSilenok approved these changes
Мержите

2019-07-09 13:36 UTC, merged