Теперь нельзя ввести некорректными данные
Students-of-the-city-of-Kostroma/Student-timetable pull request #1129
Opened 2019-07-04 11:11 UTC by venecon1

2019-07-05 07:34 UTC, YuriSilenok requested changes
- нам нужно настроить git на компьютере, а именно прараметры user.name и user.email 
Коммиты в этом запросе не идентифицируются.
- в качестве отсупов в проекте используюется табуляция. Нужно настроить VS.
- не используйте слово "теперь" в заголовках запроса. Лучше используйте Исправление для: "Заголовок бага"

2019-07-05 08:11 UTC, venecon1 commented
- В git user.name и user.email  у меня настроены, в проекте коммиты отображаются как залитые gskvorcov
![Снимок](https://user-images.githubusercontent.com/52324023/60707985-a9002780-9f15-11e9-88f7-575bbc499a58.PNG)

- А табуляцию какую делать, как по умолчанию размер в 4 пробела или в 3?

2019-07-09 09:23 UTC, YuriSilenok commented
> * В git user.name и user.email  у меня настроены, в проекте коммиты отображаются как залитые gskvorcov
>   ![Снимок](https://user-images.githubusercontent.com/52324023/60707985-a9002780-9f15-11e9-88f7-575bbc499a58.PNG)

Почта совпадает с гитхабовской?
![image](https://user-images.githubusercontent.com/14871471/60875410-753d3e80-a242-11e9-87f8-fa8825b28306.png)
Обратите внимание, как должны отображаться коммиты на гитхабе 
![image](https://user-images.githubusercontent.com/14871471/60876089-dca7be00-a243-11e9-8ee5-92f7b42e22cc.png)
то есть, возможен переход на профиль пользователя.

> * А табуляцию какую делать, как по умолчанию размер в 4 пробела или в 3?

отступы могут быть в виде табуляции или пробелов, есть специальный символ табуляции и соответсующая настройка в VS
![image](https://user-images.githubusercontent.com/14871471/60876301-4de77100-a244-11e9-8434-5d5eff943f3c.png)

2019-07-17 12:22 UTC, YuriSilenok commented
запрос закрыт, так как долги сданы

2019-07-17 12:22 UTC, closed without merging

2020-06-25 13:07 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-26 05:05 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-27 05:05 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-27 05:13 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-28 05:05 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-28 05:12 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-29 05:05 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-29 05:13 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-30 05:05 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-01 05:05 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-02 05:05 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-03 05:04 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-03 13:16 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-04 05:03 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-05 05:03 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 05:03 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 13:02 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 14:22 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 15:24 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 15:27 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 15:49 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-07 05:03 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-08 05:03 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-09 05:03 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-10 05:03 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-11 05:03 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-11 06:17 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче