Исправил сбои в автотестах расположенных в файле UT_Insert_CEnclosurse
Students-of-the-city-of-Kostroma/Student-timetable pull request #1132
Opened 2019-07-09 21:51 UTC by DemiKor

#1085

2019-07-10 03:27 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Insert_CEnclosurse.cs
> +		private MEnclosures gr = new MEnclosures("А", RefData.CUniversity.Rows[0].ItemArray[2].ToString(), "Дзержинского", "111111", "1");
Вынесение в поле в автотестах не верный подход, так как случае не выполнения этого действия, сбоя в авотесте не будет именно в этом месте. В автотестах не принято повышать связность.

2019-07-10 03:29 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Insert_CEnclosurse.cs
> +		private MEnclosures gr = new MEnclosures("А", RefData.CUniversity.Rows[0].ItemArray[2].ToString(), "Дзержинского", "111111", "1");
вы можете возвращать этот экземпляр класса из метода.
тогда сбои будут фиксироваться, так как этот метод будет вызываться в каждом из этих тестов.

2019-07-10 05:41 UTC, DemiKor commented on UnitTestOfTimetableOfClasses/UT_Insert_CEnclosurse.cs
> +		private MEnclosures gr = new MEnclosures("А", RefData.CUniversity.Rows[0].ItemArray[2].ToString(), "Дзержинского", "111111", "1");
Заменил поле на метод

2019-07-10 07:07 UTC, YuriSilenok requested changes
![image](https://user-images.githubusercontent.com/14871471/60947956-86e21d00-a2fa-11e9-88a8-0c065549719b.png)

2019-07-10 07:09 UTC, YuriSilenok commented on LibOfTimetableOfClasses/RefData.cs
> +			DataSet.Relations.Add("University-Enclosures", CUniversity.Columns["FullName"], СEnclosures.Columns["University"]);
Веротяно проект не собирается, потому что использовалась кирилическая С в классе СEnclosures

2019-07-10 07:09 UTC, YuriSilenok commented on LibOfTimetableOfClasses/RefData.cs
> +		public static void init()
метод закрытым должен быть

2019-07-10 07:11 UTC, YuriSilenok commented on LibOfTimetableOfClasses/RefData.cs
> +		public static void init()
И с большой буквы, это C#, здесь так принято

2019-07-10 07:14 UTC, YuriSilenok commented on LibOfTimetableOfClasses/RefData.cs
> +			catch (Exception e)
обработку исключений в логи это правильно, а где Вы работаете?

2019-07-10 07:16 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Insert_CEnclosurse.cs
> +			//MEnclosures gr = new MEnclosures("А", "Костромской Государственный Университет", "Дзержинского", "111111", "1");
если считаете их лишними, удалите, в комментариях не стоит оставлять прошлый код.

2019-07-10 15:03 UTC, DemiKor reviewed
Исправления

2019-07-10 15:03 UTC, DemiKor commented on LibOfTimetableOfClasses/RefData.cs
> +			catch (Exception e)
В ММТР

2019-07-10 15:09 UTC, DemiKor commented on LibOfTimetableOfClasses/RefData.cs
> +			DataSet.Relations.Add("University-Enclosures", CUniversity.Columns["FullName"], СEnclosures.Columns["University"]);
исправил на латинскую

2019-07-10 15:11 UTC, DemiKor reviewed
Update

2019-07-10 15:12 UTC, DemiKor commented on LibOfTimetableOfClasses/RefData.cs
> +		public static void init()
Исправил

2019-07-10 15:16 UTC, DemiKor reviewed
UPD

2019-07-10 15:16 UTC, DemiKor commented on UnitTestOfTimetableOfClasses/UT_Insert_CEnclosurse.cs
> +			//MEnclosures gr = new MEnclosures("А", "Костромской Государственный Университет", "Дзержинского", "111111", "1");
Убрал

2019-07-10 16:19 UTC, YuriSilenok requested changes
https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1132/checks

2019-07-11 09:10 UTC, closed without merging

2020-06-25 13:07 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-26 05:05 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-27 05:05 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-27 05:13 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-28 05:05 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-28 05:12 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-29 05:05 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-29 05:13 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-30 05:05 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-01 05:05 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-02 05:05 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-03 05:04 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-03 13:16 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-04 05:03 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-05 05:03 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 05:03 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 13:02 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 14:22 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 15:24 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 15:27 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 15:49 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-07 05:03 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-08 05:03 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-09 05:03 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-10 05:03 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-11 05:03 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-11 06:17 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче