Исправил сбои в автотестах расположенных в файле UT_Insert_CInstitute
Students-of-the-city-of-Kostroma/Student-timetable pull request #1134
Opened 2019-07-10 15:35 UTC by DemiKor

#1096

2019-07-10 16:12 UTC, YuriSilenok requested changes
https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1134/checks

синтаксические ошибки. у нас прикручена непрерываня интеграция, пожалуйста, проверяйте их самостоятельно до того как вы сдаете запрос на проверку

2019-07-11 09:44 UTC, YuriSilenok commented on LibOfTimetableOfClasses/RefData.cs
> +			{
Я решил мы не будем обрабатывать исключения внутри этого метода, так как ошибки заполнения рефдаты становятся неочевмидными. Пожалуйста, удалите отлов исключений.

2019-07-11 09:46 UTC, DemiKor commented on LibOfTimetableOfClasses/RefData.cs
> +			{
Убрал

2019-07-11 09:47 UTC, YuriSilenok commented on LibOfTimetableOfClasses/RefData.cs
> +				MAcademicDegree mAademicDegree = new MAcademicDegree("Магистр", "Маг.");
сдвиньте пожалуйста лишние отсупы, нужно поставить последнюю закрывающую фигурную скобку

2019-07-11 09:47 UTC, DemiKor commented on LibOfTimetableOfClasses/RefData.cs
> +				MAcademicDegree mAademicDegree = new MAcademicDegree("Магистр", "Маг.");
Выполнено

2019-07-11 09:52 UTC, YuriSilenok requested changes
+20 сбоев, это не хорошо. В чем причина?

2019-07-11 09:53 UTC, DemiKor commented
Где можно посмотреть сбои?

2019-07-11 09:58 UTC, YuriSilenok commented
**Details**
![image](https://user-images.githubusercontent.com/14871471/61041527-22e35580-a3db-11e9-9347-b430441c85d5.png)
2 errors
![image](https://user-images.githubusercontent.com/14871471/61041549-30004480-a3db-11e9-8b19-aec658059ee1.png)
Tests
![image](https://user-images.githubusercontent.com/14871471/61041586-41495100-a3db-11e9-808a-d7a3297c9a88.png)

2019-07-11 10:00 UTC, DemiKor commented
Есть подозрения, что в некоторых из них, где сценарий связан с пустой таблицей, в коде таблицу не зачищают, отсюда может получаться не верный результат

2019-07-11 10:08 UTC, DemiKor commented
А т.к. я создал метод заполнения таблиц, их нужно обязательно зачищать
Я посмотрел остальные пул-реквесты, сбои в одних и тех же тестах, за исключением того, что я менял в каждом реквесте

2019-07-11 10:09 UTC, YuriSilenok commented
Нужно проверить, по идее вставка в пустую таблицу это обычный позитивный тест и не так важно пустая таблица или нет. Важно что функция добавления вообще работает.

Пожалуйста, проверьте эту гипотезу.

2019-07-11 10:09 UTC, YuriSilenok commented
> А т.к. я создал метод заполнения таблиц, их нужно обязательно зачищать

вообще я бы сказал что нужно избавиться от зачистки таблиц вообще во всех тестах.
Иметь зачистку таблиц это не очень правильно.

2019-07-11 10:11 UTC, DemiKor commented
Если тест будет написан с данными, которые ограничивает ключ, то запись не будет добавлена
Чтобы быть уверенным в выполнении теста на обычную вставку, лучше будет делать ее в пустые таблицы, на мой взгляд

2019-07-11 10:14 UTC, YuriSilenok commented
В автоматизации не все так просто, не всегда тестировщик имеет право дропнуть рефдату, но при автоматизации, можно сгенерировать значения и проверить что таковых значений нет, прежде чем производить вставку и это будет более надежный тест. Так как в реальной жизни таблицы редко являются пустыми, чаще в них есть данные.

2019-07-11 10:18 UTC, DemiKor commented
Это же самый простой тест, проверка на возможность добавления записи, без каких-либо ограничений
А если в таблице будут данные, то это будет накладывать ограничения, нужно быть уверенным, что данные в новой записи не нарушают ограничений
Как раз в остальных сценариях тестируются ограничения, но в обычной вставке в этом нет необходимости

2019-07-11 10:22 UTC, YuriSilenok commented
> А если в таблице будут данные, то это будет накладывать ограничения, нужно быть уверенным, что данные в новой записи не нарушают ограничений

Теряется смысл в инициализации рефдаты (очистка это было временное решение). Выхода здесь 2:
- либо подогнать данные так, что бы добавляемая строка не пересекалась с имеюшимися данными (инициализатор рефдаты особо меняться не будет, а если поменяется критично, автотесты жэто отобразят)
- либо генерировать данные случайным образом и перед вставкой проверять что сгенерированные значения не пересекаются с имеющимися.

2019-07-11 10:25 UTC, DemiKor commented
Инициализация не теряет смысл, т.к. во многих таблицах для вставки нужны значения из других таблиц, из-за чего раньше и были сбои в тестах

2019-07-11 10:31 UTC, YuriSilenok commented
> Инициализация не теряет смысл, т.к. во многих таблицах для вставки нужны значения из других таблиц, из-за чего раньше и были сбои в тестах

она теряет смысл так как первый же тест на преподавателя пытается снести рефдату, а так как появились реляционные сввязи, тесту это не удается сделать, и выходит ошибка 
![image](https://user-images.githubusercontent.com/14871471/61043771-bcad0180-a3df-11e9-8ec0-efecedcb75f9.png)
А если докрутить тест на очистку данных, то уже к середине тестовой бибилиотеки, от рефдаты ничего не останется, и какой тогда смысл было создавать ее.

Я бы сказал что тесты должны учитывать существующую рефдату.
При ручном тестировании, что бы добавить преподавателя, не будут сносить 100 штук существующих.

2019-07-11 10:33 UTC, YuriSilenok commented
Я закомментировал чистку таблицы и тест был пройден.
![image](https://user-images.githubusercontent.com/14871471/61044036-69877e80-a3e0-11e9-8e6e-01e8e2606583.png)
Не гарантирую что везде так будет, но во многих тестах так и будет

2019-07-11 10:39 UTC, DemiKor commented
Вы предлагаете перебрать все тесты и избавиться от зачистки?

2019-07-11 10:49 UTC, YuriSilenok reviewed
Я предлагаю создать 3 отдельных задачи, которы будут засчитанные по баллу за каждый.
Первая - это создание рефдаты, по сути у вас есть заготовка, останется только оформить
Вторая - удалить любые очистки таблиц, при этом если автотест будет сбоить по другим причинам, то это не повлияет на зачет задачи.
Третья - удалить методы Delete в тестах которые не связаны с тестированием метода Delete. Так же сбои которые появяться не будут влиять на завершение задачи.

Безумно, но это необходимо, да и внушительная пачка задач появиться, а тьо должникам уже мало задач стало.

2019-07-11 10:57 UTC, DemiKor commented
Хорошо, сейчас заведу задачи и сделаю их
Что делать с рефдатой? Как заполнять?

2019-07-11 11:00 UTC, YuriSilenok commented
Давайте сделаем элегантно, создадим по 3 записи в каждой таблице

2019-07-11 11:02 UTC, DemiKor commented
А чем заполнять?
Генерировать случайным образом?

2019-07-11 17:31 UTC, YuriSilenok commented
> А чем заполнять?
> Генерировать случайным образом?

Нет, генерирование в данном случае всей рефдаты случайным образом будет плохо, так как под угозой сбоев окажутся тесты которые не имеют генерирования тестов случайным образом и соответсвующих проверок перед добавлением, изменением, удалением данных.

либо из реальной жизни
либо сгенерироваными значениями (не случайным образом) который всегда будут одни и те же.
Завязанные на счетчики, типа +=(char)('a'+i) это джаст достаточно стабильные тестовые данные и при этом можно будет легко увеличить количество значений в таблице.

2019-07-11 18:55 UTC, closed without merging

2020-06-25 13:07 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-26 05:05 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-27 05:05 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-27 05:13 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-28 05:05 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-28 05:12 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-29 05:05 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-29 05:13 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-30 05:05 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-01 05:05 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-02 05:05 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-03 05:04 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-03 13:16 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-03 13:21 UTC, Heriuple commented
Это требуется сделать мне?

2020-07-03 13:28 UTC, YuriSilenok commented
уже не надо, сделал сам