Создана форма "ВУЗы"
Students-of-the-city-of-Kostroma/Student-timetable pull request #115
Opened 2019-03-03 18:00 UTC by SamuraSwordS

[Задача](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/111).

2019-03-04 06:44 UTC, YuriSilenok approved these changes
По коду замечаний нет.
Вам нужно решить мержконфликт.
Попробуйте это сделать через Web-интерфейс
Нажмите на кнопку **Resolve conflicts**
![image](https://user-images.githubusercontent.com/14871471/53715216-2c274900-3e62-11e9-852e-dd12069a7d23.png)

2019-03-04 14:16 UTC, SamuraSwordS commented
Задача выполнена.

2019-03-04 16:39 UTC, SamuraSwordS commented
Я решил мёржконфликт первый раз, и как вижу, он появился снова.
Скажите пожалуйста, мне что-то нужно делать ?

2019-03-04 16:43 UTC, map82top commented
Я спонсор данного мерж конфликта. Прими то, что изменилось в Testing и все

2019-03-04 16:50 UTC, SamuraSwordS commented
<<<<<<< task-111
    <Compile Include="University.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="University.Designer.cs">
      <DependentUpon>University.cs</DependentUpon>
    </Compile>
=======
    <EmbeddedResource Include="AcademicDegree.resx">
      <DependentUpon>AcademicDegree.cs</DependentUpon>
    </EmbeddedResource>
>>>>>>> Testing
Это оставить целиком, я так понимаю ?

2019-03-04 16:51 UTC, SamuraSwordS commented
`<<<<<<< task-111
    <Compile Include="University.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="University.Designer.cs">
      <DependentUpon>University.cs</DependentUpon>
    </Compile>
=======
    <EmbeddedResource Include="AcademicDegree.resx">
      <DependentUpon>AcademicDegree.cs</DependentUpon>
    </EmbeddedResource>
>>>>>>> Testing`
Это оставить целиком , я так понимаю ?

2019-03-04 16:53 UTC, SamuraSwordS commented
"<Compile Include="University.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="University.Designer.cs">
      <DependentUpon>University.cs</DependentUpon>
    </Compile>
=======
    <EmbeddedResource Include="AcademicDegree.resx">
      <DependentUpon>AcademicDegree.cs</DependentUpon>
    </EmbeddedResource>"
Это целиком, я так понял ?

2019-03-04 16:58 UTC, map82top commented
Да

2019-03-05 16:31 UTC, YuriSilenok commented
@map82top почему Вы ОТОШЛИ от алгоритма?
Кто Вам сказал что так можно мержить? 
Вы изуродовали репозиторий.
> Я спонсор данного мерж конфликта. Прими то, что изменилось в Testing и все

2019-03-05 16:33 UTC, YuriSilenok commented on TimetableOfClasses/Start.cs
> -		private void министерстваToolStripMenuItem_Click(object sender, EventArgs e)
Почему была удалена обработка Министертсва?

2019-03-05 16:34 UTC, YuriSilenok commented on TimetableOfClasses/TimetableOfClasses.csproj
> +      <Name>LibOfTimetableOfClasses</Name>
Почему столько изменений в этом файле?

2019-03-05 16:35 UTC, map82top commented
Потому что я не понял как менять направление мержа, и почему она вообще оказалось неправильным.

2019-03-05 16:35 UTC, YuriSilenok requested changes
Вы изменили файлы которые не должны были измениться.

2019-03-05 16:38 UTC, YuriSilenok commented
То есть, в место того что бы почитать, разобраться, спросить посчле всего этого, Вы приступили к действиям? К действиям которым вы не особо отдавали себе отчети и на которые у Вас небыло никаких рекомендаций и инструкций?
> Потому что я не понял как менять направление мержа, и почему она вообще оказалось неправильным.

2019-03-05 16:41 UTC, SamuraSwordS commented on TimetableOfClasses/Start.cs
> -		private void министерстваToolStripMenuItem_Click(object sender, EventArgs e)
Потому что на момент создания мной формы этого обработчика не было, видимо поэтому я подумал, что его надо удалить.

2019-03-05 16:41 UTC, map82top commented
Во-первых, я спросил, до того как начал что-то делать
Во-вторых, я отдавал отчет свои действиям, просто не предусмотрел все последствия. Я подумал несколько раз прежде, чем что-то сделать. 
Было сказано "выполнить мерж снова в правильном направлении." я его выполнил

2019-03-05 16:44 UTC, SamuraSwordS commented on TimetableOfClasses/TimetableOfClasses.csproj
> +      <Name>LibOfTimetableOfClasses</Name>
Понятия не имею, наверное это каким то образом случилось из-за создания новой формы.

2019-03-05 16:49 UTC, SamuraSwordS commented
> Вы изменили файлы которые не должны были измениться.

Если же это касается меня, то с того момента, как вы мне сказали, что по коду замечаний нет - никаких изменений я не делал.

2019-03-06 17:54 UTC, YuriSilenok requested changes
Здравствуйте.
После того как я сказал что к коду замечаний нет, было два мержа, видимо с решением конфликтов. Как во второй лабораторной работе нужно было оставить оба изменения.
Сейчас ситуация такова, что есть удаленные участик кода, которые необходимо восстановить.
Жду Ваших коммитов с исправлениями.
Спасибо

2019-03-06 19:02 UTC, SamuraSwordS commented
![image](https://user-images.githubusercontent.com/47320646/53906228-71629b00-405b-11e9-93bf-47785c2f7b52.png)
Прошу помощи.
Что мне с этим делать ?
Я пытался отправить коммит.

2019-03-07 06:22 UTC, YuriSilenok commented
Вы перевели то, что написано желтым?

2019-03-07 15:31 UTC, SamuraSwordS commented
> Вы перевели то, что написано желтым?

Конечно.
Но , если бы я всё понял , я бы не просил помощи.

2019-03-07 15:56 UTC, SamuraSwordS commented
Хотя я попробовал воспользоваться командой git pull , но результат то же .
Есть смысл пересоздать ветку ?

2019-03-07 16:20 UTC, SamuraSwordS commented
К счастью или нет, я смог запушить, прошу прощения, что потревожил вопросом.

2019-03-08 19:16 UTC, YuriSilenok reviewed
Приступайте к решению конфликта.
Думаю web-интерфейс здесь будет более приемлем.

2019-03-12 10:08 UTC, YuriSilenok commented
Решите еще один конфликт

2019-03-12 16:31 UTC, SamuraSwordS commented
Сделано

2019-03-15 11:57 UTC, YuriSilenok reviewed
У Вас проект работает?

2019-03-15 11:57 UTC, YuriSilenok commented on TimetableOfClasses/TimetableOfClasses.csproj
>        <SubType>Form</SubType>
Нет закрывающего тега для `<Compile Include="University.Designer.cs">`
В Вашей ветке проект открывается?

2019-03-15 11:57 UTC, YuriSilenok commented on TimetableOfClasses/TimetableOfClasses.csproj
>      <EmbeddedResource Include="TypesOfOccupations.resx">
`<EmbeddedResource Include="University.resx">` нет закрывающего тега

2019-03-15 14:10 UTC, YuriSilenok commented
Попробую залить изменения. 
Но кажется должно что-то поломаться.

2019-03-15 14:10 UTC, merged

2019-03-15 14:12 UTC, YuriSilenok commented
Так и есть, в тестинг повредилась, буду чинить

2019-03-15 14:13 UTC, YuriSilenok commented
И Ваш так так же не работает.

2019-03-15 21:59 UTC, SamuraSwordS commented
У меня всё запускается , если конечно это не вы уже всё исправили.