Исправил У текстовых полей формы "Добавление ученой степени" нет прив…
Students-of-the-city-of-Kostroma/Student-timetable pull request #1167
Opened 2019-07-11 21:03 UTC by DemiKor

#1161

2019-07-14 10:20 UTC, YuriSilenok requested changes
![image](https://user-images.githubusercontent.com/14871471/61182315-fbd68f00-a639-11e9-8b74-01853929eafe.png)
желтым выделены пробелы, пожалуйста, настройте VS, отступы на табуляцию, они автоматически будут подставляться.

2019-07-14 12:41 UTC, DemiKor commented
Исправил

2019-07-14 13:01 UTC, YuriSilenok approved these changes
мержите

2019-07-14 14:22 UTC, merged

2020-06-25 13:07 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-26 05:05 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-27 05:05 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-27 05:12 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-28 05:04 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-28 05:12 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-29 05:05 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-29 05:13 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-30 05:04 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-01 05:04 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-02 05:04 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-03 05:03 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-03 13:16 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-04 05:02 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-05 05:02 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 05:03 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 13:02 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 14:22 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 15:24 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 15:26 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 15:49 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-07 05:02 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-08 05:02 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-09 05:02 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-10 05:02 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-11 05:02 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-11 06:17 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче