Исправил Неправильное название формы "Добавить Учебную неделю"
Students-of-the-city-of-Kostroma/Student-timetable pull request #1168
Opened 2019-07-11 21:17 UTC by DemiKor

#1151

2019-07-12 06:21 UTC, YuriSilenok requested changes
с маленькой буквы учебную

2019-07-12 06:55 UTC, DemiKor reviewed
Исправлено

2019-07-14 10:18 UTC, YuriSilenok approved these changes

2019-07-14 12:22 UTC, merged

2020-06-25 13:07 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-26 05:05 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-27 05:05 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-27 05:12 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-28 05:04 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-28 05:12 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-29 05:05 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-29 05:13 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-30 05:04 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-01 05:04 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-02 05:04 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-03 05:03 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-03 13:16 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-04 05:02 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-05 05:02 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 05:03 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 13:02 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 14:22 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 15:24 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 15:26 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 15:49 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-07 05:02 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-08 05:02 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-09 05:02 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-10 05:02 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-11 05:02 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-11 06:17 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче