Добавил минимальный размер окна "Добавить институт"
Students-of-the-city-of-Kostroma/Student-timetable pull request #1169
Opened 2019-07-12 10:17 UTC by MaximTrapeznikov

#1165

2019-07-14 10:16 UTC, YuriSilenok reviewed
Я бы сказал что кнопки добавить не очень удобны, особенно при растяжении. 
Предлагаю перенести их правее комбобокса, а текст заменить на один символ + , соответственно при увеличении ширины формы, будет изменяться размер комбобокса, а кнопка будет перемещаться в след правой границе.
![image](https://user-images.githubusercontent.com/14871471/61182255-6d620d80-a639-11e9-8bf8-ae4623437676.png)
![image](https://user-images.githubusercontent.com/14871471/61182262-8e2a6300-a639-11e9-93a5-fb4245c3d10f.png)

2019-07-16 15:13 UTC, YuriSilenok commented
![image](https://user-images.githubusercontent.com/14871471/61306444-4cdeb280-a7f5-11e9-9ec1-97752250fd31.png)
Кнопки должны быть привязаны к правой и нижней границе

2019-07-16 15:13 UTC, YuriSilenok reviewed
привязать кнопки к нижнему краю

2019-07-17 12:23 UTC, MaximTrapeznikov commented
Зравствуйте @YuriSilenok 
К нижнему краю по центру или к правому нижнему углу?
Спасибо

2019-07-17 12:24 UTC, YuriSilenok commented
![image](https://user-images.githubusercontent.com/14871471/61375205-f8940b00-a8a6-11e9-921b-cd95670153fc.png)
К правому нижнему краю, как на скрине

2019-07-17 12:25 UTC, MaximTrapeznikov commented
Сделано

2019-07-17 12:26 UTC, YuriSilenok requested changes
![image](https://user-images.githubusercontent.com/14871471/61375287-32fda800-a8a7-11e9-899a-77c9938232b9.png)
Пожалуйста, проверяйте свою работу

2019-07-17 12:31 UTC, YuriSilenok approved these changes
Мержите,
у Вас еще вторая зхадача ожидае правок

2019-07-17 12:32 UTC, merged