Реализация задачи #118 Создать форму "Ученые степени"
Students-of-the-city-of-Kostroma/Student-timetable pull request #120
Opened 2019-03-04 11:19 UTC by map82top

#118

2019-03-04 11:25 UTC, YuriSilenok requested changes
В остальном замечательно.

2019-03-04 11:25 UTC, YuriSilenok commented on LibOfTimetableOfClasses/LibOfTimetableOfClasses.csproj
> +    <Reference Include="System.Drawing" />
Почему были добавлены эти две ссылки?

2019-03-04 11:42 UTC, map82top reviewed
Почему 2? Здесь же добавилась только одна строка(в той части кода, что вы указали в комментарии)

2019-03-04 11:42 UTC, map82top commented on LibOfTimetableOfClasses/LibOfTimetableOfClasses.csproj
> +    <Reference Include="System.Drawing" />
Потому что я сначала по ошибке создал форму в LibOfTimetableOfClasses, после чего удалил ее. А это создалось автоматически и поэтому я его не удалил, так как не знал, что они создались.  Когда я добавлял файлы на коммит я решил добавить и этот файл, так как вдруг без него ничего работать не будет

2019-03-04 11:45 UTC, map82top commented
В мерж-конфликте надо совместить все 3 записи?

2019-03-04 11:47 UTC, YuriSilenok commented on LibOfTimetableOfClasses/LibOfTimetableOfClasses.csproj
> +    <Reference Include="System.Drawing" />
Верните этот файл в исходное положение.

2019-03-04 11:50 UTC, YuriSilenok commented
Мерж делается в последжнюю очередь, когда других замечаний нет.

2019-03-04 11:50 UTC, YuriSilenok requested changes

2019-03-04 11:50 UTC, YuriSilenok commented on LibOfTimetableOfClasses/LibOfTimetableOfClasses.csproj
> +    <Reference Include="System.Windows.Forms" />
Вот вторая строчка

2019-03-04 11:55 UTC, map82top commented
Исправление замечаний выполнено

2019-03-04 11:56 UTC, YuriSilenok commented
о новых коммитах при существующем запросе я получаю автоматическое уведомление, писать об этом не нужно в комментариях.

2019-03-04 11:59 UTC, YuriSilenok approved these changes
Можете приступать к решению конфликта.

2019-03-04 12:48 UTC, map82top commented
Мерж-конфликт решен

2019-03-04 13:23 UTC, YuriSilenok commented
Здравствуйте.

Еще раз напоминаю, о ваших коммитах мне не нужно напоминать.
Уведомление об этом мне приходят автоматически.
Вы допустили ошибку, у Вас произошел мерж из ветки Testing в ветку task-118. 
Нужно было на оборот.
Вы должны выполнить команду revert для коммита с мержем и выполнить мерж снова в правильном направлении.

Спасибо.

2019-03-04 14:13 UTC, map82top commented
Не могу понять как использовать команду revert
После -m чтобы какое число нужно указывать?
После этого мерж нужно производить в консоли?

2019-03-04 14:31 UTC, merged

2019-03-05 15:38 UTC, YuriSilenok commented on TimetableOfClasses/Start.Designer.cs
> -			this.редактироватьЗаписьToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
Зачем вы это удалили?

2019-03-05 15:38 UTC, YuriSilenok commented on TimetableOfClasses/Start.Designer.cs
> -			this.добавитьЗаписьToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
Зачем это было удалено?

2019-03-05 15:39 UTC, YuriSilenok commented on TimetableOfClasses/Start.Designer.cs
> -            this.добавитьЗаписьToolStripMenuItem});
Почему это было удалено?

2019-03-05 15:40 UTC, YuriSilenok commented on TimetableOfClasses/Start.Designer.cs
> -			this.добавитьЗаписьToolStripMenuItem.Text = "Добавить запись";
Почему это было удалено?

2019-03-05 15:40 UTC, YuriSilenok commented on TimetableOfClasses/Start.Designer.cs
> -		private System.Windows.Forms.ToolStripMenuItem добавитьЗаписьToolStripMenuItem;
Почему это было удалено?

2019-03-05 15:41 UTC, YuriSilenok reviewed
У Вас почти получилось, но много вы удалили.
Вам необходимо сделать еще оджин коммит, который бы восстановил удаленные значения в ветьку task-118

2019-03-05 15:57 UTC, map82top commented
Но ведь ветвь уже слита?
Не помню, что бы я что-то делал с этими строками кода

2019-03-05 16:25 UTC, map82top commented
Я залил изменения в свою ветку. Получается мне создавать новый запрос?

2019-03-06 13:31 UTC, YuriSilenok commented
что значит в свою ветку?

2019-03-06 14:02 UTC, YuriSilenok commented
Давайте так, ищите колммит в котором было все нормально, от этого коммита пустите ветку `task-118-1` и если в ней нужно что-то доделать, доделайте и создайте новый запрос на слияние.

2019-03-06 14:29 UTC, map82top commented
ветку task-118

2019-03-06 14:36 UTC, map82top commented
![image](https://user-images.githubusercontent.com/36793054/53888709-4154d100-4036-11e9-87c1-6dbc3b4b1459.png)
Пишет вот это 
Создавал новую ветку по коммиту "Откат изменения в файле LibOfTimetableOfClasses/LibOfTimetableOfClass" (2 коммит)

2019-03-06 18:18 UTC, YuriSilenok commented
Это может говорить о точ, что в ветке тестинг уже все есть. 
Пойду посмотрю фактически

2019-03-06 18:19 UTC, YuriSilenok commented
Ох, ветка тестинг не рабочая, что-то дуда попало, что сломало проект с гуёй