Test > fix UT_Update_CUniversity
Students-of-the-city-of-Kostroma/Student-timetable pull request #1205
Opened 2019-09-22 07:11 UTC by Rogachev99

#1088

2019-09-22 07:21 UTC, Rogachev99 commented
> @Rogachev99
> Никаких очисток таблицы, у нас есть общая рефдата

Не совсем понял замечание. Чем плох этот метод, если мы работает только с тестами? У нас же юнит тестирование, и данные одних тестов не должны влиять на другие тесты. Или я не прав?

2019-09-22 07:23 UTC, YuriSilenok commented
> > @Rogachev99
> > Никаких очисток таблицы, у нас есть общая рефдата
> 
> Не совсем понял замечание. Чем плох этот метод, если мы работает только с тестами? У нас же юнит тестирование, и данные одних тестов не должны влиять на другие тесты. Или я не прав?

Что бы данные не влияли на другие тесты, нужно убирать за собственным тестом, а не за всеми.
Что конкретно мешает Вашему тесту?

2019-09-22 07:24 UTC, YuriSilenok requested changes
Мерж должен быть представлен в ветку Elite

2019-09-22 07:26 UTC, Rogachev99 commented
> Что конкретно мешает Вашему тесту?
Сразу в нескольких тестах не проходило.

2019-09-22 07:34 UTC, Rogachev99 commented
> Что бы данные не влияли на другие тесты, нужно убирать за собственным тестом, а не за всеми.

Так и не понял, в чем недостаток моего решения. Если в одном тесте мы опираемся на данные, которые были загружены в другом тесте - это ведь не правильный подход. А если нам нужно загрузить изначальное состояние для всех тестов, то закоменченный метод специально был для этого добавлен.

2019-09-22 07:56 UTC, YuriSilenok commented
> Если в одном тесте мы опираемся на данные, которые были загружены в другом тесте

Они загружены не в результате тестирования, а в результате инициализации рефдаты и эту рефдату могут использовать многие тесты. И в тестах не нужно будет пересоздавать множество таблиц зависящих друг от друга.

2019-09-22 07:57 UTC, YuriSilenok commented
> закоменченный метод специально был для этого добавлен.

закоменченый метод ничего не делает, либо он есть и что-то делает, либо удаляйте его

2019-09-22 07:58 UTC, YuriSilenok commented
> Сразу в нескольких тестах не проходило.

Я не понял ответа

2019-09-22 08:02 UTC, Rogachev99 commented
> > Если в одном тесте мы опираемся на данные, которые были загружены в другом тесте
> 
> Они загружены не в результате тестирования, а в результате инициализации рефдаты и эту рефдату могут использовать многие тесты. И в тестах не нужно будет пересоздавать множество таблиц зависящих друг от друга.

Этот метод не очищает всю таблицу, только содержимое, т.е. зависимость одной таблицы от другой останется. Если речь про сами данные, то действительно придется пересоздавать.

2019-09-22 08:08 UTC, YuriSilenok commented
> > > Если в одном тесте мы опираемся на данные, которые были загружены в другом тесте
> > 
> > 
> > Они загружены не в результате тестирования, а в результате инициализации рефдаты и эту рефдату могут использовать многие тесты. И в тестах не нужно будет пересоздавать множество таблиц зависящих друг от друга.
> 
> Этот метод не очищает всю таблицу, только содержимое, т.е. зависимость одной таблицы от другой останется. Если речь про сами данные, то действительно придется пересоздавать.

Проблема в том, что Вы чистите чужие данные, которые могут потребоваться для других тестов.
В рамках одного тест-комплекта UT_Update_CUniversity вы можете инициализировать собственную рефдату и потом ее удалить, но не трогайте чужую

2019-09-22 08:12 UTC, YuriSilenok commented
![image](https://user-images.githubusercontent.com/14871471/65384321-bf09d100-dd29-11e9-8d28-459e3dbe7307.png)
Думаю эти сбои моут быть связаны с тем что в тестах Вашего тест-комплекта нет промежуточных проверок, например здесь `RefData.CUniversity.Insert(gr);` 
Где гарантия того что строка была добавлена?

2019-09-22 08:12 UTC, Rogachev99 commented
> Проблема в том, что Вы чистите чужие данные, которые могут потребоваться для других тестов.

Не видел такого места, где данные заполняются и используются.

> В рамках одного тест-комплекта UT_Update_CUniversity вы можете инициализировать собственную рефдату и потом ее удалить, но не трогайте чужую

Думал об этом, но решил переделать как вы просили.

2019-09-22 08:14 UTC, YuriSilenok commented
> > Проблема в том, что Вы чистите чужие данные, которые могут потребоваться для других тестов.
> 
> Не видел такого места, где данные заполняются и используются.

Это не что их сейчас нет, они могут появится в дальнейшем. 
Вдруг тестировщик после Вас будет маньяк

2019-09-22 08:15 UTC, YuriSilenok commented
> > В рамках одного тест-комплекта UT_Update_CUniversity вы можете инициализировать собственную рефдату и потом ее удалить, но не трогайте чужую
> 
> Думал об этом, но решил переделать как вы просили.

Если о том закоментированном методе, то моя претензия была в том что он был закоментирован, это мусор, если бы вы его реализовали, я бы смотрел что он делает

2019-09-22 08:18 UTC, Rogachev99 commented
> ![image](https://user-images.githubusercontent.com/14871471/65384321-bf09d100-dd29-11e9-8d28-459e3dbe7307.png)
> Думаю эти сбои моут быть связаны с тем что в тестах Вашего тест-комплекта нет промежуточных проверок, например здесь `RefData.CUniversity.Insert(gr);`
> Где гарантия того что строка была добавлена?

Насколько понимаю, проблема с тем, что в другом тестовом сценарии данные не удаляются. Как мне поступить в данном случае?

2019-09-22 09:02 UTC, Rogachev99 commented
Решил проблему, теперь появилась новая. Тест Task_497_1 не проходит. Посмотрел сценарий, он не совсем правильный (не верный ожидаемый результат), а сам тест вообще не соответствует сценарию. Приводить тест в соответствии с сценарием, а в сценарии поправить ожидаемый результат?

2019-09-22 09:05 UTC, YuriSilenok commented
> Решил проблему, теперь появилась новая. Тест Task_497_1 не проходит. Посмотрел сценарий, он не совсем правильный (не верный ожидаемый результат), а сам тест вообще не соответствует сценарию. Приводить тест в соответствии с сценарием, а в сценарии поправить ожидаемый результат?

Смотрите на цель теста и приведите в соответствие и сценарии и тест с тем, как считаете правильным.

2019-09-22 09:08 UTC, YuriSilenok commented
> > ![image](https://user-images.githubusercontent.com/14871471/65384321-bf09d100-dd29-11e9-8d28-459e3dbe7307.png)
> > Думаю эти сбои моут быть связаны с тем что в тестах Вашего тест-комплекта нет промежуточных проверок, например здесь `RefData.CUniversity.Insert(gr);`
> > Где гарантия того что строка была добавлена?
> 
> Насколько понимаю, проблема с тем, что в другом тестовом сценарии данные не удаляются. Как мне поступить в данном случае?


Поставьте везде проверку того, что возвращает функция, в том числе и здесь 
`RefData.CUniversity.Delete(gr);`
Получается что вы только попытались удалить данные но не проверили удалились ли они.

2019-09-22 09:51 UTC, Rogachev99 commented
С сценарием все было правильно, не заметил что используется ИНН. Поправил только тест.

2019-09-22 09:54 UTC, Rogachev99 commented
> Поставьте везде проверку того, что возвращает функция, в том числе и здесь
> RefData.CUniversity.Delete(gr);
> Получается что вы только попытались удалить данные но не проверили удалились ли они.

Решил вернуть свой метод с очисткой, чтобы не делать проверки. Теперь удаляется содержимое только моей созданной таблицы.

2019-09-22 10:12 UTC, YuriSilenok commented
> > Поставьте везде проверку того, что возвращает функция, в том числе и здесь
> > RefData.CUniversity.Delete(gr);
> > Получается что вы только попытались удалить данные но не проверили удалились ли они.
> 
> Решил вернуть свой метод с очисткой, чтобы не делать проверки. Теперь удаляется содержимое только моей созданной таблицы.

Это таблица не ваша, она общая, если вы хотите удалять данные созданные только вами, Создайте список и туда записывайте все что вы создали. А в ваше  методе перебирайте ваш список, а не таблицу

2019-09-22 10:14 UTC, Rogachev99 commented
> Это таблица не ваша, она общая, если вы хотите удалять данные созданные только вами, Создайте список и туда записывайте все что вы создали. А в ваше методе перебирайте ваш список, а не таблицу

Просто не правильно выразился.

2019-09-22 10:26 UTC, YuriSilenok commented
> > Это таблица не ваша, она общая, если вы хотите удалять данные созданные только вами, Создайте список и туда записывайте все что вы создали. А в ваше методе перебирайте ваш список, а не таблицу
> 
> Данные хранятся и удаляются, только созданные в данном файле с тестами. Я не использую refData, а использую созданный контроллер в своем тесте.

Вынужден огорчить, но то что вы можете создать контроллер отдельно от рефдаты это баг. Нельзя так делать, так как пропадают связи с другими таблицами.

2019-09-22 10:28 UTC, Rogachev99 commented
> Вынужден огорчить, но то что вы можете создать контроллер отдельно от рефдаты это баг. Нельзя так делать, так как пропадают связи с другими таблицами.

Сценарии не работают с другими таблицами, поэтому решил так создать. Хорошо поправлю.

2019-09-22 10:41 UTC, Rogachev99 commented
Кажется, уже про это писал. Теперь не получается запустить тест, из-за того что где-то в другом тесте добавляются записи с похожими параметрами.

2019-09-22 10:41 UTC, Rogachev99 commented
Если и их править, то все работы по правке тестов сведутся к одной работе. Единственным решением вижу создать свою refData.

2019-09-22 10:47 UTC, Rogachev99 commented
Хотя может быть и не в этом проблема. При одиночном запуске теста ситуация не меняется. Не получается добавить в таблицу данные.

2019-09-22 10:49 UTC, Rogachev99 commented
Из-за этого не работает. Находится в refData.
```C#
MUniversity mUniversity = new MUniversity("4401006286", "КГУ", "Костромской Государственный Университет", "156005, Костромская область, г. Кострома, ул. Дзержинского, 17", "156005, Костромская область, г. Кострома, ул. Дзержинского, 17", "Александр", "Рудольфович", "Наумов", "info@kstu.edu.ru", "84942317960");
RefData.CUniversity.Insert(mUniversity);
```

2019-09-22 10:51 UTC, Rogachev99 commented
Как мне поступить? Как по мне такие данные не должны содержаться в коде, а подгружаться из файла/БД. И только при запуске самого приложения.

2019-09-22 12:59 UTC, YuriSilenok commented
> Кажется, уже про это писал. Теперь не получается запустить тест, из-за того что где-то в другом тесте(не в моем файле) добавляются записи с похожими параметрами.

Ваша задача сделать их более уникальными

2019-09-22 13:00 UTC, YuriSilenok commented
> Если и их править, то все работы по правке тестов сведутся к одной работе.

о какой работе речь?

2019-09-22 13:01 UTC, YuriSilenok commented
> Хотя может быть и не в этом проблема. При одиночном запуске теста ситуация не меняется. Не получается добавить в таблицу данные.

Потому что такие данные уже существуют, это все глупый копипаст тестов, сделайте свои данные более уникальными

2019-09-22 13:01 UTC, YuriSilenok commented
> Из-за этого не работает. Находится в refData.
> 
> ```cs
> MUniversity mUniversity = new MUniversity("4401006286", "КГУ", "Костромской Государственный Университет", "156005, Костромская область, г. Кострома, ул. Дзержинского, 17", "156005, Костромская область, г. Кострома, ул. Дзержинского, 17", "Александр", "Рудольфович", "Наумов", "info@kstu.edu.ru", "84942317960");
> RefData.CUniversity.Insert(mUniversity);
> ```

Это должно остаться неизменным

2019-09-22 13:03 UTC, YuriSilenok commented
> Как мне поступить? Как по мне такие данные не должны содержаться в коде (код и данные должны быть отделены), а подгружаться из файла/БД. И только при запуске самого приложения.

Этим займется следующее поколение, сначала они пометят метод заполняющий рефдату как исполняемый только в режиме дебага. Потом уже переведут это все на файлы, в БД не будут переводить, так как на момент дисциплины о БД они ничего не знают

2019-09-22 13:20 UTC, Rogachev99 commented
В таком случае остается только одно решение - создать свою refData с нуля для тестов. Этот подход не считаю правильным, т.к. при добавлении новых связей у таблиц в основной refData, придется и тестовую refData править.

2019-09-22 13:21 UTC, Rogachev99 commented
Наследоваться от refData не получится, т.к. используются статические поля.

2019-09-22 13:24 UTC, Rogachev99 commented
В тестовой refData не будет метода init, который заполняет таблицы.

2019-09-22 13:26 UTC, Rogachev99 commented
Метод, который у меня был для очистки таблицы, в таком случае будет равносилен новым зименениям))

2019-09-22 13:40 UTC, YuriSilenok commented
Что вам мешает использовать текущую рефдату?

2019-09-22 13:41 UTC, Rogachev99 commented
> Что вам мешает использовать текущую рефдату?

Не увидел сначала вашего сообщения о уникальности)

2019-09-22 13:44 UTC, YuriSilenok commented
> > Что вам мешает использовать текущую рефдату?
> 
> Не увидел сначала вашего сообщения о уникальности)

Жду коммита

2019-09-22 18:37 UTC, YuriSilenok approved these changes
Теперь кажется все, мержите

2019-09-22 18:49 UTC, merged

2020-06-25 13:06 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-26 05:04 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-27 05:04 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-27 05:12 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-28 05:04 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-28 05:12 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-29 05:05 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-29 05:12 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-30 05:04 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-01 05:04 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-02 05:04 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-03 05:03 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-03 13:15 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-04 05:02 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-05 05:02 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 05:02 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 13:02 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 14:22 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 15:24 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 15:26 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 15:49 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-07 05:02 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-08 05:02 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-09 05:02 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-10 05:02 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-11 05:02 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-11 06:17 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче