fixed UT_Delete_CTrainingProfile
Students-of-the-city-of-Kostroma/Student-timetable pull request #1206
Opened 2019-09-22 09:54 UTC by bormolei

#1186

2019-09-22 13:54 UTC, YuriSilenok commented
Пожалуйста, расскажите почему вы выбрали такой набор меток для задачи и запроса?

2019-09-22 13:58 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Delete_CTrainingProfile.cs
> +			create_DirectionOfPreparation();
Есть ли смысл создавать метод если он вызывается единожды?

2019-09-22 13:59 UTC, YuriSilenok requested changes
Не все тесты содержат комментарии

2019-09-22 13:59 UTC, bormolei commented
Перепутал метку "Bug" она здесь не нужна, и забыл метку "Auto test". Исправлено

2019-09-22 14:05 UTC, bormolei commented on UnitTestOfTimetableOfClasses/UT_Delete_CTrainingProfile.cs
> +			create_DirectionOfPreparation();
В данном случае нет такой необходимости, можно все что содержится в методе перенести в определенный тест, я рассчитывал так что его можно будет использовать потом, если тесты к данной сущности будут добавляться. Также можно сделать вызов метода в определенном тесте, а не в Pre_condition_Del. Чтобы не вызывать данный метод в тех случаях когда это не требуется.

2019-09-22 14:10 UTC, YuriSilenok commented
> Не все тесты содержат комментарии

Не забудте

2019-09-22 14:31 UTC, bormolei commented
Второй commit был отправлен без изменений. Не сразу заметил

2019-09-22 18:52 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Delete_CTrainingProfile.cs
> +			create_DirectionOfPreparation();
Мне кажется что все же тело вашего метода это и есть часть прекондишена Pre_condition_Del

2019-09-22 18:53 UTC, YuriSilenok reviewed
Перенести тело метода create_DirectionOfPreparation в тело метода Pre_condition_Del

2019-09-23 08:54 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Delete_CTrainingProfile.cs
> +=======
@bormolei Вы надеюсь поняли что лучше не коммитить сразу после мержа, а сначала посмотреть все ли у Вас смержилось. Тем более git bush об этом сообщает

2019-09-23 08:58 UTC, YuriSilenok approved these changes
С моей стороны замечаний нет.

2019-09-23 17:28 UTC, FvckNeighbors approved these changes
Одобрено

2019-09-25 17:19 UTC, merged