fixed UT_Insert_CAcademicDegree #1188
Students-of-the-city-of-Kostroma/Student-timetable pull request #1207
Opened 2019-09-22 14:05 UTC by JennyShel18

2019-09-22 14:07 UTC, YuriSilenok requested changes
В описании нет ссылки на основную задачу

2019-09-22 14:11 UTC, JennyShel18 commented
Описание добавлено

вс, 22 сент. 2019 г. в 17:07, Юрий Силенок <notifications@github.com>:

> *@YuriSilenok* requested changes on this pull request.
>
> В описании нет ссылки на основную задачу
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1207?email_source=notifications&email_token=ALJO6YYMKQ54KSJLULHHIJLQK533BA5CNFSM4IZCYB52YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCFQBRRA#pullrequestreview-291510468>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALJO6YYDARAS2KUSKMUM7OTQK533BANCNFSM4IZCYB5Q>
> .
>

2019-09-22 14:13 UTC, YuriSilenok commented
Что за Шифр у вас в комментарии коммита?

2019-09-22 14:14 UTC, JennyShel18 commented
Видимо, случайно оставила, хотела сделать без комментария

2019-09-22 14:20 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Deleted_CTeacher.cs
>  			RefData.CTeacher.Insert(tcher);
Добавить проверку того, что добавилась строка

2019-09-22 14:22 UTC, YuriSilenok commented
> Видимо, случайно оставила, хотела сделать без комментария

Комментарии должны быть информативными

2019-09-22 15:51 UTC, JennyShel18 commented
Проверка сделана

2019-09-22 18:47 UTC, YuriSilenok reviewed
Стереть и поставить последнюю фигурную скобку, для замены табуляции на пробелы во всем файле

2019-09-26 19:10 UTC, YuriSilenok submitted a review, later dismissed

2019-09-26 19:10 UTC, YuriSilenok commented
Решить конфликт самостоятельно

2019-09-30 07:59 UTC, YuriSilenok requested changes
- синтаксические ошибки
- не все требования задачи применены ко всем текстам этого тесткомплекта

2019-12-23 16:25 UTC, YuriSilenok requested changes
```
2019-11-27T23:09:45.0129436Z Failed   Task_248_1
2019-11-27T23:09:45.0129819Z Error Message:
2019-11-27T23:09:45.0130194Z  Assert.AreEqual failed. Expected:<True>. Actual:<False>. 
2019-11-27T23:09:45.0130604Z Stack Trace:
2019-11-27T23:09:45.0131012Z    at UnitTestOfTimetableOfClasses.UT_Deleted_CTeacher.Task_248_1() in d:\a\1\s\UnitTestOfTimetableOfClasses\UT_Deleted_CTeacher.cs:line 19
```

2019-12-23 16:25 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Deleted_CTeacher.cs
> +        public void Task_248_1()
`[TestMethod]` - исправить форматирование кода

2019-12-23 16:25 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Deleted_CTeacher.cs
>              Assert.AreEqual(expected, actual);
Комментарий к коду не должен отделяться пустой строкой

2020-06-25 13:06 UTC, YuriSilenok commented
Какие есть обновления по этой задаче?

2020-06-26 05:04 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

2020-06-26 05:13 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

2020-06-27 05:04 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-27 05:12 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-28 05:04 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-28 05:11 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-29 05:04 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-29 05:12 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-30 05:04 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-07-01 05:04 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-07-01 21:46 UTC, JennyShel18 commented
Данную задачу пока проблематично решить, пока не добавлена нагрузка в RefData

2020-07-02 05:04 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-07-02 05:48 UTC, YuriSilenok commented
@JennyShel18 
Я обновил вашу ветку, работа с рефдатой должна стать более стабильной, пожалуйста, получите последние обновления из удаленного репозирия командой 
```
git ckeckout task-1187
git pull origin task-1187
```

2020-08-13 13:02 UTC, YuriSilenok commented
Задача с Вас снята, так как по ней давно не было активности.

2020-08-18 07:15 UTC, closed without merging