Создана форма редактирования или добавления записи
Students-of-the-city-of-Kostroma/Student-timetable pull request #121
Opened 2019-03-04 12:34 UTC by isengrims

Задача [#110](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/110)

2019-03-04 13:40 UTC, YuriSilenok requested changes

2019-03-04 13:40 UTC, YuriSilenok commented on TimetableOfClasses/Start.Designer.cs
> +            this.menuStrip1 = new System.Windows.Forms.MenuStrip();
Нужно настроить отступы. В место пробелов, табуляция.

2019-03-04 14:36 UTC, isengrims commented
@YuriSilenok 

Отменять коммит или просто с новым коммитом изменения запушить? 

Спасибо.

2019-03-04 14:41 UTC, YuriSilenok commented
Запрос не нужно закрывать.
Вы должны сделать изменения и залить изменения

2019-03-04 14:41 UTC, isengrims commented
@YuriSilenok 

Это не я 

Спасибо.

2019-03-04 14:42 UTC, YuriSilenok commented
Где в алгоритме увидели что Вы закрывает запрос на слияние?

2019-03-04 14:42 UTC, YuriSilenok commented
Таааак

2019-03-04 14:43 UTC, isengrims commented
@YuriSilenok 

Запрос на слияние закрыл другой пользователь

2019-03-04 14:44 UTC, YuriSilenok commented
@map82top объясните ваши действия, почему Вы закрыли запрос?

2019-03-04 14:44 UTC, isengrims commented
@YuriSilenok 

А как сделать так чтобы табы применились?

Спасибо

2019-03-04 14:47 UTC, map82top commented
Извините
Не понял как менять сторону мержа
Решил сделать в консоли
Для сохранения результатов мержа залил ветку Testing на сервер
Как это все отменить?

2019-03-04 15:15 UTC, isengrims commented
@YuriSilenok 

Мне отменить коммит и исправить на табы или просто новым коммитом запушить исправление с пробелов на табы?

Спасибо.

2019-03-05 15:52 UTC, YuriSilenok commented
Новым коммитом

2019-03-05 16:00 UTC, YuriSilenok commented
@map82top пожалуйста, идите в свой запрос на слияние и свою ветку. Мы постараемся без Вашей помощи разобраться как все исправлять.

2019-03-05 16:01 UTC, isengrims commented
@YuriSilenok 

1. Можно ли это исправить здесь на github'e в webeditore?
2. Мне менять пробелы на табуляцию для всего файла или толко для выделенных строк?

Спасибо.

2019-03-05 18:05 UTC, isengrims commented
@YuriSilenok 

Я исправил свои пробелы на табы, остальные мерж конфликты из-за того что какой то студент **сам**  замержил свои изменения. 
**Вопрос:** Нужно ли мне решать эти мердж конфликты? 

Спасибо

2019-03-06 20:40 UTC, YuriSilenok commented
Не думаю что такое возможно. Обычно отменяют весь коммит. Если коммит большой, то говорят что коммит был сделан не верно. Так как коммит ассоциируют с каким-то одним изменением (не обязательно одного файла, это логическое изменение)
> Можно как то отменить изменения только в 1 файле из коммита?

2019-03-07 06:02 UTC, YuriSilenok requested changes
Вы должны настроить табуляцию в качестве отступов.
После чего в созданных и измененых файлах снова поставьте последнюю закрывающую фигурную скобку. 
Это заменит пробелы на табуляцию.

2019-03-07 06:07 UTC, YuriSilenok commented
закрыт так как создана альтернативаня ветка task-110-1

2019-03-07 06:07 UTC, closed without merging