Task 1066
Students-of-the-city-of-Kostroma/Student-timetable pull request #1211
Opened 2019-09-22 20:23 UTC by GubanovAndrey

#1066

2019-09-23 08:38 UTC, YuriSilenok requested changes
Название запроса не соответствует основной задаче

2019-09-23 11:48 UTC, FvckNeighbors commented
Отсутствует веха

2019-09-23 12:44 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CGroup.cs
> +        public void task_250_1_1() // Изменение когда все поля отличаются
Старые комментарии убрать

2019-09-23 12:45 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CGroup.cs
> +            bool expected = true;
В Вашей версии тестов переменная с ожидаемым результатом не требуется

2019-09-23 12:51 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CGroup.cs
> +            bool expected = true;
Не используется в Ваших тестах

2019-09-23 13:24 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CGroup.cs
> +        private void setupData()
В C# принято методы называть с большой буквы

2019-09-23 20:20 UTC, GubanovAndrey commented on UnitTestOfTimetableOfClasses/UT_Update_CGroup.cs
> +            bool expected = true;
> Отсутствует веха

Мне ее точно нужно ставить ? Эта задача не на отработку спринта.

2019-09-23 20:24 UTC, GubanovAndrey commented on UnitTestOfTimetableOfClasses/UT_Update_CGroup.cs
> +            bool expected = true;
@YuriSilenok  
Здравствуйте. Не понял почему переменная не используется?

2019-09-23 20:25 UTC, GubanovAndrey commented
> Отсутствует веха

Мне точно нужно ее указывать? Задача не на спринт.

2019-09-24 12:22 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CGroup.cs
> +            bool expected = true;
Нашел где используется

2019-09-24 12:22 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CGroup.cs
> +            bool expected = true;
Увидел, простите

2019-09-26 18:54 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CGroup.cs
> +	[TestClass]
Табуляцию заменить на пробелы, можно удалить и поставить последнюю скобку в файле, произойдет автозамена

2019-09-26 18:56 UTC, YuriSilenok submitted a review, later dismissed
С моей стороны одно мелкое замечание, не буду ругаться если с ним мерж будет.

2019-09-27 21:14 UTC, FvckNeighbors approved these changes
Мёржи

2019-09-28 08:44 UTC, merged

2019-09-29 13:52 UTC, YuriSilenok commented
@GubanovAndrey зачем Вы перевесили на маня запрос?

2019-09-29 14:04 UTC, GubanovAndrey commented
@YuriSilenok Извините ошибся