Исправил сбои в автотестах UT_Delete_CEnclosures
Students-of-the-city-of-Kostroma/Student-timetable pull request #1217
Opened 2019-09-23 19:56 UTC by ifuwmnn

#1082

2019-09-23 20:33 UTC, FvckNeighbors commented
Назначь себя ответственным, добавь проект (доски) и веху

2019-09-26 16:11 UTC, ifuwmnn commented
Назначил ответственного, установил веху, и добавил проект.

2019-11-27 15:55 UTC, ifuwmnn commented
Исправил merge conflict

2019-11-27 17:29 UTC, Rogachev99 commented
Конфликт решен, но тест по прежнему не работает. Один из вариантов решения: Попробуй создать свой университет, и использовать его в данных.

2019-11-28 16:16 UTC, YuriSilenok requested changes
Получить исправления для этого сбоя
```
Failed   Task_395_1
Error Message:
 Test method UnitTestOfTimetableOfClasses.UT_Delete_CEnclosures.Task_395_1 threw exception: 
System.TypeInitializationException: The type initializer for 'LibOfTimetableOfClasses.RefData' threw an exception. ---> System.Data.InvalidConstraintException: Cannot create a DataRelation if Parent or Child Columns are not in a DataSet.
Stack Trace:
    at System.Data.DataRelation.Create(String relationName, DataColumn[] parentColumns, DataColumn[] childColumns, Boolean createConstraints)
   at System.Data.DataRelation..ctor(String relationName, DataColumn parentColumn, DataColumn childColumn, Boolean createConstraints)
   at System.Data.DataRelationCollection.Add(String name, DataColumn parentColumn, DataColumn childColumn)
   at LibOfTimetableOfClasses.RefData..ctor() in D:\a\1\s\LibOfTimetableOfClasses\RefData.cs:line 51
   at LibOfTimetableOfClasses.RefData..cctor() in D:\a\1\s\LibOfTimetableOfClasses\RefData.cs:line 26
--- End of inner exception stack trace ---
    at UnitTestOfTimetableOfClasses.UT_Delete_CEnclosures.Task_395_1() in D:\a\1\s\UnitTestOfTimetableOfClasses\UT_Delete_CEnclosures.cs:line 17
```

2019-11-28 16:16 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Delete_CEnclosures.cs
> +           //arrange
Верните перфекционисту пробел

2019-11-28 16:16 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Delete_CEnclosures.cs
>              RefData.CEnclosures.Insert(gr);
Любое изменение данных долно проверятся

2019-12-11 15:29 UTC, ifuwmnn commented
@YuriSilenok  Свои авто тесты я исправил, но github выдаёт, что есть много не пройденных 
авто тестов. Только они ко мне не относятся. Должен ли я их исправлять?

2019-12-23 16:36 UTC, YuriSilenok requested changes

2019-12-23 16:36 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Delete_CEnclosures.cs
> +using LibOfTimetableOfClasses;
Что здесь изменилось?

2019-12-23 16:36 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Delete_CEnclosures.cs
> +            RefData.DataSet.Clear();
запрещено использовать

2020-05-04 08:55 UTC, ifuwmnn commented
@YuriSilenok, здравствуйте, были исправлены сбои в автотестах, проверьте пожалуйста.

2020-05-05 15:26 UTC, YuriSilenok requested changes
не все замечания исправлены

2020-05-05 15:42 UTC, ifuwmnn commented
Добавил проверку

2020-05-21 10:33 UTC, ifuwmnn commented
@YuriSilenok здравствуйте, я добавил проверку

2020-05-24 07:41 UTC, YuriSilenok requested changes
Вы добавили чистку данных методом Delete, но при этом не проверяете, действительно ли удалены были данные. Нужно добавить такую проверку

2020-05-24 07:41 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Delete_CEnclosures.cs
> +            RefData.CUniversity.Delete(grUni);
Добавить проверку того, что данные были удалены

2020-05-24 07:41 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Delete_CEnclosures.cs
> +            RefData.CEnclosures.Delete(gr);
Добавить проверку того, что данные были удалены

2020-05-24 12:20 UTC, ifuwmnn commented
@YuriSilenok Здравствуйте, добавил проверку.

2020-05-24 12:22 UTC, ifuwmnn commented
Здравсвуйте, добавил проверку.
Проверьте пожалуйста.

вс, 24 мая 2020 г. в 10:41, Юрий Силенок <notifications@github.com>:

> *@YuriSilenok* requested changes on this pull request.
>
> Вы добавили чистку данных методом Delete, но при этом не проверяете,
> действительно ли удалены были данные. Нужно добавить такую проверку
> ------------------------------
>
> In UnitTestOfTimetableOfClasses/UT_Delete_CEnclosures.cs
> <https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1217#discussion_r429608498>
> :
>
> > +            RefData.CEnclosures.Delete(gr);
>
> +            RefData.CUniversity.Delete(grUni);
>
>
> Добавить проверку того, что данные были удалены
> ------------------------------
>
> In UnitTestOfTimetableOfClasses/UT_Delete_CEnclosures.cs
> <https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1217#discussion_r429608545>
> :
>
> >              bool expected = false;
>
>              //act
>
>              bool actual = RefData.CEnclosures.Delete(gr);
>
>              //assert
>
>              Assert.AreEqual(expected, actual);
>
> +            RefData.CEnclosures.Delete(gr);
>
>
> Добавить проверку того, что данные были удалены
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1217#pullrequestreview-417334439>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALLNWUBVGV75KSAWLNEQD5TRTDFRVANCNFSM4IZQXAQQ>
> .
>

2020-05-25 07:05 UTC, YuriSilenok requested changes
У Вас имеются синтаксические ошибки в тестах.
Почему Вы сдаете код не запуская тесты или не смотря на [отчеты](https://dev.azure.com/silenok-86/Student-timetable/_build/results?buildId=2045&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=86dd5fa6-f51e-57a1-6dd4-575fd75fc7ef) из непрерывной интеграции

2020-05-25 09:20 UTC, ifuwmnn commented
@YuriSilenok Исправил, проверьте пожалуйста.

2020-05-25 09:25 UTC, ifuwmnn commented
Здравствуйте, исправил ошибки, проверьте пожалуйста.

пн, 25 мая 2020 г. в 10:05, Юрий Силенок <notifications@github.com>:

> *@YuriSilenok* requested changes on this pull request.
>
> У Вас имеются синтаксические ошибки в тестах.
> Почему Вы сдаете код не запуская тесты или не смотря на отчеты
> <https://dev.azure.com/silenok-86/Student-timetable/_build/results?buildId=2045&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=86dd5fa6-f51e-57a1-6dd4-575fd75fc7ef>
> из непрерывной интеграции
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1217#pullrequestreview-417497789>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALLNWUDUQB6BMLIUB3CP453RTIKCVANCNFSM4IZQXAQQ>
> .
>

2020-05-25 10:37 UTC, YuriSilenok requested changes
Относительно теста Task_395_2
Исходя из описания нужно попробовать удалить данные из пустой таблицы.
У вас нет на это проверки. Скорее всего вы и не сможете привести систему к этому состоянию, так как в ней много данных, которых требуются для других тестов. Это значит что и сам тест является неверным. Вообще здесь нет тестов, которые проверяли правильность удаления данных.
Вот [класс](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/Elite/LibOfTimetableOfClasses/CEnclosures.cs) содержащий тестируемый метод.
Обратите внимание на условие поиска удаляемой стоки
`if ((string)this.Rows[i]["Name"] == mEnclosures.Name && (string)this.Rows[i]["University"] == mEnclosures.University)`
У Вас нет тестов проверяющих, что метод работает именно так.

По сути, все тесты которые вы имеете сейчас плохие (спасибо Вашим коллегам которые эти тесты сочиняли)
Думаю вам нужно воспользоваться методом белого ящика что бы составить тесты заново.
Это не сложный метод. Думаю результаты будет лучше представить в задаче #1082
В помощь по этой методике даю [презентацию](https://docs.google.com/presentation/d/1eSFl5isZBYNFEqm3ndsGC1NSg4Y5D2bcSGysnJBBF6w/edit?usp=sharing)
Отчет представить по [этому](https://docs.google.com/document/d/1H6353mZjLjMmCq-1A7IrnKdwBUQXyg81wjauXlad3XY/edit) образцу

2020-05-27 12:28 UTC, ifuwmnn commented
@YuriSilenok Здравствуйте, можете разъяснить,оба ли теста надо переписать, что должен проверять второй тест, как работает метод Delete или как работает удаление из пустой таблицы.  
Спасибо.

2020-05-27 12:34 UTC, ifuwmnn commented
Здравствуйте.
Можете разъяснить, оба ли теста надо переписать, что должен проверять
второй тест, работу метода Delete или как работает удаление из пустой
таблицы.
Спасибо.

пн, 25 мая 2020 г. в 13:37, Юрий Силенок <notifications@github.com>:

> *@YuriSilenok* requested changes on this pull request.
>
> Относительно теста Task_395_2
> Исходя из описания нужно попробовать удалить данные из пустой таблицы.
> У вас нет на это проверки. Скорее всего вы и не сможете привести систему к
> этому состоянию, так как в ней много данных, которых требуются для других
> тестов. Это значит что и сам тест является неверным. Вообще здесь нет
> тестов, которые проверяли правильность удаления данных.
> Вот класс
> <https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/Elite/LibOfTimetableOfClasses/CEnclosures.cs>
> содержащий тестируемый метод.
> Обратите внимание на условие поиска удаляемой стоки
> if ((string)this.Rows[i]["Name"] == mEnclosures.Name &&
> (string)this.Rows[i]["University"] == mEnclosures.University)
> У Вас нет тестов проверяющих, что метод работает именно так.
>
> По сути, все тесты которые вы имеете сейчас плохие (спасибо Вашим коллегам
> которые эти тесты сочиняли)
> Думаю вам нужно воспользоваться методом белого ящика что бы составить
> тесты заново.
> Это не сложный метод. Думаю результаты будет лучше представить в задаче
> #1082
> <https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/1082>
> В помощь по этой методике даю презентацию
> <https://docs.google.com/presentation/d/1eSFl5isZBYNFEqm3ndsGC1NSg4Y5D2bcSGysnJBBF6w/edit?usp=sharing>
> Отчет представить по этому
> <https://docs.google.com/document/d/1H6353mZjLjMmCq-1A7IrnKdwBUQXyg81wjauXlad3XY/edit>
> образцу
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1217#pullrequestreview-417622845>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALLNWUCXEWF7WSLKFTPS7O3RTJC75ANCNFSM4IZQXAQQ>
> .
>

2020-05-27 18:06 UTC, YuriSilenok commented
> @YuriSilenok Здравствуйте, можете разъяснить,оба ли теста надо переписать, что должен проверять второй тест, как работает метод Delete или как работает удаление из пустой таблицы.
> Спасибо.

> оба ли теста надо переписать

Скорее всего оба, будет понятно когда составите тесты по методологии белый ящик

> что должен проверять второй тест

Станет понятно когда воспользуетесь белым ящиком

> как работает метод Delete

У Вас есть его исходный код, вы можете изучить его

> как работает удаление из пустой таблицы

Согласно алгоритму, на который я уже давал ссылку ранее в комментариях

2020-05-30 14:05 UTC, ifuwmnn commented
Здравствуйте, Юрий Викторович.
Подскажите пожалуйста, в каком направлении мне двигаться. Я прочитал много
статей про белый ящик, но так и не понял, как его реализовать в рамках
задания.
Спасибо.

ср, 27 мая 2020 г. в 21:06, Юрий Силенок <notifications@github.com>:

> @YuriSilenok <https://github.com/YuriSilenok> Здравствуйте, можете
> разъяснить,оба ли теста надо переписать, что должен проверять второй тест,
> как работает метод Delete или как работает удаление из пустой таблицы.
> Спасибо.
>
> оба ли теста надо переписать
>
> Скорее всего оба, будет понятно когда составите тесты по методологии белый
> ящик
>
> что должен проверять второй тест
>
> Станет понятно когда воспользуетесь белым ящиком
>
> как работает метод Delete
>
> У Вас есть его исходный код, вы можете изучить его
>
> как работает удаление из пустой таблицы
>
> Согласно алгоритму, на который я уже давал ссылку ранее в комментариях
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1217#issuecomment-634843971>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALLNWUD37ZLUXGGMIHFRYVTRTVJBRANCNFSM4IZQXAQQ>
> .
>

2020-05-31 11:26 UTC, ifuwmnn commented
Здравствуйте, проверьте пожалуйста.

2020-05-31 12:58 UTC, YuriSilenok reviewed
Давайте по порядку, нам нужен код из тестируемого метода.
Первое что нужно сделать, разметить его. Как показано в презентации.
Покажите какой результат у вас появился.

2020-05-31 13:00 UTC, YuriSilenok commented
> Здравствуйте, проверьте пожалуйста.

Когда вы нащимаете на закольцованные стрелки это и есть сигнал к проверке.
Думаю сейчас мы должны разобраться с белым ящиком, потом будем решать что-то с тестами.

2020-05-31 14:39 UTC, ifuwmnn commented
![image](https://user-images.githubusercontent.com/47635280/83355086-b4e2ac80-a365-11ea-8d4b-d7c6cd03583d.png)

2020-05-31 14:45 UTC, YuriSilenok commented
Как это у вас две двойки? И как у вас из 5 ретерна в 6 ретерн попадает?

2020-05-31 14:49 UTC, ifuwmnn commented
Ошибся, из 5 не попадает

2020-05-31 14:50 UTC, ifuwmnn commented
две двойки, как в презентации 
![image](https://user-images.githubusercontent.com/47635280/83355288-325aec80-a367-11ea-9962-386aea72f0b5.png)

2020-06-01 06:54 UTC, YuriSilenok commented
Обратите снимание что на каждое условие идет уникальная цифра.
У вас же на два условия идет по 2

2020-06-01 10:09 UTC, ifuwmnn commented
![image](https://user-images.githubusercontent.com/47635280/83398986-14de5f00-a409-11ea-9368-e47b23f9e61a.png)
Тогда возможно так?

2020-06-03 08:45 UTC, ifuwmnn commented
Здравствуйте, возможно тогда так правильно?
[image: 83398986-14de5f00-a409-11ea-9368-e47b23f9e61a.png]

пн, 1 июн. 2020 г. в 09:54, Юрий Силенок <notifications@github.com>:

> Обратите снимание что на каждое условие идет уникальная цифра.
> У вас же на два условия идет по 2
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1217#issuecomment-636648655>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALLNWUE7LKJNFFRW2K3VI3TRUNGBPANCNFSM4IZQXAQQ>
> .
>

2020-06-10 15:00 UTC, YuriSilenok commented
картинки прикрепленные к почте не подгружаются на гитхаб

2020-06-11 06:31 UTC, YuriSilenok commented
> ![image](https://user-images.githubusercontent.com/47635280/83398986-14de5f00-a409-11ea-9368-e47b23f9e61a.png)
> Тогда возможно так?

у вас не обрабатывается второе условие в ветке if

2020-06-12 10:59 UTC, ifuwmnn commented
![image](https://user-images.githubusercontent.com/47635280/84495965-c9ec0380-acb4-11ea-8116-01b74c3833e6.png)
@YuriSilenok Здравствуйте,  тогда возможно так?

2020-06-13 15:10 UTC, YuriSilenok commented
Нельзя использовать двунаправленные стрелки, вы теряете регионы.

2020-06-14 14:32 UTC, ifuwmnn commented
![image](https://user-images.githubusercontent.com/47635280/84596191-f6468200-ae64-11ea-9174-08279af13a31.png)
@YuriSilenok Здравствуйте, возможна так?

2020-06-14 16:08 UTC, YuriSilenok commented
Добрый день.
У вас потерян ещё один регион.
Нумерации подвергаются в том числе начало и конец функции, в вашем случае
это фигурные скобки.

Внесите их на картинку и пронумеруйте.

вс, 14 июн. 2020 г., 17:32 Виноградов Александр <notifications@github.com>:

> [image: image]
> <https://user-images.githubusercontent.com/47635280/84596191-f6468200-ae64-11ea-9174-08279af13a31.png>
> @YuriSilenok <https://github.com/YuriSilenok> Здравствуйте, возможна так?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1217#issuecomment-643774710>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADROXL5JF7YVXJH4GKSI3Q3RWTNRJANCNFSM4IZQXAQQ>
> .
>

2020-06-15 15:11 UTC, ifuwmnn commented
![image](https://user-images.githubusercontent.com/47635280/84674377-881cc080-af33-11ea-8a22-6163fd998b4f.png)
Здравствуйте, возможно так?

2020-06-16 07:23 UTC, YuriSilenok commented
Привет,
уже ближе, но где закрывающая функцию фигурная скобка, она нам нужна. У вас по прежнему две конечные вершины.

2020-06-16 07:24 UTC, YuriSilenok commented
Сделайте так, что бы на скрине был весь код, относящийся к методу

2020-06-16 12:43 UTC, ifuwmnn commented
![image](https://user-images.githubusercontent.com/47635280/84775536-05097200-afe8-11ea-8810-ba7420b2d88d.png)
Здравствуйте, вроде поправил.

2020-06-16 14:06 UTC, YuriSilenok commented
с каждым разом все сложнее понять что вы нарисовали, могу порекомендовать вот эту бесплатную рисовалку на гугл диске.
![image](https://user-images.githubusercontent.com/14871471/84784595-2f146180-aff3-11ea-9976-b7fdf4f70bc1.png)

кажется в этой паутине все нормально.
давайте перейдем к следующему шагу, нарисуйте в ранее указанном приложении полученный управляющий граф и распределите регионы.

2020-06-18 15:53 UTC, ifuwmnn commented
![Новый рисунок](https://user-images.githubusercontent.com/47635280/85043325-e5637c80-b194-11ea-981a-7882da9e5f84.jpg)
Здравствуйте, я правильно понял задание?

2020-06-19 08:02 UTC, YuriSilenok commented
Добрый день,
да, мысль Вы поняли верно, но есть несколько замечаний.
- У вас три внешних региона R1, R3, R4. Метки регионов должны писаться внутри области ограниченной ребрами управляющего графа.
- Ошибка в регионе R3 в переходе 1-4

После этого вам нужно представить таблицу в которой бы были перечислены входные данные, которые бы позволили бы пройти по каждому маршруту в отдельности.

2020-06-19 08:57 UTC, ifuwmnn commented
![трпо](https://user-images.githubusercontent.com/47635280/85115149-dd9ee900-b223-11ea-9939-e017dc051f57.jpg)
Здравствуйте, исправил недочёты. По поводу переменных, нужны конкретные примеры или как я сделал в таблице?

2020-06-19 12:47 UTC, YuriSilenok commented
1. Если транспонируете таблицу, то код будет более читабельным.
2. Я говорил что нужно предоставить входные данные а не прописать условия которые срабатывают. Вы видели образец таблицы в лабораторной работе, могли бы сделать такую же?

2020-06-20 14:15 UTC, ifuwmnn commented
![трпо (2)](https://user-images.githubusercontent.com/47635280/85203938-9bf06a00-b319-11ea-8c26-e5671a1f0511.jpg)
Здравствуйте, возможно так?

2020-06-22 18:13 UTC, ifuwmnn commented
@yuri.silenok@gmail.com <yuri.silenok@gmail.com>
Здравствуйте, проверьте пожалуйста task-1082.
Спасибо.

2020-06-23 05:11 UTC, YuriSilenok commented
Добрый день,
пожалуйста, ознакомьтесь с [этим](https://docs.google.com/document/d/1H6353mZjLjMmCq-1A7IrnKdwBUQXyg81wjauXlad3XY/edit?usp=sharing) документом.
Я так и не увидел нужную таблицу, пожалуйста, приведите ваши результаты в соответствие с этим отчетом.

2020-06-24 13:32 UTC, ifuwmnn commented
![трпо (3)](https://user-images.githubusercontent.com/47635280/85565829-28f83380-b638-11ea-8432-95a95f6e0d37.jpg)
@YuriSilenok Здравствуйте, возможно так?

2020-06-25 06:30 UTC, YuriSilenok commented
Добрый день,

Есть несколько вопросов:
1. У Вас в таблице есть столбец Input value и в тестируемом методе один входной параметр, но экземпляр класса который ожидается, является моделью (MVC) и составной структурой данных. Это значит что в Input Value нужно указать в какоих полях какими данными должны быть заполнены. Для описания этого вы можете использовать JSON формат или что-то близкое к нему.
2. Так как Вы тестируете метод в котором логика зависит от значений выходящих за рамки метода, то нужно указывать состояние системы. Это значит, что таблица, которая перебирается в цикле, должна быть так же описана в таблице с тестами. Если бы мы использовали процедурный язык, то эта таблица передавалась бы во входных параметрах. Но у нас ООП и мы должны использовать принципы ООТ. Для разрешения этой проблемы нужно ввести еще один столбец RefData, в нем нужно будет указать из каких значимых данных должна состоять наша таблица, что бы маршрут верно сработал.
3. Вы написали фактический результат и статус теста. Я не увидел у вас автотестов, что бы вы могли получить эти результаты. Думаю вы посмешили.
4. В Test title указывается описание теста, а не то, какое условие сработало. В этот столбец нужно указывать описание ситуации из жизни системы в момент вызова этого метода.
5. Я так и не увидел на снимке метода, заголовок метода, именно он дает понимание количества входных параметров.

P.S. Мы почти закончили с белым ящиком.

Спасибо,
Юрий

2020-06-26 05:04 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

2020-06-26 05:13 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

2020-06-26 11:17 UTC, YuriSilenok reviewed
Я жду вашего решения, поторопитесь.

2020-06-28 16:48 UTC, ifuwmnn commented
![Снимоктрпо](https://user-images.githubusercontent.com/47635280/85953297-1489a300-b978-11ea-8e15-3209d0f25fc5.JPG)
![трпо (4)](https://user-images.githubusercontent.com/47635280/85953314-2e2aea80-b978-11ea-8431-9042f486eb55.jpg)
@YuriSilenok Здравствуйте, надеюсь что это правильно.

2020-06-29 06:23 UTC, YuriSilenok commented
Добрый день.
Выглядит верно, можете приступать к написанию тестов по этим сценариям.
Есть одно небольшое замечание, значения все же не совпадают
![image](https://user-images.githubusercontent.com/14871471/85979937-1b50fe00-b9ea-11ea-8344-348dec1ff449.png)

2020-06-30 08:07 UTC, ifuwmnn commented
@YuriSilenok Здравствуйте, если значения будут одинаковы, разве это не будет другими регионами?
![image](https://user-images.githubusercontent.com/47635280/86099527-43ab2c00-bac0-11ea-87fc-b5079c2bec97.png)

2020-07-02 05:42 UTC, YuriSilenok commented
Маршрут R2 1-2-1-6-7 будет пройден если имена не совпадают, в тестовых данных у вас как раз эта ситуация описана, но заголовок говорит что имена не должны совпадать, в этом случае алгоритм уйдет на маршрут R3 или R4/

Есть ли у Вас какие-то обновления по автотестам?

2020-07-02 11:34 UTC, ifuwmnn commented
> Маршрут R2 1-2-1-6-7 будет пройден если имена не совпадают, в тестовых данных у вас как раз эта ситуация описана, но заголовок говорит что имена не должны совпадать, в этом случае алгоритм уйдет на маршрут R3 или R4/
> 
> Есть ли у Вас какие-то обновления по автотестам?

Здравствуйте, работаю на этим.

2020-07-02 16:51 UTC, ifuwmnn commented
![image](https://user-images.githubusercontent.com/47635280/86388332-4e6ee800-bc9d-11ea-98af-6810b63418ad.png)
@YuriSilenok  Здравствуйте, я написал тесты, проверьте их правильность. Спасибо.

2020-07-03 08:31 UTC, YuriSilenok commented
Здравствуйте, это работает не так.
Когда вы пишите тесты, вы отправляете их на удаленный репозиторий, там запускается Azure.
Она публикует отчет о тестировании. Если там все нормально, после этого я смотрю на код

2020-07-03 09:27 UTC, ifuwmnn commented
> Здравствуйте, это работает не так.
> Когда вы пишите тесты, вы отправляете их на удаленный репозиторий, там запускается Azure.
> Она публикует отчет о тестировании. Если там все нормально, после этого я смотрю на код

@YuriSilenok Здравствуйте, я не могу зарегистрироваться на Azure, т.к. нет подходящей карты.

2020-07-03 10:06 UTC, YuriSilenok commented
Вам не нужно регистрироваться в Азуре, для этого проекта она уже настроена.
Все что вам нужно сделать, отдать свои изменения на удаленный репозиторий
И вы уже можете наблюдать за ходом своих тестов, если увидите что тесты прошли, то можете сделать повторный запрос на проверку (не на слияние)

2020-07-04 15:39 UTC, ifuwmnn commented
[проверка  метода delete белым ящиком.docx](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/files/4873082/delete.docx) 
https://docs.google.com/document/d/1SX3ZTRcYN3wx98cjMPxtKzwJz14dB96kA65ToCkxBUo/edit?usp=sharing
@YuriSilenok Здравствуйте, прикрепляю отчёт.
Можете объяснить, что такое тест-комплект и какую таблицу сценариев я должен исправить. 
Спасибо.

2020-07-04 16:43 UTC, YuriSilenok commented
Обойдёмся без сценариев. См. Чат
У вас метки R1 и  R4 находятся в одном регионе. См. Чат.

2020-07-05 09:32 UTC, ifuwmnn commented
> Обойдёмся без сценариев. См. Чат
> У вас метки R1 и R4 находятся в одном регионе. См. Чат.

@YuriSilenok Здравствуйте, исправил регионы. 
https://docs.google.com/document/d/1SX3ZTRcYN3wx98cjMPxtKzwJz14dB96kA65ToCkxBUo/edit?usp=sharing

2020-07-06 09:37 UTC, YuriSilenok requested changes
- Хотел бы увидеть отчет о тестировании белым ящиком на гитхаб
- Не  увидел комментариев к тестам.

2020-07-06 15:04 UTC, YuriSilenok requested changes
Я ожидаю отчет на гитхабе

2020-07-06 15:09 UTC, YuriSilenok requested changes
Вордовских файлов не должно быть в папке
Docs/REPORT.docx

2020-07-06 15:59 UTC, YuriSilenok requested changes
У каждого отчета своя папка, прочитайте чат

2020-07-06 16:01 UTC, YuriSilenok commented
вы хоть сами проверяйте себя, посмотрите какую хрень вы прислали
![image](https://user-images.githubusercontent.com/14871471/86614012-09a7c180-bfbb-11ea-9152-0f265b7c877e.png)

2020-07-06 16:02 UTC, ifuwmnn commented
> вы хоть сами проверяйте себя, посмотрите какую хрень вы прислали
> ![image](https://user-images.githubusercontent.com/14871471/86614012-09a7c180-bfbb-11ea-9152-0f265b7c877e.png)

у меня отображалось нормально

2020-07-06 16:03 UTC, YuriSilenok commented
скрин приложите всей страницы

2020-07-06 16:04 UTC, YuriSilenok commented
не забудьте обновить страницу прежде чем делать скрин

2020-07-06 16:04 UTC, ifuwmnn commented
> У каждого отчета своя папка, прочитайте чат

![image](https://user-images.githubusercontent.com/47635280/86614288-6e631c00-bfbb-11ea-81b3-63115b609649.png)
Просто на этом скрине скрины и отчёт в одной папке

2020-07-06 16:05 UTC, YuriSilenok commented
Внимательнее пожалуйста
![image](https://user-images.githubusercontent.com/14871471/86614418-a36f6e80-bfbb-11ea-92df-24ea36aea405.png)

2020-07-06 17:58 UTC, YuriSilenok commented
Так как я ухожу в отпуск и не имею более возможности уделять вам целый день. То вводу следующую проверки работ. Пусть когда вы готовы отдавать на проверку, вы в качестве проверяющих назначаете все ваших коллег по горю. Если хотя бы двое из них говорят что все хорошо, то вы добавляете в качестве проверяющего меня. Список ников можно найти в таблице по поссылке.

https://docs.google.com/spreadsheets/d/1GL9mDzYrl9kAgqGBcz5EHABCn_00m8nzLO3Yl99hlPI/edit?usp=sharing
[Ссылка]
ТРПО должники
https://docs.google.com/spreadsheets/d/1GL9mDzYrl9kAgqGBcz5EHABCn_00m8nzLO3Yl99hlPI/edit?usp=sharing

2020-07-06 17:59 UTC, YuriSilenok requested changes
Так как я ухожу в отпуск и не имею более возможности уделять вам целый день. То вводу следующую проверки работ. Пусть когда вы готовы отдавать на проверку, вы в качестве проверяющих назначаете все ваших коллег по горю. Если хотя бы двое из них говорят что все хорошо, то вы добавляете в качестве проверяющего меня. Список ников можно найти в таблице по поссылке.

https://docs.google.com/spreadsheets/d/1GL9mDzYrl9kAgqGBcz5EHABCn_00m8nzLO3Yl99hlPI/edit?usp=sharing
[Ссылка]
ТРПО должники
https://docs.google.com/spreadsheets/d/1GL9mDzYrl9kAgqGBcz5EHABCn_00m8nzLO3Yl99hlPI/edit?usp=sharing

2020-07-07 17:34 UTC, ssas18 reviewed
@ifuwmnn , Сань, в отчете(report.md у тебя не отображаются скриншоты из-за того что ты указал разные форматы(jpeg и jpg) так же таблица с путями(сценарии тестирования) отображается неверно, там нужно добавить символы 
![image](https://user-images.githubusercontent.com/47377817/86820056-34644980-c091-11ea-8aa9-aa518380f78d.png)
и скорее всего убрать лишние "enter"
Хороший пример заполнения отчета в примере у Юрия викторовича, и, скорее всего, тебе надо из своей папки docks удалить его отчет

2020-07-08 09:29 UTC, ifuwmnn commented
Исправил ошибки в отчёте.

2020-07-08 10:36 UTC, ssas18 submitted a review, later dismissed
Я не знаю на счет того, можно ли что бы в папке Docs лежали 2 папки с отчетами, 1 пример, 1 твой, но надеюсь это не критично, и, пожалуйста, просмотри мой отчеты(#1280 , #1066 )

2020-07-08 12:26 UTC, ZhizhikinIvan submitted a review, later dismissed

2020-07-08 13:03 UTC, YuriSilenok requested changes
Регионов должно быть больше, товарищи проверяющих, прошу тщательнее проверять.

2020-07-08 18:14 UTC, JennyShel18 submitted a review, later dismissed

2020-07-09 18:45 UTC, YuriSilenok commented
![image](https://user-images.githubusercontent.com/14871471/87078538-7b874180-c22d-11ea-9474-5a88fa229804.png)
меня сейчас запросили, сейчас нет двух апрувов от членов команды?

2020-07-09 18:53 UTC, ssas18 submitted a review, later dismissed

2020-07-10 18:08 UTC, ZhizhikinIvan submitted a review, later dismissed

2020-07-10 19:27 UTC, YuriSilenok requested changes
![image](https://user-images.githubusercontent.com/14871471/87190582-65e04d80-c2fb-11ea-9535-538473a78bb5.png)
У этого блока должны быть порядковые номера начиная с 1
![image](https://user-images.githubusercontent.com/14871471/87190827-e606b300-c2fb-11ea-8708-5e43d868d34f.png)
Вот так выглядит конструктор класса который вы передаете на вход. 
Обратите внимание, что входных данных по сути больше для это метода. Вам нужно перегрузить ваши тестами проверки на то, что остальные параметры не проверяются в условии.
![image](https://user-images.githubusercontent.com/14871471/87191011-3da51e80-c2fc-11ea-8e9b-9e7845425048.png)
А так же обратите что у вас имеются ограничения на уникальность в некоторых столбцах,
![image](https://user-images.githubusercontent.com/14871471/87191116-675e4580-c2fc-11ea-8654-ea2ec549d00b.png)
Пожалуйста, внести скринт этого кода в свой отчет, сделав в нем только нумерацию так, что бы нумерация не перекрывала код.

2020-07-11 18:03 UTC, ssas18 reviewed
Скорее всего тесты должны нумероваться так: 395_1, 395_2 ...

2020-07-12 11:47 UTC, ssas18 submitted a review, later dismissed

2020-07-12 16:26 UTC, ifuwmnn commented
@YuriSilenok  Здравствуйте, подскажите пожалуйста по поводу замечаний про входные данные и их уникальность. 
Мне нужно просто добавить больше данных или нужно написать больше тестов? И разве уникальность касается моего метода? Спасибо.

2020-07-14 19:06 UTC, YuriSilenok commented
> Мне нужно просто добавить больше данных или нужно написать больше тестов?

Вам нужно описать входные параметры подробнее. У вас описаны не все поля передаваемого экземпляра модели.

>  И разве уникальность касается моего метода?

Да, Вы правы, методы удаления не касаются проверки уникальности данных.

2020-07-15 17:09 UTC, ifuwmnn commented
Добавил больше входных параметров в отчёт.

2020-07-17 06:40 UTC, ssas18 submitted a review, later dismissed

2020-07-17 08:49 UTC, Heriuple submitted a review, later dismissed

2020-07-19 15:10 UTC, YuriSilenok requested changes
Проверил не полностью, остановился на трех замечаниях, надеюсь все их прочтут и проверят свой код на предмет этих ошибок.

2020-07-19 15:10 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Delete_CEnclosures.cs
>          }
В заголовке теста говориться что мы выполняем удаление в условиях когда таблица пуста. 
Но я не увидел что проверку на то, что таблица действительно пуста.

2020-07-19 15:10 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Delete_CEnclosures.cs
> +            MUniversity grUni2 = new MUniversity("4401906286", "ВТБ", "Костьомкой Госуьарственный Унивеьситет", "159005, Костьомская оьласть, р. Коьтрома, пл. Дзержиьского, 27", "158005, Костьомская
Уточните пожалуйста, зачем создается экземпляр класса университет?

2020-07-19 15:10 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Delete_CEnclosures.cs
> +            refData.CEnclosures.Insert(gr);
Пожалуйста, делайте проверки при манипуляции с данными, ведь если они не выполнились, то результаты теста не должны считаться валидными.

2020-07-21 13:25 UTC, ifuwmnn commented on UnitTestOfTimetableOfClasses/UT_Delete_CEnclosures.cs
> +            MUniversity grUni2 = new MUniversity("4401906286", "ВТБ", "Костьомкой Госуьарственный Унивеьситет", "159005, Костьомская оьласть, р. Коьтрома, пл. Дзержиьского, 27", "158005, Костьомская
Здравствуйте, я должен использовать уже существующие университеты, а не создавать новые?

2020-07-21 15:29 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Delete_CEnclosures.cs
> +            MUniversity grUni2 = new MUniversity("4401906286", "ВТБ", "Костьомкой Госуьарственный Унивеьситет", "159005, Костьомская оьласть, р. Коьтрома, пл. Дзержиьского, 27", "158005, Костьомская
Вы можете использовать оба подхода, просто Вы создали строку, а в таблицу ее не добавляете.

2020-07-23 11:51 UTC, ssas18 submitted a review, later dismissed

2020-07-26 14:14 UTC, ifuwmnn commented
Если у кого-нибудь есть предложения как исправить то , что тест Task_395_1 фейлится из-за того что refdata заполнена, буду благодарен их услышать.

2020-07-27 16:46 UTC, ssas18 submitted a review, later dismissed

2020-07-28 18:01 UTC, ZhizhikinIvan submitted a review, later dismissed

2020-07-30 19:57 UTC, YuriSilenok commented
> Если у кого-нибудь есть предложения как исправить то , что тест Task_395_1 фейлится из-за того что refdata заполнена, буду благодарен их услышать.

Предлагаю поднять задачу на отделение инициализации данных рефдаты из конструктора рефдаты. Тогда вы сможете создавать тестовые данные тогда, когда надо.

2020-07-30 20:00 UTC, YuriSilenok requested changes
Я не смогу одобрить запрос в котором фейлятся тесты, потому что ещё не решили проблему у которой есть варианты решений. По заданию нужно устранить сбои, так что я не очень понимаю почему есть другие одобрения.

2020-08-07 09:19 UTC, ifuwmnn commented
@YuriSilenok Здравствуйте, в этой ветке нет активности т.к. для её завершения нужно чтобы была завершина задача #1323

2020-08-11 17:09 UTC, YuriSilenok commented
> @YuriSilenok Здравствуйте, в этой ветке нет активности т.к. для её завершения нужно чтобы была завершина задача #1323

Задача была выдана на исполнение. 
Следите за ее исполнением, думаю она будет завершена быстро.

2020-08-20 05:02 UTC, YuriSilenok commented
Задача с Вас снята, так как по ней давно не было активности.

2020-08-24 05:02 UTC, YuriSilenok commented
Задача с Вас снята, так как по ней давно не было активности.

2020-08-25 10:32 UTC, ifuwmnn commented
@YuriSilenok  В задаче нет активности т.к. меня блокирует задача #1323

2020-08-27 06:09 UTC, YuriSilenok requested changes
Знайте, когда вы встречаете return, происходит прерывание работы функции, это значит что управление передается на выход функции.
![image](https://user-images.githubusercontent.com/14871471/91398648-2c30bb00-e845-11ea-94a2-026a66e4bb7e.png)

2020-08-27 14:16 UTC, ifuwmnn commented
> Знайте, когда вы встречаете return, происходит прерывание работы функции, это значит что управление передается на выход функции.
> ![image](https://user-images.githubusercontent.com/14871471/91398648-2c30bb00-e845-11ea-94a2-026a66e4bb7e.png)

@YuriSilenok , Здравствуйте. 
 Мне нужно перерисовать этот граф? Вроде это не должно отобразиться на коде.

2020-08-27 19:18 UTC, YuriSilenok commented
> > Знайте, когда вы встречаете return, происходит прерывание работы функции, это значит что управление передается на выход функции.
> > ![image](https://user-images.githubusercontent.com/14871471/91398648-2c30bb00-e845-11ea-94a2-026a66e4bb7e.png)
> 
> @YuriSilenok , Здравствуйте. 
>  Мне нужно перерисовать этот граф? Вроде это не должно отобразиться на коде.

Вершина 6 выпадет из маршрута.

2020-08-28 09:12 UTC, ifuwmnn commented
> > > Знайте, когда вы встречаете return, происходит прерывание работы функции, это значит что управление передается на выход функции.
> > > ![image](https://user-images.githubusercontent.com/14871471/91398648-2c30bb00-e845-11ea-94a2-026a66e4bb7e.png)
> > 
> > 
> > @YuriSilenok , Здравствуйте.
> > Мне нужно перерисовать этот граф? Вроде это не должно отобразиться на коде.
> 
> Вершина 6 выпадет из маршрута.

@YuriSilenok  Дак маршрут из четвёрки не попадает в шесть.

2020-08-28 09:32 UTC, ifuwmnn commented
![image](https://user-images.githubusercontent.com/47635280/91545611-eef22900-e929-11ea-9767-da45424aee63.png)
@YuriSilenok , Юрий Викторович, redData вроде была отделена, но тест всё ещё фэйлится. Я посмотрел код и разве InitData должен вызываться в RefData? Он ведь тогда автоматически её заполняет. Я удалил вызов и тест прошёл.

2020-08-28 09:35 UTC, ifuwmnn commented
> ![image](https://user-images.githubusercontent.com/47635280/91545611-eef22900-e929-11ea-9767-da45424aee63.png)
> @YuriSilenok , Юрий Викторович, redData вроде была отделена, но тест всё ещё фэйлится. Я посмотрел код и разве InitData должен вызываться в RefData? Он ведь тогда автоматически её заполняет. Я удалил вызов и тест прошёл.

Хм, а в Github строчки нет, странно я вроде скачивал обновлённый репазиторий

2020-08-28 11:10 UTC, YuriSilenok commented
Вам сообщили о том, что вы должны получить изменения из ветки dev?

2020-08-28 11:11 UTC, ifuwmnn commented
> Вам сообщили о том, что вы должны получить изменения из ветки dev?

Нет

2020-08-28 11:30 UTC, YuriSilenok commented
> @YuriSilenok В задаче нет активности т.к. меня блокирует задача #1323

а вы видели что эта задача завершена, задача которая вас блокировала?

2020-08-28 11:34 UTC, YuriSilenok commented
хотя нет, по статусу она не завершена, но вы могли это узнать только из чата
если вы знали что она завершена, то почему не получили обновления, которые бы разблокировали вашу задачу?
если вы не знали что она завершена, то почему начали какую-то активность по этой задаче?

2020-08-28 11:35 UTC, YuriSilenok commented
прежде чем мержить, нужно почитать об этом, хоть чуть-чуть
![image](https://user-images.githubusercontent.com/14871471/91556648-be1aef80-e93b-11ea-919b-5272d59b1fce.png)

2020-08-28 11:36 UTC, ifuwmnn commented
> хотя нет, по статусу она не завершена, но вы могли это узнать только из чата
> если вы знали что она завершена, то почему не получили обновления, которые бы разблокировали вашу задачу?
> если вы не знали что она завершена, то почему начали какую-то активность по этой задаче?

Что мне нужно сделать с поднятой мной задачей, на отделение refdata?

2020-08-28 11:55 UTC, YuriSilenok commented
> > хотя нет, по статусу она не завершена, но вы могли это узнать только из чата
> > если вы знали что она завершена, то почему не получили обновления, которые бы разблокировали вашу задачу?
> > если вы не знали что она завершена, то почему начали какую-то активность по этой задаче?
> 
> Что мне нужно сделать с поднятой мной задачей, на отделение refdata?

С Самой задачей пока ничего, она не на Вас висит.
Человек, который ее делает, должен сейчас оповестить всех о том, нужно получить обновления из дев, после этого он перевешивает на меня эту задачу, так как она выдавалась мной. я перевешиваю на Вас. Вы подтверждаете комментарием что вы получили его обновления и ваша задача действительно больше не заблокирована. После этого вы отдаете ее мне, я ставлю Соколову отметку в журнал. Вы можете подтвердить или не подтвердить прямо сейчас, что все сделано верно. это ускорит процесс.

2020-08-28 11:56 UTC, YuriSilenok requested changes
по конфликту

2020-08-28 11:56 UTC, YuriSilenok commented on LibOfTimetableOfClasses/RefData.cs
> +
разрыв убрать

2020-08-28 11:56 UTC, YuriSilenok commented on LibOfTimetableOfClasses/RefData.cs
> +            ec99c5b9657d2f21f4c5e0e4f297bac66598dd51
осталось от неправильно решенного мержконфликта

2020-08-28 11:56 UTC, YuriSilenok commented on LibOfTimetableOfClasses/RefData.cs
> +
разрыв убрать

2020-08-28 11:56 UTC, YuriSilenok commented on LibOfTimetableOfClasses/RefData.cs
> +            ec99c5b9657d2f21f4c5e0e4f297bac66598dd51
осталось от неправильно решенного мержконфликта

2020-08-28 12:06 UTC, YuriSilenok requested changes
Почти, но невидимые пробелы оказались проворнее переносов строки

2020-08-28 12:06 UTC, YuriSilenok commented on LibOfTimetableOfClasses/RefData.cs
> +            DataSet.Relations.Add("TypesOfOccupations-AcademicLoad", CTypesOfOccupations.Columns["FullName"], CAcademicLoad.Columns["KindOfLesson"]);
Лишние пробелы после ;

2020-08-28 12:06 UTC, YuriSilenok commented on LibOfTimetableOfClasses/RefData.cs
> +            DataSet.Relations.Add("University-Enclosures", CUniversity.Columns["FullName"], CEnclosures.Columns["University"]);
Лишние пробелы после ;

2020-08-28 12:11 UTC, YuriSilenok commented
Что там с блокировкой ваших тестов?

2020-08-28 12:15 UTC, ifuwmnn commented
> Что там с блокировкой ваших тестов?

Мои тесты все прошли

2020-08-28 12:31 UTC, YuriSilenok commented
ждем двух проверок от команды и проверяю я.
сейчас вы можете заняться проверкой работ команды или другим таском.

2020-08-28 12:43 UTC, ifuwmnn commented
> ждем двух проверок от команды и проверяю я.
> сейчас вы можете заняться проверкой работ команды или другим таском.

К сожалению у меня нет другого таска, можете выдать?

2020-08-28 12:46 UTC, YuriSilenok commented
> > ждем двух проверок от команды и проверяю я.
> > сейчас вы можете заняться проверкой работ команды или другим таском.
> 
> К сожалению у меня нет другого таска, можете выдать?


Тогда вы можете пойти по пути User Story.
Как это делать, было описано ранее в чате.
Проверяя другие работы, вы ускорите проверку и своей работы.

2020-08-29 12:34 UTC, ZhizhikinIvan approved these changes, later dismissed

2020-08-29 12:43 UTC, ssas18 submitted a review, later dismissed

2020-08-29 12:43 UTC, ssas18 commented on UnitTestOfTimetableOfClasses/UT_Delete_CEnclosures.cs
> +            Assert.AreEqual(refData.CEnclosures.Rows.Count == 0, true);
Для методов класса assert  нужно использовать другую перегрузку метода, примерно так она должна выглядеть:

![image](https://user-images.githubusercontent.com/47377817/91328691-e8e83500-e7cf-11ea-97e0-8d729b93afdd.png)

2020-08-29 18:38 UTC, YuriSilenok commented
Проверять буду в понедельние

2020-08-29 18:38 UTC, YuriSilenok commented
Проверять буду в понедельник

2020-08-29 19:58 UTC, Alphavite51 commented
Ветка смержена, можете продолжать работу, вам нужно мержить dev в вашу ветку!

2020-09-02 08:03 UTC, YuriSilenok commented
это сообщение о том, что блокирующая задача выполнена?
Если да, то об этом ни слова не написано в вашем сообщении.
Непонятно зачем человеку нужно что-то мержить.

2020-09-02 08:06 UTC, YuriSilenok requested changes
![image](https://user-images.githubusercontent.com/14871471/91955788-5b936c00-ed0c-11ea-9ff6-596761129985.png)
не нужно собирать мусор, оставьте один файл

2020-09-02 08:06 UTC, YuriSilenok commented on Docs/UT_Delete_CEnclosures/REPORT.md
> +| R1 | Task_395_1 | check that table isn’t empty | empty | “Name”:“Я” “University”:”Костьомкой Госуьарственный Унивеьситет” "Address":"Дзержинского" "Phone":"112111" "Comment" "8" | false | false | P
> check that table isn’t empty

Вы тестируете не состояния таблицы, а определенный метод, так в чем смысл теста?

2020-09-04 06:46 UTC, ssas18 submitted a review, later dismissed
Вроде как вышеуказанные замечания исправлены

2020-09-04 09:48 UTC, YuriSilenok commented
намекаю, если вы исправили мое замечание или другого человека, нужно запросить повторную проверку, а то ваш запрос висит без активности

2020-09-05 05:02 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1342', '#1322', '#1309', '#1295', '#1294', '#1228']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-05 14:27 UTC, ifuwmnn commented
> У вас есть непроверенные запросы ['#1342', '#1322', '#1309', '#1295', '#1294', '#1228']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

Проверил запросы.

2020-09-06 05:02 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1341']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-06 08:04 UTC, MyachevM commented
> 
> 
> Вроде как вышеуказанные замечания исправлены

Соглашусь с коллегой

2020-09-06 08:04 UTC, MyachevM approved these changes, later dismissed

2020-09-07 14:29 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1341']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-07 14:40 UTC, YuriSilenok requested changes
Переводите в сценариях на русский все. в комментариях к автотестам все корректно описано, а на инглише, размыто.

2020-09-07 14:40 UTC, YuriSilenok commented on Docs/UT_Delete_CEnclosures/REPORT.md
> +| R4 | Task_395_4 | correct execution of code |  “Name”:“Я” “University”:”Костьомкой Госуьарственный Унивеьситет” "Address":"Дзержинского" "Phone":"112111" "Comment" "8" | “Name”:“Я” “University”:”Ко
>  correct execution of code 

во всех остальных случая код выполняется не корректно?
Что это значит? в чем идея теста?

2020-09-07 14:40 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Delete_CEnclosures.cs
> +        /// Удаление данных при не совпадающих значениях поля Name
Удаление? мы ожидаем удаление данных?

2020-09-07 14:40 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Delete_CEnclosures.cs
> +            Assert.AreEqual(refData.CUniversity.Insert(grUni), true, "Запись не добавлена");
> "Запись не добавлена"

вот мы получили сбой по тесту с заголовком `Удаление данных из пустой таблицы` и сообщением `Запись не добавлена`. Вам ведь для понимания того, что произошло в тесте, нужно будет открывать код теста, смотреть в какой строке это произошло и только тогда вы сообразите что это было. Сообщения о сбоях должны быть исчерпывающими. Опишите о какой таблице идет речь.

2020-09-07 14:40 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Delete_CEnclosures.cs
> +        /// Удаление данных при не совпадающих значениях поля Name
> поля Name

никаких указаний на поля или другие объекты инфраструктуры, это тест имеющий проверить что-то логическое. вот и распишите, какое ограничение вы проверяете.

2020-09-08 10:48 UTC, ssas18 approved these changes

2020-09-08 17:58 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы []. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-08 17:58 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1335', '#1322']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-08 18:23 UTC, MyachevM approved these changes

2020-09-09 19:03 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1335', '#1322', '#1309', '#1295', '#1294']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-10 06:07 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы []. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-10 06:07 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1335', '#1322', '#1309', '#1295', '#1294']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-10 06:12 UTC, YuriSilenok commented
> У вас есть непроверенные запросы []. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

Прошу прощение, из старого скрипта не убрал косячную проверку, сам запрошу проверку повторно

2020-09-10 06:36 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1335', '#1322', '#1309', '#1295', '#1294']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-10 08:36 UTC, Alphavite51 approved these changes

2020-09-10 09:48 UTC, YuriSilenok approved these changes
Да, либо день сегодня такой (я не могу найти ошибки), либо Вы решили сделать все хорошо.

2020-09-10 10:13 UTC, YuriSilenok commented
После того, как преподаватель провел положительную проверку запроса, Вы его должны смержить. После этого перевесить основную задачу на преподавателя.

2020-09-10 10:14 UTC, YuriSilenok commented
После того, как преподаватель провел положительную проверку запроса, Вы его должны смержить. После этого перевесить основную задачу на преподавателя.

2020-09-10 10:14 UTC, YuriSilenok commented
После того, как преподаватель провел положительную проверку запроса, Вы его должны смержить. После этого перевесить основную задачу на преподавателя.

2020-09-10 10:15 UTC, YuriSilenok commented
После того, как преподаватель провел положительную проверку запроса, Вы его должны смержить. После этого перевесить основную задачу на преподавателя.

2020-09-10 10:15 UTC, merged

2020-09-10 10:29 UTC, YuriSilenok commented
После того, как преподаватель провел положительную проверку запроса #1217, Вы должны смержить запрос. После этого перевесить основную задачу #1082 на преподавателя.

2020-09-10 10:29 UTC, YuriSilenok commented
После того, как преподаватель провел положительную проверку запроса #1217, Вы должны смержить запрос. После этого перевесить основную задачу #1082 на преподавателя.

2020-09-10 10:40 UTC, YuriSilenok commented
После того, как преподаватель провел положительную проверку запроса #1217, Вы должны смержить запрос. После этого перевесить основную задачу #1082 на преподавателя.

2020-09-10 10:40 UTC, YuriSilenok commented
После того, как преподаватель провел положительную проверку запроса #1217, Вы должны смержить запрос. После этого перевесить основную задачу #1082 на преподавателя.

2020-09-10 10:42 UTC, YuriSilenok commented
После того, как преподаватель провел положительную проверку запроса #1217, Вы должны смержить запрос. После этого перевесить основную задачу #1082 на преподавателя.

2020-09-10 10:42 UTC, YuriSilenok commented
После того, как преподаватель провел положительную проверку запроса #1217, Вы должны смержить запрос. После этого перевесить основную задачу #1082 на преподавателя.

2020-09-10 10:45 UTC, YuriSilenok commented
После того, как преподаватель провел положительную проверку запроса #1217, Вы должны смержить запрос. После этого перевесить основную задачу #1082 на преподавателя.

2020-09-10 10:46 UTC, YuriSilenok commented
После того, как преподаватель провел положительную проверку запроса #1217, Вы должны смержить запрос. После этого перевесить основную задачу #1082 на преподавателя.

2020-09-10 10:50 UTC, YuriSilenok commented
После того, как преподаватель провел положительную проверку запроса #1217, Вы должны смержить запрос. После этого перевесить основную задачу #1082 на преподавателя.

2020-09-10 10:56 UTC, YuriSilenok commented
После того, как преподаватель провел положительную проверку запроса #1217, Вы должны смержить запрос. После этого перевесить основную задачу #1082 на преподавателя.

2020-09-10 10:56 UTC, YuriSilenok commented
После того, как преподаватель провел положительную проверку запроса #1217, Вы должны смержить запрос. После этого перевесить основную задачу #1082 на преподавателя.

2020-09-12 23:55 UTC, YuriSilenok commented
После того, как преподаватель провел положительную проверку запроса #1217, Вы должны смержить запрос. После этого перевесить основную задачу #1082 на преподавателя.

2020-09-12 23:55 UTC, YuriSilenok commented
После того, как преподаватель провел положительную проверку запроса #1217, Вы должны смержить запрос. После этого перевесить основную задачу #1082 на преподавателя.