fixed UT_Insert_CAcademicDegree
Students-of-the-city-of-Kostroma/Student-timetable pull request #1221
Opened 2019-09-24 15:19 UTC by ssas18

#1188

2019-11-27 17:51 UTC, Rogachev99 commented
@Tokotoru, конфликт решен

2019-11-28 06:36 UTC, YuriSilenok commented on LibOfTimetableOfClasses/LibOfTimetableOfClasses.csproj
> +    </Reference>
Незачем подключать в библиотеку компоненты из юниттестирования

2019-11-28 06:37 UTC, YuriSilenok commented on LibOfTimetableOfClasses/LibOfTimetableOfClasses.csproj
> +  </ItemGroup>
Зачем это подключено?

2019-11-28 06:37 UTC, YuriSilenok commented on LibOfTimetableOfClasses/packages.config
> +</packages>
Зачем этот файл?

2019-11-28 06:37 UTC, YuriSilenok commented on TimetableOfClasses/TimetableOfClasses.csproj
> +    </Reference>
Зачем в формы подключили компоненты тестирования?

2019-11-28 06:37 UTC, YuriSilenok commented on TimetableOfClasses/TimetableOfClasses.csproj
> +    <None Include="packages.config" />
Зачем?

2019-11-28 06:38 UTC, YuriSilenok commented on TimetableOfClasses/packages.config
> +  <package id="MSTest.TestFramework" version="2.0.0" targetFramework="net45" />
Не трогать то, что работает

2019-11-28 06:39 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UnitTestOfTimetableOfClasses.csproj
> +      <HintPath>..\packages\MSTest.TestFramework.2.0.0\lib\net45\Microsoft.VisualStudio.TestPlatform.TestFramework.dll</HintPath>
не трогать то, что работает

2019-11-28 06:39 UTC, YuriSilenok requested changes
Такие изменения не долны попасть в ветку элита

2019-11-28 06:39 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UnitTestOfTimetableOfClasses.csproj
> +      <HintPath>..\packages\MSTest.TestFramework.2.0.0\lib\net45\Microsoft.VisualStudio.TestPlatform.TestFramework.Extensions.dll</HintPath>
не трогать то, что работает

2019-11-28 06:39 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/packages.config
> +  <package id="MSTest.TestFramework" version="2.0.0" targetFramework="net45" />
не трогать то, что работает

2020-04-20 12:52 UTC, closed without merging