fixed UT_Update_CEnclosurse
Students-of-the-city-of-Kostroma/Student-timetable pull request #1222
Opened 2019-09-25 10:02 UTC by Proffet78

#1194

2019-09-28 18:59 UTC, YuriSilenok requested changes
Почему вы прислали тесты со сбоями? 
Вы задание читали?

![image](https://user-images.githubusercontent.com/14871471/65821212-3a441900-e23b-11e9-9688-68cdb8ca4a01.png)

2019-10-02 18:18 UTC, YuriSilenok requested changes
Уже на финише

2019-10-02 18:18 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CEnclosurse.cs
> +        public void Task_396_2()// повтор адреса
Старые комментарии удалить

2019-10-05 19:37 UTC, YuriSilenok requested changes
Решите конфликт

2019-10-07 09:45 UTC, Proffet78 commented
Конфликт решен

2019-10-07 18:51 UTC, YuriSilenok requested changes
Появились сбои в Ваших автотестах
![image](https://user-images.githubusercontent.com/14871471/66339828-9bab6c80-e94c-11e9-842d-7e7f679c0707.png)
![image](https://user-images.githubusercontent.com/14871471/66341709-82a4ba80-e950-11e9-8ed2-9fec55ef96a6.png)

2019-10-07 21:18 UTC, Proffet78 commented
Прошу прощения, что так много изменений, забыл в начале обновить ветку, поэтому выдало ошибку, поэтому в основном за все изменения отвечает fixed ut 3.0 !
Спасибо

2019-10-08 17:48 UTC, YuriSilenok approved these changes
Мержите

2019-10-08 19:26 UTC, merged