Исправил сбои в автотестах расположенных в файле UT_Insert_CEnclosurse
Students-of-the-city-of-Kostroma/Student-timetable pull request #1223
Opened 2019-09-25 10:40 UTC by Nosolev

#1085

2019-10-03 17:32 UTC, FvckNeighbors reviewed
Комментарии к коду должны быть осуществлены через ///, к каждому тестовому методу

2019-10-03 18:43 UTC, FvckNeighbors reviewed
Почему отсутствует метод 397_9? 
В сценариях он имеется
[Ссылка на 397-9](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=983700952&range=A79:E79)

2019-10-03 18:46 UTC, FvckNeighbors commented on UnitTestOfTimetableOfClasses/UT_Insert_CEnclosurse.cs
> +			bool expected = false;
Не соответствует ожидаемому результату в сценариях
[Ссылка на 397_7](https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=983700952&range=A77:E77)

2019-11-27 18:32 UTC, Tokotoru commented
Решил мерж конфликт

2019-11-27 20:15 UTC, Rogachev99 commented
> Решил мерж конфликт

@Tokotoru, конфликт не верно решен. Откати изменения. И попробуй заново.
![image](https://user-images.githubusercontent.com/32433285/69756515-c0150f80-116b-11ea-8779-0ebea5094dca.png)

2019-11-27 20:59 UTC, Rogachev99 commented
Конфликт решен

2019-11-27 21:07 UTC, Rogachev99 commented
@Nosolev, тесты по прежнему не работают. Нужны уникальные данные для заполнения.

2019-11-28 07:00 UTC, YuriSilenok commented
Подтверждаю
![image](https://user-images.githubusercontent.com/14871471/69784021-df408b00-11c5-11ea-8afe-9d3676e2623c.png)

2019-11-28 09:04 UTC, Nosolev commented
В моей версии не проходят только 3 теста, скорее всего мерж конфликт был решен не правильно
![trpoo](https://user-images.githubusercontent.com/48089916/69792132-0bb0d300-11d7-11ea-84ff-1f0082150dbc.jpg)

2019-11-28 16:12 UTC, YuriSilenok requested changes
предварительно получить фикс этой ошибки
```
Failed   Task_397_1
Error Message:
 Test method UnitTestOfTimetableOfClasses.UT_Insert_CEnclosurse.Task_397_1 threw exception: 
System.TypeInitializationException: The type initializer for 'LibOfTimetableOfClasses.RefData' threw an exception. ---> System.Data.InvalidConstraintException: Cannot create a DataRelation if Parent or Child Columns are not in a DataSet.
Stack Trace:
    at System.Data.DataRelation.Create(String relationName, DataColumn[] parentColumns, DataColumn[] childColumns, Boolean createConstraints)
   at System.Data.DataRelation..ctor(String relationName, DataColumn parentColumn, DataColumn childColumn, Boolean createConstraints)
   at System.Data.DataRelationCollection.Add(String name, DataColumn parentColumn, DataColumn childColumn)
   at LibOfTimetableOfClasses.RefData..ctor() in D:\a\1\s\LibOfTimetableOfClasses\RefData.cs:line 51
   at LibOfTimetableOfClasses.RefData..cctor() in D:\a\1\s\LibOfTimetableOfClasses\RefData.cs:line 26
--- End of inner exception stack trace ---
    at UnitTestOfTimetableOfClasses.UT_Insert_CEnclosurse.Task_397_1() in D:\a\1\s\UnitTestOfTimetableOfClasses\UT_Insert_CEnclosurse.cs:line 15
```

2019-11-28 16:12 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Insert_CEnclosurse.cs
> +			Assert.AreEqual(expected, actual);
заменить табуляцию на пробелы во всех изменениях

2019-11-28 16:12 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Insert_CEnclosurse.cs
> +
зачем этот перенос строки?

2019-11-28 17:26 UTC, Rogachev99 commented on UnitTestOfTimetableOfClasses/UT_Insert_CEnclosurse.cs
> +		{
еще остались tab

2019-11-28 17:35 UTC, Jeen99 submitted a review, later dismissed
good job

2019-11-28 17:37 UTC, Rogachev99 commented
@YuriSilenok, одобрите, пожалуйста, работу.

2019-11-28 19:16 UTC, YuriSilenok requested changes
![Screenshot_20191128_221451_com android chrome](https://user-images.githubusercontent.com/14871471/69828365-b30c2500-122c-11ea-808a-1f13e2fc06a3.jpg)

2019-11-28 20:39 UTC, Rogachev99 commented
Странно, у меня почему-то зеленым все горело.

2019-11-29 00:18 UTC, Rogachev99 commented
@Nosolev, из-за того что данные дублируются с refData, новые данные не добавляются. Как вариант решение в UT_Update_CEnclosurse. И у тебя не все есть проверки на добавление.

2019-11-29 06:53 UTC, YuriSilenok requested changes
```
Passed   Task_397_1
Failed   Task_397_2
Error Message:
 Assert.AreEqual failed. Expected:<False>. Actual:<True>. 
Stack Trace:
   at UnitTestOfTimetableOfClasses.UT_Insert_CEnclosurse.Task_397_2() in d:\a\1\s\UnitTestOfTimetableOfClasses\UT_Insert_CEnclosurse.cs:line 32
Passed   Task_397_3
Passed   Task_397_4
Passed   Task_397_6
Passed   Task_397_5
Passed   Task_397_7
Passed   Task_397_8
Passed   Task_397_9
```

Прогоняйте все тесты разом

2019-11-29 08:08 UTC, Nosolev commented
![image](https://user-images.githubusercontent.com/48089916/69853651-7aa23080-1298-11ea-86f5-1dac5062534a.png)

2019-11-29 08:33 UTC, Jeen99 approved these changes
![image](https://user-images.githubusercontent.com/32433285/69855233-1b461f80-129c-11ea-8ff6-00a4ac8fd60e.png)
good job

2019-11-29 08:34 UTC, Rogachev99 commented
не забудь поправить сценарий

2019-11-29 11:25 UTC, YuriSilenok approved these changes

2019-11-29 11:27 UTC, merged