Разработать форму "Добавить нагрузку"
Students-of-the-city-of-Kostroma/Student-timetable pull request #1228
Opened 2019-09-25 21:50 UTC by JennyShel18

https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/1199
![ImageOfForm](https://user-images.githubusercontent.com/47378275/65642222-6f602980-dff7-11e9-9f4e-99e10838538e.png)

2019-09-25 22:56 UTC, FvckNeighbors commented
Заголовок пулл реквеста должен звучать как законченная задача, в прошедшем времени. То есть "Разработала ..."

И необходимо поставить себя ответственной и добавить проект и веху

2019-09-26 18:39 UTC, YuriSilenok requested changes
Файлы не размещены в проекте!!!

2019-11-26 20:34 UTC, Rogachev99 commented
@JennyShel18 , форма должна находится в TimetableOfClasses. Там же находятся и другие.

2019-11-28 06:09 UTC, Rogachev99 commented
Отлично, только нужно еще удалить старые файлы, которые были добавлены не в TimetableOfClasses. А для TimetableOfClasses в Visual Studio добавить форму: 1)правой кнопкой по TimetableOfClasses, 2) добавить -> существующий элемент 3) выбрать файл AddAcademicLoad.cs

2019-11-28 12:06 UTC, Rogachev99 commented
Еще не хватает кое-чего в пул-реквесте. 
![image](https://user-images.githubusercontent.com/32433285/69804874-889c7680-11f0-11ea-88e2-24614a5febc6.png)

2019-11-28 17:32 UTC, Rogachev99 commented on TimetableOfClasses.sln
> +Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "Solution Items", "Solution Items", "{946757A0-6466-4894-BEF1-C02F9BB30139}"
по идее этих изменений не должно быть

2019-11-28 20:22 UTC, Jeen99 submitted a review, later dismissed
good job

2019-11-29 06:50 UTC, YuriSilenok requested changes

2019-11-29 06:50 UTC, YuriSilenok commented on TimetableOfClasses/AddAcademicLoad.cs
> +        }
Заполнить добавлением в контроллер данных

2020-06-25 13:06 UTC, YuriSilenok commented
Какие есть обновления по этой задаче?

2020-06-26 05:04 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

2020-06-26 05:13 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

2020-06-27 05:04 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-27 05:12 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-28 05:04 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-28 05:11 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-29 05:04 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-29 05:12 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-30 05:04 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-07-01 05:04 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-07-02 05:04 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-07-02 08:29 UTC, JennyShel18 commented
Для выполнения моей задачи,добавление нагрузки, в рефдате нет нагрузки

2020-07-02 09:01 UTC, YuriSilenok commented
> Для выполнения моей задачи,добавление нагрузки, в рефдате нет нагрузки
> #1199

Добрый день, #1199 это задача которая была Вам поставлена и в рамках этой задачи вы создали запрос на слияние.
Пока я не понимаю сути проблемы.

2020-07-02 12:11 UTC, JennyShel18 commented
Юрий Викторович, Вы выше в этой задаче дали задание : заполнить добавлением данных в контроллер

2020-07-02 12:18 UTC, YuriSilenok commented
> Юрий Викторович, Вы выше в этой задаче дали задание : заполнить добавлением данных в контроллер

Я не смог найти комментарий о котором вы говорите, моли бы предоставить ссылку на него?

2020-07-02 12:20 UTC, JennyShel18 commented
https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1228#discussion_r351998402

2020-07-02 12:25 UTC, YuriSilenok commented
> [#1228 (comment)](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1228#discussion_r351998402)

Уже стало кое-что понятно, теперь по подробнее, почему вы не можете заполнить метод.
Вы считаете что чего-то не хватает? Чего именно?

2020-07-02 12:31 UTC, JennyShel18 commented
При заполнении данных о нагрузке, нажимая кнопку добавить, у меня происходит ошибка -  в refdata нет нагрузки. Этой задачей, то есть разработкой в рефдате нагрузки, должен был заниматься Виктор Комаров, но видимо еще не доделал. Есть возможность поменять эту задачу на идентичную по добавлению данных в контроллере?

2020-07-02 12:49 UTC, YuriSilenok commented
> При заполнении данных о нагрузке, нажимая кнопку добавить, у меня происходит ошибка - в refdata нет нагрузки. Этой задачей, то есть разработкой в рефдате нагрузки, должен был заниматься Виктор Комаров, но видимо еще не доделал. Есть возможность поменять эту задачу на идентичную по добавлению данных в контроллере?

Я ничего не понимаю, могли бы описать со скринами и ссылками на какой-то код?

2020-07-02 12:52 UTC, YuriSilenok commented
> у меня происходит ошибка - в refdata нет нагрузки

например этого недостаточно для описания получаемой вами ошибки

2020-07-02 12:53 UTC, YuriSilenok commented
> Этой задачей, то есть разработкой в рефдате нагрузки, должен был заниматься Виктор Комаров, но видимо еще не доделал.

я посмотрел проект в вашей ветке и не увидел чего-то что бы вам не хватало

2020-07-02 12:54 UTC, YuriSilenok commented
> Есть возможность поменять эту задачу на идентичную по добавлению данных в контроллере?

Пока я не пойму что эта задача заблокирована чем-то, мы не можем ничего менять

2020-07-02 13:10 UTC, JennyShel18 commented
В рефдате нет нагрузки
![4](https://user-images.githubusercontent.com/47378275/86362764-7733b500-bc7e-11ea-85af-7995d7b3d297.png)
Либо я чего-то не понимаю

2020-07-02 13:24 UTC, YuriSilenok commented
Думаю да, вы кое-что пропустили, в вашу ветку на репозитории были залиты обновления. Вам их нужно получить, например командой `git pull origin task-1199`
Обратите как выглядит файл [рефдаты](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/task-1199/LibOfTimetableOfClasses/RefData.cs). Теперь он не статический. Что бы к нему обратится нужно обращаться через класс Program, вот [пример](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/task-1199/TimetableOfClasses/AddTeacher.cs) доступный в вашей ветке.
![image](https://user-images.githubusercontent.com/14871471/86364106-6b48f280-bc80-11ea-89c8-db8bd511674e.png)

2020-07-02 13:25 UTC, JennyShel18 commented
Поняла, приступаю

2020-07-02 14:51 UTC, JennyShel18 commented
Юрий Викторович, вылетела такая ошибка при открытии своей формы. Как ее исправить, не навредив целостности проекта?
![5](https://user-images.githubusercontent.com/47378275/86373925-9fc2ab80-bc8c-11ea-89a9-459fbdf527f1.png)

2020-07-02 14:54 UTC, YuriSilenok commented
> Юрий Викторович, вылетела такая ошибка при открытии своей формы. Как ее исправить, не навредив целостности проекта?
> ![5](https://user-images.githubusercontent.com/47378275/86373925-9fc2ab80-bc8c-11ea-89a9-459fbdf527f1.png)

Для того что бы понять этого фрагмента ошибки недостаточно.
Предполагаю что у вас возникли конфликты и возможно некоторые из них вы не решили или решили с синтаксическими ошибками. Вам нужно проверить в перовую очередь класс дизайнер. Вы понимаете о каком классе я говорю?

2020-07-02 15:59 UTC, JennyShel18 commented
Да

2020-07-02 17:01 UTC, JennyShel18 commented
Можно ли изменять другие файлы в проекте? В задаче мне нужна переменная ChoseReductionGroups, которую нужно определить в классе Groups

2020-07-02 17:50 UTC, JennyShel18 commented
И мне нужно запускать открытие формы, а это нужно добавлять код в AcademicLoad.cs - addAcademicLoad.ShowDialog()

2020-07-03 08:32 UTC, YuriSilenok commented
Вы вправе сделать все что угодно, на все на это я буду смотреть и если у меня появятся вопросы, я их задам.

2020-07-03 11:25 UTC, JennyShel18 commented
Юрий Викторович, возникает ошибка при добавлении нагрузки. Когда отлаживаю программу, в файле CAcademiLoad.cs возникает такая ошибка:
![error](https://user-images.githubusercontent.com/47378275/86464643-9db62680-bd38-11ea-8ae3-d67e308180e8.png)

2020-07-03 12:09 UTC, YuriSilenok commented
Сделайте пошаговую отладку, найдите строку в которой генерируется исключени. И текст который вы показываете не относится к исключению которое вызвалось, это текст другого исключения, видимо еще переменная хранящая сведения об исключении не сформировалась Думаю нужно еще один шаг сделать, что бы получить сведения о первоначальном исключении

2020-07-03 12:20 UTC, JennyShel18 commented
![error2](https://user-images.githubusercontent.com/47378275/86468758-c4785b00-bd40-11ea-9da0-13644ad958bd.png)

2020-07-03 12:30 UTC, YuriSilenok commented
Я конечно понимаю что для меня все очевидно.
Но Вас то на какие мысли наводит это сообщение?

2020-07-03 13:50 UTC, JennyShel18 commented
Не очень понимаю, какая таблица является родительской. Group?

2020-07-03 13:56 UTC, YuriSilenok commented
![image](https://user-images.githubusercontent.com/14871471/86475840-12479000-bd4e-11ea-806e-8dda086f359e.png)
здесь указано какие таблицы связывает реляционная зависимость, это имя можно поискать в классе рефдата

2020-07-03 13:56 UTC, JennyShel18 commented
Я так понимаю, в рефдате описаны все связи по ключам, так?

2020-07-03 13:57 UTC, YuriSilenok commented
> Я так понимаю, в рефдате описаны все связи по ключам, так?

да, верное направление мысли

2020-07-03 14:01 UTC, JennyShel18 commented
Дак это получается, я добавляю элемент, которого просто нет в Group?

2020-07-03 14:01 UTC, JennyShel18 commented
Сейчас проверю свою теорию

2020-07-03 14:03 UTC, YuriSilenok commented
Или ты при создании группы пытаешься указать академическую нагрузку которой не существует

2020-07-03 14:20 UTC, JennyShel18 commented
Юрий Викторович, такой вопрос. Изначально на форме Group на событии "дабл клик" стоит метод update. Как мне сделать так, чтобы при добавлении нагрузки, когда при нажатии на кнопку "выбрать" у поля группа открывается форма Group, и там был не метод Update, а мой метод?

2020-07-03 14:23 UTC, YuriSilenok commented
Мне кажется подобный функционал уже есть, при работе с формой преподаватели. Там выбирается ученая степень и ученое звание. и вот в них как раз что-то подобное есть.

2020-07-03 14:29 UTC, JennyShel18 commented
Поняла, спасибо

2020-07-03 14:32 UTC, JennyShel18 commented
Там на двойной клик вместо апдейт поставили свой метод

2020-07-03 14:37 UTC, YuriSilenok commented
посмотри другие варианты, выбери который тебе больше нравится

2020-07-03 14:49 UTC, JennyShel18 commented
Юрий Викторович, нужно ли реализовывать то, что при добавлении нагрузки это отображалось в форме AcademicLoad.cs?

2020-07-03 14:49 UTC, JennyShel18 commented
Или моя задача состоит только в добавлении данных в контроллере?

2020-07-03 15:01 UTC, YuriSilenok commented
Смотри, вот нагрузка, у нее указывается группа.
![image](https://user-images.githubusercontent.com/14871471/86480625-07452d80-bd57-11ea-8dd7-0462d255794d.png)
а вот группа, у нее нагрузка не указывается.
![image](https://user-images.githubusercontent.com/14871471/86480690-2b087380-bd57-11ea-92c0-4a9cbdf8e674.png)
предполагаю что связь группа-нагрузка перевернута.
Нужно для нагрузки указывать группу, а сейчас для группы требуется нагрузка.

2020-07-03 15:05 UTC, YuriSilenok commented
![image](https://user-images.githubusercontent.com/14871471/86480914-a1a57100-bd57-11ea-8eb6-945412570421.png)
думаю так и есть,в 49 строке нагрузка идет третьим параметром, а должна вторым

2020-07-03 15:07 UTC, YuriSilenok commented
Оформи этот баг, он пойдет как еще один долг.
Ты можешь по идее попытаться сделать и эту задачу, но проверить работоспособность ты сможешь только после исправления бага.
Нужно здесь указать ссылку на этот баг с комментарием

2020-07-03 15:08 UTC, YuriSilenok commented
Потом когда баг будет решен, тебе нужно будет получить обновления из дев и смержить его с текущей веткой, тогда тебе придут исправления.

2020-07-03 15:14 UTC, JennyShel18 commented
Баг получается нужно исправить в текущей ветке?

2020-07-03 15:15 UTC, YuriSilenok commented
> Баг получается нужно исправить в текущей ветке?

Нет, ты поднимешь задачу с меткой баг и другими метками, у нее будет свой номер, нужно создать под баг ветку
все как обычно

2020-07-03 15:16 UTC, JennyShel18 commented
Не очень поняла, где нужно указывать ссылку на баг с комментарием
![баг](https://user-images.githubusercontent.com/47378275/86481732-3e1c4300-bd59-11ea-9dae-7a3d45a72826.png)

2020-07-03 15:16 UTC, YuriSilenok commented
> Баг получается нужно исправить в текущей ветке?

если ты будешь править его в этой ветке, то задержишь выпуск исправлений

2020-07-03 15:16 UTC, JennyShel18 commented
то есть мне нужно поднять еще одну задачу?

2020-07-03 15:17 UTC, YuriSilenok commented
> Не очень поняла, где нужно указывать ссылку на баг с комментарием
> ![баг](https://user-images.githubusercontent.com/47378275/86481732-3e1c4300-bd59-11ea-9dae-7a3d45a72826.png)

здесь укажи. в комментариях к этому запросу. что бы было понятно почему деятельность над этим запросом приостановлена. Но сначала тебе нужно баг поднять.

2020-07-03 15:18 UTC, YuriSilenok commented
> то есть мне нужно поднять еще одну задачу?

да, задачу, ветку, исправить в ветке, создать запрос

2020-07-28 05:02 UTC, YuriSilenok commented
Добрый день. В ветке task-1228 давно не было активности

2020-07-29 05:02 UTC, YuriSilenok commented
Добрый день. В ветке task-1228 давно не было активности

2020-07-30 05:02 UTC, YuriSilenok commented
Добрый день. В ветке task-1228 давно не было активности

2020-07-31 05:02 UTC, YuriSilenok commented
Добрый день. В ветке task-1228 давно не было активности

2020-08-01 05:02 UTC, YuriSilenok commented
Добрый день. В ветке task-1228 давно не было активности

2020-08-02 05:02 UTC, YuriSilenok commented
Добрый день. В ветке task-1228 давно не было активности

2020-08-03 05:02 UTC, YuriSilenok commented
Добрый день. В ветке task-1228 давно не было активности

2020-08-13 13:02 UTC, YuriSilenok commented
Задача с Вас снята, так как по ней давно не было активности.

2020-08-21 05:02 UTC, YuriSilenok commented
Задача с Вас снята, так как по ней давно не было активности.

2020-08-23 10:13 UTC, JennyShel18 commented
Юрий Викторович, здравствуйте. Решила я обновить данные из проекта командой git pull origin task-1199, доработала нужные свои файлы, выдает такое исключение:
![ерр](https://user-images.githubusercontent.com/47378275/90976024-51ba7d80-e542-11ea-9c67-e493f3263512.png) Почему возникает такая ошибка? Как это можно исправить?

2020-08-24 06:35 UTC, YuriSilenok commented
- Возможно вам бы и ответили, если бы вы в проверяющих добавили **ВСЮ КОМАНДУ.**
- что значит `добавила свои файлы`, вы что там, копипастом занимаетесь?
- `выдает такое исключение` я не вижу здесь исключений

2020-08-24 16:02 UTC, JennyShel18 commented
Юрий Викторович, я не добавила файлы, а доделала в них код по задаче, из за этих строчек, которые на скрине я не могу теперь проверить свой код. Остальных ребят добавлю в ревьюеры, но не думаю, что сейчас есть у них время мне помочь

2020-08-24 17:09 UTC, JennyShel18 commented
Юрий Викторович, я для проверки сейчас скачала еще раз репозиторий, перешла в ветку dev, и запустила проект. Так же выводит эти строки, и я когда нажимаю кнопку продолжить, то все закрывается и программа выходит из режима отладки.
![a](https://user-images.githubusercontent.com/47378275/91074786-b7dbf900-e645-11ea-9fb6-06e0e9e51001.png)

2020-08-25 10:51 UTC, YuriSilenok commented
возможно проблема в том, что при старте проекта происходит инициализация данных. думаю Вас блокирует задача #1323

2020-08-25 11:14 UTC, JennyShel18 commented
Что получается мне нужно делать?

2020-08-25 11:16 UTC, JennyShel18 commented
Я сделала коммит, может быть Вы так оцените проделанную работу?

2020-08-25 11:36 UTC, YuriSilenok commented
> Что получается мне нужно делать?

Кожа она будет решена, вам нужно получить обновления в свою ветку и продолжить работу. Следующей задачей по плану было предложение от вас о том, как можно улучшить данную программу и реализацию этой идео после согласования, обсуждать в общем чате.

2020-08-29 05:02 UTC, YuriSilenok commented
Задача с Вас снята, так как по ней давно не было активности.

2020-08-29 11:09 UTC, NordScandinavian commented
@YuriSilenok, здравствуйте. Пытаюсь запустить проект из этой ветки, при старте выдаёт такую ошибку. Как я увидел выше, задача #1323 блокировала запуск на тот момент, когда над задачей работала @JennyShel18. Сейчас задача #1323 решена, но запуск так же не происходит. Объясните пожалуйста, возможно я чего-то не понимаю?
![image](https://user-images.githubusercontent.com/47521360/91635356-9477cc00-ea00-11ea-8803-115ce0793f67.png)

2020-08-29 18:36 UTC, YuriSilenok commented
Вам нужно получить изменения из ветки dev себе в ветку.

2020-08-31 08:01 UTC, Alphavite51 commented
Ветка смержена, можете продолжать работу, вам нужно мержить dev в вашу ветку!

2020-08-31 15:40 UTC, JennyShel18 commented
Поняла, приступаю

2020-09-04 06:44 UTC, ssas18 reviewed
Пока не вижу изменений с последнего комментария

2020-09-04 07:58 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1342', '#1335', '#1333', '#1322', '#1309', '#1295', '#1294', '#1217']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-05 14:26 UTC, ifuwmnn reviewed
Не вижу новых изменений.

2020-09-05 21:11 UTC, MyachevM reviewed
Также не наблюдаю новых изменений

2020-09-07 18:28 UTC, NordScandinavian commented
Изменений нет, проверять нечего

2020-09-08 12:25 UTC, Alphavite51 requested changes
у вас все те же непроверенные запросы которые описаны выше

2020-09-11 20:11 UTC, NordScandinavian requested changes
Изменений нет, проверять нечего

2020-09-15 20:48 UTC, JennyShel18 commented
Юрий Викторович, добрый вечер. Я вытянула изменения из ветки dev, перешла обратно на свою, и опять выдает исключение. Не поможете разобраться?
![дд](https://user-images.githubusercontent.com/47378275/93262951-bcf81800-f7ad-11ea-81d6-b2907be561b0.png)

2020-09-15 20:51 UTC, YuriSilenok commented
> Юрий Викторович, добрый вечер. Я вытянула изменения из ветки dev, перешла обратно на свою, и опять выдает исключение. Не поможете разобраться?
> ![дд](https://user-images.githubusercontent.com/47378275/93262951-bcf81800-f7ad-11ea-81d6-b2907be561b0.png)

закройте git bush
в Visual Studio есть встроенный git

2020-09-15 20:56 UTC, JennyShel18 commented
Поняла, а насчет исключения, по-моему это связано с задачей заполнения реф даты, я думала её уже давно закрыли?

2020-09-15 21:00 UTC, YuriSilenok commented
> Поняла, а насчет исключения, по-моему это связано с задачей заполнения реф даты, я думала её уже давно закрыли?

А вы получили исправления для этой проблемы?

2020-09-15 21:04 UTC, YuriSilenok commented
> Ветка смержена, можете продолжать работу, вам нужно мержить dev в вашу ветку!

[вот ](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1228#pullrequestreview-484079761)же вам писали, почему это не было сделано?

2020-09-15 21:05 UTC, JennyShel18 commented
Да, я вытянула изменения из ветки dev

2020-09-15 21:10 UTC, YuriSilenok commented
> Да, я вытянула изменения из ветки dev

Похоже у Вас понимание термина смержить ветки. вы ведь не выполняли команду git merge?

2020-09-15 21:15 UTC, YuriSilenok commented
Пройдите [обучение](https://learngitbranching.js.org/?locale=ru_RU). это быстро и визуально наглядно.

2020-09-17 15:53 UTC, Alphavite51 commented on TimetableOfClasses/AddAcademicLoad.cs
> +                    else MessageBox.Show("Новозможно добавить эту нагрузку", "Попробуйте снова");
нЕвозможно добавить эту нагрузку

2020-09-17 15:54 UTC, Alphavite51 commented on TimetableOfClasses/AddAcademicLoad.cs
> +                MessageBox.Show("Заполенены не все поля или заполнены некорректно", "Ошибка", MessageBoxButtons.OK);
Заполнены не все поля

2020-09-17 15:55 UTC, Alphavite51 requested changes
Несколько ошибок

2020-09-17 16:01 UTC, YuriSilenok requested changes
Названия переменных должны быть говорящие

2020-09-19 21:17 UTC, JennyShel18 commented
Я смержила ветки, но так же происходит несколько исключений:
![ффф](https://user-images.githubusercontent.com/47378275/93689332-5a1cbe80-fad6-11ea-995f-b37855c8c9c9.png)

2020-09-20 07:17 UTC, YuriSilenok commented
Так задача с вас снята уже

2020-09-20 07:18 UTC, YuriSilenok commented
> Я смержила ветки, пишет, что уже все обновлено и так же происходит несколько исключений:
> ![ффф](https://user-images.githubusercontent.com/47378275/93689332-5a1cbe80-fad6-11ea-995f-b37855c8c9c9.png)
> 

Этот снимок не показывает что ветки смержены

2020-09-26 14:25 UTC, closed without merging