Создан интерфейс для классов наследников контроллера
Students-of-the-city-of-Kostroma/Student-timetable pull request #123
Opened 2019-03-04 13:55 UTC by Parallusion

#91

2019-03-04 13:58 UTC, YuriSilenok requested changes

2019-03-04 13:58 UTC, YuriSilenok commented on LibOfTimetableOfClasses/Controller.cs
> +    }
Для интерфейса должен быть создан отдельный файл

2019-03-05 16:26 UTC, YuriSilenok commented on TimetableOfClasses/AcademicDegree.Designer.cs
> +}
Это откуда у Вас появилось?

2019-03-05 16:27 UTC, YuriSilenok commented on TimetableOfClasses/AcademicDegree.cs
> +}
Этот файл откуда?

2019-03-05 16:27 UTC, YuriSilenok commented on TimetableOfClasses/AcademicDegree.resx
> +</root>
Этот файл откуда?

2019-03-05 16:27 UTC, YuriSilenok commented on TimetableOfClasses/Start.Designer.cs
> +		private System.Windows.Forms.ToolStripMenuItem ученыеСтепениToolStripMenuItem;
Этот файл почему зменился?

2019-03-05 16:28 UTC, YuriSilenok commented on TimetableOfClasses/Start.cs
> +		}
Этот файл почему изменился?

2019-03-05 16:28 UTC, YuriSilenok commented on TimetableOfClasses/TimetableOfClasses.csproj
> +    </Compile>
Этот файл почему изменился?

2019-03-05 16:28 UTC, YuriSilenok requested changes
Обнаружены файлы которые не должны были измениться.

2019-03-05 16:39 UTC, Parallusion commented
Это не мой commit. Это commit Ильи Бурова, который попал ко мне в запрос по ошибке. Вы сами видели, что он по ошибке сделал много всего, в том числе и это. Мой commit единственный который тут остался называется commit  и он корректен.
![image](https://user-images.githubusercontent.com/47377888/53821169-46eee000-3f7e-11e9-972c-2eff28387261.png)

2019-03-05 18:28 UTC, YuriSilenok commented
Тем не менее я не могу принять лишние изменея.
Тут несколько путей решения проблемы:
-  Попросить Илью исправлять его изменения, под нашим чутким руководством.
- Сделать новую ветку из ветки Testing и из коммита с Вими изменениями скопировать файлы в новую ветку и открыть запрос на слияние
- Либо самостоятельно выправить недостатки.
Какой вариант Вы предпочитаете?

2019-03-05 18:31 UTC, Parallusion commented
Можно я просто создам ветку task-91v2 или что то типа того и сделаю всё заново? Займёт 5 минут.

2019-03-06 06:26 UTC, YuriSilenok commented
Видел вы создали новую ветку, этот запрос я закрываю и удаляю ветку.

2019-03-06 06:26 UTC, closed without merging