Test: "Fix UT_Update_CInstitute"
Students-of-the-city-of-Kostroma/Student-timetable pull request #1235
Opened 2019-11-11 04:46 UTC by Rogachev99

#1095

2019-11-24 17:37 UTC, Rogachev99 commented
@YuriSilenok, здравствуйте. Не могли бы посмотреть работу? Сейчас нахожусь в списке возможных тимлидов. И если выбирут меня - будет не совсем правильно, т.к. эта единственная работа, которую я должен сделать.

2019-11-28 16:08 UTC, YuriSilenok requested changes

2019-11-28 16:08 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CInstitute.cs
> +		}
Инициализация контроллеров производится в рефдате.
Если вам нужна ссылка, возьмите из рефдаты.
То как у вВас написано, работать не будет

2019-11-28 16:08 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CInstitute.cs
> +		}
нет вижу смывсла в этом методе, все доступно через рефдату

2019-11-29 19:27 UTC, closed without merging

2020-06-25 13:06 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-06-26 05:04 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-06-26 05:14 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-06-27 05:04 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-06-27 05:12 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-06-28 05:04 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-06-28 05:12 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-06-29 05:04 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-06-29 05:12 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-06-30 05:04 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-07-01 05:04 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-07-02 05:04 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-07-03 05:03 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-07-03 13:15 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-07-04 05:02 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-07-05 05:02 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-07-06 05:02 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-07-06 13:02 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-07-06 14:22 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-07-06 15:24 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-07-06 15:26 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-07-06 15:49 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-07-07 05:02 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-07-08 05:02 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-07-09 05:02 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-07-10 05:02 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-07-11 05:02 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-07-11 06:17 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу