Исправить сбои в автотестах расположенных в файле UT_Update_CTeacher
Students-of-the-city-of-Kostroma/Student-timetable pull request #1237
Opened 2019-11-26 19:40 UTC by Proffet78

#1036

2019-11-26 19:42 UTC, Proffet78 commented
Выполнено, просьба проверить!

Спасибо

2019-11-27 14:10 UTC, Rogachev99 commented
@Proffet78, добавь меня в ревью.

2019-11-27 18:35 UTC, Proffet78 commented
@Rogachev99, сделал

2019-11-28 16:06 UTC, YuriSilenok requested changes
В эту ветку необходимо смержить исправления для ошибки 
```
Failed   Task_247_1
Error Message:
 Test method UnitTestOfTimetableOfClasses.UT_Update_CTeacher.Task_247_1 threw exception: 
System.TypeInitializationException: The type initializer for 'LibOfTimetableOfClasses.RefData' threw an exception. ---> System.Data.DuplicateNameException: A Relation named 'AcademicDegree-Teacher' already belongs to this DataSet.
Stack Trace:
    at System.Data.DataRelationCollection.RegisterName(String name)
   at System.Data.DataRelationCollection.DataSetRelationCollection.AddCore(DataRelation relation)
   at System.Data.DataRelationCollection.Add(DataRelation relation)
   at System.Data.DataRelationCollection.Add(String name, DataColumn parentColumn, DataColumn childColumn)
   at LibOfTimetableOfClasses.RefData..ctor() in D:\a\1\s\LibOfTimetableOfClasses\RefData.cs:line 49
   at LibOfTimetableOfClasses.RefData..cctor() in D:\a\1\s\LibOfTimetableOfClasses\RefData.cs:line 26
--- End of inner exception stack trace ---
    at UnitTestOfTimetableOfClasses.UT_Update_CTeacher.Task_247_1() in D:\a\1\s\UnitTestOfTimetableOfClasses\UT_Update_CTeacher.cs:line 19
```

2019-11-29 20:26 UTC, Proffet78 commented
Исправил, просьба проверить!
Спасибо!

2019-11-30 06:59 UTC, YuriSilenok requested changes
Есть ошибки требующие исправления

2019-11-30 06:59 UTC, YuriSilenok commented on TimetableOfClasses/TimetableOfClasses.csproj
> +    </NuGetPackageImportStamp>
Никаких тестовых библиотек в основной проекте

2019-11-30 06:59 UTC, YuriSilenok commented on TimetableOfClasses/TimetableOfClasses.csproj
> +  <Import Project="..\packages\MSTest.TestAdapter.1.4.0\build\net45\MSTest.TestAdapter.props" Condition="Exists('..\packages\MSTest.TestAdapter.1.4.0\build\net45\MSTest.TestAdapter.props')" />
Никаких тестовых библиотек в основной проекте

2019-11-30 06:59 UTC, YuriSilenok commented on TimetableOfClasses/TimetableOfClasses.csproj
> +    </Reference>
Никаких тестовых библиотек в основной проекте

2019-11-30 06:59 UTC, YuriSilenok commented on TimetableOfClasses/TimetableOfClasses.csproj
> +    <None Include="packages.config" />
Никаких тестовых библиотек в основной проекте

2019-11-30 06:59 UTC, YuriSilenok commented on TimetableOfClasses/TimetableOfClasses.csproj
> +    <Error Condition="!Exists('..\packages\MSTest.TestAdapter.1.4.0\build\net45\MSTest.TestAdapter.props')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\MSTest.TestAdapter.1.4.0\build
Никаких тестовых библиотек в основной проекте

2019-11-30 06:59 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UnitTestOfTimetableOfClasses.csproj
> +      <Private>True</Private>
Зачем это нужно?

2019-11-30 06:59 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UnitTestOfTimetableOfClasses.csproj
> +      <Private>True</Private>
Зачем это нужно?

2019-12-01 00:37 UTC, Proffet78 commented
Исправил ошибки!
Спасибо!

2019-12-01 06:11 UTC, YuriSilenok reviewed
![image](https://user-images.githubusercontent.com/14871471/69910303-92092700-141a-11ea-912e-16d0a863a71f.png)

2019-12-01 06:11 UTC, YuriSilenok commented on TimetableOfClasses/TimetableOfClasses.csproj
> +  <ItemGroup>
удалить добавленные пробелы после тега

2019-12-01 06:11 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UnitTestOfTimetableOfClasses.csproj
> +</Project>
добавить в этот файл перенос на новую строку

2019-12-02 14:16 UTC, Proffet78 commented
Недочеты исправлены! Просьба проверить!
Спасибо!

2019-12-03 13:08 UTC, YuriSilenok approved these changes
![image](https://user-images.githubusercontent.com/14871471/70053734-1c05eb00-15e7-11ea-90c2-c8990e984433.png)

2019-12-03 13:09 UTC, YuriSilenok reviewed
а где 2, 3,4 тесты?

2019-12-03 18:45 UTC, Proffet78 commented
@YuriSilenok , сценарии только для 1, 5, 6, 7, 8 те
![FaebnKDGtTc](https://user-images.githubusercontent.com/47320491/70079632-2e4b4d80-1616-11ea-9efd-a98e92d07778.jpg)
![LllbkhYZxJA](https://user-images.githubusercontent.com/47320491/70079636-2f7c7a80-1616-11ea-98d9-7eb1d4ed8bb2.jpg)

стов есть.

2019-12-05 14:56 UTC, Proffet78 commented
Можно мержить?

2019-12-07 11:45 UTC, NordScandinavian approved these changes
Checked

2019-12-08 18:38 UTC, Proffet78 commented
Что дальше делать?

2019-12-09 06:57 UTC, YuriSilenok approved these changes
@NordScandinavian задали вопрос, похоже тебе, видимо по никнейму не умеют обращаться.

2019-12-09 14:55 UTC, merged