Заполнена информация аудиторного фонда корпуса Б
Students-of-the-city-of-Kostroma/Student-timetable pull request #1249
Opened 2019-11-28 15:19 UTC by Heriuple

2019-11-28 16:23 UTC, Rogachev99 commented
@Heriuple нет ссылки на задачу. В ревью нужно добавить еще Юрия Викторовича.

2019-11-28 16:31 UTC, Heriuple commented
Описание добавлено, в ревью добавлен Юрий Викторович

2019-11-28 17:43 UTC, Rogachev99 commented
@Heriuple, подтяни, пожалуйста, изменения из ветки Elite, чтобы можно было проверить на ошибки.

2019-11-28 18:00 UTC, Jeen99 approved these changes
good job

2019-11-28 19:08 UTC, YuriSilenok requested changes
`git merge Elite`

2019-11-29 11:15 UTC, YuriSilenok approved these changes

2019-11-29 11:16 UTC, merged