Создана форма "Справочники"
Students-of-the-city-of-Kostroma/Student-timetable pull request #125
Opened 2019-03-04 17:42 UTC by KharlamovaAlexandra

[109](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/109)

2019-03-05 19:31 UTC, KharlamovaAlexandra commented
Здравствуйте,  @YuriSilenok 
С момента создания вопроса на слияние прошло более 24 часов, я хотела бы напомнить о сделанном здании 
С уважением, Харламова Александра
17-ИСбо-2б

2019-03-05 19:41 UTC, KharlamovaAlexandra commented
Здравствуйте, @YuriSilenok 
Извиняюсь, я запуталась в интерфейсе и не назначила вас проверяющим задачи
С уважением, Харламова Александра
17-ИСбо-2б

2019-03-06 18:11 UTC, YuriSilenok commented on TimetableOfClasses/Start.cs
> +			directory.Show();
Обратите внимание на то как я вызвал метод UploadTable. Я в него передал таблицу. 
У контроллреа CAuditor есть конструктор, который задает имя контроллреа. Именно это имя должно было отобразиться в заголовке формы. Сейчас это не так.
 `public CAuditor() : base("Аудитория")`

в входного параметра метода UploadTable есть свойство что-то типа TableName, Думаю именно его нужно использовать в качестве названия для заголовка формы. Сейчас получается вот так.
![image](https://user-images.githubusercontent.com/14871471/53903252-4de82200-4054-11e9-850d-70ceafc55bc7.png)
Не забудте получить мои изменения командой git pull

2019-03-06 18:11 UTC, YuriSilenok requested changes
Еще пол строчки поправить.

2019-03-06 19:08 UTC, KharlamovaAlexandra commented
Здравствуйте @YuriSilenok

В связи с общими проблемами с ветками, я хочу уточнить стоит ли делать git pull сейчас или лучше дождаться когда все починят? ( Извиняюсь если вопрос не оправдан, просто боюсь все испортить еще больше) 

С уважением, Харламова Александра
17-ИСбо-2б

2019-03-07 06:24 UTC, YuriSilenok commented
Здравствуйте.
Вашу ветку это не затронуло.
Смело продолжайте работать.
Спасибо.

2019-03-08 12:51 UTC, YuriSilenok approved these changes
Приступайте решению конфиликта.

2019-03-09 10:11 UTC, merged