Task 1244(Done)
Students-of-the-city-of-Kostroma/Student-timetable pull request #1250
Opened 2019-11-28 18:16 UTC by ssas18

task-1244 сделано

2019-11-28 20:29 UTC, Rogachev99 commented
Не в ту ветку!!! Нужно в Elite

2019-11-28 20:31 UTC, Rogachev99 commented
![image](https://user-images.githubusercontent.com/32433285/69830717-13a05f80-1237-11ea-9d7d-22c1519de68e.png)
здесь тоже не правильно заполнено. И название пул реквеста не подходящее + нет ссылки на задачу.

2019-11-29 16:14 UTC, NordScandinavian commented
Поменяй название пул реквеста.

2019-11-30 06:50 UTC, YuriSilenok requested changes
Имеется мержконфликт

2019-11-30 06:50 UTC, YuriSilenok commented on LibOfTimetableOfClasses/RefData.cs
> +
Очень много переносов

2019-12-10 14:17 UTC, YuriSilenok reviewed
Предоставить на проверку после решения конфликат

2019-12-23 18:35 UTC, YuriSilenok requested changes
В чем причина этих ошибок?

```
2019-12-13T13:14:45.7839838Z Failed   Task_555_1
2019-12-13T13:14:45.7840149Z Error Message:
2019-12-13T13:14:45.7840451Z  Test method UnitTestOfTimetableOfClasses.UT_Delete_CDirectionOfPreparation.Task_555_1 threw exception: 
2019-12-13T13:14:45.7841075Z System.TypeInitializationException: The type initializer for 'LibOfTimetableOfClasses.RefData' threw an exception. ---> System.ArgumentException: DataTable already belongs to this DataSet.
2019-12-13T13:14:45.7841890Z Stack Trace:
2019-12-13T13:14:45.7842457Z     at System.Data.DataTableCollection.BaseAdd(DataTable table)
2019-12-13T13:14:45.7843035Z    at System.Data.DataTableCollection.Add(DataTable table)
2019-12-13T13:14:45.7843767Z    at LibOfTimetableOfClasses.RefData..ctor() in D:\a\1\s\LibOfTimetableOfClasses\RefData.cs:line 47
2019-12-13T13:14:45.7870172Z    at LibOfTimetableOfClasses.RefData..cctor() in D:\a\1\s\LibOfTimetableOfClasses\RefData.cs:line 27
2019-12-13T13:14:45.7871119Z --- End of inner exception stack trace ---
2019-12-13T13:14:45.7871323Z     at UnitTestOfTimetableOfClasses.UT_Delete_CDirectionOfPreparation.Pre_condition_Del() in D:\a\1\s\UnitTestOfTimetableOfClasses\UT_Delete_CDirectionOfPreparation.cs:line 14
2019-12-13T13:14:45.7871665Z    at UnitTestOfTimetableOfClasses.UT_Delete_CDirectionOfPreparation.Task_555_1() in D:\a\1\s\UnitTestOfTimetableOfClasses\UT_Delete_CDirectionOfPreparation.cs:line 23
```

2019-12-23 19:02 UTC, YuriSilenok commented
Следите за исправлениями рефдаты

2020-06-25 13:06 UTC, YuriSilenok commented
Какие есть обновления по этой задаче?

2020-06-26 05:04 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

2020-06-26 05:13 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

2020-06-27 05:04 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-27 05:12 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-28 05:04 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-28 05:11 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-29 05:04 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-29 05:12 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-30 05:04 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-07-01 05:04 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-07-02 05:03 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-07-02 09:12 UTC, ssas18 commented
Что необходимо сделать чтобы замержить мою задачу, она не проходит 37 автотестов. Их получается необходимо исправить?

2020-07-02 09:17 UTC, YuriSilenok commented
Добрый день.
Нет, вам нужно устранить замечания которые были указаны в прошлых проверках.
Для вас главное что бы критических ошибок не было при создании рефдаты.
Таковых сейчас не наблюдается.

2020-07-02 09:47 UTC, ssas18 commented
> В чем причина этих ошибок?
> 
> ```
> 2019-12-13T13:14:45.7839838Z Failed   Task_555_1
> 2019-12-13T13:14:45.7840149Z Error Message:
> 2019-12-13T13:14:45.7840451Z  Test method UnitTestOfTimetableOfClasses.UT_Delete_CDirectionOfPreparation.Task_555_1 threw exception: 
> 2019-12-13T13:14:45.7841075Z System.TypeInitializationException: The type initializer for 'LibOfTimetableOfClasses.RefData' threw an exception. ---> System.ArgumentException: DataTable already belongs to this DataSet.
> 2019-12-13T13:14:45.7841890Z Stack Trace:
> 2019-12-13T13:14:45.7842457Z     at System.Data.DataTableCollection.BaseAdd(DataTable table)
> 2019-12-13T13:14:45.7843035Z    at System.Data.DataTableCollection.Add(DataTable table)
> 2019-12-13T13:14:45.7843767Z    at LibOfTimetableOfClasses.RefData..ctor() in D:\a\1\s\LibOfTimetableOfClasses\RefData.cs:line 47
> 2019-12-13T13:14:45.7870172Z    at LibOfTimetableOfClasses.RefData..cctor() in D:\a\1\s\LibOfTimetableOfClasses\RefData.cs:line 27
> 2019-12-13T13:14:45.7871119Z --- End of inner exception stack trace ---
> 2019-12-13T13:14:45.7871323Z     at UnitTestOfTimetableOfClasses.UT_Delete_CDirectionOfPreparation.Pre_condition_Del() in D:\a\1\s\UnitTestOfTimetableOfClasses\UT_Delete_CDirectionOfPreparation.cs:line 14
> 2019-12-13T13:14:45.7871665Z    at UnitTestOfTimetableOfClasses.UT_Delete_CDirectionOfPreparation.Task_555_1() in D:\a\1\s\UnitTestOfTimetableOfClasses\UT_Delete_CDirectionOfPreparation.cs:line 23
> ```

На данный момент этот тест проходит успешно, причина ошибки была в том что были повторяющиеся данные(насколько я понял). Мерж конфликт исправлен и решен.

2020-07-02 10:10 UTC, YuriSilenok commented
> > В чем причина этих ошибок?
> > ```
> > 2019-12-13T13:14:45.7839838Z Failed   Task_555_1
> > 2019-12-13T13:14:45.7840149Z Error Message:
> > 2019-12-13T13:14:45.7840451Z  Test method UnitTestOfTimetableOfClasses.UT_Delete_CDirectionOfPreparation.Task_555_1 threw exception: 
> > 2019-12-13T13:14:45.7841075Z System.TypeInitializationException: The type initializer for 'LibOfTimetableOfClasses.RefData' threw an exception. ---> System.ArgumentException: DataTable already belongs to this DataSet.
> > 2019-12-13T13:14:45.7841890Z Stack Trace:
> > 2019-12-13T13:14:45.7842457Z     at System.Data.DataTableCollection.BaseAdd(DataTable table)
> > 2019-12-13T13:14:45.7843035Z    at System.Data.DataTableCollection.Add(DataTable table)
> > 2019-12-13T13:14:45.7843767Z    at LibOfTimetableOfClasses.RefData..ctor() in D:\a\1\s\LibOfTimetableOfClasses\RefData.cs:line 47
> > 2019-12-13T13:14:45.7870172Z    at LibOfTimetableOfClasses.RefData..cctor() in D:\a\1\s\LibOfTimetableOfClasses\RefData.cs:line 27
> > 2019-12-13T13:14:45.7871119Z --- End of inner exception stack trace ---
> > 2019-12-13T13:14:45.7871323Z     at UnitTestOfTimetableOfClasses.UT_Delete_CDirectionOfPreparation.Pre_condition_Del() in D:\a\1\s\UnitTestOfTimetableOfClasses\UT_Delete_CDirectionOfPreparation.cs:line 14
> > 2019-12-13T13:14:45.7871665Z    at UnitTestOfTimetableOfClasses.UT_Delete_CDirectionOfPreparation.Task_555_1() in D:\a\1\s\UnitTestOfTimetableOfClasses\UT_Delete_CDirectionOfPreparation.cs:line 23
> > ```
> 
> На данный момент этот тест проходит успешно, причина ошибки была в том что были повторяющиеся данные(насколько я понял). Мерж конфликт исправлен и решен.

Где вы нашли эту ошибку?

2020-07-02 10:15 UTC, ssas18 commented
Ошибку вы сами скидывали в комменты, а мерж конфликт стал закрыт после того как я добавил метки к задаче

2020-07-02 10:25 UTC, YuriSilenok commented
> Ошибку вы сами скидывали в комменты, а мерж конфликт стал закрыт после того как я добавил метки к задаче

я не могу найти подобного комментария в этом запросе. могли бы ссылку на него дать?
Не думаю что мерж-конфликт и метки как-то связаны между собой, может быть и здесь вы дадите ссылку?

2020-07-02 10:32 UTC, ssas18 commented
Скорее всего Вы правы, данный конфликт был просто закрыт без каких либо изменений.
https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/1263

2020-07-02 10:42 UTC, YuriSilenok commented
Все конфликты я уже решил, так как нужно было обновить рабочие ветки проекта.
Возвращаемся к задача.
Вам нужно было заполнить институты как оф.сайте КГУ. Вы заполнили?

2020-07-02 10:49 UTC, ssas18 commented
Да, заполнил

2020-07-02 10:53 UTC, YuriSilenok commented
На данный момент я насчитываю больше чем 3 института
![image](https://user-images.githubusercontent.com/14871471/86350380-41d19c00-bc6b-11ea-82d9-e71027f5e9bd.png)
У вас создается 3 
![image](https://user-images.githubusercontent.com/14871471/86350424-5877f300-bc6b-11ea-8331-7b1186d1f407.png)

2020-07-02 10:57 UTC, ssas18 commented
Их там вроде и было больше, понял, будет сделано

2020-07-02 12:01 UTC, ssas18 commented
В институте "Юридический институт им. Ю. П. Новицкого" есть заглавные буквы кроме 1 символа, а так же там есть точки, что не допускает проверка, необходимо ее перенастроить?

2020-07-02 12:03 UTC, YuriSilenok commented
> В институте "Юридический институт им. Ю. П. Новицкого" есть заглавные буквы кроме 1 символа, а так же там есть точки, что не допускает проверка, необходимо ее перенастроить?

Думаю это пахнет новой задачей, у вас кроме этой задачи еще что-то нужно делать?

2020-07-02 12:10 UTC, ssas18 commented
так же института "Институт дополнительного профессионального образования" не проходит проверку по кол-ву символов, пока что локально у себя я увеличил количество максимальных символов. Да долги еще есть, но у меня на данный момент нет доступа к бэклогу.

2020-07-02 12:15 UTC, YuriSilenok commented
> так же института "Институт дополнительного профессионального образования" не проходит проверку по кол-ву символов, пока что локально у себя я увеличил количество максимальных символов. Да долги еще есть, но у меня на данный момент нет доступа к бэклогу.

не стоит исправлять в этой ветке ничего.
Алгоритм следующий.
Вы поднимаете 2 задачи.
Выполняете их и продолжаете эту. 
Две задачи я зачту как две ЛР.
Приостановите деятельность.
Когда задачи будут подняты, нужно будет сослаться на них и сказать что это блокирующие задачи.

2020-07-02 12:30 UTC, ssas18 commented
Приостановлено по причине блокирующих задач: 
#1276 
#1277

2020-07-02 12:47 UTC, YuriSilenok commented
> Приостановлено по причине блокирующих задач:
> #1276
> #1277

Добавил задачи в [бэклог](https://docs.google.com/spreadsheets/d/1KUTm05XHLL1p6AiVZ8-M7TF2RMoE9NAPqR4KMn6NwZM/edit?usp=sharing) и расшарил доступ по ссылке

2020-07-03 08:51 UTC, ssas18 commented
@YuriSilenok  Юрий Викторович, после того как задачи #1276 , #1277 выполнены я пушу изменения рефдаты сюда, но так как ветка (task-1244) старая скорее всего появятся мерж конфликты. Мне просто пушить Рефдату и решать мерж конфликты?

2020-07-03 08:57 UTC, YuriSilenok commented
Нет, сейчас все изменения находятся в ветке дев, вам нужно локально смержить ветку dev  с вашей веткой, конфликты если будут, то минимальные. Удобно мержить и решать конфликты через приложение github desktop.

2020-07-03 09:31 UTC, ssas18 commented
Все изменения сделаны

2020-07-03 10:11 UTC, YuriSilenok approved these changes

2020-07-03 10:41 UTC, merged