Заполнение сущности Преподаватель
Students-of-the-city-of-Kostroma/Student-timetable pull request #1251
Opened 2019-11-28 20:26 UTC by alexeylisica

#1226

2019-11-28 20:34 UTC, Rogachev99 commented
@ alexeylisica , ты от той ветки создавал изменения? Предполагаю, что от master. (нужно от Elite)

2019-11-28 20:48 UTC, alexeylisica commented
@Rogachev99, я делал в ветке задачи

2019-11-28 20:53 UTC, Rogachev99 commented
> @Rogachev99, я делал в ветке задачи

имелось в виду, от какой ветки ты создавал свою?

2019-11-28 20:59 UTC, alexeylisica commented
> > @Rogachev99, я делал в ветке задачи
> 
> имелось в виду, от какой ветки ты создавал свою?

от элиты

2019-11-28 22:08 UTC, Rogachev99 commented
![image](https://user-images.githubusercontent.com/32433285/69833419-c88d4900-1244-11ea-8fb7-fdcd4d595fc3.png)

2019-11-29 14:33 UTC, alexeylisica commented
![image](https://user-images.githubusercontent.com/47520257/69875517-66792600-12ce-11ea-93fa-770a9d18f196.png)

2019-11-29 18:20 UTC, alexeylisica commented
В другом регионе существуют переменные с такими же именами.

2019-11-29 20:02 UTC, NordScandinavian commented
Поправь Assigners, сделай правильно.
\

2019-11-30 07:01 UTC, YuriSilenok requested changes
необходимо из ветки Элита, получить изменения в Вашу ветку
`git merge Elita`

2019-12-01 06:05 UTC, YuriSilenok requested changes
Заполнить табуляцию на пробелы и объединить коммиты в ветке task-1226 dв один коммит

2019-12-06 19:43 UTC, YuriSilenok commented
Жду проверки тимлида

2019-12-11 07:59 UTC, YuriSilenok reviewed
Передать на проверку мне, после проверки тимлидом

2019-12-11 08:02 UTC, YuriSilenok requested changes
Ветка испорчена, ее нужно удалить, и сделать все заного.

2019-12-11 15:37 UTC, closed without merging