fix UT_Insert_CTeacher
Students-of-the-city-of-Kostroma/Student-timetable pull request #1255
Opened 2019-11-30 15:08 UTC by bormolei

#1032

2019-11-30 19:13 UTC, YuriSilenok requested changes
Есть что исправить

2019-11-30 19:13 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Insert_CTeacher.cs
>          public void Task_246_1() //Добавление в пустую таблицу
добавить XML комментарии

2019-11-30 19:13 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Insert_CTeacher.cs
> +			MTeacher tcher = new MTeacher("Садовская", "Ольга", "Борисовна", ma[0]["Reduction"].ToString(), maTi[1]["Reduction"].ToString(), "ФАСТ", "Пн, Вт", "Ср, Чт, Пт", "Воскресенье");
в качестве отступов использовать пробелы

2019-11-30 19:13 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Insert_CTeacher.cs
> +   //         string maTi = addTitle("Профессор", "Проф.");
что это за мусор?

2019-11-30 19:13 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Insert_CTeacher.cs
> +			RefData.CTeacher.Delete(tcher1);
любые действия должны быть проверены на предмет исполнения

2019-11-30 19:37 UTC, bormolei commented on UnitTestOfTimetableOfClasses/UT_Insert_CTeacher.cs
> +			RefData.CTeacher.Delete(tcher1);
Не совсем понимаю, что не так. Здесь я подчищаю те записи которые добавляются в тесте, т.к. при прохождении всех тестов разом выполняется только первые, а остальные не имеют возможности добавить уже имеющуюся запись

2019-12-01 17:26 UTC, YuriSilenok requested changes
Тесты стали выглядеть лучше, нужно добавить проверки

2019-12-01 17:26 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Insert_CTeacher.cs
> +            RefData.CTeacher.Delete(tcher1);
Метод удаления строки вернет истину, если строка удалена, нужно проверять, действительно ли Вам удалось удалить строку

2019-12-04 10:51 UTC, NordScandinavian approved these changes
Checked

2019-12-04 18:28 UTC, YuriSilenok approved these changes

2019-12-04 20:10 UTC, merged

2020-06-25 13:06 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-26 05:04 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-26 05:14 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-27 05:04 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-27 05:12 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-28 05:04 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-28 05:12 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-29 05:04 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-29 05:12 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-30 05:04 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-01 05:04 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-02 05:04 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-03 05:03 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-03 13:15 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-04 05:02 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-05 05:02 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 05:02 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 13:02 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 14:22 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 15:24 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 15:26 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 15:49 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-07 05:02 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-08 05:02 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-09 05:02 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче