Заполнить RefData для сущности Нагрузка для группы 17-ВТбо-1
Students-of-the-city-of-Kostroma/Student-timetable pull request #1257
Opened 2019-12-02 10:46 UTC by MyachevM

#1238

2019-12-04 11:46 UTC, NordScandinavian commented
Поменять табуляцию на пробелы

2019-12-04 15:35 UTC, MyachevM commented
Изменено: замена табуляции на пробелы

2019-12-04 18:29 UTC, YuriSilenok commented
Требуется проверка тимлида

2019-12-05 08:22 UTC, NordScandinavian submitted a review, later dismissed
Checked

2019-12-05 08:34 UTC, YuriSilenok requested changes
Обратите внимание, что в коммите с которого начиналась ветка таска было [36 сбоев](https://dev.azure.com/silenok-86/Student-timetable/_build/results?buildId=1826&view=ms.vss-test-web.build-test-results-tab)
![image](https://user-images.githubusercontent.com/14871471/70217672-ad45a080-1752-11ea-9241-ac4e325479fe.png)

сейчас же их [102](https://dev.azure.com/silenok-86/Student-timetable/_build/results?buildId=1824&view=ms.vss-test-web.build-test-results-tab)
![image](https://user-images.githubusercontent.com/14871471/70217711-c1899d80-1752-11ea-9bc4-735b4af57fcc.png)

причем в [логе](https://dev.azure.com/silenok-86/Student-timetable/_build/results?buildId=1824&view=logs) видно, что тесты посыпались из-за критических ошибок в рефдате, это значит что рефдата не заполняется
![image](https://user-images.githubusercontent.com/14871471/70217810-eb42c480-1752-11ea-8914-013591bf1e92.png)

Тимлид, все это должен бы ты проверить
В следующий раз я заставлю тебя исправлять ошибки которые ты пропустишь

2019-12-23 16:28 UTC, YuriSilenok commented
Нарисовался конфликт

2020-06-25 13:06 UTC, YuriSilenok commented
Какие есть обновления по этой задаче?

2020-06-26 05:04 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

2020-06-26 05:13 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

2020-06-26 09:01 UTC, MyachevM commented
> 
> 
> Какие есть обновления по этой задаче?
Здравствуйте. Пока никаких.

2020-06-27 05:04 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-27 05:12 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-28 05:04 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-28 05:11 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-29 05:04 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-29 05:12 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-30 05:04 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-07-01 05:04 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-07-02 05:03 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-07-03 05:03 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-07-03 08:26 UTC, closed without merging