Разработка и автоматизация сценария тестирования метода Insert (Model model) сущности Нагрузка
Students-of-the-city-of-Kostroma/Student-timetable pull request #1262
Opened 2019-12-05 20:37 UTC by NesgovorovVS

#1240 

https://docs.google.com/spreadsheets/d/114F1wKsHoGB75gmF2p_XUR5zgbUb6IeQNX1ziO_BSIw/edit#gid=1813879881&range=A52:F57 - ссылка на сценарий

2019-12-06 20:44 UTC, NesgovorovVS commented
Исправил ошибки в последнем комите

2019-12-11 07:53 UTC, YuriSilenok reviewed
Повторно отправить мне на проверку, после того, как тимлид проверит этот запрос

2019-12-12 22:26 UTC, NordScandinavian submitted a review, later dismissed
Checked

2019-12-16 15:52 UTC, YuriSilenok requested changes

2019-12-16 15:52 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Insert_CAdemicLoad.cs
> +            CAcademicLoad ca = new CAcademicLoad();
Контроллеры не должны создаваться вне класса рефдата

2019-12-16 15:52 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Insert_CAdemicLoad.cs
> +            CAcademicLoad ca = new CAcademicLoad();
Контроллеры не должны создаваться вне класса рефдата

2019-12-16 15:52 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Insert_CAdemicLoad.cs
> +            bool m = ca.Insert(ma);
где проверка на то, что запись добавилась?

2019-12-23 18:02 UTC, NesgovorovVS commented
Изменения добавлены, отвечу на вопрос заранее, изменил 1240_2 в соответствии со сценарием

2019-12-23 19:11 UTC, YuriSilenok commented
1. Если вы хотите что бы я или тимлид снова что-то проверили, то есть специальная кнопка
![image](https://user-images.githubusercontent.com/14871471/71376018-3113df80-25d1-11ea-82d9-6cfa9c2d2aed.png)

2019-12-26 12:38 UTC, YuriSilenok requested changes
В чем разница в этих тестах?

2019-12-26 12:38 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Insert_CAdemicLoad.cs
> +        /// </summary>
Вы проверили что у Вас таблица пустая?

2020-01-21 12:57 UTC, NesgovorovVS commented
> В чем разница в этих тестах?

в них обязательно должна быть разница?

2020-01-27 07:58 UTC, YuriSilenok commented
> > В чем разница в этих тестах?
> 
> в них обязательно должна быть разница?

Не понимаю причину Вашего вопроса, какие плюсы Вы видете в одинаковых тестах?

2020-05-25 06:58 UTC, YuriSilenok reviewed
С последней моей проверки Вы ничего не исправили, зачем запросили повторную проверку кода?

2020-06-25 13:06 UTC, YuriSilenok commented
Какие есть обновления по этой задаче?

2020-06-25 13:06 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-26 05:04 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

2020-06-26 05:13 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

2020-06-27 05:04 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-27 05:12 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-07-03 13:27 UTC, YuriSilenok requested changes
Из вашего тест-комплекта я не смог найти ссылку на расчеты тестов методом белого ящика.
Смотрите задание, там есть образец.
![image](https://user-images.githubusercontent.com/14871471/86473699-15408180-bd4a-11ea-9f62-26d25cb232d9.png)

2020-07-04 20:01 UTC, NesgovorovVS commented
> Из вашего тест-комплекта я не смог найти ссылку на расчеты тестов методом белого ящика.
> Смотрите задание, там есть образец.
> ![image](https://user-images.githubusercontent.com/14871471/86473699-15408180-bd4a-11ea-9f62-26d25cb232d9.png)

Я отправил, на повторную проверку, но уже понял, что у меня не так сделано. Буду читать внимательнее

2020-07-06 09:30 UTC, YuriSilenok commented
На данный момент мы отказались от ведения сценариев, будет достаточно только отчета на гитхаб

2020-07-06 12:12 UTC, YuriSilenok reviewed
Жду ваших расчетов на гитхаб

2020-08-05 20:59 UTC, YuriSilenok commented
Рекомендую вам добавить больше проверяющих

2020-08-10 06:26 UTC, YuriSilenok commented
Добавьте больше проверяющих

2020-08-13 14:08 UTC, YuriSilenok requested changes
Посмотрел ваш граф
![image](https://user-images.githubusercontent.com/14871471/90144392-70bd5080-dd87-11ea-8503-94b3d158e0ef.png)
Вы уверены что разработчик ожидает исключение в момент выполнение оператора с меткой 10?
![image](https://user-images.githubusercontent.com/14871471/90144486-8cc0f200-dd87-11ea-827a-884e23657de9.png)
Как Вы думаете, зачем сюда поставили исключение?

2020-08-16 11:28 UTC, ssas18 requested changes
Теперь нужно разметить пути и нанести эти регионы на граф

2020-08-21 10:49 UTC, ssas18 requested changes
Ты забыл указать на графе и в пути 15 пункт
И если отрабатывает 11 пункт, то программа никогда не зайдет в пункт 12  
![image](https://user-images.githubusercontent.com/47377817/90882757-23f3fe00-e3b5-11ea-86e7-f173f72a5597.png)

2020-09-09 13:03 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1342', '#1335', '#1333', '#1329', '#1322', '#1294', '#1217']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-14 08:10 UTC, YuriSilenok commented on Docs/UT_Insert_CAcademicLoad/REPORT.md
> +временно не мог работать над задачами, завтра внесу новые изменения
а почему не комментарием?

2020-09-14 13:49 UTC, NesgovorovVS commented on Docs/UT_Insert_CAcademicLoad/REPORT.md
> +временно не мог работать над задачами, завтра внесу новые изменения
> а почему не комментарием?

избавить от лишнего спама

2020-09-14 15:52 UTC, YuriSilenok commented on Docs/UT_Insert_CAcademicLoad/REPORT.md
> +временно не мог работать над задачами, завтра внесу новые изменения
почему вы считаете что информация о том, что срок реализации задачи откладывается, является спамом?

2020-09-14 16:25 UTC, NesgovorovVS commented on Docs/UT_Insert_CAcademicLoad/REPORT.md
> +временно не мог работать над задачами, завтра внесу новые изменения
> почему вы считаете что информация о том, что срок реализации задачи откладывается, является спамом?

![image](https://user-images.githubusercontent.com/47756995/93111965-0d914780-f6c0-11ea-8b5e-b8090776ae3c.png)

2020-09-14 16:28 UTC, NesgovorovVS commented on Docs/UT_Insert_CAcademicLoad/REPORT.md
> +временно не мог работать над задачами, завтра внесу новые изменения
> > почему вы считаете что информация о том, что срок реализации задачи откладывается, является спамом?
> 
> ![image](https://user-images.githubusercontent.com/47756995/93111965-0d914780-f6c0-11ea-8b5e-b8090776ae3c.png)

потому что мне показалось в тот момент, что сообщения об отложении работы, тем более, если не в одном таске, являются спамом

2020-09-14 17:54 UTC, YuriSilenok commented on Docs/UT_Insert_CAcademicLoad/REPORT.md
> +временно не мог работать над задачами, завтра внесу новые изменения
Объясню.
Сообщение `Ведутся работы` выглядит как спам, потому что нет коммитов и обсуждений, подтверждающих это. Это как минимум ложная информация. Если работы ведутся, то достаточно коммитов с изменениями. 

Здесь `временно не мог работать над задачами, завтра внесу новые изменения` есть сведения о том, что вы не могли работать и я понимаю что работа простаивала, в идеале указать причину по которой работа простаивала, а так же вы сказали когда работы возобновятся, что означает что Вы берете на себя ответственность показать какие-то улучшения/изменения в коде.

Вам стала понятна моя позиция относительно двух этих ситуация и почему я так отреагировал в каждой из них?

2020-09-14 18:27 UTC, NesgovorovVS commented on Docs/UT_Insert_CAcademicLoad/REPORT.md
> +временно не мог работать над задачами, завтра внесу новые изменения
> Объясню.
> Сообщение `Ведутся работы` выглядит как спам, потому что нет коммитов и обсуждений, подтверждающих это. Это как минимум ложная информация. Если работы ведутся, то достаточно коммитов с изменениями.
> 
> Здесь `временно не мог работать над задачами, завтра внесу новые изменения` есть сведения о том, что вы не могли работать и я понимаю что работа простаивала, в идеале указать причину по которой работа простаивала, а так же вы сказали когда работы возобновятся, что означает что Вы берете на себя ответственность показать какие-то улучшения/изменения в коде.
> 
> Вам стала понятна моя позиция относительно двух этих ситуация и почему я так отреагировал в каждой из них?

да, теперь понял

2020-10-07 13:53 UTC, YuriSilenok requested changes
Нарушены [требования именования веток](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/branches.md#issue-d). Головная ветка task-1240 не соответствует требованиям.

2020-10-07 14:01 UTC, YuriSilenok commented
Нарушены [требования именования веток](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/branches.md#issue-d). Головная ветка task-1240 не соответствует требованиям.

2020-10-07 14:01 UTC, closed without merging