Разработал метод хранения данных получаемых  в XML формате.
Students-of-the-city-of-Kostroma/Student-timetable pull request #1265
Opened 2019-12-10 10:32 UTC by NesgovorovVS

#1264

2019-12-11 07:59 UTC, YuriSilenok reviewed
Передать на проверку мне, после проверки тимлидом

2019-12-23 16:34 UTC, YuriSilenok requested changes
Почему ваши разработки находятся в тестовом проекте?

2019-12-23 17:16 UTC, NesgovorovVS commented
> Почему ваши разработки находятся в тестовом проекте?

А где они должны находится?

2019-12-23 19:10 UTC, YuriSilenok commented
> > Почему ваши разработки находятся в тестовом проекте?
> 
> А где они должны находится?

В библиотечном проекте, функционал не может разрабатываться в тестовм проекте, так как тестовый проект предназначен для тестирования разработанной в библиотечном проекте функциональности

2019-12-24 16:07 UTC, NesgovorovVS commented
Перекинул разработки в библиотечный проект

2019-12-26 12:42 UTC, YuriSilenok requested changes
Добавить к классу XML-документацию

2020-05-25 06:56 UTC, YuriSilenok requested changes
Исправить XML документацию кода

2020-05-25 06:56 UTC, YuriSilenok commented on LibOfTimetableOfClasses/WriteXML.cs
> +        //в то время как метод записывает только схему. WriteXml Чтобы записать данные и схему, задайте mode для WriteSchemaпараметра значение.
Неправильная документирование класса, используйте `///`

2020-05-25 06:56 UTC, YuriSilenok commented on LibOfTimetableOfClasses/WriteXML.cs
> +    class writeXmltofile
отсутствует XML документация

2020-06-25 13:06 UTC, YuriSilenok commented
Какие есть обновления по этой задаче?

2020-06-26 05:04 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

2020-06-26 05:13 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в вехе для которой пройден дедлайн, а задача при этом открыта

2020-06-27 05:04 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-06-27 05:12 UTC, YuriSilenok commented
Пожалуйста, обратите внимание что эта задача находится в закрытой вехе, а сама является открытой

2020-08-10 06:19 UTC, YuriSilenok commented
Когда будет готово к проверке, добавьте больше проверяющих.

2020-08-12 07:54 UTC, YuriSilenok commented
Закрывается в связи с передачей основной задачи

2020-08-12 07:54 UTC, closed without merging