Заполнение RefData сущности преподаватель для группы 17-Идбо-3
Students-of-the-city-of-Kostroma/Student-timetable pull request #1266
Opened 2019-12-11 16:30 UTC by alexeylisica

#1226

2019-12-12 18:53 UTC, NordScandinavian submitted a review, later dismissed
Checked

2019-12-12 18:54 UTC, NordScandinavian commented
Исправь табуляцию на пробелы

2019-12-12 20:18 UTC, NordScandinavian submitted a review, later dismissed
Checked

2019-12-16 15:48 UTC, YuriSilenok requested changes
Есть вопросы

2019-12-16 15:48 UTC, YuriSilenok commented on LibOfTimetableOfClasses/RefData.cs
> +            DataSet.Relations.Add("CTitle-Teacher", CTitle.Columns["Reduction"], CTeacher.Columns["academicTitle"]);
Почему были переименованы **academicDegree** и **academicTitle**?

2019-12-16 15:48 UTC, YuriSilenok commented on LibOfTimetableOfClasses/RefData.cs
> -            CAuditor.Insert(new MAuditor("418", "", 0, "Б"));
Почему было удалено заполнение рефдаты?

2019-12-16 15:48 UTC, YuriSilenok commented on README.md
> +Задача - это активность за выполнение которой начисляютс баллы. 1 task = 1 балл. Каждая задача может иметь любое количество меток, они определяют тип задачи, этап ее выполнения и принадлежность к фун
Почему это было изменено?

2019-12-16 15:48 UTC, YuriSilenok commented on azure-pipelines.yml
> +- master
Почему это добавлено сюда?

2019-12-16 21:38 UTC, alexeylisica commented on LibOfTimetableOfClasses/RefData.cs
> -            CAuditor.Insert(new MAuditor("418", "", 0, "Б"));
> Почему было удалено заполнение рефдаты?

Для исправления ошибок был использован старый клон ветки, где данного кода еще нет

2019-12-16 21:51 UTC, alexeylisica commented on README.md
> +Задача - это активность за выполнение которой начисляютс баллы. 1 task = 1 балл. Каждая задача может иметь любое количество меток, они определяют тип задачи, этап ее выполнения и принадлежность к фун
> Почему это было изменено?

вероятно потому что в новой версии клона ветки был добавлен пробел между словами "с ней" "задачами", сам я пробел не добавлял

2019-12-17 18:55 UTC, alexeylisica commented on azure-pipelines.yml
> +- master
> Почему это добавлено сюда?

Использовался старый клон ветки

2019-12-17 18:56 UTC, alexeylisica commented
> Есть вопросы

сделал новый клон ветки и добавил свой код

2019-12-22 10:14 UTC, YuriSilenok requested changes
Переделать, используя актуальную ветку.

2019-12-23 18:36 UTC, YuriSilenok requested changes
В чем причина этих ошибок?
```
2019-12-22T11:26:47.5265952Z Failed   Task_1245_1
2019-12-22T11:26:47.5281217Z Error Message:
2019-12-22T11:26:47.5281509Z  Test method UnitTestOfTimetableOfClasses.UT_Update_CAcademicLoad.Task_1245_1 threw exception: 
2019-12-22T11:26:47.5281755Z System.TypeInitializationException: The type initializer for 'LibOfTimetableOfClasses.RefData' threw an exception. ---> System.ArgumentException: DataTable already belongs to this DataSet.
2019-12-22T11:26:47.5281949Z Stack Trace:
2019-12-22T11:26:47.5282608Z     at System.Data.DataTableCollection.BaseAdd(DataTable table)
2019-12-22T11:26:47.5282762Z    at System.Data.DataTableCollection.Add(DataTable table)
2019-12-22T11:26:47.5282956Z    at LibOfTimetableOfClasses.RefData..ctor() in D:\a\1\s\LibOfTimetableOfClasses\RefData.cs:line 44
2019-12-22T11:26:47.5283151Z    at LibOfTimetableOfClasses.RefData..cctor() in D:\a\1\s\LibOfTimetableOfClasses\RefData.cs:line 26
2019-12-22T11:26:47.5283336Z --- End of inner exception stack trace ---
2019-12-22T11:26:47.5283528Z     at UnitTestOfTimetableOfClasses.UT_Update_CAcademicLoad.Task_1245_1() in D:\a\1\s\UnitTestOfTimetableOfClasses\UT_Update_CAcademicLoad.cs:line 18
```

2019-12-23 19:07 UTC, YuriSilenok commented
Следите за исправлениями рефдаты

2020-01-05 17:25 UTC, YuriSilenok commented
перенес обсуждение коммита в диалог

2020-01-19 14:45 UTC, YuriSilenok approved these changes

2020-01-19 14:47 UTC, YuriSilenok commented on LibOfTimetableOfClasses/RefData.cs
> -            CAuditor.Insert(new MAuditor("418", "", 0, "Б"));
Вы не правильно используете git

2020-02-11 15:13 UTC, merged