Task 1192
Students-of-the-city-of-Kostroma/Student-timetable pull request #1286
Opened 2020-07-03 16:21 UTC by ZhizhikinIvan

Метод белого ящика.

![image](https://user-images.githubusercontent.com/47943099/86485490-7e7fbf00-bd61-11ea-8fc2-712df5c9c37a.png)

![image](https://user-images.githubusercontent.com/47943099/86485504-8a6b8100-bd61-11ea-9700-89d82ca07e96.png)

2020-07-03 17:35 UTC, YuriSilenok commented
Вижу кто помогал, но мы там кое-что не обсуждали.
- и гитхаб теперь есть возможность в атрибута задачи или запроса указать связанную с ним запрос или задачу соответственно. Этим нужно пользоваться.
- запрос на слияние нужен для проверки кода и не правильно будет в нем проверять расчёты по белому ящику.
-  расчёты по белому ящику нужно представлять в виде гугл документа, на который ведёт ссылка из сценариев. Если этого нет, то я добавлю в описание задачи.

2020-07-03 17:37 UTC, YuriSilenok requested changes
Откроете этот запрос тогда, когда будет верно рассчитан белый ящик

2020-07-07 15:18 UTC, ssas18 approved these changes

2020-07-08 11:05 UTC, ifuwmnn approved these changes

2020-07-09 17:43 UTC, YuriSilenok approved these changes
Замечаний нет.

2020-07-24 21:01 UTC, merged

2020-07-27 16:26 UTC, YuriSilenok commented
Я не несу ответственности за запрос.