Исправил сбои в автотестах расположенных в файле UT_Insert_CGroup
Students-of-the-city-of-Kostroma/Student-timetable pull request #1287
Opened 2020-07-03 18:44 UTC by ZhizhikinIvan

Метод белого ящика.

![image](https://user-images.githubusercontent.com/47943099/86492214-0bcd0e80-bd76-11ea-9d73-50601b7875f9.png)

2020-07-03 18:50 UTC, YuriSilenok commented
Убрать расчёты белого ящика из запроса

2020-07-06 12:11 UTC, YuriSilenok reviewed
Жду ваших расчетов на github

2020-07-07 15:17 UTC, ssas18 submitted a review, later dismissed

2020-07-08 11:04 UTC, ifuwmnn submitted a review, later dismissed

2020-07-09 15:42 UTC, YuriSilenok requested changes
![image](https://user-images.githubusercontent.com/14871471/87060936-c7c58800-c213-11ea-9602-a5b0dd70a183.png)
Маршруты не имеют конечной вершины.

2020-07-09 17:02 UTC, ssas18 submitted a review, later dismissed

2020-07-09 17:11 UTC, ifuwmnn submitted a review, later dismissed

2020-07-09 17:32 UTC, YuriSilenok reviewed
![image](https://user-images.githubusercontent.com/14871471/87071574-14fd2600-c223-11ea-9a47-7c56b171e765.png)
![image](https://user-images.githubusercontent.com/14871471/87071598-1cbcca80-c223-11ea-8a1e-cf355afa7615.png)

Не совсем понял разницу между двумя формулировками, мне показалось это одним и тем же?

2020-07-09 19:20 UTC, ZhizhikinIvan commented
В первом случае, мы пытаемся добавить модель к уже существующей с одинаковыми группами.
Во втором случае, все атрибуты отличаются от уже существующей записи.

2020-07-10 19:13 UTC, YuriSilenok reviewed
Простите, мой вопрос не очень корректен был, я сравнил не те тесты.
![image](https://user-images.githubusercontent.com/14871471/87189710-c8d0e500-c2f9-11ea-84f1-2972b8ecfb28.png)
![image](https://user-images.githubusercontent.com/14871471/87189726-d4bca700-c2f9-11ea-8382-a2e8b635b91a.png)

Я воспринимаю что термин "Новые данные" означает что добавляемые атрибуты "не дублируют", то есть, не совпадают с уже существующими данными. Мне кажется это одинаковые (дубликаты) тесты.

2020-07-10 19:41 UTC, ZhizhikinIvan commented
Да, вы правы, тесты одинаковые. Я исходил из предположения, что в первом случае, таблица полностью пустая. А во втором случае, в таблицу уже занесены какие-то данные.

2020-07-11 06:23 UTC, YuriSilenok commented
В вашем алгоритме нет цикла перебора таблицы, для которого пустая таблица стала бы условием для пропуска итераций этого цикла.

2020-07-12 18:08 UTC, ZhizhikinIvan commented
Я имел в виду что, при запуске тестов, в RefData.CGroup записываются инициализирущие значения, т.е. фактически таблица не пустая. Но я считаю таблицу пустой, потому что эти значения вставлены не в рамках теста. Поэтому в тесте 251_1, я добавляю данные первый раз и добавляю одну группу.
В тесте 251_10, я добавляю не одну группу, а две. Т.е. фактически, этот тест повторяет тест 251_1, плюс добавление еще одной группы.

2020-07-14 19:30 UTC, YuriSilenok commented
> Я имел в виду что, при запуске тестов, в RefData.CGroup записываются инициализирущие значения, т.е. фактически таблица не пустая. Но я считаю таблицу пустой, потому что эти значения вставлены не в рамках теста. Поэтому в тесте 251_1, я добавляю данные первый раз и добавляю одну группу.
> В тесте 251_10, я добавляю не одну группу, а две. Т.е. фактически, этот тест повторяет тест 251_1, плюс добавление еще одной группы.
> Возможно я не прав и это действие избыточно.

Вот что нужно сделать, в названии теста нужно писать идею теста, пример я писал в чат недавно. Думаю это поможет прояснить задумку. Описание с уклоном на реализацию не такая хорошая практика. 
Относительно рефдаты, если вы считаете что плохо что рефдата заполняется в конструкторе рефдаты, то предлагаю создать задачу в которой нужно будет вызывать заполнение рефдаты отдельно, тогда, когда это нужно.

2020-07-14 19:30 UTC, YuriSilenok reviewed
отписал в комментарии выше

2020-07-18 12:36 UTC, ssas18 approved these changes

2020-07-19 15:13 UTC, YuriSilenok reviewed
> Относительно рефдаты, если вы считаете что плохо что рефдата заполняется в конструкторе рефдаты, то предлагаю создать задачу в которой нужно будет вызывать заполнение рефдаты отдельно, тогда, когда это нужно.

Можно услышать ваше мнение по этому поводу?

2020-07-19 18:16 UTC, ZhizhikinIvan commented
Честно говоря, мне не хватает знаний и опыта, что бы судить о правильности заполнения рефдаты таким образом.

2020-07-19 18:51 UTC, YuriSilenok reviewed
Я не увидел ошибок в отчете, думаю вы можете приступать к сверке тестов и автотестов

2020-07-19 18:52 UTC, ZhizhikinIvan commented
Хорошо

2020-07-21 17:15 UTC, ZhizhikinIvan commented
Юрий Викторович, а что вы подразумеваете под "сверкой тестов и автотестов"?

2020-07-22 12:59 UTC, YuriSilenok commented
> Юрий Викторович, а что вы подразумеваете под "сверкой тестов и автотестов"?

У многих из вас задание выдано на разработку тестов по белому ящику при условии что какие-то тесты уже есть. Есть вероятность что то, что вы получите, не совпадет с тем, что вы предоставили в отчете, нужно проверить. все ли совпадает, если не совпадает, сделать как надо.

2020-07-27 10:55 UTC, ZhizhikinIvan commented
Юрий Викторович, тесты я сверил, вроде всё совпадает.

2020-07-27 16:34 UTC, YuriSilenok reviewed
По старой традиции нужны две положительные проверки Вашей работы.
Тогда я Приступить к заключительной проверке.

2020-07-27 17:55 UTC, ifuwmnn submitted a review, later dismissed

2020-07-27 19:17 UTC, ssas18 submitted a review, later dismissed

2020-07-30 11:01 UTC, ZhizhikinIvan commented
Юрий Викторович, две положительные проверки работы есть. Не могли бы вы проверить работу?

2020-07-30 20:06 UTC, YuriSilenok commented
Как буду у компа. Может кто-то ещё проверит? По методике

2020-08-01 12:29 UTC, YuriSilenok requested changes
![image](https://user-images.githubusercontent.com/14871471/89101764-b08d4b00-d40b-11ea-8cd4-67c075e8d392.png)
Если вы совершаете манипуляции с данными, то нужно убедится что они совершены.

2020-08-01 12:29 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Insert_CGroup.cs
>          /// Ввод корректных данных в пустую таблицу
Идея теста в отчете гласит `Добавить новые корректные данные в таблицу.`

2020-08-06 16:48 UTC, ZhizhikinIvan commented on UnitTestOfTimetableOfClasses/UT_Insert_CGroup.cs
>          /// Ввод корректных данных в пустую таблицу
Юрий Викторович, что вы подразумеваете под "нужно убедится что они совершены"?  
Я смотрел, что бы вводимые данные удовлетворяли идее теста.

2020-08-06 20:13 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Insert_CGroup.cs
>          /// Ввод корректных данных в пустую таблицу
Простите, не проверил свое сообщение. Суть в том, что вызов метода вставки не гарантирует что данные будут добавлены, если они не будут добавлены, то ход теста изменится и нельзя считать результаты теста дрстоверными, по этому нужно проверять, были ли добавлены данные методом insert

2020-08-12 18:06 UTC, ZhizhikinIvan commented on UnitTestOfTimetableOfClasses/UT_Insert_CGroup.cs
>          /// Ввод корректных данных в пустую таблицу
Юрий Викторович, вы правы. Исправил.

2020-08-13 15:04 UTC, YuriSilenok approved these changes
![image](https://user-images.githubusercontent.com/14871471/90150782-ae71a780-dd8e-11ea-85ad-c2f00197eaee.png)
Все тесты пройдены
![image](https://user-images.githubusercontent.com/14871471/90151442-630bc900-dd8f-11ea-86fb-63c4b6ee10b8.png)
Покрытие кода 100%

2020-08-13 16:40 UTC, merged