Исправление сбоев в автотестах расположенных в  UT_Update_CAcademicLoad
Students-of-the-city-of-Kostroma/Student-timetable pull request #1294
Opened 2020-07-06 08:25 UTC by ssas18

#1280

2020-07-06 11:12 UTC, YuriSilenok requested changes
Маршрут и граф не совместимы.
![image](https://user-images.githubusercontent.com/14871471/86587629-a73acb00-bf92-11ea-8f2e-81a805d80933.png)

2020-07-06 11:41 UTC, YuriSilenok requested changes
Маршруты после прохода своего региона должны стремиться пройти по максимально короткому маршруту.
R3 = 0 - 2 - 3 - 2 - 3 - 4 - 5 - 6 - 7 - 8 - 10 - 11 - 12 - 13 -18

То есть, 0-2-3-2- не3, а куда?

2020-07-06 11:46 UTC, ssas18 commented
Получается 0-2-3-2-17-18?

2020-07-06 11:47 UTC, YuriSilenok commented
да

2020-07-06 11:57 UTC, YuriSilenok requested changes
Только сейчас заметил. Только один регион находится в одной области ограниченной ребрами графа
![image](https://user-images.githubusercontent.com/14871471/86590838-0c91ba80-bf99-11ea-95b2-3ba356fc9acd.png)

2020-07-06 11:57 UTC, YuriSilenok commented on Docs/UT_Update_CAcademicLoad/REPORT.md
> +R3 = 0 - 2 - 3 - 2 - 3 - 17 - 18
Не существует перехода 3-17

2020-07-06 11:59 UTC, ssas18 commented on Docs/UT_Update_CAcademicLoad/REPORT.md
> +R3 = 0 - 2 - 3 - 2 - 3 - 17 - 18
Правильно понимаю что путь R6 не может существовать?

2020-07-06 12:02 UTC, YuriSilenok commented on Docs/UT_Update_CAcademicLoad/REPORT.md
> +R3 = 0 - 2 - 3 - 2 - 3 - 17 - 18
R6 это регион и вы пишете в комментарию к конкретной строке документа, а значит не по теме.
Отвечу в общих комментариях

2020-07-06 12:03 UTC, ssas18 commented
Правильно понимаю что путь R6 не может существовать?

2020-07-06 12:03 UTC, YuriSilenok commented
> Правильно понимаю что путь R6 не может существовать?

Думаю количество регионов у станет меньше, когда вы пронумеруете их верно и в маршруте для региона 6 не будет необходимости

2020-07-06 12:46 UTC, YuriSilenok reviewed
Внимательнее пожалуйста к составлению маршрутов
![image](https://user-images.githubusercontent.com/14871471/86594428-ad837400-bf9f-11ea-89b2-8e9da71dca36.png)
Можете приступать к составлению тестовых сценариев.

2020-07-06 13:03 UTC, ssas18 commented
Да извините, не увидел

2020-07-06 13:07 UTC, YuriSilenok requested changes
![image](https://user-images.githubusercontent.com/14871471/86596376-c7728600-bfa2-11ea-93ea-e5582a550808.png)
Ну,а тесты где, что тут проверять?
Я же просил приступить к написанию тестов

2020-07-06 13:12 UTC, ssas18 commented
@YuriSilenok  мне написать сценарии для прохождения тестов?
Или что-то другое?
Можно пример правильного отчета если можно?

2020-07-06 13:41 UTC, YuriSilenok commented
> @YuriSilenok мне написать сценарии для прохождения тестов?
> Или что-то другое?
> Можно пример правильного отчета если можно?

ты для каждого маршрута должен смоделировать ситуацию при которых эта ситуация будет воспроизведенена.
могут появиться ситуации когда маршрут недостижим, тогда нужно объяснить почему это так.
А так же обратить внимание, что на один маршрут, может быть несколько тестов, их так же нужно объяснить. 
Все объяснения можно сделать в выводе.

2020-07-06 13:43 UTC, ssas18 commented
Все понял, спасибо

2020-07-07 14:38 UTC, ZhizhikinIvan submitted a review, later dismissed

2020-07-08 10:58 UTC, ifuwmnn submitted a review, later dismissed

2020-07-08 13:36 UTC, YuriSilenok requested changes
1. В инпутах нужно указывать значения для всех полей. Иначе складывается впечатления что их не нужно заполнять.
2. Для маршрута R1 указанные вами входные данные не поведут вас по маршруту R1.
3. Нумерация тестов не удовлетворяет требованиям.

2020-07-08 15:09 UTC, ssas18 commented
1. Я тестирую метод update, и, как мне кажется, я должен вводить только ту информацию, которую обновляю, или я не прав?
2. В R1 условие что MAcademic.Group == null, как мне это обозначить чтобы было правильно? Написать что MAcademic.Group = null или MAcademic.Group == null?
3. Нумерация тестов должна быть 1245_1, 1245_2... ?

2020-07-08 16:46 UTC, ssas18 commented
> 1. В инпутах нужно указывать значения для всех полей. Иначе складывается впечатления что их не нужно заполнять.
> 2. Для маршрута R1 указанные вами входные данные не поведут вас по маршруту R1.
> 3. Нумерация тестов не удовлетворяет требованиям.

1. Я тестирую метод update, и, как мне кажется, я должен вводить только ту информацию, которую обновляю, или я не прав?
2. В R1 условие что MAcademic.Group == null, как мне это обозначить чтобы было правильно? Написать что MAcademic.Group = null или MAcademic.Group == null?
3. Нумерация тестов должна быть 1245_1, 1245_2... ?

2020-07-09 17:03 UTC, YuriSilenok commented
> > 1. В инпутах нужно указывать значения для всех полей. Иначе складывается впечатления что их не нужно заполнять.
> > 2. Для маршрута R1 указанные вами входные данные не поведут вас по маршруту R1.
> > 3. Нумерация тестов не удовлетворяет требованиям.
> 
> 1. Я тестирую метод update, и, как мне кажется, я должен вводить только ту информацию, которую обновляю, или я не прав?
> 2. В R1 условие что MAcademic.Group == null, как мне это обозначить чтобы было правильно? Написать что MAcademic.Group = null или MAcademic.Group == null?
> 3. Нумерация тестов должна быть 1245_1, 1245_2... ?

1. Вы не сможете заполнить только отдельное поле из объекта, так как на сами поля накладываются ограничения, вы просто не сможете создать такой экземпляр класса. Если вы хотите указать что только вот эти поля важны, то для остальных нужно написать что-то типа "Валидные данные". Это будет значить что тестировщик сам должен их придумать от сложившейся ситуации.

2. MAcademic.Group не инициализировано, не заполнено или как вы написали.

3. Думаю да, можете предложенную Вами нумерацию оставить

2020-07-09 17:04 UTC, YuriSilenok reviewed
Ответил в [комментарии](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1294#issuecomment-656243506)

2020-07-10 18:06 UTC, ZhizhikinIvan submitted a review, later dismissed

2020-07-11 07:27 UTC, ssas18 commented
Проверьте хоть кто-то, пожалуйста

2020-07-11 10:39 UTC, Heriuple submitted a review, later dismissed

2020-07-11 11:29 UTC, YuriSilenok requested changes
- R1 -  согласен что не достижим, по причине того, что данная проверка осуществляется вне этого метода. Это значит что мы нашли логическую ошибку в самом методе. Предлагаю вам поднять на это задачу, в рамках которой будет выполнено исправление когда и отчета о тестировании. Нумерацию для недостижимых тестов нумерацию тестов следует пропускать.

- R2 - не смог найти объяснений почему данный маршрут недостижим, почему?

- R3 - так же как и в R3 я не вижу причин почему этот маршрут является недостижимым. Заголовок этого теста не указывает на особенности маршрута.

- R5 - так же не могу понять почему маршрут недостижим?

2020-07-11 12:33 UTC, ssas18 commented
> * R1 -  согласен что не достижим, по причине того, что данная проверка осуществляется вне этого метода. Это значит что мы нашли логическую ошибку в самом методе. Предлагаю вам поднять на это задачу, в рамках которой будет выполнено исправление когда и отчета о тестировании. Нумерацию для недостижимых тестов нумерацию тестов следует пропускать.
> * R2 - не смог найти объяснений почему данный маршрут недостижим, почему?
> * R3 - так же как и в R3 я не вижу причин почему этот маршрут является недостижимым. Заголовок этого теста не указывает на особенности маршрута.
> * R5 - так же не могу понять почему маршрут недостижим?

 R2 -  в рамках данного теста мы не можем изменять поле Group, так как по функционалу оно не подвержено изменению, но если исправлять автотесты и добавлять в метод update поле Group, то да, данный путь достижим.
R3  - Если следовать логике описанной в R2, то он так же достижим
R5 - Если следовать входным данным, то в поле discipline  мы вводим число, что недопустимо для этого поля и он просто не дойдет до ексершена

2020-07-13 06:53 UTC, ssas18 commented
@ifuwmnn , @ZhizhikinIvan , @Heriuple  , @MyachevM  , @NesgovorovVS  , нужен ревью. пожалуйста

2020-07-13 13:26 UTC, ssas18 commented
@ifuwmnn , @ZhizhikinIvan , @Heriuple , @MyachevM , @NesgovorovVS , @NordScandinavian  нужен ревью. пожалуйста

2020-07-14 17:42 UTC, ifuwmnn submitted a review, later dismissed

2020-07-14 18:41 UTC, ssas18 commented
@ZhizhikinIvan , @Heriuple , @MyachevM , @NesgovorovVS , @NordScandinavian нужен ревью. пожалуйста

2020-07-16 06:52 UTC, ssas18 commented
> @ZhizhikinIvan , @Heriuple , @MyachevM , @NesgovorovVS , @NordScandinavian нужен ревью. пожалуйста

2020-07-16 21:43 UTC, Heriuple submitted a review, later dismissed
Не смог найти ошибки, связанной с R2.

2020-07-19 14:51 UTC, YuriSilenok requested changes
> Атрибут Группа пустой

Думая самая близкая формулировка не задан, так как термин "Пустой" легко спутать с пустой строкой.

> Атрибут Rows не содержит строк

Это не выглядит как идея теста и эта фраза содержит технические подробности.

> нуждается в исправлении, пока не знаю как

Я хотел бы понять в чем заключается трудность, что вы не можете сделать?

2020-07-19 15:04 UTC, ssas18 commented
> > Атрибут Группа пустой
> 
> Думая самая близкая формулировка не задан, так как термин "Пустой" легко спутать с пустой строкой.
> 
> > Атрибут Rows не содержит строк
> 
> Это не выглядит как идея теста и эта фраза содержит технические подробности.
> 
> > нуждается в исправлении, пока не знаю как
> 
> Я хотел бы понять в чем заключается трудность, что вы не можете сделать?

Мне сложно понять как и где задается атрибут Rows.count, в каждом тесте он имеет свое значение, и как ни старался я на него повлиять, не выходило, в связи с этим я посчитал тест 1245_2  недостижимым. Так же я не понимаю за что он отвечает, да, я вижу что ему присваиваются значения для обновления, но я не понимаю как на него повлиять

2020-07-19 18:43 UTC, YuriSilenok commented
> Мне сложно понять как и где задается атрибут Rows.count, в каждом тесте он имеет свое значение, и как ни старался я на него повлиять, не выходило

Есть несколько путей: 
- Не заполнять RefData при ее создании, а заполнять отдельным методом. Все таблицы будут пустыми. Минус в том, что для создания Академической нагрузке потребуется создание данных в других таблицах, так как академическая нагрузка имеет реляционные связи. 
- Воспользоваться методом Delete, но тут придется циклом удалять, думаю это не очень красиво будет выглядеть.
- Если вы обратите внимание, то класс в котором находится тестируемый метод является наследником класса DataTable, а он в свою очередь имеет [метод очистки таблицы](https://docs.microsoft.com/ru-ru/dotnet/api/system.data.datatable.clear?view=netframework-4.5). 

> Так же я не понимаю за что он отвечает, да, я вижу что ему присваиваются значения для обновления, но я не понимаю как на него повлиять

Для понимания что это за класс, вы можете почитать про его родителя [DataTable](https://docs.microsoft.com/ru-ru/dotnet/api/system.data.datatable?view=netframework-4.5).

2020-07-23 11:48 UTC, ssas18 commented
> @ifuwmnn , @ZhizhikinIvan , @Heriuple , @MyachevM , @NesgovorovVS , @NordScandinavian  нужен ревью. пожалуйста

Нужен ревью

2020-07-23 12:54 UTC, Alphavite51 submitted a review, later dismissed

2020-07-23 15:41 UTC, YuriSilenok commented
@Alphavite51 
Обратите на [комментарий](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1295#issuecomment-663078957).

2020-07-27 16:30 UTC, YuriSilenok reviewed
[Коммент](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1295#pullrequestreview-455943106)

2020-07-27 16:38 UTC, ssas18 commented
> > @ifuwmnn , @ZhizhikinIvan , @Heriuple , @MyachevM , @NesgovorovVS , @NordScandinavian  нужен ревью. пожалуйста
> 
> Нужен ревью

2020-07-28 08:13 UTC, NesgovorovVS submitted a review, later dismissed

2020-07-31 09:39 UTC, Alphavite51 reviewed
Второй регион описан не верно 
Сначала идет "Предварительное условие " , а потом информация о "Входных параметрах"

2020-07-31 09:55 UTC, Alphavite51 commented
Или условие заключается в том что "Входных данных" нет?

2020-07-31 10:04 UTC, ssas18 commented
> Или условие заключается в том что "Входных данных" нет?

Да, в этом заключается условие

2020-08-01 12:59 UTC, YuriSilenok requested changes
Нужно разобраться с назначением столбцов в таблице сценариев

2020-08-01 12:59 UTC, YuriSilenok commented on Docs/UT_Update_CAcademicLoad/REPORT.md
> +|R2|1245_1|Изменить сведения в пустой таблице| Входных данных нет | Rows.count = "0" Discipline = "Валидные данные"; Distributed = "Валидные данные"; Occupation = "Валидные данные"; Teacher = "Валидн
> Входных данных нет

Предварительное условие не имеет отношение к входным данным, оно описывает состояние системы, это значит что здесь нужно написать что таблица академической нагрузки пуста.

> Rows.count = "0" 

А это не имеет отношение к входным данным

> Входные данные не могут быть пусты

Они у вас и не пусты, вы же написали что они заполнены валидными данными.

2020-08-05 06:55 UTC, ssas18 commented
@Students-of-the-city-of-Kostroma/17-elite нужен ревью

2020-08-05 14:47 UTC, YuriSilenok commented
> @Students-of-the-city-of-Kostroma/17-elite нужен ревью
> 

Да если бы читали почту, у многих больше недели задачи висят.

2020-08-05 15:59 UTC, Alphavite51 submitted a review, later dismissed
Выглядит верно

2020-08-05 20:50 UTC, YuriSilenok commented
Жду второго проверяющего

2020-08-07 05:01 UTC, ssas18 commented
@Students-of-the-city-of-Kostroma/17-elite нужен ревью

2020-08-08 06:57 UTC, ssas18 commented
@Students-of-the-city-of-Kostroma/17-elite нужен ревью

2020-08-08 10:26 UTC, NesgovorovVS submitted a review, later dismissed
На мой взгляд ошибок не обнаружено

2020-08-11 17:54 UTC, YuriSilenok requested changes
![image](https://user-images.githubusercontent.com/14871471/89931093-6b8bc480-dc14-11ea-93b4-3b998bcc6ba5.png)


> Данный автотест не можнт обновлять пустые данные

Ну как бы ожидаемо что невозможно обновить данные которых нет, а маршрут то почему недостижим?

2020-08-13 14:02 UTC, YuriSilenok requested changes
![image](https://user-images.githubusercontent.com/14871471/90142248-d0662c80-dd84-11ea-8d0f-a7c24b21a081.png)
Вот это часть реализации, лучше словами распишите условие.
Еще я думаю что Вы не поняли как должны подбираться входные параметры для теста 1245_2
Рассказываю,
|Предварительное условие|Входные параметры|
| --- | --- |
|Таблица содержит одну строку с данными: Параметр1=100; Параметр2=200; Параметр3=300|Параметр1=0; Параметр2=200; Параметр3=300|

Если мы знаем что Параметр1 является первичным ключом, то есть, тем параметром который будет уникальным в системе и отвечать за поиск нужной строки. И наша задача протестировать, что если мы будем пытаться изменить данные которые не совпадают по первичному ключу. То мы как тестировщики должны дать максимально похожие данные что уже есть, за исключение данных, которые должны проверить условие. Если данный тест отработает ожидаемо, то это будет значить что обновление данных в системе происходит по единственному параметру это Параметр1 и не происходит по параметру Параметр2 и Параметр3. То есть, если произойдет вдруг обновление данных, это будет значить что Параметр1 не является первичным ключом поиска. По этому не стоит писать во входных параметрах валидные данные, так как нам нужно что бы параметр 2 и 3 точно совпадали, а параметр 1 не совпадал.

2020-08-14 07:32 UTC, YuriSilenok requested changes
![image](https://user-images.githubusercontent.com/14871471/90225061-5cc22f00-de19-11ea-99c2-69a7681bc966.png)
Мне кажется здесь какая-то путаница

2020-08-14 07:42 UTC, YuriSilenok requested changes
![image](https://user-images.githubusercontent.com/14871471/90225675-6b5d1600-de1a-11ea-85d6-09b0d345e5cf.png)
Пожалуйста, не используйте вставки кода тестовых сценариях.
Опишите словами, например: Поле Группа не задана или поле группа в изменяемой нагрузке не соответствует ни одной записи в таблице нагрузка.

2020-08-14 08:00 UTC, YuriSilenok requested changes
![image](https://user-images.githubusercontent.com/14871471/90226878-613c1700-de1c-11ea-90b8-285ca4bc61ce.png)
А тестировщик спрашивает, у меня тест падает, потому что я в группу ввел "777", для группы не указано правило, я ввел любое.

2020-08-15 11:31 UTC, Alphavite51 submitted a review, later dismissed

2020-08-16 11:35 UTC, ssas18 commented
@Students-of-the-city-of-Kostroma/17-elite нужен ревью

2020-08-17 06:03 UTC, ifuwmnn submitted a review, later dismissed

2020-08-17 06:33 UTC, YuriSilenok requested changes
> Ввод некоректных данных

У функционала может быть несколько ограничений из-за которого данные могут быть считаться не корректными. И для каждого этого ограничения нужно написать тест. Какие ограничения существуют?

2020-08-17 06:55 UTC, ssas18 commented
> > Ввод некоректных данных
> 
> У функционала может быть несколько ограничений из-за которого данные могут быть считаться не корректными. И для каждого этого ограничения нужно написать тест. Какие ограничения существуют?

Для каждого поля есть примерно по 3-4 ограничения(not null, кол-во символов, первая буква должна быть заглавной, валидные значения(Пример: для дисциплины можно использовать только буквы))

2020-08-17 07:01 UTC, YuriSilenok commented
> > > Ввод некоректных данных
> > 
> > 
> > У функционала может быть несколько ограничений из-за которого данные могут быть считаться не корректными. И для каждого этого ограничения нужно написать тест. Какие ограничения существуют?
> 
> Для каждого поля есть примерно по 3-4 ограничения(not null, кол-во символов, первая буква должна быть заглавной, валидные значения(Пример: для дисциплины можно использовать только буквы))

Не совсем так, те ограничения которые вы перечислили реализованы в модели, а не в контроллере. Это значит что они будут проверены при создании экземпляра класса модели (для простейшего понимания, при создании строки). А вот когда вы этот экземпляр модели (строку) вставляете в контроллер (таблицу), выполняются следующие проверки:
- Значения в столбце уникальны
- Значения в группе столбцов уникально
- Ограничения реляционной связи

Вам нужно посмотреть, существуют ли подобные ограничения для этой сущности.

2020-08-17 07:03 UTC, YuriSilenok commented
Ограничения на уникальность прописываются в конструкторе контроллера, а реляционные связи прописаны в рефдате

2020-08-17 07:27 UTC, ssas18 commented
> > > > Ввод некоректных данных
> > > 
> > > 
> > > У функционала может быть несколько ограничений из-за которого данные могут быть считаться не корректными. И для каждого этого ограничения нужно написать тест. Какие ограничения существуют?
> > 
> > 
> > Для каждого поля есть примерно по 3-4 ограничения(not null, кол-во символов, первая буква должна быть заглавной, валидные значения(Пример: для дисциплины можно использовать только буквы))
> 
> Не совсем так, те ограничения которые вы перечислили реализованы в модели, а не в контроллере. Это значит что они будут проверены при создании экземпляра класса модели (для простейшего понимания, при создании строки). А вот когда вы этот экземпляр модели (строку) вставляете в контроллер (таблицу), выполняются следующие проверки:
> 
> * Значения в столбце уникальны
> * Значения в группе столбцов уникальны
> * Ограничения реляционной связи
> 
> Вам нужно посмотреть, существуют ли подобные ограничения для этой сущности.

Я нашел только реляционные ограничения
![image](https://user-images.githubusercontent.com/47377817/90369346-4c59c080-e074-11ea-86e3-43fed3713caf.png)

2020-08-17 07:39 UTC, YuriSilenok commented
> > > > > Ввод некоректных данных
> > > > 
> > > > 
> > > > У функционала может быть несколько ограничений из-за которого данные могут быть считаться не корректными. И для каждого этого ограничения нужно написать тест. Какие ограничения существуют?
> > > 
> > > 
> > > Для каждого поля есть примерно по 3-4 ограничения(not null, кол-во символов, первая буква должна быть заглавной, валидные значения(Пример: для дисциплины можно использовать только буквы))
> > 
> > 
> > Не совсем так, те ограничения которые вы перечислили реализованы в модели, а не в контроллере. Это значит что они будут проверены при создании экземпляра класса модели (для простейшего понимания, при создании строки). А вот когда вы этот экземпляр модели (строку) вставляете в контроллер (таблицу), выполняются следующие проверки:
> > 
> > * Значения в столбце уникальны
> > * Значения в группе столбцов уникальны
> > * Ограничения реляционной связи
> > 
> > Вам нужно посмотреть, существуют ли подобные ограничения для этой сущности.
> 
> Я нашел только реляционные ограничения
> ![image](https://user-images.githubusercontent.com/47377817/90369346-4c59c080-e074-11ea-86e3-43fed3713caf.png)

Что означает вот [эта](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/027c52244ef4000306c46054e107cd267a3b158a/LibOfTimetableOfClasses/CAcademicLoad.cs#L23) строка?

2020-08-17 07:41 UTC, ssas18 commented
> > > > > > Ввод некоректных данных
> > > > > 
> > > > > 
> > > > > У функционала может быть несколько ограничений из-за которого данные могут быть считаться не корректными. И для каждого этого ограничения нужно написать тест. Какие ограничения существуют?
> > > > 
> > > > 
> > > > Для каждого поля есть примерно по 3-4 ограничения(not null, кол-во символов, первая буква должна быть заглавной, валидные значения(Пример: для дисциплины можно использовать только буквы))
> > > 
> > > 
> > > Не совсем так, те ограничения которые вы перечислили реализованы в модели, а не в контроллере. Это значит что они будут проверены при создании экземпляра класса модели (для простейшего понимания, при создании строки). А вот когда вы этот экземпляр модели (строку) вставляете в контроллер (таблицу), выполняются следующие проверки:
> > > 
> > > * Значения в столбце уникальны
> > > * Значения в группе столбцов уникальны
> > > * Ограничения реляционной связи
> > > 
> > > Вам нужно посмотреть, существуют ли подобные ограничения для этой сущности.
> > 
> > 
> > Я нашел только реляционные ограничения
> > ![image](https://user-images.githubusercontent.com/47377817/90369346-4c59c080-e074-11ea-86e3-43fed3713caf.png)
> 
> Что означает вот [эта](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/027c52244ef4000306c46054e107cd267a3b158a/LibOfTimetableOfClasses/CAcademicLoad.cs#L23) строка?

Честно сказать не заметил ее, она сообщает о том что группа должна быть уникальна

2020-08-17 07:43 UTC, YuriSilenok commented
> > > > > > > Ввод некоректных данных
> > > > > > 
> > > > > > 
> > > > > > У функционала может быть несколько ограничений из-за которого данные могут быть считаться не корректными. И для каждого этого ограничения нужно написать тест. Какие ограничения существуют?
> > > > > 
> > > > > 
> > > > > Для каждого поля есть примерно по 3-4 ограничения(not null, кол-во символов, первая буква должна быть заглавной, валидные значения(Пример: для дисциплины можно использовать только буквы))
> > > > 
> > > > 
> > > > Не совсем так, те ограничения которые вы перечислили реализованы в модели, а не в контроллере. Это значит что они будут проверены при создании экземпляра класса модели (для простейшего понимания, при создании строки). А вот когда вы этот экземпляр модели (строку) вставляете в контроллер (таблицу), выполняются следующие проверки:
> > > > 
> > > > * Значения в столбце уникальны
> > > > * Значения в группе столбцов уникальны
> > > > * Ограничения реляционной связи
> > > > 
> > > > Вам нужно посмотреть, существуют ли подобные ограничения для этой сущности.
> > > 
> > > 
> > > Я нашел только реляционные ограничения
> > > ![image](https://user-images.githubusercontent.com/47377817/90369346-4c59c080-e074-11ea-86e3-43fed3713caf.png)
> > 
> > 
> > Что означает вот [эта](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/027c52244ef4000306c46054e107cd267a3b158a/LibOfTimetableOfClasses/CAcademicLoad.cs#L23) строка?
> 
> Честно сказать не заметил ее, она сообщает о том что группа должна быть уникальна

Исходя из этих ограничений, вы можете составить тесты на каждое из этих ограничений. При нарушении этих ограничений, будет генерироваться исключение, которое соответствует региону R5

2020-08-17 07:48 UTC, YuriSilenok commented
> > > > > > > Ввод некоректных данных
> > > > > > 
> > > > > > 
> > > > > > У функционала может быть несколько ограничений из-за которого данные могут быть считаться не корректными. И для каждого этого ограничения нужно написать тест. Какие ограничения существуют?
> > > > > 
> > > > > 
> > > > > Для каждого поля есть примерно по 3-4 ограничения(not null, кол-во символов, первая буква должна быть заглавной, валидные значения(Пример: для дисциплины можно использовать только буквы))
> > > > 
> > > > 
> > > > Не совсем так, те ограничения которые вы перечислили реализованы в модели, а не в контроллере. Это значит что они будут проверены при создании экземпляра класса модели (для простейшего понимания, при создании строки). А вот когда вы этот экземпляр модели (строку) вставляете в контроллер (таблицу), выполняются следующие проверки:
> > > > 
> > > > * Значения в столбце уникальны
> > > > * Значения в группе столбцов уникальны
> > > > * Ограничения реляционной связи
> > > > 
> > > > Вам нужно посмотреть, существуют ли подобные ограничения для этой сущности.
> > > 
> > > 
> > > Я нашел только реляционные ограничения
> > > ![image](https://user-images.githubusercontent.com/47377817/90369346-4c59c080-e074-11ea-86e3-43fed3713caf.png)
> > 
> > 
> > Что означает вот [эта](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/027c52244ef4000306c46054e107cd267a3b158a/LibOfTimetableOfClasses/CAcademicLoad.cs#L23) строка?
> 
> Честно сказать не заметил ее, она сообщает о том что группа должна быть уникальна

![image](https://user-images.githubusercontent.com/14871471/90371053-0d793a00-e077-11ea-9f70-1d30793e1838.png)
Обратите внимание, что ваша ветка устарела по реляционным связям, вам нужно получить изменения из ветки dev

2020-08-17 07:52 UTC, ssas18 commented
> > > > > > > > Ввод некоректных данных
> > > > > > > 
> > > > > > > 
> > > > > > > У функционала может быть несколько ограничений из-за которого данные могут быть считаться не корректными. И для каждого этого ограничения нужно написать тест. Какие ограничения существуют?
> > > > > > 
> > > > > > 
> > > > > > Для каждого поля есть примерно по 3-4 ограничения(not null, кол-во символов, первая буква должна быть заглавной, валидные значения(Пример: для дисциплины можно использовать только буквы))
> > > > > 
> > > > > 
> > > > > Не совсем так, те ограничения которые вы перечислили реализованы в модели, а не в контроллере. Это значит что они будут проверены при создании экземпляра класса модели (для простейшего понимания, при создании строки). А вот когда вы этот экземпляр модели (строку) вставляете в контроллер (таблицу), выполняются следующие проверки:
> > > > > 
> > > > > * Значения в столбце уникальны
> > > > > * Значения в группе столбцов уникальны
> > > > > * Ограничения реляционной связи
> > > > > 
> > > > > Вам нужно посмотреть, существуют ли подобные ограничения для этой сущности.
> > > > 
> > > > 
> > > > Я нашел только реляционные ограничения
> > > > ![image](https://user-images.githubusercontent.com/47377817/90369346-4c59c080-e074-11ea-86e3-43fed3713caf.png)
> > > 
> > > 
> > > Что означает вот [эта](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/027c52244ef4000306c46054e107cd267a3b158a/LibOfTimetableOfClasses/CAcademicLoad.cs#L23) строка?
> > 
> > 
> > Честно сказать не заметил ее, она сообщает о том что группа должна быть уникальна
> 
> ![image](https://user-images.githubusercontent.com/14871471/90371053-0d793a00-e077-11ea-9f70-1d30793e1838.png)
> Обратите внимание, что ваша ветка устарела по реляционным связям, вам нужно получить изменения из ветки dev

Это делается так?
просто подзабыл это, а косячить не хочется
![image](https://user-images.githubusercontent.com/47377817/90371476-b4f66c80-e077-11ea-9daf-9aa36ba74b9d.png)

2020-08-17 07:55 UTC, YuriSilenok commented
- Переключаетесь на дев, нажимаете на кнопку Fetch origin
- Переключаетесь на task-1280
- Далее по картинке, думаю не запутаетесь.
![image](https://user-images.githubusercontent.com/14871471/90371751-1585a980-e078-11ea-98cf-a77743d87384.png)

2020-08-17 07:57 UTC, ssas18 commented
> * Переключаетесь на дев, нажимаете на кнопку Fetch origin
> * Переключаетесь на task-1280
> * Далее по картинке, думаю не запутаетесь.
>   ![image](https://user-images.githubusercontent.com/14871471/90371751-1585a980-e078-11ea-98cf-a77743d87384.png)

Спасибо большое!

2020-08-17 08:09 UTC, ssas18 commented
> > > > > > > > Ввод некоректных данных
> > > > > > > 
> > > > > > > 
> > > > > > > У функционала может быть несколько ограничений из-за которого данные могут быть считаться не корректными. И для каждого этого ограничения нужно написать тест. Какие ограничения существуют?
> > > > > > 
> > > > > > 
> > > > > > Для каждого поля есть примерно по 3-4 ограничения(not null, кол-во символов, первая буква должна быть заглавной, валидные значения(Пример: для дисциплины можно использовать только буквы))
> > > > > 
> > > > > 
> > > > > Не совсем так, те ограничения которые вы перечислили реализованы в модели, а не в контроллере. Это значит что они будут проверены при создании экземпляра класса модели (для простейшего понимания, при создании строки). А вот когда вы этот экземпляр модели (строку) вставляете в контроллер (таблицу), выполняются следующие проверки:
> > > > > 
> > > > > * Значения в столбце уникальны
> > > > > * Значения в группе столбцов уникальны
> > > > > * Ограничения реляционной связи
> > > > > 
> > > > > Вам нужно посмотреть, существуют ли подобные ограничения для этой сущности.
> > > > 
> > > > 
> > > > Я нашел только реляционные ограничения
> > > > ![image](https://user-images.githubusercontent.com/47377817/90369346-4c59c080-e074-11ea-86e3-43fed3713caf.png)
> > > 
> > > 
> > > Что означает вот [эта](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/027c52244ef4000306c46054e107cd267a3b158a/LibOfTimetableOfClasses/CAcademicLoad.cs#L23) строка?
> > 
> > 
> > Честно сказать не заметил ее, она сообщает о том что группа должна быть уникальна
> 
> ![image](https://user-images.githubusercontent.com/14871471/90371053-0d793a00-e077-11ea-9f70-1d30793e1838.png)
> Обратите внимание, что ваша ветка устарела по реляционным связям, вам нужно получить изменения из ветки dev

Если есть реляционные связи, к примеру, для поля дисциплина, то его соответственно нельзя изменять?
или я что-то не понимаю?

2020-08-17 08:16 UTC, YuriSilenok commented
> > > > > > > > > Ввод некоректных данных
> > > > > > > > 
> > > > > > > > 
> > > > > > > > У функционала может быть несколько ограничений из-за которого данные могут быть считаться не корректными. И для каждого этого ограничения нужно написать тест. Какие ограничения существуют?
> > > > > > > 
> > > > > > > 
> > > > > > > Для каждого поля есть примерно по 3-4 ограничения(not null, кол-во символов, первая буква должна быть заглавной, валидные значения(Пример: для дисциплины можно использовать только буквы))
> > > > > > 
> > > > > > 
> > > > > > Не совсем так, те ограничения которые вы перечислили реализованы в модели, а не в контроллере. Это значит что они будут проверены при создании экземпляра класса модели (для простейшего понимания, при создании строки). А вот когда вы этот экземпляр модели (строку) вставляете в контроллер (таблицу), выполняются следующие проверки:
> > > > > > 
> > > > > > * Значения в столбце уникальны
> > > > > > * Значения в группе столбцов уникальны
> > > > > > * Ограничения реляционной связи
> > > > > > 
> > > > > > Вам нужно посмотреть, существуют ли подобные ограничения для этой сущности.
> > > > > 
> > > > > 
> > > > > Я нашел только реляционные ограничения
> > > > > ![image](https://user-images.githubusercontent.com/47377817/90369346-4c59c080-e074-11ea-86e3-43fed3713caf.png)
> > > > 
> > > > 
> > > > Что означает вот [эта](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/027c52244ef4000306c46054e107cd267a3b158a/LibOfTimetableOfClasses/CAcademicLoad.cs#L23) строка?
> > > 
> > > 
> > > Честно сказать не заметил ее, она сообщает о том что группа должна быть уникальна
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/14871471/90371053-0d793a00-e077-11ea-9f70-1d30793e1838.png)
> > Обратите внимание, что ваша ветка устарела по реляционным связям, вам нужно получить изменения из ветки dev
> 
> Если есть реляционные связи, к примеру, для поля дисциплина, то его соответственно нельзя изменять?
> или я что-то не понимаю?

Что мы имеем:
- метод изменяющий данные
- вторичные ключи у таблицы

Для полей со вторичными ключами вы можете указать только те данные, которые имеются в первичном ключе связанной реляционной связью таблицы.
Думаю вам нужно чуть больше прочитать о том, как работает реляционная связь.
Что это значит на практике: Допустим в таблице академической нагрузки вы имеете запись в которой дисциплина указана Математика. Это значит что в таблице Дисциплины, есть такая запись в которой написано Математика. Допустим вы решили заменить в нагрузке математику на физику. Если в таблице с дисциплинами нет Физики, то вы получите исключение. Так это работает. Можно указывать только то, что есть в другой таблице.

2020-08-17 08:18 UTC, ssas18 commented
> > > > > > > > > > Ввод некоректных данных
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > У функционала может быть несколько ограничений из-за которого данные могут быть считаться не корректными. И для каждого этого ограничения нужно написать тест. Какие ограничения существуют?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Для каждого поля есть примерно по 3-4 ограничения(not null, кол-во символов, первая буква должна быть заглавной, валидные значения(Пример: для дисциплины можно использовать только буквы))
> > > > > > > 
> > > > > > > 
> > > > > > > Не совсем так, те ограничения которые вы перечислили реализованы в модели, а не в контроллере. Это значит что они будут проверены при создании экземпляра класса модели (для простейшего понимания, при создании строки). А вот когда вы этот экземпляр модели (строку) вставляете в контроллер (таблицу), выполняются следующие проверки:
> > > > > > > 
> > > > > > > * Значения в столбце уникальны
> > > > > > > * Значения в группе столбцов уникальны
> > > > > > > * Ограничения реляционной связи
> > > > > > > 
> > > > > > > Вам нужно посмотреть, существуют ли подобные ограничения для этой сущности.
> > > > > > 
> > > > > > 
> > > > > > Я нашел только реляционные ограничения
> > > > > > ![image](https://user-images.githubusercontent.com/47377817/90369346-4c59c080-e074-11ea-86e3-43fed3713caf.png)
> > > > > 
> > > > > 
> > > > > Что означает вот [эта](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/027c52244ef4000306c46054e107cd267a3b158a/LibOfTimetableOfClasses/CAcademicLoad.cs#L23) строка?
> > > > 
> > > > 
> > > > Честно сказать не заметил ее, она сообщает о том что группа должна быть уникальна
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/14871471/90371053-0d793a00-e077-11ea-9f70-1d30793e1838.png)
> > > Обратите внимание, что ваша ветка устарела по реляционным связям, вам нужно получить изменения из ветки dev
> > 
> > 
> > Если есть реляционные связи, к примеру, для поля дисциплина, то его соответственно нельзя изменять?
> > или я что-то не понимаю?
> 
> Что мы имеем:
> 
> * метод изменяющий данные
> * вторичные ключи у таблицы
> 
> Для полей со вторичными ключами вы можете указать только те данные, которые имеются в первичном ключе связанной реляционной связью таблицы.
> Думаю вам нужно чуть больше прочитать о том, как работает реляционная связь.
> Что это значит на практике: Допустим в таблице академической нагрузки вы имеете запись в которой дисциплина указана Математика. Это значит что в таблице Дисциплины, есть такая запись в которой написано Математика. Допустим вы решили заменить в нагрузке математику на физику. Если в таблице с дисциплинами нет Физики, то вы получите исключение. Так это работает. Можно указывать только то, что есть в другой таблице.

Понятно, еще раз большое спасибо

2020-08-17 09:22 UTC, YuriSilenok reviewed
Что означает `true` в тестах 2, 4, 5, 6?

2020-08-17 09:39 UTC, ssas18 commented
> Что означает `true` в тестах 2, 4, 5, 6?

ошибки копипаста, сейчас исправлю

2020-08-17 09:53 UTC, YuriSilenok reviewed
Давайте попробуем автоматизировать их

2020-08-18 12:25 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CAcademicLoad.cs
> +        /// Изменить сведения в пустой таблице
не забыть проверить таблицу что она пустая

2020-08-18 13:44 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CAcademicLoad.cs
> +            Assert.IsTrue(refData.CAcademicLoad.Rows.Count == 0);
Добавьте сразу комментарий, я внес это требование в требования к тестам.

2020-08-19 06:46 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CAcademicLoad.cs
> +            Assert.AreEqual(expected, actual, "Ожидаемое и действительное не совпало");
Вы же не "Капитан очевидность", зачем такие комментарии, и так понятно, что если сбой в тесте, то не сошлись ожидаемое и фактическое. Это главная проверка теста, а раз так, то составьте сообщение исходя из названия теста. Данные в пустой таблице изменены.

2020-08-19 15:46 UTC, YuriSilenok requested changes
есть на что взглянуть

2020-08-19 15:46 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CAcademicLoad.cs
> +            Assert.AreEqual(true, actualPreMa, "Ожидаемое и действительное не совпало");
Формулировку конкретнее

2020-08-19 15:46 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CAcademicLoad.cs
> +            PreMa1.TotalHours = "120";
кажется уже было

2020-08-19 15:46 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CAcademicLoad.cs
> +            PreMa.TotalHours = "120";
здесь

2020-08-20 14:01 UTC, YuriSilenok requested changes

2020-08-20 14:01 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CAcademicLoad.cs
> +            PreMa.TotalHours = "120";
все еще тут

2020-08-20 14:23 UTC, ssas18 commented on UnitTestOfTimetableOfClasses/UT_Update_CAcademicLoad.cs
> +            PreMa.TotalHours = "120";
> все еще тут

Странно, надо обзавестись привычкой перепроверять коммиты

2020-08-21 15:01 UTC, YuriSilenok requested changes

2020-08-21 15:01 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CAcademicLoad.cs
> +            Assert.AreEqual(expected, actual, " Удалось изменить несуществующую группу в заполненной таблице");
Проверка предварительного условия?

2020-08-21 15:21 UTC, ssas18 commented on UnitTestOfTimetableOfClasses/UT_Update_CAcademicLoad.cs
> +            Assert.AreEqual(expected, actual, " Удалось изменить несуществующую группу в заполненной таблице");
К сожалению не понимаю о чем Вы

2020-08-21 15:25 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CAcademicLoad.cs
> +            Assert.AreEqual(expected, actual, " Удалось изменить несуществующую группу в заполненной таблице");
Какое состояние таблицы перед началом теста должно быть, что бы алгоритм пошел по маршруту R2?

2020-08-21 15:27 UTC, ssas18 commented on UnitTestOfTimetableOfClasses/UT_Update_CAcademicLoad.cs
> +            Assert.AreEqual(expected, actual, " Удалось изменить несуществующую группу в заполненной таблице");
Проверить на заполненность таблицу?

2020-08-21 15:31 UTC, ssas18 commented on UnitTestOfTimetableOfClasses/UT_Update_CAcademicLoad.cs
> +            Assert.AreEqual(expected, actual, " Удалось изменить несуществующую группу в заполненной таблице");
Тогда это нужно сделать во всех трёх тестах

2020-08-21 15:34 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CAcademicLoad.cs
> +            Assert.AreEqual(expected, actual, " Удалось изменить несуществующую группу в заполненной таблице");
Да, и во всех остальных тест-комплектах.

2020-08-23 12:42 UTC, ssas18 commented on UnitTestOfTimetableOfClasses/UT_Update_CAcademicLoad.cs
> +            Assert.AreEqual(expected, actual, " Удалось изменить несуществующую группу в заполненной таблице");
да, хорошо

2020-08-25 10:14 UTC, YuriSilenok requested changes

2020-08-25 10:14 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CAcademicLoad.cs
> +            Assert.IsTrue(refData.CAcademicLoad.Rows.Count != 0, "Таблица нагрузки пуста!");
Почему проверка предварительного условия идет после основного сценария?

2020-08-25 10:14 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CAcademicLoad.cs
> +        [ExpectedException(typeof(System.Exception))]
Зачем нужен атрибут этого метода?

2020-08-25 10:34 UTC, ssas18 commented on UnitTestOfTimetableOfClasses/UT_Update_CAcademicLoad.cs
> +            Assert.IsTrue(refData.CAcademicLoad.Rows.Count != 0, "Таблица нагрузки пуста!");
Согласен, глупо, исправлю

2020-08-25 10:35 UTC, ssas18 commented on UnitTestOfTimetableOfClasses/UT_Update_CAcademicLoad.cs
> +        [ExpectedException(typeof(System.Exception))]
Вы про данную строку? [ExpectedException(typeof(System.Exception))]

2020-08-25 11:05 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CAcademicLoad.cs
> +        [ExpectedException(typeof(System.Exception))]
Да

2020-08-25 11:08 UTC, ssas18 commented on UnitTestOfTimetableOfClasses/UT_Update_CAcademicLoad.cs
> +        [ExpectedException(typeof(System.Exception))]
Тут сработал постулат “работает, не трожь”  я так понимаю он что-то делает с исключениями, его нужно удалить?

2020-08-25 11:11 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CAcademicLoad.cs
> +        [ExpectedException(typeof(System.Exception))]
Только потому что Вы постоянно работаете, рассказываю. Иногда, для негативных тестов, ожидаемым результатом является исключение. Вот для того, что бы поймать иключение как ожидаемый результат, ставится этот атрибут для метода (теста)

2020-08-25 11:13 UTC, ssas18 commented on UnitTestOfTimetableOfClasses/UT_Update_CAcademicLoad.cs
> +        [ExpectedException(typeof(System.Exception))]
Интересно, даже не знал о такой функции, у меня в ожидаемом результате исключений не должно быть, соответственно, мне данная строка не нужна?

2020-08-25 11:31 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CAcademicLoad.cs
> +        [ExpectedException(typeof(System.Exception))]
Думаю не нужна.

2020-08-26 06:55 UTC, YuriSilenok requested changes
Мы вроде нагрузку тестируем, а не группу?

2020-08-26 06:55 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CAcademicLoad.cs
> +        /// Изменить несуществующую группу в заполненной таблице
Не совсем понимаю причем тут группа при тестировании академической нагрузки?

2020-08-26 07:03 UTC, ssas18 commented on UnitTestOfTimetableOfClasses/UT_Update_CAcademicLoad.cs
> +        /// Изменить несуществующую группу в заполненной таблице
Да, все верно, будет исправлено

2020-08-28 11:01 UTC, ssas18 commented
Данные коммиты пока не нужно проверять, у меня пока по ним еще ведутся работы

2020-08-28 12:55 UTC, ssas18 commented
@YuriSilenok, прошу Вашей помощи, не могу заполнить данные в родительской таблице
![image](https://user-images.githubusercontent.com/47377817/91563025-dba18680-e946-11ea-8e6b-4b4eafe7e461.png)

2020-08-28 12:57 UTC, YuriSilenok commented
> @YuriSilenok, прошу Вашей помощи, не могу заполнить данные в родительской таблице
> ![image](https://user-images.githubusercontent.com/47377817/91563025-dba18680-e946-11ea-8e6b-4b4eafe7e461.png)

В таблицу группы, нужно добавить группу с шифром 17-ИСбо-2а. У вас ограничение реляционной связи сработало.

2020-08-28 13:00 UTC, ssas18 commented
> > @YuriSilenok, прошу Вашей помощи, не могу заполнить данные в родительской таблице
> > ![image](https://user-images.githubusercontent.com/47377817/91563025-dba18680-e946-11ea-8e6b-4b4eafe7e461.png)
> 
> В таблицу группы, нужно добавить группу с шифром 17-ИСбо-2а. У вас ограничение реляционной связи сработало.

Да,я это понимаю, я так делал, но оно меня заводило еще дальше в MTraningprofile, а он в свою очередь еще дальше, такое может быть, или я делаю что-то не то?

2020-08-28 13:05 UTC, YuriSilenok commented
> Да,я это понимаю, я так делал, но оно меня заводило еще дальше в MTraningprofile, а он в свою очередь еще дальше, такое может быть, или я делаю что-то не то?

ах да, вы же получили обновление из дев.
А это значит что все таблицы теперь будут пусты.
У вас два пути:
- создать нужные таблицы самостоятельно.
- создать конструктор для тест-комплекта (класс UT_*) и в нем вызвать метод инициализации данных у рефдаты.

2020-08-28 17:23 UTC, ifuwmnn approved these changes, later dismissed

2020-08-29 10:42 UTC, NordScandinavian approved these changes, later dismissed

2020-08-29 18:33 UTC, YuriSilenok commented
Проверять буду в понедельник

2020-08-31 09:22 UTC, YuriSilenok requested changes
Меня радует Ваше усердие, но печалит Ваша невнимательность.

2020-08-31 09:22 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CAcademicLoad.cs
> +            Assert.AreEqual(expected, actual, "Произошел ввод группы, дублирующей другую группу");
Вижу что тест запасился.
Но, я не увидел что вы добавили запись с такой же группой.
Скорее всего есть проходит потому запись была не добавлена из-за другого ограничения.
По этому подумайте о следующем. Как Вы проверяете, что созданы условия для теста, при котором сработает только проверяемое ограничение и не сработает не проверяемые ограничения.
Я вот вижу что тест пошел по маршруту R3. 
Проверяйте по какому маршруту ходят ваши тесты.
![image](https://user-images.githubusercontent.com/14871471/91704587-79ce6000-eb84-11ea-9d92-e8b7c1a6612e.png)
![image](https://user-images.githubusercontent.com/14871471/91704656-91a5e400-eb84-11ea-9489-86e60c5ebdda.png)

2020-08-31 09:29 UTC, YuriSilenok commented
@NordScandinavian 
@ifuwmnn 
Изучите обозначенную мной проблему.

2020-08-31 09:34 UTC, ssas18 commented on UnitTestOfTimetableOfClasses/UT_Update_CAcademicLoad.cs
> +            Assert.AreEqual(expected, actual, "Произошел ввод группы, дублирующей другую группу");
Да, это глупо с моей стороны было не проверять это, я так понимаю в других запросах у меня может быть такая же проблема

2020-09-01 18:46 UTC, ssas18 commented
@Students-of-the-city-of-Kostroma/17-elite нужен ревью, пожалуйста

2020-09-04 09:04 UTC, YuriSilenok requested changes
Проверка маршрутов
- 1 - пройден
- 2 - пройден
- 3 - пройден
- 4 - пройден
- 5 - не пройден - выполнено маршрут 3
- 6 - не пройден - выполнено маршрут 3

2020-09-04 09:25 UTC, ssas18 commented
> Проверка маршрутов
> 
> * 1 - пройден
> * 2 - пройден
> * 3 - пройден
> * 4 - пройден
> * 5 - не пройден - выполнено, маршрут 3
> * 6 - не пройден - выполнено, маршрут 3

Правильно понимаю что 5 и 6 тест не пройден по назначенному маршруту?
и тогда что с тестом 7?

2020-09-04 09:57 UTC, YuriSilenok commented
> > Проверка маршрутов
> > 
> > * 1 - пройден
> > * 2 - пройден
> > * 3 - пройден
> > * 4 - пройден
> > * 5 - не пройден - выполнено, маршрут 3
> > * 6 - не пройден - выполнено, маршрут 3
> 
> Правильно понимаю что 5 и 6 тест не пройден по назначенному маршруту?
> тогда это распространяется и на тест 7

скорее всего, я не посмотрел 7 маршрут, проверка этого критерия занимает много времени

2020-09-04 13:55 UTC, ssas18 commented
проверка работы подсчета активности, комментарий будет удален

2020-09-05 14:14 UTC, ifuwmnn approved these changes, later dismissed

2020-09-06 05:02 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1341']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-06 08:02 UTC, MyachevM submitted a review, later dismissed

2020-09-07 13:41 UTC, Alphavite51 commented on UnitTestOfTimetableOfClasses/UT_Update_CAcademicLoad.cs
> +            MAcademicLoad PreMa = new MAcademicLoad("17-ИСбо-2а", "100", "История", "Иванова Ивана Ивановича", "Лекцияа", "20");
119, 136, 153 будьте внимательней, у вас написано "ЛекциЯА"

2020-09-07 13:43 UTC, Alphavite51 requested changes
124, 141 "некорректных" с 2 "н" и слитно.

2020-09-07 14:29 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1341']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-07 17:15 UTC, ssas18 commented on UnitTestOfTimetableOfClasses/UT_Update_CAcademicLoad.cs
> +            MAcademicLoad PreMa = new MAcademicLoad("17-ИСбо-2а", "100", "История", "Иванова Ивана Ивановича", "Лекцияа", "20");
в 119 это идея теста 
а в 136  и 153 это, как мне кажется роли не делает

2020-09-07 17:16 UTC, ssas18 commented
> 124, 141 "некорректных" с 2 "н" и слитно. 

наверное  2 "р"

2020-09-08 12:03 UTC, ifuwmnn submitted a review, later dismissed

2020-09-08 12:05 UTC, Alphavite51 requested changes
У вас есть непроверенные запросы ['#86', '#87']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-08 12:14 UTC, ssas18 commented
> У вас есть непроверенные запросы ['#86', '#87']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

Это относится к другому репозиторию и никак Вашу деятельность не тормозит, и зачем ты выполняешь задачи скрипта?

2020-09-08 12:16 UTC, Alphavite51 commented
> > У вас есть непроверенные запросы ['#86', '#87']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса
> 
> Это относится к другому репозиторию и никак Вашу деятельность не тормозит, и зачем ты выполняешь задачи скрипта?

чтобы небыло активности у того профиля который со скриптом

2020-09-08 12:16 UTC, Alphavite51 approved these changes, later dismissed

2020-09-08 12:18 UTC, ssas18 commented
> > > У вас есть непроверенные запросы ['#86', '#87']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса
> > 
> > 
> > Это относится к другому репозиторию и никак Вашу деятельность не тормозит, и зачем ты выполняешь задачи скрипта?
> 
> чтобы небыло активности у того профиля который со скриптом

Тогда это уже перевыполнение обязанностей, тк эти запросы не относятся к данному репозиторию

2020-09-08 12:20 UTC, Alphavite51 commented
> > > > У вас есть непроверенные запросы ['#86', '#87']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса
> > > 
> > > 
> > > Это относится к другому репозиторию и никак Вашу деятельность не тормозит, и зачем ты выполняешь задачи скрипта?
> > 
> > 
> > чтобы небыло активности у того профиля который со скриптом
> 
> Тогда это уже перевыполнение обязанностей, тк эти запросы не относятся к данному репозиторию

обязанностей чего?

2020-09-08 12:22 UTC, ssas18 commented
> > > > > У вас есть непроверенные запросы ['#86', '#87']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса
> > > > 
> > > > 
> > > > Это относится к другому репозиторию и никак Вашу деятельность не тормозит, и зачем ты выполняешь задачи скрипта?
> > > 
> > > 
> > > чтобы небыло активности у того профиля который со скриптом
> > 
> > 
> > Тогда это уже перевыполнение обязанностей, тк эти запросы не относятся к данному репозиторию
> 
> обязанностей чего?

Наших с вами обязанностей как членов данного сообщества, Вы их превысили, сославшись здесь на активность в другом репозитории

2020-09-08 12:25 UTC, Alphavite51 commented
> > > > > > У вас есть непроверенные запросы ['#86', '#87']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса
> > > > > 
> > > > > 
> > > > > Это относится к другому репозиторию и никак Вашу деятельность не тормозит, и зачем ты выполняешь задачи скрипта?
> > > > 
> > > > 
> > > > чтобы небыло активности у того профиля который со скриптом
> > > 
> > > 
> > > Тогда это уже перевыполнение обязанностей, тк эти запросы не относятся к данному репозиторию
> > 
> > 
> > обязанностей чего?
> 
> Наших с вами обязанностей как членов данного сообщества, Вы их превысили, сославшись здесь на активность в другом репозитории

извини, впредь буду внимательней, работу твою посмотрел, все верно

2020-09-08 17:57 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы []. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-08 17:57 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1335']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-08 18:37 UTC, MyachevM approved these changes, later dismissed

2020-09-09 14:15 UTC, ssas18 commented
@YuriSilenok , Юрий Викторович, мне ждать сегодня проверки запросов? И если нет, то примерно когда они будут?

2020-09-09 17:23 UTC, YuriSilenok requested changes
При подготовке тестовых данных, нет проверки того, что они были добавлены в таблицы.

2020-09-09 17:24 UTC, YuriSilenok commented
> @YuriSilenok , Юрий Викторович, мне ждать сегодня проверки запросов? И если нет, то примерно когда они будут?

Я пока с телефона, могу проводить только статический анализ кода.

2020-09-09 18:26 UTC, YuriSilenok requested changes
Остальное завтра посмотрю, чувствую есть недостижим тесты, умеете проверять маршруты?

2020-09-09 18:26 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CAcademicLoad.cs
> +            Assert.AreEqual(expected, actual, " Удалось изменить несуществующую группу в заполненной таблице");
Мы тестируем нагрузку, а не группу

2020-09-09 18:29 UTC, ssas18 commented
> Остальное завтра посмотрю, чувствую есть недостижим тесты, умеете проверять маршруты?

сейчас попробую перепроверить

2020-09-09 18:29 UTC, ssas18 commented on UnitTestOfTimetableOfClasses/UT_Update_CAcademicLoad.cs
> +            Assert.AreEqual(expected, actual, " Удалось изменить несуществующую группу в заполненной таблице");
сейчас будет исправлено

2020-09-10 07:26 UTC, YuriSilenok requested changes
Обновите код, граф и маршруты, очень не удобно проверять, когда нет одного региона.

2020-09-10 07:29 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CAcademicLoad.cs
> +        /// Атрибут "Группа" дублирует уже существующий атрибут "Группа"
Этот тест недостижим, так как нельзя поменять атрибут Группа, так как функционал смены первичного ключа не заявлен.

2020-09-10 07:39 UTC, YuriSilenok requested changes
![image](https://user-images.githubusercontent.com/14871471/92696002-f5cd6280-f351-11ea-8a71-4439fa4f1584.png)

2020-09-10 08:36 UTC, ifuwmnn reviewed
Ну кроме того, что написал Юрий Викорович, мне добавить нечего.

2020-09-10 12:31 UTC, ssas18 commented on UnitTestOfTimetableOfClasses/UT_Update_CAcademicLoad.cs
> +        /// Атрибут "Группа" дублирует уже существующий атрибут "Группа"
по всем замечаниям:
мне нужео удалить R1 тк он недостижим ,соответственно переделать отчет
удалить тест 1245_4
и разобраться с 1245_6?

2020-09-10 12:38 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CAcademicLoad.cs
> +        /// Атрибут "Группа" дублирует уже существующий атрибут "Группа"
да

2020-09-10 14:24 UTC, YuriSilenok approved these changes

2020-09-10 14:25 UTC, merged