Исправил сбои в автотестах  UT_Update_CGroup
Students-of-the-city-of-Kostroma/Student-timetable pull request #1295
Opened 2020-07-06 08:37 UTC by ssas18

#1066

2020-07-06 13:27 UTC, ssas18 commented
Тут на правильность так же не претендую, просто для того что бы Вы видели мою активность

2020-07-06 13:48 UTC, YuriSilenok requested changes
![image](https://user-images.githubusercontent.com/14871471/86600066-330b2200-bfa8-11ea-81c8-bfc177828cd1.png)
Код не отображается
![image](https://user-images.githubusercontent.com/14871471/86600193-68177480-bfa8-11ea-9012-0443184dcc66.png)
лишние строки в таблице
![image](https://user-images.githubusercontent.com/14871471/86600237-749bcd00-bfa8-11ea-8bcf-c62cba263d0f.png)

2020-07-07 14:37 UTC, ZhizhikinIvan submitted a review, later dismissed

2020-07-08 11:00 UTC, ifuwmnn submitted a review, later dismissed

2020-07-08 13:41 UTC, YuriSilenok requested changes
Ваш отчет расположен в неправильной папке.

2020-07-08 15:22 UTC, ssas18 commented
> Прошу прощения, возможно не там оставляю комментарий. Но путь R3, вроде бы, должен быть внутри блока, а не снаружи. Спасибо.

Все там, спасибо за указанный недочет

2020-07-08 18:13 UTC, JennyShel18 submitted a review, later dismissed

2020-07-08 19:16 UTC, ZhizhikinIvan submitted a review, later dismissed

2020-07-09 17:26 UTC, YuriSilenok requested changes
![image](https://user-images.githubusercontent.com/14871471/87071033-55a86f80-c222-11ea-8b45-8dfefd4c35cf.png)
Не может быть двух регионов с одинаковым именем

2020-07-10 18:05 UTC, ZhizhikinIvan submitted a review, later dismissed

2020-07-10 19:15 UTC, YuriSilenok commented
Где же второй герой, который сделает предварительную проверку работы

2020-07-11 07:29 UTC, ssas18 commented
Проверьте кто-нибууудь, пожалуйста

2020-07-12 08:03 UTC, ssas18 commented
@YuriSilenok , по данной задаче нет никакой активности 2 суток, никто ее не проверяет, что мне делать?

2020-07-12 08:06 UTC, NesgovorovVS submitted a review, later dismissed

2020-07-12 11:05 UTC, YuriSilenok commented
Пока проверить не могу, я о запросе не забыл, пометки себе.

2020-07-12 11:06 UTC, ssas18 commented
> Пока проверить не могу, я о запросе не забыл, пометки себе.

Хорошо

2020-07-14 18:35 UTC, YuriSilenok requested changes
- относительно Test title отписал в чат
- относительно теста 250_1 я не увидел объяснения почему этот тест является недостижимым?

2020-07-14 18:40 UTC, ssas18 commented
> - относительно Test title отписал в чат
> 
> - относительно теста 250_1 я не увидел объяснения почему этот тест является недостижимым?

По первому пункту понял, исправлю
А по второму, я не могу понять как добиться величины rows.count == 0,    прошу Вашей помощи

2020-07-18 08:03 UTC, ssas18 commented
@ifuwmnn , @ZhizhikinIvan , @Heriuple , @MyachevM , @NesgovorovVS , @NordScandinavian нужен ревью. пожалуйста

2020-07-19 09:38 UTC, ssas18 commented
@ifuwmnn , @ZhizhikinIvan , @Heriuple , @MyachevM , @NesgovorovVS , @NordScandinavian нужен ревью. пожалуйста

2020-07-19 18:33 UTC, YuriSilenok requested changes

2020-07-19 18:33 UTC, YuriSilenok commented on Docs/UT_Update_CGroup/REPORT.md
> +|R2|250_2|Изменить сведения в не пустой таблице |Rows.count = 5, но mGroup.Group != (string)this.Rows[i]["Group"] Остальные данные - валидны |false|
> Изменить сведения в не пустой таблице

Не ясна в чем суть идеи. Под это можно выполнить все стеты кроме первого

2020-07-19 18:33 UTC, YuriSilenok commented on Docs/UT_Update_CGroup/REPORT.md
> +|R4|250_7|Ввод корректных данных при условии что она будет дублировать другую записать (невозможно изменение)|Semester = 1 Specialty = "ММЭТ" Shift = 1 Students = 1 MaxNumberOfClass = 0 MinNumberOfCl
> Ввод корректных данных при условии что она будет дублировать другую записать (невозможно изменение)

На мой взгляд этот тест является суммой многих предыдущих тестов и сбой в этим тесте не укажет на ограничение атрибута из-за которого произошел этот сбой.

2020-07-20 06:56 UTC, ssas18 commented on Docs/UT_Update_CGroup/REPORT.md
> +|R4|250_7|Ввод корректных данных при условии что она будет дублировать другую записать (невозможно изменение)|Semester = 1 Specialty = "ММЭТ" Shift = 1 Students = 1 MaxNumberOfClass = 0 MinNumberOfCl
Этот тест надо разбить на множество тестов?

2020-07-20 07:05 UTC, ssas18 commented on Docs/UT_Update_CGroup/REPORT.md
> +|R2|250_2|Изменить сведения в не пустой таблице |Rows.count = 5, но mGroup.Group != (string)this.Rows[i]["Group"] Остальные данные - валидны |false|
Изменить сведения в не пустой таблице при условии что рефдата заполнена?
примерно так?

2020-07-20 12:03 UTC, YuriSilenok commented on Docs/UT_Update_CGroup/REPORT.md
> +|R2|250_2|Изменить сведения в не пустой таблице |Rows.count = 5, но mGroup.Group != (string)this.Rows[i]["Group"] Остальные данные - валидны |false|
Я имею ввиду что описание следующего теста `Ввод корректных данных, при условии, что Смена дублирует Смена существующего экземпляра` принадлежит условию `Изменить сведения в не пустой таблице`. Идея должна нам показать, какую особенность алгоритма мы хотим проверить. Что такого уникального в этом тесте, чего нет в других тестах.

2020-07-20 12:04 UTC, YuriSilenok commented on Docs/UT_Update_CGroup/REPORT.md
> +|R4|250_7|Ввод корректных данных при условии что она будет дублировать другую записать (невозможно изменение)|Semester = 1 Specialty = "ММЭТ" Shift = 1 Students = 1 MaxNumberOfClass = 0 MinNumberOfCl
Я думаю он избыточный и его не нужно вообще.

2020-07-20 13:58 UTC, ssas18 commented on Docs/UT_Update_CGroup/REPORT.md
> +|R4|250_7|Ввод корректных данных при условии что она будет дублировать другую записать (невозможно изменение)|Semester = 1 Specialty = "ММЭТ" Shift = 1 Students = 1 MaxNumberOfClass = 0 MinNumberOfCl
Его, наверное, стоит заменить другим тестом подходящим под маршрут R4?

2020-07-20 14:10 UTC, ssas18 commented on Docs/UT_Update_CGroup/REPORT.md
> +|R2|250_2|Изменить сведения в не пустой таблице |Rows.count = 5, но mGroup.Group != (string)this.Rows[i]["Group"] Остальные данные - валидны |false|
Обновление данных группы, но при этом так же происходит обновление название группы?

2020-07-20 16:18 UTC, YuriSilenok commented on Docs/UT_Update_CGroup/REPORT.md
> +|R2|250_2|Изменить сведения в не пустой таблице |Rows.count = 5, но mGroup.Group != (string)this.Rows[i]["Group"] Остальные данные - валидны |false|
R2 маршрут будет возможен тогда, когда в таблице одна запись (но мы можем несколько раз по циклу ходить, главное что бы условие для R3 не сработало), а мы пытаемся поменять данные которых нет в этой таблице. То есть, идея теста будет что-то типа. `Изменить несуществующую запись в заполненной таблице`.

2020-07-20 16:22 UTC, YuriSilenok commented on Docs/UT_Update_CGroup/REPORT.md
> +|R4|250_7|Ввод корректных данных при условии что она будет дублировать другую записать (невозможно изменение)|Semester = 1 Specialty = "ММЭТ" Shift = 1 Students = 1 MaxNumberOfClass = 0 MinNumberOfCl
R4 это тесты, когда мы пытаемся сделать изменение существующих данных, но упираемся в некоторое(ые) ограничение(я) из-за которых невозможно совершить операцию. Здесь нужно смотреть на существующие ограничения (реляционные, на атрибуты), если таковых не имеется, то маршрут считается недостижимым и нужно поднимать улучшение кода (халявная задача).

2020-07-20 17:47 UTC, ssas18 commented on Docs/UT_Update_CGroup/REPORT.md
> +|R4|250_7|Ввод корректных данных при условии что она будет дублировать другую записать (невозможно изменение)|Semester = 1 Specialty = "ММЭТ" Shift = 1 Students = 1 MaxNumberOfClass = 0 MinNumberOfCl
Тогда получается  test title  теста 250_7  (Ввод корректных данных при условии что она будет дублировать другую записать) некорректен?
Должно быть что-то вроде (Ввод некорректных данных не удовлетворяющим ограничением полей)?

2020-07-21 11:55 UTC, YuriSilenok commented on Docs/UT_Update_CGroup/REPORT.md
> +|R4|250_7|Ввод корректных данных при условии что она будет дублировать другую записать (невозможно изменение)|Semester = 1 Specialty = "ММЭТ" Shift = 1 Students = 1 MaxNumberOfClass = 0 MinNumberOfCl
Нужно не просто сказать что тест проверяет какое-то ограничение, а сказать конкретно какое ограничение.
Вы знаете где эти ограничения можно посмотреть?

2020-07-21 12:27 UTC, ssas18 commented on Docs/UT_Update_CGroup/REPORT.md
> +|R4|250_7|Ввод корректных данных при условии что она будет дублировать другую записать (невозможно изменение)|Semester = 1 Specialty = "ММЭТ" Shift = 1 Students = 1 MaxNumberOfClass = 0 MinNumberOfCl
Наверное в сценариях тестирования?
Или я не прав?

2020-07-21 14:34 UTC, YuriSilenok commented on Docs/UT_Update_CGroup/REPORT.md
> +|R4|250_7|Ввод корректных данных при условии что она будет дублировать другую записать (невозможно изменение)|Semester = 1 Specialty = "ММЭТ" Shift = 1 Students = 1 MaxNumberOfClass = 0 MinNumberOfCl
- есть ограничения на уникальность атрибута. Они могут быть составные или простые. Составные отличаются тем, что комбинация нескольких атрибутов должна быть уникальна. Эти ограничения можно посмотреть в конструкторе контроллера. Это как раз тот класс в котором находится тестируемый метод. Пример простой уникальности: Шифр группы представлен строкой и должен быть всегда уникален. Пример составной: Серия и номер паспорта представлены двумя строковыми атрибутами. И комбинации серии и номера должны быть уникальны.
- есть ограничение реляционной связи. Они перечислены к конструкторе рефдаты. суть этого ограничения следующая. Допустим есть студент Иванов и он учиться в группе 666-ИСбо-2а. Так вот, вы не сможете удалить студента пока он будет указан в группе. И вы не сможете добавить студента, который не создан в таблице студенты.

Если не сможете разобраться с тем, куда конкретно смотреть, пишите

2020-07-21 15:26 UTC, ssas18 commented on Docs/UT_Update_CGroup/REPORT.md
> +|R4|250_7|Ввод корректных данных при условии что она будет дублировать другую записать (невозможно изменение)|Semester = 1 Specialty = "ММЭТ" Shift = 1 Students = 1 MaxNumberOfClass = 0 MinNumberOfCl
Ввод некорректных данных не удовлетворяющим ограничением поля MaxNumberOfClass ?
получается так?

2020-07-22 12:53 UTC, YuriSilenok commented on Docs/UT_Update_CGroup/REPORT.md
> +|R4|250_7|Ввод корректных данных при условии что она будет дублировать другую записать (невозможно изменение)|Semester = 1 Specialty = "ММЭТ" Shift = 1 Students = 1 MaxNumberOfClass = 0 MinNumberOfCl
У одного атрибута может быть несколько ограничений, по этому следует указывать по конкретнее какое ограничение проверяется. На одно ограничение делается один тест.

2020-07-22 14:16 UTC, ssas18 commented on Docs/UT_Update_CGroup/REPORT.md
> +|R4|250_7|Ввод корректных данных при условии что она будет дублировать другую записать (невозможно изменение)|Semester = 1 Specialty = "ММЭТ" Shift = 1 Students = 1 MaxNumberOfClass = 0 MinNumberOfCl
Ввод некорректных данных не удовлетворяющим ограничением диапазона(от 1 до 6) поля MaxNumberOfClass ?

2020-07-23 11:47 UTC, ssas18 commented
> @ifuwmnn , @ZhizhikinIvan , @Heriuple , @MyachevM , @NesgovorovVS , @NordScandinavian нужен ревью. пожалуйста

Нужен ревью

2020-07-23 12:26 UTC, Alphavite51 approved these changes

2020-07-23 12:31 UTC, Alphavite51 submitted a review, later dismissed

2020-07-23 15:39 UTC, YuriSilenok commented
![image](https://user-images.githubusercontent.com/14871471/88306747-ca47d780-cd13-11ea-87f9-ca6847a016e6.png)
Могли бы пояснить, что Вы проверяли, если я правильно понял, вы еще не приступили к реализации собственных задач, так как изучаете работу с гитхаб. Что же вы тут могли проверить?

2020-07-23 15:43 UTC, Alphavite51 commented
> ![image](https://user-images.githubusercontent.com/14871471/88306747-ca47d780-cd13-11ea-87f9-ca6847a016e6.png)
> @Alphavite51 
> Могли бы пояснить, что Вы проверяли, если я правильно понял, вы еще не приступили к реализации собственных задач, так как изучаете работу с гитхаб. Что же вы тут могли проверить?

Я просто не понял что за уведомления мне пришли и закрыл, не знал что это какая то проверка работ. 
В следующий раз буду внимательней, извините

2020-07-23 15:46 UTC, YuriSilenok commented
> > ![image](https://user-images.githubusercontent.com/14871471/88306747-ca47d780-cd13-11ea-87f9-ca6847a016e6.png)
> > @Alphavite51
> > Могли бы пояснить, что Вы проверяли, если я правильно понял, вы еще не приступили к реализации собственных задач, так как изучаете работу с гитхаб. Что же вы тут могли проверить?
> 
> Я просто не понял что за уведомления мне пришли и закрыл, не знал что это какая то проверка работ.
> В следующий раз буду внимательней, извините

Вы как член команды должны проверять работы коллег. Не нужно говорить что все хорошо, если вы ничего не проверили. В Ваших интересах искать ошибки и писать о них. Это ускоряет работу команды в целом и фиксирует вашу активность в профиле.

2020-07-27 16:27 UTC, YuriSilenok reviewed
Я пока не могу приступить к проверке, так как двое студентов не проверили Вашу работу.
Я очень ценю Вашу активность.

2020-07-27 16:37 UTC, ssas18 commented
> > @ifuwmnn , @ZhizhikinIvan , @Heriuple , @MyachevM , @NesgovorovVS , @NordScandinavian нужен ревью. пожалуйста
> 
> Нужен ревью

2020-07-28 08:14 UTC, NesgovorovVS submitted a review, later dismissed

2020-07-31 09:43 UTC, Alphavite51 submitted a review, later dismissed

2020-08-01 12:52 UTC, YuriSilenok requested changes
Как насчет проверки реляционных ограничений для региона R4?

2020-08-01 12:52 UTC, YuriSilenok commented on Docs/UT_Update_CGroup/REPORT.md
> +|R1|250_1|Изменить сведения в пустой таблице |Входных данных нет|Rows.count = 0; Остальные данные - валидны|true|
![image](https://user-images.githubusercontent.com/14871471/89102014-e92e2400-d40d-11ea-863a-6381a503fbf8.png)
Где во входных параметрах это указывается?

2020-08-01 12:52 UTC, YuriSilenok commented on Docs/UT_Update_CGroup/REPORT.md
> +|R2|250_2|Изменить несуществующую группу в заполненной таблице |group = "17-ММЭбо-2б",semester = 2, specialty = "ММЭ", shift = 2, students = 2, minNumberOfClass = 1, maxNumberOfClass = 1, weekends =
![image](https://user-images.githubusercontent.com/14871471/89102059-432ee980-d40e-11ea-9181-da34bb2028b8.png)
У вас противоречие в данных, из предварительного условия можно подумать что строк в таблице одна и она перечислена, а во входных параметрах написано что строк должно быть 5.

2020-08-01 12:52 UTC, YuriSilenok commented on Docs/UT_Update_CGroup/REPORT.md
> +|R4|250_7|Ввод корректных данных при условии что она будет дублировать другую записать (невозможно изменение)|group = "17-ММЭбо-2б",semester = 2, specialty = "ММЭ", shift = 2, students = 2, minNumber
Что значит дублировать полностью, как вы этого собираетесь добиться, вам известно о наличии ограничений уникальности некоторых атрибутов? Посмотрите внимательнее, первичный ключ здесь нельзя изменить.

2020-08-04 13:49 UTC, YuriSilenok commented
@Students-of-the-city-of-Kostroma/17-elite пожалуйста, принимайте более активное участие в проверках запросов.

2020-08-04 16:50 UTC, Alphavite51 reviewed
Во 2 регионе опечатка в слове "заипси"

2020-08-05 06:54 UTC, ssas18 commented
@Students-of-the-city-of-Kostroma/17-elite нужен ревью

2020-08-05 20:52 UTC, YuriSilenok commented
> Во 2 регионе опечатка в слове "заипси"

Только выбирайте пункт request change, а не comment. С коммент активность не фиксируется и коммент не означает что требуются какие-то изменения

2020-08-05 20:53 UTC, YuriSilenok commented
> @Students-of-the-city-of-Kostroma/17-elite нужен ревью

А вы, если исправили замечание, должны запросить повторную проверку.

2020-08-05 20:55 UTC, YuriSilenok commented
> Во 2 регионе опечатка в слове "заипси"

А ещё, что бы словестно не указывать где ошибка, можете выделять строку и к ней делать обращение с комментарием

2020-08-06 06:05 UTC, Alphavite51 commented
> > Во 2 регионе опечатка в слове "заипси"
> 
> Только выбирайте пункт request change, а не comment. С коммент активность не фиксируется и коммент не означает что требуются какие-то изменения 

Вас понял

2020-08-07 04:59 UTC, ssas18 commented
> @Students-of-the-city-of-Kostroma/17-elite нужен ревью

2020-08-07 07:32 UTC, Alphavite51 requested changes
В каждом регионе когда вы пишите "смена дублирует смена... " или "График работы дуюлирует график" думаю лучше поставить кавычки для большего понимания (график работы дублирует "график работы муществующего экземпляра")

2020-08-07 09:03 UTC, ssas18 commented
> > @Students-of-the-city-of-Kostroma/17-elite нужен ревью
> 
> А вы, если исправили замечание, должны запросить повторную проверку.

Хорошо, а как это сделать?

2020-08-07 09:20 UTC, ssas18 commented
> > > @Students-of-the-city-of-Kostroma/17-elite нужен ревью
> > 
> > 
> > А вы, если исправили замечание, должны запросить повторную проверку.
> 
> Хорошо, а как это сделать?
Этот значок? 
![image](https://user-images.githubusercontent.com/47377817/89630685-6216fb00-d8a8-11ea-9ff4-317da64fd7b0.png)

2020-08-07 09:50 UTC, Alphavite51 submitted a review, later dismissed
кажется все верно, кто то еще будет проверять? @Students-of-the-city-of-Kostroma/17-elite

2020-08-08 06:56 UTC, ssas18 commented
@Students-of-the-city-of-Kostroma/17-elite нужен ревью

2020-08-09 08:04 UTC, ssas18 commented
@Students-of-the-city-of-Kostroma/17-elite нужен ревью

2020-08-11 10:37 UTC, ssas18 commented
@Students-of-the-city-of-Kostroma/17-elite нужен ревью

2020-08-11 16:03 UTC, ifuwmnn submitted a review, later dismissed

2020-08-11 18:10 UTC, YuriSilenok requested changes
![image](https://user-images.githubusercontent.com/14871471/89932982-0eddd900-dc17-11ea-8128-65be4848c0ec.png)
Зачем вы это удалили?
Наша задача не имеет отношения к этим файлам

2020-08-12 04:48 UTC, ssas18 commented
> ![image](https://user-images.githubusercontent.com/14871471/89932982-0eddd900-dc17-11ea-8128-65be4848c0ec.png)
> Зачем вы это удалили?
> Наша задача не имеет отношения к этим файлам

Я подумал что я словил баг переходя от задачи #1280 в эту, поэтому и удалил, мне вернуть это обратно?

2020-08-12 07:58 UTC, YuriSilenok commented
> > ![image](https://user-images.githubusercontent.com/14871471/89932982-0eddd900-dc17-11ea-8128-65be4848c0ec.png)
> > Зачем вы это удалили?
> > Наша задача не имеет отношения к этим файлам
> 
> Я подумал что я словил баг переходя от задачи #1280 в эту, поэтому и удалил, мне вернуть это обратно?

да, сделайте реверт коммита, который это удалил.

2020-08-12 08:16 UTC, ssas18 commented
> > > ![image](https://user-images.githubusercontent.com/14871471/89932982-0eddd900-dc17-11ea-8128-65be4848c0ec.png)
> > > Зачем вы это удалили?
> > > Наша задача не имеет отношения к этим файлам
> > 
> > 
> > Я подумал что я словил баг переходя от задачи #1280 в эту, поэтому и удалил, мне вернуть это обратно?
> 
> да, сделайте реверт коммита, который это удалил.

А как это делать?

2020-08-13 14:09 UTC, YuriSilenok requested changes
![image](https://user-images.githubusercontent.com/14871471/90144706-d3aee780-dd87-11ea-8fe1-7a51842df922.png)

Зачем вы меняли эти файлы?

2020-08-13 14:10 UTC, YuriSilenok commented
Вообщем навертели

2020-08-13 14:11 UTC, YuriSilenok commented
возьмите скопируйте эти файлы из дев в свою ветку, сделайте коммит и отдайте на гитхаб, посмотрим, будет ли он в таком случае их отображать как измененые, по идее не должен.

2020-08-14 07:28 UTC, YuriSilenok requested changes
![image](https://user-images.githubusercontent.com/14871471/90224764-d9084280-de18-11ea-966b-3e3f302f4dab.png)
Если данных нет, то что изменится?

2020-08-14 07:30 UTC, ssas18 commented
> ![image](https://user-images.githubusercontent.com/14871471/90224764-d9084280-de18-11ea-966b-3e3f302f4dab.png)
> Если данных нет, то что изменится?
нет, извините, сейчас исправлю

2020-08-14 07:37 UTC, YuriSilenok requested changes
![image](https://user-images.githubusercontent.com/14871471/90225426-05708e80-de1a-11ea-9261-f401857d05c8.png)
Пожалуйста, не используйте вставки кода в сценариях. Прописывайте условия словами.

2020-08-14 07:40 UTC, ssas18 commented
> ![image](https://user-images.githubusercontent.com/14871471/90225426-05708e80-de1a-11ea-9261-f401857d05c8.png)
> Пожалуйста, не используйте вставки кода в сценариях. Прописывайте условия словами.

А как это описать корректно?
"не совпадают первичные ключи"?

2020-08-14 07:43 UTC, YuriSilenok commented
> > ![image](https://user-images.githubusercontent.com/14871471/90225426-05708e80-de1a-11ea-9261-f401857d05c8.png)
> > Пожалуйста, не используйте вставки кода в сценариях. Прописывайте условия словами.
> 
> А как это описать корректно?
> "не совпадают первичные ключи"?

Привел пример [здесь](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1294#pullrequestreview-467369375).

2020-08-14 08:08 UTC, YuriSilenok reviewed
По отчету в целом нормально.
Думаю сейчас вы займетесь автотестами.

2020-08-14 10:04 UTC, ssas18 commented
> По отчету в целом нормально.
> Думаю сейчас вы займетесь автотестами.

То есть мне надо сделать автотесты такими, какие описаны у меня в отчете?

2020-08-15 18:25 UTC, YuriSilenok commented
Да, именно так. Нужно автотесты передалить к написанл в вашем  отчёте.

пт, 14 авг. 2020 г., 13:04 Александр Коваленко <notifications@github.com>:

> По отчету в целом нормально.
> Думаю сейчас вы займетесь автотестами.
>
> То есть мне надо сделать автотесты такими, какие описаны у меня в отчете?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1295#issuecomment-673998696>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADROXL3HACDEJHQZLLBCUH3SAUD2XANCNFSM4ORL76YA>
> .
>

2020-08-16 09:50 UTC, ssas18 commented
Юрий Викторович, я пытался переделать автотесты, но у меня не совсем это получается (250_1(Изменить сведения в пустой таблице) и 250_2(Изменить несуществующую группу в заполненной таблице))  Все по одной причине, я не могу изменить того, чего не существует

2020-08-16 10:54 UTC, YuriSilenok commented
А кто сказал что данные должны изменится, у вас в отчёте ведь функция возвращает false, ощнаяающа что ПОПЫТКА изменить данные не удалась?

2020-08-16 10:56 UTC, ssas18 commented
> А кто сказал что данные должны изменится, у вас в отчёте ведь функция возвращает false, ощнаяающа что ПОПЫТКА изменить данные не удалась?

нет, я не понимаю как логически написать этот автотест

2020-08-16 10:59 UTC, YuriSilenok commented
А можно по конкретнее, например первый тест, предварительное условие говорит что таблица должна быть пуста, вы это проверили?

2020-08-16 11:02 UTC, ssas18 commented
> А можно по конкретнее, например первый тест, предварительное условие говорит что таблица должна быть пуста, вы это проверили?

Ну в рефдате, таблицы преподавателей нет

2020-08-16 11:24 UTC, YuriSilenok commented
> > А можно по конкретнее, например первый тест, предварительное условие говорит что таблица должна быть пуста, вы это проверили?
> 
> Ну в рефдате, таблицы групп нет

Если нет таблицы, это супер баг, в таблице должно быть 0 строк

2020-08-16 11:27 UTC, ssas18 commented
> > > А можно по конкретнее, например первый тест, предварительное условие говорит что таблица должна быть пуста, вы это проверили?
> > 
> > 
> > Ну в рефдате, таблицы групп нет
> 
> Если нет таблицы, это супер баг, в таблице должно быть 0 строк

Да, вы правы таблица то сама есть(1 скрин)
![image](https://user-images.githubusercontent.com/47377817/90333199-8ec7c280-dfcc-11ea-953e-797e4b092b57.png)
и она не заполнена 
![image](https://user-images.githubusercontent.com/47377817/90333206-9b4c1b00-dfcc-11ea-84ed-1a1c2b919ffa.png)

2020-08-17 06:29 UTC, YuriSilenok commented
> А можно по конкретнее, например первый тест, предварительное условие говорит что таблица должна быть пуста, вы это проверили?

Так что там с проверкой того, что таблица пуста?

2020-08-17 06:42 UTC, ssas18 commented
> > А можно по конкретнее, например первый тест, предварительное условие говорит что таблица должна быть пуста, вы это проверили?
> 
> Так что там с проверкой того, что таблица пуста?

Ну я так понимаю что таблица содержит 0 строк

2020-08-17 06:45 UTC, YuriSilenok commented
> > > А можно по конкретнее, например первый тест, предварительное условие говорит что таблица должна быть пуста, вы это проверили?
> > 
> > 
> > Так что там с проверкой того, что таблица пуста?
> 
> Ну я так понимаю что таблица содержит 0 строк

Вы знаете как сделать  эту проверку?

2020-08-17 06:46 UTC, ssas18 commented
> > > > А можно по конкретнее, например первый тест, предварительное условие говорит что таблица должна быть пуста, вы это проверили?
> > > 
> > > 
> > > Так что там с проверкой того, что таблица пуста?
> > 
> > 
> > Ну я так понимаю что таблица содержит 0 строк
> 
> Вы знаете как сделать эту проверку?

Нет, прошу Вашей помощи

2020-08-17 06:57 UTC, YuriSilenok commented
> > > > > А можно по конкретнее, например первый тест, предварительное условие говорит что таблица должна быть пуста, вы это проверили?
> > > > 
> > > > 
> > > > Так что там с проверкой того, что таблица пуста?
> > > 
> > > 
> > > Ну я так понимаю что таблица содержит 0 строк
> > 
> > 
> > Вы знаете как сделать эту проверку?
> 
> Нет, прошу Вашей помощи

Смотрите на класс родителя и [документацию ](https://docs.microsoft.com/ru-ru/dotnet/api/system.data.datatable?view=netframework-4.5) для него

2020-08-17 07:37 UTC, ssas18 commented
> > > > > > А можно по конкретнее, например первый тест, предварительное условие говорит что таблица должна быть пуста, вы это проверили?
> > > > > 
> > > > > 
> > > > > Так что там с проверкой того, что таблица пуста?
> > > > 
> > > > 
> > > > Ну я так понимаю что таблица содержит 0 строк
> > > 
> > > 
> > > Вы знаете как сделать эту проверку?
> > 
> > 
> > Нет, прошу Вашей помощи
> 
> Смотрите на класс родителя и [документацию ](https://docs.microsoft.com/ru-ru/dotnet/api/system.data.datatable?view=netframework-4.5) для него

Вроде как он не пустой 
![image](https://user-images.githubusercontent.com/47377817/90370141-942d1780-e075-11ea-897b-8ce224cdb809.png)

2020-08-17 07:42 UTC, YuriSilenok commented
> > > > > > > А можно по конкретнее, например первый тест, предварительное условие говорит что таблица должна быть пуста, вы это проверили?
> > > > > > 
> > > > > > 
> > > > > > Так что там с проверкой того, что таблица пуста?
> > > > > 
> > > > > 
> > > > > Ну я так понимаю что таблица содержит 0 строк
> > > > 
> > > > 
> > > > Вы знаете как сделать эту проверку?
> > > 
> > > 
> > > Нет, прошу Вашей помощи
> > 
> > 
> > Смотрите на класс родителя и [документацию ](https://docs.microsoft.com/ru-ru/dotnet/api/system.data.datatable?view=netframework-4.5) для него
> 
> Вроде как он не пустой
> ![image](https://user-images.githubusercontent.com/47377817/90370141-942d1780-e075-11ea-897b-8ce224cdb809.png)

Соответственно либо вы делаете принудительную очистку, кажется метод Clear(), либо вы ждете решения задачи которая отделяет заполнение рефдаты от конструктора. #1323

2020-08-17 09:42 UTC, YuriSilenok requested changes
Что это за одиннадцатый тест, такого нет в отчете

2020-08-17 09:44 UTC, ssas18 commented
> Что это за одиннадцатый тест, такого нет в отчете

Да, понимаю, там сейчас полная путаница в обозначениях, пока пытаюсь разобраться с автотестами, это не конечный вариант

2020-08-17 09:55 UTC, YuriSilenok commented
> > Что это за одиннадцатый тест, такого нет в отчете
> 
> Да, понимаю, там сейчас полная путаница в обозначениях, пока пытаюсь разобраться с автотестами, это не конечный вариант

Хорошо, вы смело можете старые тесты удалять, так как у вас всегда под рукой будет старый код в ветке dev

2020-08-18 09:18 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CGroup.cs
> +            refData.CGroup.Clear();
Проверьте что таблица пуста, ни один вызов функции не гарантирует что действие, возложенное на нее, было совершено.

2020-08-18 09:20 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CGroup.cs
> +            gr.Weekends = "Суббота";
Думаю эти действия избыточны

2020-08-18 09:21 UTC, ssas18 commented on UnitTestOfTimetableOfClasses/UT_Update_CGroup.cs
> +            refData.CGroup.Clear();
> Проверьте что таблица пуста, ни один вызов функции не гарантирует что действие, возложенное на нее, было совершено.

конструкция if else подойдет?

2020-08-18 10:13 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CGroup.cs
> +            refData.CGroup.Clear();
`Assert.IsTrue(refData.CGroup.Rows.Count == 0)`

Попробуйте что-то вроде этого

2020-08-18 12:54 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CGroup.cs
> +            Assert.IsTrue(refData.CGroup.Rows.Count == 0, "Не удалось очистить таблицу группа");
Методы проверки лучше использовать вместе с комментариями, дабы не проводить глубоких исследований о том, где именно и на чем упал тест.

2020-08-18 12:57 UTC, ssas18 commented on UnitTestOfTimetableOfClasses/UT_Update_CGroup.cs
> +            Assert.IsTrue(refData.CGroup.Rows.Count == 0, "Не удалось очистить таблицу группа");
Смысл понял, в ближайшее время исправлю данную ошибку во всех автотестах

2020-08-18 13:45 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CGroup.cs
> +            Assert.IsTrue(refData.CGroup.Rows.Count == 0, "Не удалось очистить таблицу группа");
Хорошо

2020-08-18 14:34 UTC, Alphavite51 submitted a review, later dismissed

2020-08-18 14:50 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CGroup.cs
> +>>>>>>> f96d5a698448814a2da303de4fb42eb024c9c9d3
Решите мержконфликт

2020-08-18 15:20 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CGroup.cs
> +            Assert.IsTrue(refData.CDirectionOfPreparation.Insert(mDirection),"Не вставить удалить профиль обучения");
`"Не вставить удалить профиль обучения"` - вставить или удалить?

2020-08-18 15:21 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CGroup.cs
> +            gr2.Weekends = "Суббота";
Не знаю завершено ли это, но когда будет завершено, я спрошу зачем это нужно?

2020-08-19 06:49 UTC, YuriSilenok requested changes
```
new MDirectionOfPreparation("01.03.04", "Прикладная математика", 4);
new MTrainingProfile("Математическое моделирование в экономике и технике", "ММЭТ", "01.03.04");
new MTrainingProfile("Математические методы в экономике", "ММЭ", "01.03.04");
```

Если вы решили оставить создание данных, то вынесите их в поля, так как вы создаете одни и те же объекты в разных методах.

2020-08-19 09:37 UTC, ssas18 reviewed
> к как вы создаете одни и те же объекты в разных методах.



> ```
> new MDirectionOfPreparation("01.03.04", "Прикладная математика", 4);
> new MTrainingProfile("Математическое моделирование в экономике и технике", "ММЭТ", "01.03.04");
> new MTrainingProfile("Математические методы в экономике", "ММЭ", "01.03.04");
> ```
> 
> Если вы решили оставить создание данных, то вынесите их в поля, так как вы создаете одни и те же объекты в разных методах.

Юрий Вкторович, я не сильно понимаю зачем это надо, они же вынесены в метод и я не понимаю зачем делать это просто полями

2020-08-19 09:37 UTC, ssas18 commented on UnitTestOfTimetableOfClasses/UT_Update_CGroup.cs
> +            gr2.Weekends = "Суббота";
Это было завершено до этого момента)
Да, я понял что на эту ошибку мне уже было указано, но я ее здесь проглядел

2020-08-19 15:36 UTC, YuriSilenok commented
> > к как вы создаете одни и те же объекты в разных методах.
> 
> > ```
> > new MDirectionOfPreparation("01.03.04", "Прикладная математика", 4);
> > new MTrainingProfile("Математическое моделирование в экономике и технике", "ММЭТ", "01.03.04");
> > new MTrainingProfile("Математические методы в экономике", "ММЭ", "01.03.04");
> > ```
> > 
> > 
> > Если вы решили оставить создание данных, то вынесите их в поля, так как вы создаете одни и те же объекты в разных методах.
> 
> Юрий Вкторович, я не сильно понимаю зачем это надо, они же вынесены в метод и я не понимаю зачем делать это просто полями

Трата ресурсов ПК при создании нового экземпляра класса. В основном процессорное время.

2020-08-19 15:43 UTC, ssas18 commented
> > > к как вы создаете одни и те же объекты в разных методах.
> > 
> > 
> > > ```
> > > new MDirectionOfPreparation("01.03.04", "Прикладная математика", 4);
> > > new MTrainingProfile("Математическое моделирование в экономике и технике", "ММЭТ", "01.03.04");
> > > new MTrainingProfile("Математические методы в экономике", "ММЭ", "01.03.04");
> > > ```
> > > 
> > > 
> > > Если вы решили оставить создание данных, то вынесите их в поля, так как вы создаете одни и те же объекты в разных методах.
> > 
> > 
> > Юрий Вкторович, я не сильно понимаю зачем это надо, они же вынесены в метод и я не понимаю зачем делать это просто полями
> 
> Трата ресурсов ПК при создании нового экземпляра класса. В основном процессорное время.

То есть нужно разделить объявление переменной и ее инициализацию?

2020-08-19 15:48 UTC, YuriSilenok commented
> > > > к как вы создаете одни и те же объекты в разных методах.
> > > 
> > > 
> > > > ```
> > > > new MDirectionOfPreparation("01.03.04", "Прикладная математика", 4);
> > > > new MTrainingProfile("Математическое моделирование в экономике и технике", "ММЭТ", "01.03.04");
> > > > new MTrainingProfile("Математические методы в экономике", "ММЭ", "01.03.04");
> > > > ```
> > > > 
> > > > 
> > > > Если вы решили оставить создание данных, то вынесите их в поля, так как вы создаете одни и те же объекты в разных методах.
> > > 
> > > 
> > > Юрий Вкторович, я не сильно понимаю зачем это надо, они же вынесены в метод и я не понимаю зачем делать это просто полями
> > 
> > 
> > Трата ресурсов ПК при создании нового экземпляра класса. В основном процессорное время.
> 
> То есть нужно разделить объявление переменной и ее инициализацию?

У вас два варианта, либо вы инициализируете прямо в полях либо в конструкторе, но сами переменные будут объявлены в полях.

2020-08-19 15:53 UTC, ssas18 commented
> > > > > к как вы создаете одни и те же объекты в разных методах.
> > > > 
> > > > 
> > > > > ```
> > > > > new MDirectionOfPreparation("01.03.04", "Прикладная математика", 4);
> > > > > new MTrainingProfile("Математическое моделирование в экономике и технике", "ММЭТ", "01.03.04");
> > > > > new MTrainingProfile("Математические методы в экономике", "ММЭ", "01.03.04");
> > > > > ```
> > > > > 
> > > > > 
> > > > > Если вы решили оставить создание данных, то вынесите их в поля, так как вы создаете одни и те же объекты в разных методах.
> > > > 
> > > > 
> > > > Юрий Вкторович, я не сильно понимаю зачем это надо, они же вынесены в метод и я не понимаю зачем делать это просто полями
> > > 
> > > 
> > > Трата ресурсов ПК при создании нового экземпляра класса. В основном процессорное время.
> > 
> > 
> > То есть нужно разделить объявление переменной и ее инициализацию?
> 
> У вас два варианта, либо вы инициализируете прямо в полях либо в конструкторе, но сами переменные будут объявлены в полях.

А «в полях» значит без метода?

2020-08-19 15:54 UTC, YuriSilenok commented
> > > > > > к как вы создаете одни и те же объекты в разных методах.
> > > > > 
> > > > > 
> > > > > > ```
> > > > > > new MDirectionOfPreparation("01.03.04", "Прикладная математика", 4);
> > > > > > new MTrainingProfile("Математическое моделирование в экономике и технике", "ММЭТ", "01.03.04");
> > > > > > new MTrainingProfile("Математические методы в экономике", "ММЭ", "01.03.04");
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > > Если вы решили оставить создание данных, то вынесите их в поля, так как вы создаете одни и те же объекты в разных методах.
> > > > > 
> > > > > 
> > > > > Юрий Вкторович, я не сильно понимаю зачем это надо, они же вынесены в метод и я не понимаю зачем делать это просто полями
> > > > 
> > > > 
> > > > Трата ресурсов ПК при создании нового экземпляра класса. В основном процессорное время.
> > > 
> > > 
> > > То есть нужно разделить объявление переменной и ее инициализацию?
> > 
> > 
> > У вас два варианта, либо вы инициализируете прямо в полях либо в конструкторе, но сами переменные будут объявлены в полях.
> 
> А «в полях» значит без метода?

Да, в методах вы просто используете эти поля для добавления и удаления данных.

2020-08-19 15:57 UTC, ssas18 commented
> > > > > > > к как вы создаете одни и те же объекты в разных методах.
> > > > > > 
> > > > > > 
> > > > > > > ```
> > > > > > > new MDirectionOfPreparation("01.03.04", "Прикладная математика", 4);
> > > > > > > new MTrainingProfile("Математическое моделирование в экономике и технике", "ММЭТ", "01.03.04");
> > > > > > > new MTrainingProfile("Математические методы в экономике", "ММЭ", "01.03.04");
> > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > > Если вы решили оставить создание данных, то вынесите их в поля, так как вы создаете одни и те же объекты в разных методах.
> > > > > > 
> > > > > > 
> > > > > > Юрий Вкторович, я не сильно понимаю зачем это надо, они же вынесены в метод и я не понимаю зачем делать это просто полями
> > > > > 
> > > > > 
> > > > > Трата ресурсов ПК при создании нового экземпляра класса. В основном процессорное время.
> > > > 
> > > > 
> > > > То есть нужно разделить объявление переменной и ее инициализацию?
> > > 
> > > 
> > > У вас два варианта, либо вы инициализируете прямо в полях либо в конструкторе, но сами переменные будут объявлены в полях.
> > 
> > 
> > А «в полях» значит без метода?
> 
> Да, в методах вы просто используете эти поля для добавления и удаления данных.

Хорошо, надеюсь понял

2020-08-19 16:35 UTC, ssas18 commented
@YuriSilenok , это должно выглядеть как в 250_2?

2020-08-20 14:04 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CGroup.cs
> +            Assert.IsTrue(refData.CDirectionOfPreparation.Delete(mDirection), "Не удалось удалить направление подготовки");*/
Не забыть разобрать мусор

2020-08-20 14:04 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CGroup.cs
> +
не забыть убрать мусор

2020-08-20 14:06 UTC, YuriSilenok commented
> @YuriSilenok , это должно выглядеть как в 250_2?

я не много не об этом говорил, но делайте дальше, там посмотрим что получится.

2020-08-21 15:04 UTC, YuriSilenok reviewed
что будет с закоментированном участком кода?

2020-08-23 12:42 UTC, ssas18 commented
> что будет с закоментированном участком кода?

Он уже удален, простите за невнимательность

2020-08-24 13:34 UTC, Alphavite51 approved these changes, later dismissed

2020-08-25 10:44 UTC, YuriSilenok requested changes

2020-08-25 10:44 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CGroup.cs
> +            bool actual = refData.CGroup.Update(gr2);
![image](https://user-images.githubusercontent.com/14871471/91165326-1ef6bd80-e6d9-11ea-9a27-d0e6df9b62ca.png)
Где сообщение о сбое в тесте?

2020-08-27 06:19 UTC, YuriSilenok requested changes
Проблема с предварительным условием, подумайте над этим во всех тестах.

2020-08-27 06:19 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CGroup.cs
> +            Assert.AreEqual(expected, actual, "Удалось изменить несуществующую группу в заполненной таблице");
Откуда мы знаем, что группы "17-ММЭбо-2в" нет в таблице, вы в таблицу с неизвестным состоянием добавляете данные, а только потом проверяете что она не пуста. Типа x + 2 != 0, где x >= 0, ну такое всегда является верным.

2020-08-28 17:15 UTC, ifuwmnn approved these changes, later dismissed

2020-08-29 18:30 UTC, YuriSilenok commented
Буду смотреть в понедельник

2020-08-29 19:58 UTC, Alphavite51 commented
Ветка смержена, можете продолжать работу, вам нужно мержить dev в вашу ветку!

2020-08-31 13:46 UTC, YuriSilenok requested changes
![image](https://user-images.githubusercontent.com/14871471/91726754-6c779c80-eba9-11ea-99a6-32e48dcf904e.png)
Хотел было посмотреть как работают тесты, но в них сбои

2020-08-31 14:02 UTC, ssas18 commented
Такое решение проблемы допустимо?

2020-09-01 18:46 UTC, ssas18 commented
@Students-of-the-city-of-Kostroma/17-elite нужен ревью, пожалуйста

2020-09-04 08:20 UTC, YuriSilenok commented
> Такое решение проблемы допустимо?

удаление проверок наобум не самая лучшая стратегия, вы снижаете качество тестов.

2020-09-04 08:23 UTC, YuriSilenok commented
предварительные условия должны быть проверены

2020-09-04 08:24 UTC, YuriSilenok commented
я откачусь на коммит где прошлый раз проверял, посмотрю что там не так было с тестами

2020-09-04 08:32 UTC, YuriSilenok reviewed
![image](https://user-images.githubusercontent.com/14871471/92218624-1012c680-eea2-11ea-9358-ef42e7090104.png)
Вы не добавляли данные в таблицу, что бы ожидать, что она чем-то заполнена.
Вы не знаете состояние системы на момент проверки.
здесь вам вообще незачем проверять что таблица не пуста.
Думаю что вы правильно сделали что убрали проверки. 
Посмотрю тогда на текущий вариант.

2020-09-04 08:45 UTC, YuriSilenok requested changes
Проверка соответствия маршрутов
|Порядковый номер теста|Статус|Комментарий|
| --- | --- | --- |
| 1 | Passed | |
| 2 | Passed | |
| 3 | Passed | |
| 4 | Passed | |
| 5 | Passed | |
| 6 | Passed | |
| 7 | Passed | |
| 8 | Failed | Этот тест выполняется по маршруту R1 |

2020-09-04 08:45 UTC, YuriSilenok commented on Docs/UT_Update_CGroup/REPORT.md
> +|R4|250_8Ввод  данных при условии что указанная Группа не существует|group = "17-ММЭбо-2б",semester = 2, specialty = "ММЭ", shift = 2, students = 2, minNumberOfClass = 1, maxNumberOfClass = 1, weeken
Строка поехала

2020-09-04 09:53 UTC, ssas18 commented
> Проверка соответствия маршрутов
> 
> Порядковый номер теста	Статус	Комментарий
> 1	Passed	
> 2	Passed	
> 3	Passed	
> 4	Passed	
> 5	Passed	
> 6	Passed	
> 7	Passed	
> 8	Failed	Этот тест выполняется по маршруту R1

Я не смог исправить данный тест, чтобы он проходил по маршруту R4
Мне кажется это невозможным т.к в методе условие отрабатывает когда есть совпадение по группе 
![image](https://user-images.githubusercontent.com/47377817/92226488-823cd880-eead-11ea-8909-75fc9a1637d6.png)
Данный тест должен проходить по другому маршруту?
Или я что-то не понял?

2020-09-04 09:58 UTC, YuriSilenok commented
> > Проверка соответствия маршрутов
> > Порядковый номер теста	Статус	Комментарий
> > 1	Passed
> > 2	Passed
> > 3	Passed
> > 4	Passed
> > 5	Passed
> > 6	Passed
> > 7	Passed
> > 8	Failed	Этот тест выполняется по маршруту R1
> 
> Я не смог исправить данный тест, чтобы он проходил по маршруту R4
> Мне кажется это невозможным т.к в методе условие отрабатывает когда есть совпадение по группе
> ![image](https://user-images.githubusercontent.com/47377817/92226488-823cd880-eead-11ea-8909-75fc9a1637d6.png)
> Данный тест должен проходить по другому маршруту?
> Или я что-то не понял?

совершенно верно, я оставил такой сценарий для автоматизации, моя посхалка. Такой сценарий действительно невозможен. так как по нашим правилам, нельзя менять первичный ключ в таблице.

2020-09-04 13:36 UTC, ssas18 commented
> > > Проверка соответствия маршрутов
> > > Порядковый номер теста	Статус	Комментарий
> > > 1	Passed
> > > 2	Passed
> > > 3	Passed
> > > 4	Passed
> > > 5	Passed
> > > 6	Passed
> > > 7	Passed
> > > 8	Failed	Этот тест выполняется по маршруту R1
> > 
> > 
> > Я не смог исправить данный тест, чтобы он проходил по маршруту R4
> > Мне кажется это невозможным т.к в методе условие отрабатывает когда есть совпадение по группе
> > ![image](https://user-images.githubusercontent.com/47377817/92226488-823cd880-eead-11ea-8909-75fc9a1637d6.png)
> > Данный тест должен проходить по другому маршруту?
> > Или я что-то не понял?
> 
> совершенно верно, я оставил такой сценарий для автоматизации, моя посхалка. Такой сценарий действительно невозможен. так как по нашим правилам, нельзя менять первичный ключ в таблице.

С моей внимательностью это, наверное, первая найденная мною пасхалка)
Мне все же перевести его в другой маршрут или пометить как "недостижим"?

2020-09-04 19:22 UTC, YuriSilenok commented
Если на маршруте один тест, Пометить как недостижим. Если на маршруте несколько тестов, сжечь  его.

2020-09-05 12:45 UTC, ssas18 commented
> Если на маршруте один тест, Пометить как недостижим. Если на маршруте несколько тестов, сжечь его.

сожжено!

2020-09-05 13:54 UTC, ifuwmnn approved these changes, later dismissed

2020-09-06 05:02 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1341']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-06 08:01 UTC, MyachevM submitted a review, later dismissed

2020-09-07 14:10 UTC, NesgovorovVS approved these changes, later dismissed
Маршруты, которые нужно было сжечь - сжёг. Остальное тоже вроде верно.

2020-09-07 14:29 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1341']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-07 15:56 UTC, Alphavite51 requested changes
Почему на скриншоте не пронумерованы операторы?

2020-09-07 17:10 UTC, ssas18 commented
> Почему на скриншоте не пронумерованы операторы?

![image](https://user-images.githubusercontent.com/47377817/92408448-2e98ec00-f146-11ea-88d0-3388bd0074c7.png)

2020-09-07 18:14 UTC, NordScandinavian approved these changes, later dismissed
Ошибки исправлены, других, вроде бы не появилось

2020-09-08 12:08 UTC, Alphavite51 requested changes
У вас есть непроверенные запросы ['#86', '#87']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-08 12:14 UTC, ssas18 commented
> У вас есть непроверенные запросы ['#86', '#87']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

Это относится к другому репозиторию и никак Вашу деятельность не тормозит, и зачем ты выполняешь задачи скрипта?

2020-09-08 12:17 UTC, Alphavite51 commented
> > У вас есть непроверенные запросы ['#86', '#87']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса
> 
> Это относится к другому репозиторию и никак Вашу деятельность не тормозит, и зачем ты выполняешь задачи скрипта?

чтобы у профиля со скриптом небыло активности

2020-09-08 12:17 UTC, Alphavite51 submitted a review, later dismissed

2020-09-08 12:20 UTC, ssas18 commented
> > > У вас есть непроверенные запросы ['#86', '#87']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса
> > 
> > 
> > Это относится к другому репозиторию и никак Вашу деятельность не тормозит, и зачем ты выполняешь задачи скрипта?
> 
> чтобы у профиля со скриптом небыло активности

Ответил в #1294 , давайте не будем плодить фейковую активность

2020-09-08 12:21 UTC, Alphavite51 commented
> > > > У вас есть непроверенные запросы ['#86', '#87']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса
> > > 
> > > 
> > > Это относится к другому репозиторию и никак Вашу деятельность не тормозит, и зачем ты выполняешь задачи скрипта?
> > 
> > 
> > чтобы у профиля со скриптом небыло активности
> 
> Ответил в #1294 , давайте не будем плодить фейковую активность

давно пора прекращать

2020-09-08 15:23 UTC, ZhizhikinIvan submitted a review, later dismissed

2020-09-08 17:57 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы []. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-08 17:57 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1335']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-09 17:05 UTC, YuriSilenok reviewed
Как сюда попали изменения тестов из UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs

2020-09-09 17:08 UTC, ssas18 commented
> Как сюда попали изменения тестов из UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs

Переключался между ветками не закрывая студию, вот она и подтащила изменения с прошлой ветки в эту, но вроде сделал реверт

2020-09-09 17:10 UTC, ssas18 commented
> Как сюда попали изменения тестов из UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs

ох я накосячил

2020-09-09 17:12 UTC, YuriSilenok commented
> > Как сюда попали изменения тестов из UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> 
> ох я накосячил
> 
> 

Сможете поправить?

2020-09-09 17:13 UTC, ssas18 commented
> > > Как сюда попали изменения тестов из UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> > 
> > 
> > ох я накосячил
> 
> Сможете поправить?

Да, я думаю лучше реверт или все руками восстановить?

2020-09-09 17:35 UTC, YuriSilenok commented
Да, столько человек, и не увидели что был изменён лишний текст

2020-09-09 17:37 UTC, YuriSilenok reviewed
![Screenshot_20200909_203629_com.github.android.jpg](https://user-images.githubusercontent.com/14871471/92633922-2d012c80-f2dc-11ea-8da3-9c8f70bd7860.jpg)
Кожется не получилось

2020-09-09 17:40 UTC, ssas18 commented
> ![Screenshot_20200909_203629_com.github.android.jpg](https://user-images.githubusercontent.com/14871471/92633922-2d012c80-f2dc-11ea-8da3-9c8f70bd7860.jpg)
> Кожется не получилось

переименовать название отчета?

2020-09-09 17:43 UTC, YuriSilenok requested changes
Почти, всего один символ.
![Screenshot_20200909_204236_com.github.android.jpg](https://user-images.githubusercontent.com/14871471/92634496-10b1bf80-f2dd-11ea-8a7f-5838a2dd3f4c.jpg)
Тут напрашивается мемас, Карл!

2020-09-09 17:44 UTC, YuriSilenok commented
> > ![Screenshot_20200909_203629_com.github.android.jpg](https://user-images.githubusercontent.com/14871471/92633922-2d012c80-f2dc-11ea-8da3-9c8f70bd7860.jpg)
> > Кожется не получилось
> 
> переименовать название отчета?
> 

Там символ переноса, полюбому

2020-09-09 18:06 UTC, ssas18 commented
> > > ![Screenshot_20200909_203629_com.github.android.jpg](https://user-images.githubusercontent.com/14871471/92633922-2d012c80-f2dc-11ea-8da3-9c8f70bd7860.jpg)
> > > Кожется не получилось
> > 
> > 
> > переименовать название отчета?
> 
> Там символ переноса, полюбому

Вообще ничего не понимаю что происходит)
мне нужно изменить название картинки и  изменить класс CTeacher?
просто много путаницы в голове

2020-09-09 18:48 UTC, YuriSilenok commented
> Почти, всего один символ.
> ![Screenshot_20200909_204236_com.github.android.jpg](https://user-images.githubusercontent.com/14871471/92634496-10b1bf80-f2dd-11ea-8a7f-5838a2dd3f4c.jpg)
> Тут напрашивается мемас, Карл! 

Видите здесь красное и зелёное. Они отличаются нечитаемым символом. Это квест, найти не читаемый символ и добавить /удалить его.

2020-09-09 18:49 UTC, ssas18 commented
> > Почти, всего один символ.
> > ![Screenshot_20200909_204236_com.github.android.jpg](https://user-images.githubusercontent.com/14871471/92634496-10b1bf80-f2dd-11ea-8a7f-5838a2dd3f4c.jpg)
> > Тут напрашивается мемас, Карл!
> 
> Видите здесь красное и зелёное. Они отличаются нечитаемым символом. Это квест, найти не читаемый символ и добавить /удалить его.

я уже скопировал этот класс из дев, не помогло)

2020-09-09 18:53 UTC, ssas18 commented
> > > Почти, всего один символ.
> > > ![Screenshot_20200909_204236_com.github.android.jpg](https://user-images.githubusercontent.com/14871471/92634496-10b1bf80-f2dd-11ea-8a7f-5838a2dd3f4c.jpg)
> > > Тут напрашивается мемас, Карл!
> > 
> > 
> > Видите здесь красное и зелёное. Они отличаются нечитаемым символом. Это квест, найти не читаемый символ и добавить /удалить его.
> 
> я уже скопировал этот класс из дев, не помогло)

интересный квест, есть еще подсказки?)

2020-09-09 19:03 UTC, ssas18 commented
> > > > Почти, всего один символ.
> > > > ![Screenshot_20200909_204236_com.github.android.jpg](https://user-images.githubusercontent.com/14871471/92634496-10b1bf80-f2dd-11ea-8a7f-5838a2dd3f4c.jpg)
> > > > Тут напрашивается мемас, Карл!
> > > 
> > > 
> > > Видите здесь красное и зелёное. Они отличаются нечитаемым символом. Это квест, найти не читаемый символ и добавить /удалить его.
> > 
> > 
> > я уже скопировал этот класс из дев, не помогло)
> 
> интересный квест, есть еще подсказки?)

Справился, да еще и быстрее 60 мин)

2020-09-10 07:21 UTC, YuriSilenok approved these changes

2020-09-10 08:33 UTC, ifuwmnn approved these changes

2020-09-10 10:40 UTC, merged