Исправление сбоев в автотестах расположенных в файле UT_Update_CDiscipline
Students-of-the-city-of-Kostroma/Student-timetable pull request #1304
Opened 2020-07-08 12:29 UTC by badsster

#1282
[Отчет](https://docs.google.com/document/d/11_k3P-g3HWXO-b2ftnc_CTK-VURiBBF7EPNlCBIPWZ8/edit)

2020-07-08 13:43 UTC, YuriSilenok requested changes
Зачем вы меня назначили проверяющим?

2020-07-08 17:49 UTC, ifuwmnn submitted a review, later dismissed

2020-07-09 19:03 UTC, NordScandinavian submitted a review, later dismissed

2020-07-10 19:30 UTC, YuriSilenok requested changes
Я не увидел отчета по методике тестирования "белый ящик", @Students-of-the-city-of-Kostroma/17-elite внимательнее проверяйте пожалуйста.
Пожалуйста, сделайте линк на задачу в атрибутах запроса.

2020-07-12 04:51 UTC, YuriSilenok reviewed
По текущему положению, вашу работу сначало должны проверить члены команды. Читайте чат.

2020-07-12 11:09 UTC, ifuwmnn submitted a review, later dismissed

2020-07-12 20:54 UTC, MyachevM approved these changes

2020-07-12 20:57 UTC, MyachevM submitted a review, later dismissed

2020-07-15 18:45 UTC, MyachevM submitted a review, later dismissed

2020-07-15 20:59 UTC, ifuwmnn submitted a review, later dismissed

2020-07-16 17:37 UTC, YuriSilenok requested changes
- ![image](https://user-images.githubusercontent.com/14871471/87703447-8d279680-c7a3-11ea-8f8f-0b3da6f9be06.png)
Этот раздел должен быть заполнен
- ![image](https://user-images.githubusercontent.com/14871471/87703523-afb9af80-c7a3-11ea-9b37-3aa67dfdb24a.png)
На графе не помечены регионы
- ![image](https://user-images.githubusercontent.com/14871471/87703749-fe674980-c7a3-11ea-897a-a29da74bfcc4.png)
Вы смогли создать экземпляр модели с такими значениями, вижу что у вас статус теста пройденный.

2020-07-17 19:29 UTC, badsster commented
- Изменила отчет
- Удалила предыдущий граф
- Добавила новый граф
- Добавила linked issues 

![image](https://user-images.githubusercontent.com/47521045/87812387-c118bf80-c868-11ea-9a48-5a0d74954b27.png)

![image](https://user-images.githubusercontent.com/47521045/87812349-ae9e8600-c868-11ea-8658-4d8bfc8e0f7c.png)
Тест с null был пройден

2020-07-18 12:38 UTC, ssas18 reviewed
Из вершины 5 должно выходить 2 ветки, если условие пройдет и если нет

2020-07-19 16:44 UTC, YuriSilenok requested changes

2020-07-19 16:44 UTC, YuriSilenok commented on Docs/UT_Update_CDiscipline/REPORT.md
> +| R2 | Attempt to enter null values | “Fullname”: null "Shortname": null "CycleOfDiscipline":null | false | false | Passed |
Получается, у сущности Дисциплина нет ограничений на атрибуты. Думаю стоит поднять баг.

2020-07-19 16:44 UTC, YuriSilenok commented on Docs/UT_Update_CDiscipline/REPORT.md
> +| R3 | Attempt to update doesn’t exist | “Fullname”:“Абвг” "Shortname":"Физ." "CycleOfDiscipline":"33" | false | false | Passed|
> Attempt to update doesn’t exist

Не совсем понимаю что вы здесь хотите сказать, можно ли попросить вас заполнить столбец Test title на русском. Что бы не создавать языкового барьера. В свою очередь я поправлю в образце английские слова на русские.

2020-07-19 16:44 UTC, YuriSilenok commented on Docs/UT_Update_CDiscipline/REPORT.md
> +![alt text](GRAPH.png "Управляющий граф")
Как уже упоминали, из вершины 5 должно выходить 2 ребра.

2020-07-19 18:49 UTC, badsster commented on Docs/UT_Update_CDiscipline/REPORT.md
> +| R3 | Attempt to update doesn’t exist | “Fullname”:“Абвг” "Shortname":"Физ." "CycleOfDiscipline":"33" | false | false | Passed|
- По Вашей просьбе изменила Test title на русский язык.

2020-07-19 18:58 UTC, badsster commented on Docs/UT_Update_CDiscipline/REPORT.md
> +![alt text](GRAPH.png "Управляющий граф")
- Сделала изменения с 5 вершиной. В отчет и в папку Docs загрузила новый граф.

2020-07-19 19:00 UTC, badsster commented on Docs/UT_Update_CDiscipline/REPORT.md
> +| R2 | Attempt to enter null values | “Fullname”: null "Shortname": null "CycleOfDiscipline":null | false | false | Passed |
- Скажите, пожалуйста, мне нужно поднимать этот баг? Если да, то как это сделать?

2020-07-20 12:12 UTC, YuriSilenok commented on Docs/UT_Update_CDiscipline/REPORT.md
> +| R2 | Attempt to enter null values | “Fullname”: null "Shortname": null "CycleOfDiscipline":null | false | false | Passed |
Да, поднимите баг. 
И укажите в нем, какие бы Вы ожидали ограничения на вводимые данные.
А так же укажите какой тест-комплект это затрагивает при исправлении этого бага.

2020-07-20 12:15 UTC, YuriSilenok requested changes
![image](https://user-images.githubusercontent.com/14871471/87936572-c0b43a80-ca9b-11ea-8e1d-eadb670e8454.png)
@Students-of-the-city-of-Kostroma/17-elite 
Чуть не проглядел грубую ошибку. Если условие составное, то каждое условие это вершина графа.

2020-07-22 12:56 UTC, YuriSilenok requested changes
Думаю теперь у Вас появилось больше регионов на графе.

2020-07-22 16:19 UTC, ssas18 reviewed
Я думаю если в графе количество маршрутов увеличилось, то оно должно увеличиться и в разделе "Маршруты на основании управляющего графа". Так же в графе вроде как название маршрута  не должно повторяться

2020-07-23 13:50 UTC, ssas18 requested changes
Под каждый маршрут тестирования нужен свой сценарий тестирования

2020-08-05 21:04 UTC, YuriSilenok commented
Работа готова к проверке?

2020-08-14 05:02 UTC, YuriSilenok commented
Задача с Вас снята, так как по ней давно не было активности.

2020-08-21 10:13 UTC, closed without merging