Исбравила критический сбой в связи учитель-нагрузка
Students-of-the-city-of-Kostroma/Student-timetable pull request #1305
Opened 2020-07-08 17:39 UTC by JennyShel18

https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/1285

2020-07-08 18:05 UTC, ssas18 submitted a review, later dismissed

2020-07-09 16:03 UTC, YuriSilenok requested changes
Я не думаю что дело в направлении реляционной связи, мне кажется старый вариант был правильным. Скорее всего вы пытаетесь во вторичный ключ записать данные, которые не соответствуют ни одному первичному ключу. Для этого нужно провести детальный дебаг. Посмотреть какие данные пытались записаться и какие данные существовали на текущий момент в рефдате.

2020-07-09 16:21 UTC, YuriSilenok commented
Хотя, может быть и Вы и правы в исправлениях, но нужно переворачивать все связи для AcademicLoad

2020-07-09 16:29 UTC, YuriSilenok commented
После [исправлений ](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1305/commits/0c04232be4e7abb73d7dfe6064ed61bcf61de8c6) количество сбоев снизилось с 36 до 29

2020-07-09 16:31 UTC, JennyShel18 commented
То есть, получается, мои исправления были верными?

2020-07-09 16:34 UTC, YuriSilenok approved these changes
[Сценарий](url) сбоя не воспроизводится.

2020-07-09 16:36 UTC, YuriSilenok commented
> То есть, получается, мои исправления были верными?

Думаю да, у меня возникли сомнения относительно того, что только одна связь была перевернута, я перевернул все остальные.

2020-07-09 16:37 UTC, JennyShel18 commented
Поняла, можно теперь решать мерж-конфликт?

2020-07-09 16:38 UTC, YuriSilenok commented
> Поняла, можно теперь решать мерж-конфликт?

да я вот смотрю на этот конфликт, ввел новые ограничения, но пока сам пытаюсь понять как решить это все дело, наверное банальным мержем

2020-07-09 16:43 UTC, YuriSilenok commented
![image](https://user-images.githubusercontent.com/14871471/87067204-69e96e00-c21c-11ea-8e64-c8e3500c0372.png)
странное поведение, при условии что нечего мержить и ребейзить

2020-07-09 16:44 UTC, YuriSilenok commented
Я пока отключу это ограничение

2020-07-09 16:44 UTC, JennyShel18 commented
Хорошо

2020-07-09 16:45 UTC, JennyShel18 commented
Теперь конфликтов нет

2020-07-09 16:46 UTC, YuriSilenok commented
Готово и я включил автоматическое удаление веток, отпиши, увидишь ли ты сразу что ветку удалилась после мержа

2020-07-09 16:47 UTC, JennyShel18 commented
Поняла, хорошо

2020-07-09 16:47 UTC, merged

2020-07-09 16:48 UTC, JennyShel18 commented
Ветка удалилась, все хорошо