Исправление сбоев в автотестах расположенных в UT_Update_CTeacher
Students-of-the-city-of-Kostroma/Student-timetable pull request #1309
Opened 2020-07-10 15:22 UTC by ssas18

#1036

2020-07-10 18:07 UTC, ZhizhikinIvan submitted a review, later dismissed

2020-07-12 08:03 UTC, ssas18 commented
@YuriSilenok , по данной задаче нет никакой активности 2 суток, никто ее не проверяет, что мне делать?

2020-07-12 10:39 UTC, YuriSilenok commented
> @YuriSilenok , по данной задаче нет никакой активности 2 суток, никто ее не проверяет, что мне делать?

К сожалению розги отменили.

2020-07-12 10:45 UTC, MyachevM commented
150 тестов прошли
29 провалились
не знаю, даст ли эта информация что-то полезное здесь

2020-07-12 11:01 UTC, YuriSilenok commented
> 150 тестов прошли
> 29 провалились
> не знаю, даст ли эта информация что-то полезное здесь

- если это была проверка работы, то пользуйтесь не комментарием а специальным блоком для проверяющих.
- ваша информация была бы полезнее, если бы вы предоставили скрин с азуры о том, что тесты пасяться.

2020-07-12 11:11 UTC, MyachevM reviewed
![изображение](https://user-images.githubusercontent.com/47633738/87244898-76064300-c449-11ea-963a-2f7fe2d10cf2.png)
151 тестов прошли
29 провалились

2020-07-13 08:49 UTC, MyachevM submitted a review, later dismissed

2020-07-13 20:19 UTC, JennyShel18 submitted a review, later dismissed

2020-07-15 18:08 UTC, YuriSilenok commented
> ![изображение](https://user-images.githubusercontent.com/47633738/87244898-76064300-c449-11ea-963a-2f7fe2d10cf2.png)
> 151 тестов прошли
> 29 провалились

Из этой информации важно прошли ли тесты над которыми ведутся работы

2020-07-15 18:16 UTC, YuriSilenok commented
> > ![изображение](https://user-images.githubusercontent.com/47633738/87244898-76064300-c449-11ea-963a-2f7fe2d10cf2.png)
> > 151 тестов прошли
> > 29 провалились
> 
> Из этой информации важно прошли ли тесты над которыми ведутся работы 

@MyachevM вы можете предоставить скрин статусов необходимых тестов?

2020-07-15 19:28 UTC, YuriSilenok requested changes
Пожалуйста, если вам дается замечание в [одном](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1295#issuecomment-658346090) запросе на проверку, задумайтесь, а не содержится ли эта ошибка в других запросах.  Экономьте свое и чужое время.

2020-07-18 08:03 UTC, ssas18 commented
@ifuwmnn , @ZhizhikinIvan , @Heriuple , @MyachevM , @NesgovorovVS , @NordScandinavian нужен ревью. пожалуйста

2020-07-19 09:18 UTC, NesgovorovVS submitted a review, later dismissed
Нужные тесты вроде прошли

2020-07-19 09:37 UTC, ssas18 commented
@ifuwmnn , @ZhizhikinIvan , @Heriuple , @MyachevM  , @NordScandinavian нужен ревью. пожалуйста

2020-07-19 18:21 UTC, YuriSilenok requested changes
Я не думаю что есть переход 13-14
![image](https://user-images.githubusercontent.com/14871471/87882022-d5de8a00-ca05-11ea-9e06-4387ea077bbf.png)

2020-07-20 12:11 UTC, YuriSilenok requested changes
Мне не хотелось бы проверять 2 раза одни и те же ошибки у одного и того же человека.
Отложите активность по этому запросу, пока мы не справимся с другим отчетом.

2020-07-20 12:11 UTC, YuriSilenok commented on Docs/UT_Update_CTeacher/REPORT.md
> +|R2|247_2|Изменить сведения в не пустой таблице |Rows.count = 5, но (string)this.Rows[i]["FullName"] != fullName AcademicDegree = "Валидные данные"; AcademicTitle = "Валидные данные"; MetodicalDays =
Кажется я уже видел эту обобщенную формулировку в другом отчете.

2020-07-20 14:11 UTC, ssas18 commented
Заморожено до решения схожих ошибок в другом отчете

2020-08-04 13:36 UTC, ssas18 commented
Ревью запрошено ошибочно

2020-08-05 21:00 UTC, YuriSilenok commented
> Ревью запрошено ошибочно
> 

Ничего страшного, ждём двух проверок от команды

2020-08-07 05:01 UTC, ssas18 commented
@Students-of-the-city-of-Kostroma/17-elite нужен ревью

2020-08-07 09:02 UTC, ssas18 commented
@YuriSilenok  В этой ветке нет активности неделю, прошу не удалять т.к я жду проверки от коллег

2020-08-07 09:21 UTC, ifuwmnn submitted a review, later dismissed

2020-08-07 09:53 UTC, Alphavite51 commented on Docs/UT_Update_CTeacher/REPORT.md
> +R1 = 0 - 1 - 14 - 15
А региона разве не " R " обозначаться должны

2020-08-07 09:57 UTC, Alphavite51 submitted a review, later dismissed
Извините у меня видимо что то подвисло и буквы не те показывало

2020-08-11 17:16 UTC, YuriSilenok requested changes
![image](https://user-images.githubusercontent.com/14871471/89927799-8ad42300-dc0f-11ea-9684-1dc62b5cc467.png)
Почему Вы удалили файлы которые не имеют отношения к вашей работе?

2020-08-11 17:23 UTC, YuriSilenok requested changes
![image](https://user-images.githubusercontent.com/14871471/89928371-675da800-dc10-11ea-89f5-1f9ee4fe01f7.png)
Как бы вы описываете входные параметры в предварительных условиях, почему?

2020-08-12 04:45 UTC, ssas18 commented
> ![image](https://user-images.githubusercontent.com/14871471/89927799-8ad42300-dc0f-11ea-9684-1dc62b5cc467.png)
> Почему Вы удалили файлы которые не имеют отношения к вашей работе?

Я подумал что я словил баг переходя от задачи #1280 в эту, поэтому и удалил, мне вернуть это обратно?

2020-08-12 12:52 UTC, Alphavite51 requested changes
R2 путь составлен не верно

2020-08-12 12:53 UTC, Alphavite51 approved these changes

2020-08-12 12:56 UTC, ssas18 commented
> R2 путь составлен не верно

А почему и где ошибка можно узнать пожалуйста

2020-08-12 13:04 UTC, Alphavite51 commented
> > R2 путь составлен не верно
> 
> А почему и где ошибка можно узнать пожалуйста

Открыл не те изменения, извиняюсь

2020-08-12 13:05 UTC, Alphavite51 submitted a review, later dismissed

2020-08-12 13:21 UTC, NesgovorovVS submitted a review, later dismissed
Разметка кода верна, граф составлен верно, маршруты тоже правильно составлены, сценарии соответствуют маршрутам

2020-08-13 14:53 UTC, YuriSilenok requested changes
> Ввод коректных данных, при условии, что они не дублируют данные других экземпляров

А как тогда эти данные будут найдены, если переданные данные ни с чем не совпадают, что будет изменено?

2020-08-14 07:25 UTC, ssas18 commented
> ктных данных, при условии, что они не дублируют данные других экземпляров



> > Ввод коректных данных, при условии, что они не дублируют данные других экземпляров
> 
> А как тогда эти данные будут найдены, если переданные данные ни с чем не совпадают, что будет изменено?

Имелось в виду что мы  не меняем fullname преподавателя, а все остальные данные меняем

2020-08-14 07:35 UTC, YuriSilenok commented
![image](https://user-images.githubusercontent.com/14871471/90225263-b4609a80-de19-11ea-8857-352bac0cb525.png)
Но здесь об этом не указано, постарайтесь меньше оставлять в голове. Сценарии не должны трактоваться двусмысленно.

2020-08-14 07:36 UTC, ssas18 commented
> ![image](https://user-images.githubusercontent.com/14871471/90225263-b4609a80-de19-11ea-8857-352bac0cb525.png)
> Но здесь об этом не указано, постарайтесь меньше оставлять в голове. Сценарии не должны трактоваться двусмысленно.

Да, хорошо

2020-08-14 07:50 UTC, YuriSilenok requested changes
![image](https://user-images.githubusercontent.com/14871471/90226641-f38feb00-de1b-11ea-9295-bad79b20e484.png)
Чутка уехала первая строка

2020-08-14 09:43 UTC, YuriSilenok reviewed
Попробуйте привести тесты в соответствие.

2020-08-14 09:44 UTC, YuriSilenok commented
я имею ввиду приступайте к автотестам, думаю появится ошибка в процессе

2020-08-15 06:25 UTC, ssas18 commented
> я имею ввиду приступайте к автотестам, думаю появится ошибка в процессе

То есть мне надо сделать автотесты такими, какие описаны у меня в отчете?

2020-08-15 18:27 UTC, YuriSilenok commented
Да

2020-08-16 09:59 UTC, ssas18 commented
Та же проблема что и в #1295

2020-08-17 11:06 UTC, Alphavite51 submitted a review, later dismissed

2020-08-18 09:20 UTC, ssas18 commented
В первом автотесте происходит такое исключение
![image](https://user-images.githubusercontent.com/47377817/90495317-248a5b80-e14d-11ea-9a26-ec0f933f0d10.png)
я правильно понимаю что тоже жду #1323 ?

2020-08-18 09:26 UTC, YuriSilenok commented
> В первом автотесте происходит такое исключение
> ![image](https://user-images.githubusercontent.com/47377817/90495317-248a5b80-e14d-11ea-9a26-ec0f933f0d10.png)
> я правильно понимаю что тоже жду #1323 ?

У вас два пути:
- ждать исправление бага - долгий вариант
- предварительно очистить таблицы, в которых используются преподаватели - быстрый вариант, найти по реляционным связям эти таблицы и очистить предварительно их

2020-08-18 12:59 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +            Assert.IsTrue((refData.CInstitute.Rows.Count == 0) && (refData.CTeacher.Rows.Count == 0));
Не стоит объединять проверки. Лучше их делать отдельно и для каждого написать комментарий для случая сбоя в этом месте.

2020-08-18 14:59 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +            Assert.IsTrue(refData.CInstitute.Rows.Count == 0, "Не удалось Очистить таблицу Институт");
Подобные проверки нужно выполнять сразу после действия. так как во время следующего удаления, может произойти исключение и сообщение не будет получено что таблица очищена.

2020-08-19 06:55 UTC, YuriSilenok requested changes
Проблема в тесте 2

2020-08-19 06:55 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +        public void Task_247_2()
Мне кажется этот тест пойдет по маршруту R1, а по отчету должен пойти по маршруту R2

2020-08-21 10:59 UTC, YuriSilenok requested changes
Думаю что проблема второго  теста еще не решена.

2020-08-21 10:59 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +            tcher1.Weekends = "Пт";
что-то не удаляемое, похоже

2020-08-21 11:09 UTC, ssas18 commented
> Думаю что проблема второго теста еще не решена.

Этот тест должен четко проходить по данному маршруту R2 = 0 - 1 - 2 - 1 - 14 - 15, или же допускается несколько итераций в 1 - 2 - 1 - 14?

2020-08-21 15:06 UTC, YuriSilenok commented
> > Думаю что проблема второго теста еще не решена.
> 
> Этот тест должен четко проходить по данному маршруту R2 = 0 - 1 - 2 - 1 - 14 - 15, или же допускается несколько итераций в 1 - 2 - 1 - 14?

можно и несколько, главное суть теста.

2020-08-23 12:41 UTC, ssas18 commented
> > > Думаю что проблема второго теста еще не решена.
> > 
> > 
> > Этот тест должен четко проходить по данному маршруту R2 = 0 - 1 - 2 - 1 - 14 - 15, или же допускается несколько итераций в 1 - 2 - 1 - 14?
> 
> можно и несколько, главное суть теста.

Хорошо, оставлю несколько итераций

2020-08-24 06:43 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +        public void Task_247_3()//изменение когда атрибуты не повторяются (ФИО изменить не возможно)
`//изменение когда атрибуты не повторяются (ФИО изменить не возможно)` - это мусор. Уберите все лишние комментарии, оставьте только то, что считаете нужным

2020-08-24 06:50 UTC, YuriSilenok requested changes
Не могу пока принять, так как тесты сыпятся
![image](https://user-images.githubusercontent.com/14871471/91012709-32c5f500-e5ef-11ea-88df-6bb6bf6b88b0.png)
Если есть возможность, посмотрите в чем дело.

2020-08-24 07:26 UTC, YuriSilenok commented
Я думаю зря вы закомментрировали, верните как было

2020-08-24 07:28 UTC, YuriSilenok requested changes
```
2020-08-24T06:49:14.1515933Z Failed   Task_247_1
2020-08-24T06:49:14.1516223Z Error Message:
2020-08-24T06:49:14.1516793Z  Unable to create instance of class UnitTestOfTimetableOfClasses.UT_Update_CTeacher. Error: System.Exception: РњРѕР¶РЅРѕ РёСЃРїРѕР»СЊР·РѕРІР°С‚СЊ С‚РѕР»СЊРєРѕ СЂСѓСЃСЃРєРёРµ Р±СѓРєРІС‹ .
2020-08-24T06:49:14.1517362Z Stack Trace:
2020-08-24T06:49:14.1517971Z     at LibOfTimetableOfClasses.MAcademicLoad.set_Teacher(String value) in D:\a\1\s\LibOfTimetableOfClasses\MAcademicLoad.cs:line 111
2020-08-24T06:49:14.1518813Z    at LibOfTimetableOfClasses.RefData.InitAcademicLoad() in D:\a\1\s\LibOfTimetableOfClasses\RefData.cs:line 210
2020-08-24T06:49:14.1519504Z    at LibOfTimetableOfClasses.RefData.InitData() in D:\a\1\s\LibOfTimetableOfClasses\RefData.cs:line 191
2020-08-24T06:49:14.1520141Z    at LibOfTimetableOfClasses.RefData..ctor() in D:\a\1\s\LibOfTimetableOfClasses\RefData.cs:line 53
2020-08-24T06:49:14.1520857Z    at UnitTestOfTimetableOfClasses.UT_Update_CTeacher..ctor() in D:\a\1\s\UnitTestOfTimetableOfClasses\UT_Update_CTeacher.cs:line 10
2020-08-24T06:49:14.1521396Z Failed   Task_247_2
2020-08-24T06:49:14.1521663Z Error Message:
2020-08-24T06:49:14.1522251Z  Unable to create instance of class UnitTestOfTimetableOfClasses.UT_Update_CTeacher. Error: System.Exception: РњРѕР¶РЅРѕ РёСЃРїРѕР»СЊР·РѕРІР°С‚СЊ С‚РѕР»СЊРєРѕ СЂСѓСЃСЃРєРёРµ Р±СѓРєРІС‹ .
2020-08-24T06:49:14.1522819Z Stack Trace:
2020-08-24T06:49:14.1523335Z     at LibOfTimetableOfClasses.MAcademicLoad.set_Teacher(String value) in D:\a\1\s\LibOfTimetableOfClasses\MAcademicLoad.cs:line 111
2020-08-24T06:49:14.1524075Z    at LibOfTimetableOfClasses.RefData.InitAcademicLoad() in D:\a\1\s\LibOfTimetableOfClasses\RefData.cs:line 210
2020-08-24T06:49:14.1524767Z    at LibOfTimetableOfClasses.RefData.InitData() in D:\a\1\s\LibOfTimetableOfClasses\RefData.cs:line 191
2020-08-24T06:49:14.1525398Z    at LibOfTimetableOfClasses.RefData..ctor() in D:\a\1\s\LibOfTimetableOfClasses\RefData.cs:line 53
2020-08-24T06:49:14.1526114Z    at UnitTestOfTimetableOfClasses.UT_Update_CTeacher..ctor() in D:\a\1\s\UnitTestOfTimetableOfClasses\UT_Update_CTeacher.cs:line 10
2020-08-24T06:49:14.1526647Z Failed   Task_247_3
2020-08-24T06:49:14.1526917Z Error Message:
2020-08-24T06:49:14.1527504Z  Unable to create instance of class UnitTestOfTimetableOfClasses.UT_Update_CTeacher. Error: System.Exception: РњРѕР¶РЅРѕ РёСЃРїРѕР»СЊР·РѕРІР°С‚СЊ С‚РѕР»СЊРєРѕ СЂСѓСЃСЃРєРёРµ Р±СѓРєРІС‹ .
2020-08-24T06:49:14.1528076Z Stack Trace:
2020-08-24T06:49:14.1528653Z     at LibOfTimetableOfClasses.MAcademicLoad.set_Teacher(String value) in D:\a\1\s\LibOfTimetableOfClasses\MAcademicLoad.cs:line 111
2020-08-24T06:49:14.1529403Z    at LibOfTimetableOfClasses.RefData.InitAcademicLoad() in D:\a\1\s\LibOfTimetableOfClasses\RefData.cs:line 210
2020-08-24T06:49:14.1530091Z    at LibOfTimetableOfClasses.RefData.InitData() in D:\a\1\s\LibOfTimetableOfClasses\RefData.cs:line 191
2020-08-24T06:49:14.1530730Z    at LibOfTimetableOfClasses.RefData..ctor() in D:\a\1\s\LibOfTimetableOfClasses\RefData.cs:line 53
2020-08-24T06:49:14.1531450Z    at UnitTestOfTimetableOfClasses.UT_Update_CTeacher..ctor() in D:\a\1\s\UnitTestOfTimetableOfClasses\UT_Update_CTeacher.cs:line 10
2020-08-24T06:49:14.1531987Z Failed   Task_247_4
2020-08-24T06:49:14.1532252Z Error Message:
2020-08-24T06:49:14.1532837Z  Unable to create instance of class UnitTestOfTimetableOfClasses.UT_Update_CTeacher. Error: System.Exception: РњРѕР¶РЅРѕ РёСЃРїРѕР»СЊР·РѕРІР°С‚СЊ С‚РѕР»СЊРєРѕ СЂСѓСЃСЃРєРёРµ Р±СѓРєРІС‹ .
2020-08-24T06:49:14.1533402Z Stack Trace:
2020-08-24T06:49:14.1533915Z     at LibOfTimetableOfClasses.MAcademicLoad.set_Teacher(String value) in D:\a\1\s\LibOfTimetableOfClasses\MAcademicLoad.cs:line 111
2020-08-24T06:49:14.1534656Z    at LibOfTimetableOfClasses.RefData.InitAcademicLoad() in D:\a\1\s\LibOfTimetableOfClasses\RefData.cs:line 210
2020-08-24T06:49:14.1535459Z    at LibOfTimetableOfClasses.RefData.InitData() in D:\a\1\s\LibOfTimetableOfClasses\RefData.cs:line 191
2020-08-24T06:49:14.1536095Z    at LibOfTimetableOfClasses.RefData..ctor() in D:\a\1\s\LibOfTimetableOfClasses\RefData.cs:line 53
2020-08-24T06:49:14.1536815Z    at UnitTestOfTimetableOfClasses.UT_Update_CTeacher..ctor() in D:\a\1\s\UnitTestOfTimetableOfClasses\UT_Update_CTeacher.cs:line 10
```

Эти сбои относятся к вашим тестам, проведите отладку и поясните в чем проблема

2020-08-24 07:29 UTC, ssas18 commented
> Я думаю зря вы закомментировали, верните как было

Хорошо, я просто подумал что очистка 2 таблиц как-то на это влияет, решил проверить
может помочь обновление текущей ветки до дева?

2020-08-24 07:31 UTC, YuriSilenok commented
> > Я думаю зря вы закомментировали, верните как было
> 
> Хорошо, я просто подумал что очистка 2 таблиц как-то на это влияет, решил проверить
> может помочь обновление текущей ветки до дева?

обновление не поможет, там такой-же ужас творится. начали работать ограничения моделей.

2020-08-24 07:32 UTC, YuriSilenok commented
исходя из сообщений и номеров строк, могу предположить что это происходит в момент создание экземпляром каких-то сущностей.

2020-08-24 07:37 UTC, ssas18 commented
> исходя из сообщений и номеров строк, могу предположить что это происходит в момент создание экземпляром каких-то сущностей.

Хорошо, а как мне это тестировать?
ведь у меня тесты проходят

2020-08-24 07:39 UTC, YuriSilenok commented
> > исходя из сообщений и номеров строк, могу предположить что это происходит в момент создание экземпляром каких-то сущностей.
> 
> Хорошо, а как мне это тестировать?
> ведь у меня тесты проходят

И сразу скрин обозревателя тестов

2020-08-24 07:41 UTC, ssas18 commented
> > > исходя из сообщений и номеров строк, могу предположить что это происходит в момент создание экземпляром каких-то сущностей.
> > 
> > 
> > Хорошо, а как мне это тестировать?
> > ведь у меня тесты проходят
> 
> И сразу скрин обозревателя тестов

![image](https://user-images.githubusercontent.com/47377817/91017061-635d5d00-e5f6-11ea-846c-11f171f6bd9c.png)

2020-08-24 07:42 UTC, YuriSilenok commented
сам посмотрел

2020-08-24 07:43 UTC, YuriSilenok commented
Вам нужно мерждить дев в вашу ветку

2020-08-24 07:44 UTC, ssas18 commented
> Вам нужно мерждить дев в вашу ветку

 Но это, как я понимаю, пока еще не зачет, по ней еще будут работы, да?

2020-08-24 07:45 UTC, YuriSilenok commented
> > Вам нужно мерждить дев в вашу ветку
> 
> Но это, как я понимаю, пока еще не зачет, по ней еще будут работы, да?

осталось только добиться того, что бы тесты прошли удачно.
ваша ветка существенно отстала. по этому возникает такая ситуация.
На азуре проходит проверка как раз в том состоянии, как будто вы смержили дев вашу ветку.

2020-08-24 07:56 UTC, ssas18 commented
> > > Вам нужно мерждить дев в вашу ветку
> > 
> > 
> > Но это, как я понимаю, пока еще не зачет, по ней еще будут работы, да?
> 
> осталось только добиться того, что бы тесты прошли удачно.
> ваша ветка существенно отстала. по этому возникает такая ситуация.
> На азуре проходит проверка как раз в том состоянии, как будто вы смержили дев вашу ветку.

Вроде как они более не фейлятся

2020-08-24 09:52 UTC, YuriSilenok commented
очень странное поведение. вы ведь ничего существенного не изменили.

2020-08-24 10:04 UTC, ssas18 commented
> очень странное поведение. вы ведь ничего существенного не изменили.

Я замержил дев в эту ветку через гит десктоп, но тут ничего не отобразилось и я решил сделать комит и посмотреть сработает ли так, сработало

2020-08-25 10:21 UTC, YuriSilenok requested changes

2020-08-25 10:21 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +            Assert.IsTrue(refData.CInstitute.Rows.Count != 0, "Таблица институт пуста");
> они не дублируют данные других экземпляров

как вы можете быть уверены в том, что данные что-то не дублируют, если у вас в таблице есть неизвестные данные, которые вы ни как не анализируете?

2020-08-25 11:57 UTC, ssas18 commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +            Assert.IsTrue(refData.CInstitute.Rows.Count != 0, "Таблица институт пуста");
Мне нужно сначала очистить таблицу?

2020-08-25 12:12 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +            Assert.IsTrue(refData.CInstitute.Rows.Count != 0, "Таблица институт пуста");
Это будет самый простой вариант

2020-08-26 06:59 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +            Assert.AreEqual(expected, actual, " Удалось Изменить сведения в пустой таблице");
А есть сакральный смысл использования метода `AreEqual` там, где ожидаемый результат равен false?

2020-08-26 07:03 UTC, ssas18 commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +            Assert.AreEqual(expected, actual, " Удалось Изменить сведения в пустой таблице");
AreEqual используется для того что бы сравнивать 2 значения, и как мне казалось без разницы какие в нем аргументы, или для false есть что-то получше ?

2020-08-26 07:08 UTC, YuriSilenok requested changes
Нужно перепроверить старый код и формулировки, не опирайтесь на старые тесты, не факт что их написали верно, они мной не проверялись.

2020-08-26 07:08 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
>              MTeacher tcher1 = new MTeacher("Киприна", "Людмила", "Юрьевна", "КН", "Доц", "ИАСТ", "Пт, Ср", "Пн, Вт", "Сб");
Зачем нам второго преподавателя добавлять в этом тесте?

2020-08-26 07:08 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
>          /// Ввод корректных данных, при условии, что данная запись полность. дублирует другую запись
Я не вижу здесь **полного** дублирования записи

2020-08-26 07:09 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +            Assert.AreEqual(expected, actual, " Удалось Изменить сведения в пустой таблице");
есть, IsFalse

2020-08-26 07:10 UTC, ssas18 commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +            Assert.AreEqual(expected, actual, " Удалось Изменить сведения в пустой таблице");
Хорошо, будет исправлено

2020-08-28 09:16 UTC, YuriSilenok requested changes
Мне кажется вы запросили повторную проверку не доделав сценарии, или это конечный набор сценариев?

2020-08-28 09:16 UTC, YuriSilenok commented on Docs/UT_Update_CTeacher/REPORT.md
> +|R4|247_4|Ввод корректных данных, при условии, что вводимое ученое звание преподавателя не существует|AcademicDegree = "КН"; AcademicTitle = "Доц"; MetodicalDays = "Пн, Вт";  Windows = "Ср, Чт, Пт" W
два теста с одинаковым ID?

2020-08-28 09:50 UTC, ssas18 commented on Docs/UT_Update_CTeacher/REPORT.md
> +|R4|247_4|Ввод корректных данных, при условии, что вводимое ученое звание преподавателя не существует|AcademicDegree = "КН"; AcademicTitle = "Доц"; MetodicalDays = "Пн, Вт";  Windows = "Ср, Чт, Пт" W
Это был конечный набор сценариев, не заметил ошибку, сейчас исправлю

2020-08-28 11:26 UTC, YuriSilenok commented on Docs/UT_Update_CTeacher/REPORT.md
> +|R4|247_4|Ввод корректных данных, при условии, что вводимое ученое звание преподавателя не существует|AcademicDegree = "КН"; AcademicTitle = "Доц"; MetodicalDays = "Пн, Вт";  Windows = "Ср, Чт, Пт" W
Формулировка последнего теста навела меня на мысль что реляционные связи не были проверены.
Вы тестируете таблицу, у которой больше всего связей.
Я вижу здесь 4 таких связи, и получается что аж граф изменится.
![image](https://user-images.githubusercontent.com/14871471/91555857-7182e480-e93a-11ea-8437-a1479567d75e.png)

2020-08-28 11:29 UTC, ssas18 commented on Docs/UT_Update_CTeacher/REPORT.md
> +|R4|247_4|Ввод корректных данных, при условии, что вводимое ученое звание преподавателя не существует|AcademicDegree = "КН"; AcademicTitle = "Доц"; MetodicalDays = "Пн, Вт";  Windows = "Ср, Чт, Пт" W
Вы наверное это про другой автотест, не про update_cteacher

2020-08-28 11:36 UTC, YuriSilenok commented on Docs/UT_Update_CTeacher/REPORT.md
> +|R4|247_4|Ввод корректных данных, при условии, что вводимое ученое звание преподавателя не существует|AcademicDegree = "КН"; AcademicTitle = "Доц"; MetodicalDays = "Пн, Вт";  Windows = "Ср, Чт, Пт" W
ох да, я похоже запутался. сейчас пересмотрю еще раз.

2020-08-28 11:38 UTC, YuriSilenok commented on Docs/UT_Update_CTeacher/REPORT.md
> +|R4|247_4|Ввод корректных данных, при условии, что вводимое ученое звание преподавателя не существует|AcademicDegree = "КН"; AcademicTitle = "Доц"; MetodicalDays = "Пн, Вт";  Windows = "Ср, Чт, Пт" W
![image](https://user-images.githubusercontent.com/14871471/91556874-210c8680-e93c-11ea-9fb6-3bfbafca3b13.png)
да, похоже все впорядке.

2020-08-28 11:50 UTC, YuriSilenok requested changes
Просмотрел все тесты до конца, дальнейшая проверка в этом запросе будет производится только по новым изменениям.

2020-08-28 11:50 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +            Assert.IsTrue(refData.CInstitute.Rows.Count != 0, "Таблица институт пуста");
я не особо понял, зачем мы эту проверку делаем сходу, перед очисткой таблицы, какая нам разница, пустая она или нет перед очисткой?

2020-08-28 11:50 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +            bool actual = refData.CTeacher.Update(tcher);
`/// Ввод коректных данных, при условии, что они не дублируют данные других экземпляров`

а разве при обновлении самого себя на себя он не является полным дубликатом самому себе?

2020-08-28 11:50 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +            Assert.IsFalse(actual, "Ввод корректных данных, при условии, что данная запись полность. дублирует другую запись не произошел");
лучше написать тут что-то типа
Отсутствует реляционная связь между Преподавателем и ученой степенью.

2020-08-28 11:50 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +            Assert.IsFalse(actual, "Ввод корректных данных, при условии, что данная запись полность. дублирует другую запись не произошел");
лучше написать тут что-то типа
Отсутствует реляционная связь между Преподавателем и ученым званием.

2020-08-28 17:13 UTC, ifuwmnn approved these changes, later dismissed

2020-08-29 10:40 UTC, NordScandinavian approved these changes, later dismissed
Пути R3 и R4, вероятно, надо поменять местами на графе

2020-08-29 10:43 UTC, ssas18 commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +            Assert.IsTrue(refData.CInstitute.Rows.Count != 0, "Таблица институт пуста");
Исправлено

2020-08-29 10:43 UTC, ssas18 commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +            Assert.IsFalse(actual, "Ввод корректных данных, при условии, что данная запись полность. дублирует другую запись не произошел");
Исправлено

2020-08-29 10:43 UTC, ssas18 commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +            Assert.IsFalse(actual, "Ввод корректных данных, при условии, что данная запись полность. дублирует другую запись не произошел");
Исправлено

2020-08-29 10:44 UTC, ssas18 commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +            bool actual = refData.CTeacher.Update(tcher);
Исправлено, надеюсь правильно

2020-08-29 18:34 UTC, YuriSilenok commented
Проверять буду в понедельник.

2020-08-29 19:58 UTC, Alphavite51 commented
Ветка смержена, можете продолжать работу, вам нужно мержить dev в вашу ветку!

2020-08-30 22:18 UTC, NesgovorovVS approved these changes, later dismissed

2020-08-31 14:05 UTC, ssas18 commented
начал исправление над сбоями автотестов здесь

2020-09-02 13:26 UTC, ssas18 commented
@YuriSilenok , очень жду Вашей проверки т.к в моих задачах нет активности уже 2 суток

2020-09-03 08:01 UTC, NesgovorovVS approved these changes, later dismissed

2020-09-03 15:59 UTC, YuriSilenok commented
Можно не переживать, терпеть задачи и запросы не снимутся, пока по запросу есть запрос на проверку у меня

2020-09-04 08:12 UTC, MyachevM approved these changes, later dismissed

2020-09-04 09:44 UTC, YuriSilenok requested changes
Проверка маршрутов
1 - пройден
2 - пройден
3 - пройден
4 - пройден - но сбой произошел на 4 вершине. либо переделывать графи так далее, либо испольщовать методы BeginEdit(); EndEdit();AcceptChanges(); в тестируемом методе. Тогда сбой будет происходить всегда на методе EndEdit
остальное нужно проверить по аналогии.
Выполняйте тесты в отладочном режиме и по шагам проходите тестируемый метод. смотрите соответствие маршрута и фактического поведение программы

2020-09-05 13:52 UTC, ifuwmnn approved these changes, later dismissed

2020-09-05 21:07 UTC, MyachevM approved these changes, later dismissed

2020-09-06 05:02 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1341']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-07 14:11 UTC, NesgovorovVS approved these changes, later dismissed
Маршруты построены правильно, тесты проверку прошли.

2020-09-07 14:29 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1341']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-07 18:13 UTC, NordScandinavian submitted a review, later dismissed

2020-09-08 12:06 UTC, Alphavite51 requested changes
У вас есть непроверенные запросы ['#86', '#87']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-08 12:15 UTC, ssas18 commented
> У вас есть непроверенные запросы ['#86', '#87']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

Это относится к другому репозиторию и никак Вашу деятельность не тормозит, и зачем ты выполняешь задачи скрипта?

2020-09-08 12:18 UTC, Alphavite51 commented
> > У вас есть непроверенные запросы ['#86', '#87']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса
> 
> Это относится к другому репозиторию и никак Вашу деятельность не тормозит, и зачем ты выполняешь задачи скрипта?

чтобы у профиля со скриптом небыло активности

2020-09-08 12:18 UTC, Alphavite51 approved these changes, later dismissed

2020-09-08 12:21 UTC, ssas18 commented
> > > У вас есть непроверенные запросы ['#86', '#87']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса
> > 
> > 
> > Это относится к другому репозиторию и никак Вашу деятельность не тормозит, и зачем ты выполняешь задачи скрипта?
> 
> чтобы у профиля со скриптом небыло активности

Ответил в #1294 , давайте не будем плодить фейковую активность

2020-09-08 15:23 UTC, ZhizhikinIvan approved these changes, later dismissed

2020-09-08 17:56 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы []. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-08 17:56 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1335']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-09 17:34 UTC, YuriSilenok requested changes
Так же не увидел проверок в подготовке данных.

2020-09-09 17:34 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +            setupData();
Зачем добавлять данные, чтобы сразу их удалить?

2020-09-09 17:55 UTC, ssas18 commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +            setupData();
По другому не работало)
удаил удаление)

2020-09-09 18:13 UTC, YuriSilenok requested changes

2020-09-09 18:13 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +            bool actual1 = refData.CAcademicDegree.Insert(mAcademicDegree);
Где проверка на то, что данные добавились?

2020-09-09 18:13 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +            setupData();
Если что-то не работает, нужно выяснять причину.  Я думаю у вас были перепутаны строки. Вы хотели почистить таблицу и наполнить её свежими текстовыми данными.

2020-09-09 18:16 UTC, ssas18 commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +            bool actual1 = refData.CAcademicDegree.Insert(mAcademicDegree);
я проверил, таблица изначально пуста
так что нет смысла ее чистить

2020-09-09 18:17 UTC, ssas18 commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +            setupData();
я проверил, таблица изначально пуста и ее незачем чистить

2020-09-09 20:12 UTC, NesgovorovVS approved these changes, later dismissed
Запрошенные изменения были исправлены. В остальном вроде верно.

2020-09-10 07:03 UTC, YuriSilenok approved these changes, later dismissed
Ну, только один небольшой косяк.
А так все хорошо.

2020-09-10 07:03 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +            bool expected = false;
неиспользуемая переменная `bool expected = false;`

2020-09-10 08:33 UTC, ifuwmnn approved these changes, later dismissed

2020-09-10 10:39 UTC, ssas18 commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +            bool expected = false;
нужно исправить перед мержем?

2020-09-10 10:43 UTC, Alphavite51 approved these changes, later dismissed

2020-09-10 10:44 UTC, ssas18 commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +            bool expected = false;
ну то есть исправить и смержить или исправить ждать Вашего ответа и мержить?

2020-09-10 12:36 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Update_CTeacher.cs
> +            bool expected = false;
исправить и мержить или запросить проверку, я быстро это проверю

2020-09-10 12:37 UTC, YuriSilenok approved these changes

2020-09-10 12:37 UTC, merged