Исправление сбоев в автотестах в файле UT_Delete_CInstitute
Students-of-the-city-of-Kostroma/Student-timetable pull request #1313
Opened 2020-07-13 08:46 UTC by NordScandinavian

2020-07-13 08:56 UTC, ssas18 reviewed
Нет отчетов по белому ящику

2020-07-13 10:53 UTC, ssas18 reviewed
Отчет должен находиться в директории проекта, там должно быть 3  файла, (2 скрина и сам отчет в расширении  markdown, посмотри пример Юрия Викторовичка

2020-07-17 16:45 UTC, ifuwmnn commented
Я не уверен но вроде в пути R2 ошибка? 
![image](https://user-images.githubusercontent.com/47635280/87810656-fff94600-c865-11ea-8b57-358e774bf71a.png)

2020-07-26 20:34 UTC, MyachevM reviewed
В пути R2 ошибка.
Мне кажется должно быть: R2=0-2-17-18

2020-07-27 18:57 UTC, MyachevM requested changes
В пути R2 ошибка.
Мне кажется должно быть: R2=0-2-17-18

2020-08-09 18:03 UTC, YuriSilenok commented
Задача с Вас снята, так как по ней давно не было активности.

2020-08-09 18:22 UTC, closed without merging