Create REPORT.md
Students-of-the-city-of-Kostroma/Student-timetable pull request #1314
Opened 2020-07-17 07:58 UTC by Heriuple

Создание отчета Белый ящик

2020-07-17 15:09 UTC, ssas18 reviewed
Отсутствует вывод, маршруты на основании управляющего графа построены немного не по шаблону, на графе не отображены 1 и 2 пункт, тоже наверное не критично

2020-07-26 20:27 UTC, MyachevM commented
На графе не отображен нулевой пункт, в коде не размечен 1 и 2 пункт.
Не совсем уверен, что из 9 пункта можно попасть в 11.

2020-07-26 20:29 UTC, MyachevM requested changes
На графе не отображен нулевой пункт, в коде не размечен 1 и 2 пункт.
Не совсем уверен, что из 9 пункта можно попасть в 11.

2020-07-26 20:29 UTC, MyachevM reviewed
На графе не отображен нулевой пункт, в коде не размечен 1 и 2 пункт.
Не совсем уверен, что из 9 пункта можно попасть в 11.

2020-08-09 18:03 UTC, YuriSilenok commented
Задача с Вас снята, так как по ней давно не было активности.

2020-08-09 18:22 UTC, closed without merging