AL-Repos-t: Убрал несколько лишних строк
Students-of-the-city-of-Kostroma/Student-timetable pull request #1317
Opened 2020-07-29 15:52 UTC by Alphavite51

2020-07-29 16:11 UTC, Alphavite51 commented
@ssas18 , @ifuwmnn  , @ZhizhikinIvan  , @Heriuple , @MyachevM  , @NordScandinavian  , @NesgovorovVS

2020-07-30 14:09 UTC, ifuwmnn submitted a review, later dismissed

2020-07-30 19:19 UTC, MyachevM submitted a review, later dismissed

2020-07-30 19:29 UTC, ssas18 requested changes
Твоя ветка не так называется, мержить надо в dev.
И для чего убран try catch?

2020-07-30 19:36 UTC, Alphavite51 commented
> Твоя ветка не так называется, мержить надо в dev.
> И для чего убран try catch?

try catch скрывает информацию о том, почему запись не обновлена, обрабатывать ошибку может вызывающий код.
куда надо мержить немного не понял,

2020-07-30 19:40 UTC, ssas18 commented
![image](https://user-images.githubusercontent.com/47377817/88966759-7f026b80-d2b5-11ea-8aaa-e204e7c72bec.png)
Почему твоя ветка называется именно так?

2020-07-30 19:42 UTC, Alphavite51 commented
> ![изображение](https://user-images.githubusercontent.com/47377817/88966759-7f026b80-d2b5-11ea-8aaa-e204e7c72bec.png)
> Почему твоя ветка называется именно так?

А как должна?

2020-07-30 19:49 UTC, ssas18 commented
> > ![изображение](https://user-images.githubusercontent.com/47377817/88966759-7f026b80-d2b5-11ea-8aaa-e204e7c72bec.png)
> > Почему твоя ветка называется именно так?
> 
> А как должна?

я так полагаю что-то вроде task-1312

2020-07-30 20:07 UTC, YuriSilenok commented
> > ![изображение](https://user-images.githubusercontent.com/47377817/88966759-7f026b80-d2b5-11ea-8aaa-e204e7c72bec.png)
> > Почему твоя ветка называется именно так?
> 
> А как должна?

Файл реадми в корне проекта прочитайте, он верен % на 80

2020-07-30 20:08 UTC, YuriSilenok commented
И веточки не забудьте удалить лишние потом

2020-07-31 10:48 UTC, closed without merging