Методические рекомендации к использованию метода тестирования "Белый ящик"
Students-of-the-city-of-Kostroma/Student-timetable pull request #1320
Opened 2020-07-31 10:42 UTC by YuriSilenok

2020-07-31 10:53 UTC, ssas18 requested changes
Желательно добавить нумерацию для облегчения указания недочетов и добавить пример в таблицу во избежание глупых ошибок и недопонимания

2020-07-31 16:37 UTC, YuriSilenok commented
> Желательно добавить нумерацию для облегчения указания недочетов

Думаю не стоит, так как при выпуске новой версии этого документа, нумерация может сбиться и это запутает. Но всегда можно цитировать часть этого документа. Я сделал документ более структурированным, что бы можно было проверять работы поэтапно. 

> добавить пример в таблицу во избежание глупых ошибок и недопонимания

Я добавил примеры к каждому пункту.

2020-07-31 17:08 UTC, NesgovorovVS requested changes
в 3-й строке "тестируемого когда", я так понимаю там "тестируемого кода" должно быть в файле "Update README.md"

2020-07-31 17:13 UTC, YuriSilenok commented
> тестируемого когда

Спасибо что нашли.
Но давайте сделаем это более правильно, мы можете начать обсуждение недостатков находящейся в строке или нескольких строк сразу, для этого нужно навести мышкой и нажать плюс. см снимок экрана
![image](https://user-images.githubusercontent.com/14871471/89059694-51c3c500-d36a-11ea-9bff-3f6b75208870.png)

2020-07-31 17:17 UTC, NesgovorovVS requested changes
Так правильно?

2020-07-31 17:17 UTC, NesgovorovVS commented on Docs/White-box/README.md
> +Отчет о тестировании должен содержать снимок тестируемого когда, начиная от заголовка, заканчивая последним оператором (скобкой). На снимке кода необходимо провести разметку кода по следующим правила
вместо "тестируемого когда" , я так понимаю должно было быть словосочетание "тестируемого кода"

2020-07-31 17:18 UTC, YuriSilenok commented
> Так правильно?

Да, совершенно верно.

2020-07-31 17:26 UTC, NesgovorovVS approved these changes

2020-07-31 17:26 UTC, YuriSilenok commented on Docs/White-box/README.md
> +Отчет о тестировании должен содержать снимок тестируемого когда, начиная от заголовка, заканчивая последним оператором (скобкой). На снимке кода необходимо провести разметку кода по следующим правила
Сделал исправления.
Если проблема устранена, нажмите кнопку `Resolve conversation`

2020-07-31 19:04 UTC, MyachevM commented on Docs/White-box/README.md
>  Постройте управляющий граф должен соответствовать свойствам КДА. Вершинами этого графа будут числовые метки из размеченного кода, а ребра будут соответствовать переходам от оператора к оператору. На
Опечатка в слове *регины* в последнем предложении.
Скорее всего, должно быть *регионы*.

2020-07-31 19:10 UTC, MyachevM commented on Docs/White-box/README.md
> +Рассчитайте кратчайшие маршруты по которым можно было бы обойти регионы. Для региона R1 это будет самый короткий маршрут, как правило он единственный на графе и будет содержать наименьшее количество
Опечатка *виде* "лестницы".
Скорее всего должно быть *в виде* "лестницы".

2020-07-31 19:25 UTC, MyachevM requested changes
Опечатка в слове *регины* в 22 строке, в последнем предложении.
Скорее всего, должно быть регионы.

Опечатка *виде* "лестницы" в 28 строке.
Скорее всего должно быть *в виде* "лестницы".

2020-08-01 10:25 UTC, Alphavite51 approved these changes

2020-08-01 12:44 UTC, ssas18 approved these changes

2020-08-01 15:41 UTC, ifuwmnn approved these changes

2020-08-09 18:03 UTC, YuriSilenok commented
Задача с Вас снята, так как по ней давно не было активности.

2020-08-09 18:23 UTC, YuriSilenok commented
Судя по тому, что кто хотел, тот ознакомился и дал добро, мержу в ветку дев

2020-08-09 18:23 UTC, merged