Исправлен сбой в автотестах расположенных в файле UT-Deleted-CTeacher
Students-of-the-city-of-Kostroma/Student-timetable pull request #1322
Opened 2020-08-01 12:13 UTC by MyachevM

#1281

2020-08-01 12:42 UTC, ssas18 requested changes
На скриншоте не пронумерованы операторы

2020-08-02 16:55 UTC, Alphavite51 submitted a review, later dismissed
Выглядит верно

2020-08-03 10:07 UTC, Alphavite51 reviewed
Второй (2) излишний

2020-08-04 10:52 UTC, MyachevM commented
> 
> 
> Второй (2) излишний

Не совсем понял твоего комментария

2020-08-04 13:34 UTC, ssas18 commented
> > Второй (2) излишний
> 
> Не совсем понял твоего комментария

Разметка с цифрой 2 в коде не нужна

2020-08-11 09:23 UTC, MyachevM commented
> 
> 
> > > Второй (2) излишний
> > 
> > 
> > Не совсем понял твоего комментария
> 
> Разметка с цифрой 2 в коде не нужна

Исправлено.

2020-08-11 15:39 UTC, Alphavite51 approved these changes

2020-08-16 11:30 UTC, ssas18 requested changes
Мало удалить, теперь надо переделать разметку кода и граф, т.к на графе присутствует цифра 2, а в разметке кода ее нет

2020-08-17 12:45 UTC, Alphavite51 submitted a review, later dismissed

2020-08-21 05:02 UTC, YuriSilenok commented
Задача с Вас снята, так как по ней давно не было активности.

2020-08-21 10:32 UTC, MyachevM commented
> 
> 
> Мало удалить, теперь надо переделать разметку кода и граф, т.к на графе присутствует цифра 2, а в разметке кода ее нет

Переделана разметка кода и граф, также переделан отчёт.

2020-08-21 10:44 UTC, ssas18 requested changes
Мне кажется должен быть еще один путь, повторяющий r4, но возвращающий false

2020-08-21 10:56 UTC, YuriSilenok requested changes
Какой-то странный переход между вершинами 6-8

2020-08-22 07:31 UTC, MyachevM commented
> 
> 
> Какой-то странный переход между вершинами 6-8

Что именно не так с этим переходом ?

2020-08-22 07:37 UTC, YuriSilenok commented
> > 
> > 
> > Какой-то странный переход между вершинами 6-8
> 
> Что именно не так с этим переходом ?

Меня одалевают эмоции от ваших вопросов, скажите мне, в какую сторону переход, от 6 к 8 или от 8 к 6 или в обе стороны? Деталь следующая моя проверка будет как положено после двух апрувов

2020-08-22 07:40 UTC, MyachevM commented
> 
> 
> > > Какой-то странный переход между вершинами 6-8
> > 
> > 
> > Что именно не так с этим переходом ?
> 
> Меня одалевают эмоции от ваших вопросов, скажите мне, в какую сторону переход, от 6 к 8 или от 8 к 6 или в обе стороны? Деталь следующая моя проверка будет как положено после двух апрувов

Упс, ошибочка вышла, сейчас исправлю
Не заметил, что нет указательной стрелки на переходе

2020-08-23 18:11 UTC, MyachevM commented
> 
> 
> Мне кажется должен быть еще один путь, повторяющий r4, но возвращающий false

Мне кажется, что такого пути не может быть, так как метод Delete должен отработать

2020-08-24 10:09 UTC, ssas18 commented
> > Мне кажется должен быть еще один путь, повторяющий r4, но возвращающий false
> 
> Мне кажется, что такого пути не может быть, так как метод Delete должен отработать

Мне тоже уже кажется что твой вариант верный, @YuriSilenok , не могли бы вы разрешить спорную ситуацию, нужен ли путь похожий на R4 но возвращающий false?

2020-08-24 13:29 UTC, Alphavite51 reviewed
Сначала идет номер региона потом уже идентификатор теста, затем "Идея теста"

2020-08-24 13:30 UTC, Alphavite51 requested changes
Сначала идет номер региона потом уже идентификатор теста, затем "Идея теста"

2020-08-25 08:02 UTC, MyachevM commented
> 
> 
> Сначала идет номер региона потом уже идентификатор теста, затем "Идея теста"

Исправлено

2020-08-25 11:02 UTC, YuriSilenok commented
> > Сначала идет номер региона потом уже идентификатор теста, затем "Идея теста"
> 
> Исправлено

Если вы считаете что вы исправили замечание конкретного человека, то должны запросить повторную проверку
![image](https://user-images.githubusercontent.com/14871471/91166804-9a596e80-e6db-11ea-9dc5-c597451fb181.png)

2020-08-28 09:06 UTC, YuriSilenok commented
Пока вы ждете одобрения членов команды, займитесь проверкой работ присланных Вам на проверку

2020-08-28 10:43 UTC, MyachevM commented
> 
> 
> Пока вы ждете одобрения членов команды, займитесь проверкой работ присланных Вам на проверку

Понял, так и сделаю

2020-08-29 10:36 UTC, NordScandinavian approved these changes, later dismissed

2020-08-29 10:41 UTC, Alphavite51 approved these changes, later dismissed

2020-08-29 18:32 UTC, YuriSilenok commented
Проверять буду в понедельник

2020-08-29 21:31 UTC, Alphavite51 approved these changes, later dismissed

2020-08-30 08:40 UTC, NordScandinavian approved these changes, later dismissed

2020-08-30 14:38 UTC, MyachevM commented
> 
> 
> Проверять буду в понедельник

Хорошо

2020-09-01 18:44 UTC, ssas18 requested changes
![image](https://user-images.githubusercontent.com/47377817/91892877-0ae42a80-ec9c-11ea-961c-20fcbc90aaa2.png)
Ты никак не отобразил в входных параметрах что происходит некорректное удаление преподавателя и непонятно что значит это " некорректное удаление преподавателя"
с несуществующим преподавателем то же самое

2020-09-04 06:43 UTC, ssas18 requested changes
А в чем теперь заключается невалидность данных?
![image](https://user-images.githubusercontent.com/47377817/92208097-249b9280-ee93-11ea-9b28-baf6b574b177.png)

2020-09-04 07:57 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1342', '#1335', '#1309', '#1295', '#1294', '#1228', '#1217']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-05 13:49 UTC, ifuwmnn requested changes
![image](https://user-images.githubusercontent.com/47635280/92306352-1898f900-ef97-11ea-86b6-590e9a4f5f7f.png)
Нужно переименовать тестовые сценарии в регионах R2 и R4, чтобы они отражали суть происходящего. И во входных параметрах нужно написать какие именно данные ты вводишь, а не просто корректны или некорректны они. Напиши также как ты писал в предварительных условиях.

2020-09-06 08:05 UTC, MyachevM commented
> 
> 
> У вас есть непроверенные запросы ['#1342', '#1335', '#1309', '#1295', '#1294', '#1228', '#1217']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

Проверил запросы

2020-09-06 11:41 UTC, ssas18 requested changes
Соглашусь с @ifuwmnn и добавлю что во входных параметрах тебе еще нужно отобразить название теста

2020-09-07 05:02 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1335']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-07 13:27 UTC, MyachevM commented
> 
> 
> У вас есть непроверенные запросы ['#1335']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

Проверено

2020-09-07 13:34 UTC, Alphavite51 commented on Docs/UT-Deleted-CTeacher/REPORT.md
> +| R2 | task-1281-2 | Удаление несуществующего преподавателя | FirstName = "Чередникова", SecondName = "Алла",  Patronymic = "Викторовна" |  | false |
почему нет "Входных параметров" в R под номерами 2 и 4?

2020-09-07 13:35 UTC, Alphavite51 requested changes
Добавьте пожалуйста входные параметры, оставил комментарий

2020-09-07 14:29 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1341']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-07 18:02 UTC, NordScandinavian commented
Соглашусь с коллегами, необходимо: 

- переименовать тестовые сценарии в регионах R2 и R4, чтобы они отражали суть 

- во входных параметрах R1 необходимо указать именно вводимые данные, а не их корректность или некорректность, 

- Добавить входные параметры для R2 и R4, по тому же принципу, что и R1

2020-09-08 07:57 UTC, ssas18 requested changes
Тест с данными параметрами не пройдет т.к есть ограничения на то что первая буква всегда должна быть заглавной
![image](https://user-images.githubusercontent.com/47377817/92449045-1ff01a80-f1c2-11ea-99b7-d157e15ddc00.png)

2020-09-08 11:59 UTC, ifuwmnn requested changes
![image](https://user-images.githubusercontent.com/47635280/92473700-a0734300-f1e3-11ea-833d-62b8d1aa5368.png)
И скорее всего в R3 во входных параметрах, нужно указать тоже самое, что и в предварительном условии

2020-09-08 17:20 UTC, Alphavite51 requested changes
![image](https://user-images.githubusercontent.com/47320668/92507911-653b3900-f210-11ea-93ec-c3e4dc7667c9.png)
Все еще с маленькой буквы

2020-09-08 17:24 UTC, ssas18 requested changes
к R2 это тоже отностится, но не надо просто их менять на заглавные тк входные данные не будут совпадать с идеей теста, так же согласен с замечанием @ifuwmnn

2020-09-08 17:56 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы []. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-08 17:56 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1335', '#1294', '#1217']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-09 12:20 UTC, YuriSilenok commented
Баг в скрипте исправил, должен нормально работать сейчас

2020-09-09 12:21 UTC, YuriSilenok commented
Не хорошо, сначала запрашивать проверку, а потом выкатывать обновления, вот как сейчас, я же смотрю уже

2020-09-09 12:22 UTC, YuriSilenok commented
Или это исправления не по моим комментариям относятся, тогда все хорошо

2020-09-09 12:22 UTC, MyachevM commented
> 
> 
> Не хорошо, сначала запрашивать проверку, а потом выкатывать обновления, вот как сейчас, я же смотрю уже

Извиняюсь, сначала надо было выкатить обновление, а потом запросить проверку

2020-09-09 12:25 UTC, ssas18 requested changes
В чем теперь заключается разница между 1281-2 и 1281-4?
Они оба удаляют несуществующего преподавателя

2020-09-09 12:26 UTC, YuriSilenok requested changes
![image](https://user-images.githubusercontent.com/14871471/92597946-bef34000-f2b0-11ea-8ca5-80d750c9862e.png)
1. Сведений недостаточно что бы сказать что удаление произойдет
2. что значит некорректное, нарушается какое-то ограничение, какое?

2020-09-09 12:35 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1335']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-10 08:32 UTC, ifuwmnn requested changes
Тебе нужно чтобы во 2-ом регионе предварительное условие было пустым.

2020-09-10 08:35 UTC, YuriSilenok commented
> Тебе нужно чтобы во 2-ом регионе предварительное условие было пустым.

Если вы имеете ввиду что таблица должна быть пустой, то нет, в таблице данные должны быть, но данные которые нужно удалить в таблице не должно быть.

2020-09-10 08:50 UTC, Alphavite51 requested changes
Согласен с коллегами выше, добавить нечего

2020-09-10 08:52 UTC, YuriSilenok commented
> Согласен с коллегами выше, добавить нечего

У нас тут дискуссия, значит есть две стороны, так с кем Вы согласны или это очередная отписка?

2020-09-10 10:40 UTC, Alphavite51 commented
> > Согласен с коллегами выше, добавить нечего
> 
> У нас тут дискуссия, значит есть две стороны, так с кем Вы согласны или это очередная отписка? 

Согласен с @ifuwmnn и @ssas18 .

2020-09-10 12:28 UTC, YuriSilenok commented
> Тебе нужно чтобы во 2-ом регионе предварительное условие было пустым.

Почему пустым, разве там не должно быть каких-то данных, для успешного прохождения по региону?

2020-09-11 20:09 UTC, NordScandinavian requested changes
![image](https://user-images.githubusercontent.com/47521360/92968433-c880d180-f483-11ea-92e6-362ded162575.png)
Идея первого и второго теста похожи, ты удаляешь данные из пустой таблицы, а тебе нужно удалить несуществующего преподавателя.

2020-09-12 07:33 UTC, MyachevM commented
> 
> 
> ![image](https://user-images.githubusercontent.com/47521360/92968433-c880d180-f483-11ea-92e6-362ded162575.png)
> Идея первого и второго теста похожи, ты удаляешь данные из пустой таблицы, а тебе нужно удалить несуществующего преподавателя.

Для удаления несуществующего преподавателя, нужно чтобы данные в предварительном условии были пустые

2020-09-13 06:54 UTC, YuriSilenok commented
> ![image](https://user-images.githubusercontent.com/47521360/92968433-c880d180-f483-11ea-92e6-362ded162575.png)
> Идея первого и второго теста похожи, ты удаляешь данные из пустой таблицы, а тебе нужно удалить несуществующего преподавателя.

Пожалуйста, используйте к комментарии к коду, в место скринов кода.
Вы знаете как это делается?

2020-09-14 10:55 UTC, YuriSilenok requested changes

2020-09-14 10:55 UTC, YuriSilenok commented on Docs/UT-Deleted-CTeacher/REPORT.md
> +| R4 | task-1281-4 | Некорректное удаление преподавателя |  FirstName = "Прядкина", SecondName = "Нина",  Patronymic = "Олеговна" | FirstName = "Прядкна", SecondName = "Нина",  Patronymic = "Олеовна"
Сценарии не соответствую маршрутам.

2020-09-14 11:40 UTC, Alphavite51 commented
> ![image](https://user-images.githubusercontent.com/47521360/92968433-c880d180-f483-11ea-92e6-362ded162575.png)
> Идея первого и второго теста похожи, ты удаляешь данные из пустой таблицы, а тебе нужно удалить несуществующего преподавателя.

Открываешь код и слева будет плюсик и там пишешь комментарий к нужной строке.

2020-09-15 10:59 UTC, YuriSilenok commented on Docs/UT-Deleted-CTeacher/REPORT.md
> +| R2 | task-1281-2 | Удаление несуществующего преподавателя | - | FirstName = "Чередникова", SecondName = "Алла",  Patronymic = "Викторовна" | false |
Что значит прочерк в предвариетльный условиях, система отсутсвует?

2020-09-15 10:59 UTC, YuriSilenok commented on Docs/UT-Deleted-CTeacher/REPORT.md
> +| R3 | task-1281-3 | Удаление существующей строки |  "Садовская", "Ольга", "Борисовна", "Кандидат наук", "Профессор", "ФАСТ", "Пн, Вт", "Ср, Чт, Пт", "Воскресенье" | "Садовская", "Ольга", "Борисовна"
Почему в тесте 2 в идее теста вы говорите о преподавателе, а в третьем тесте говорите о строке. Складывается впечатление что есть какая-то разница между ними, это так?

2020-09-15 10:59 UTC, YuriSilenok commented on Docs/UT-Deleted-CTeacher/REPORT.md
> +| R4 | task-1281-4 | Удаление несуществующей строки |  "Садовская", "Ольга", "Борисовна", "Кандидат наук", "Профессор", "ФАСТ", "Пн, Вт", "Ср, Чт, Пт", "Воскресенье" | "Садовская", "Ольга", "Борисовн
Что значит несуществующая строка?

2020-09-15 11:19 UTC, MyachevM commented on Docs/UT-Deleted-CTeacher/REPORT.md
> +| R2 | task-1281-2 | Удаление несуществующего преподавателя | - | FirstName = "Чередникова", SecondName = "Алла",  Patronymic = "Викторовна" | false |
> 
> 
> Что значит прочерк в предвариетльный условиях, система отсутсвует?

Отсутствие данных в предварительном условии

2020-09-15 11:20 UTC, YuriSilenok commented on Docs/UT-Deleted-CTeacher/REPORT.md
> +| R2 | task-1281-2 | Удаление несуществующего преподавателя | - | FirstName = "Чередникова", SecondName = "Алла",  Patronymic = "Викторовна" | false |
Отсутсвие данных где, в таблице преподавателей? значит такое предварительное условие как в тесте 1?
Пишите развернутее.

2020-09-15 19:22 UTC, ifuwmnn requested changes
Я извиняюсь, видимо мой неправильный комментарий сбил человека с толку. Во 2 регионе у нас есть    предварительное условие, где должны быть заполнены все поля, по принципу 3 или 4 региона, а во входных параметрах нужно изменить так чтобы при проверке FullName не было совпадения. В 3 регионе входные параметры должны отличаться от предварительного условия так, чтобы не совпадало условие по Deprtament, остальные условия должны совпадать. Ну и нужно более понятно описать идею в 2, 3, 4 регионах.

2020-09-16 07:26 UTC, MyachevM commented
> 
> 
> Я извиняюсь, видимо мой неправильный комментарий сбил человека с толку. Во 2 регионе у нас есть предварительное условие, где должны быть заполнены все поля, по принципу 3 или 4 региона, а во входных параметрах нужно изменить так чтобы при проверке FullName не было совпадения. В 3 регионе входные параметры должны отличаться от предварительного условия так, чтобы не совпадало условие по Deprtament, остальные условия должны совпадать. Ну и нужно более понятно описать идею в 2, 3, 4 регионах.

Спасибо за разьяснение !

2020-09-17 14:39 UTC, YuriSilenok commented
Нарушены [требования именования веток](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/branches.md). Головная ветка не соответсвует требованиям.

2020-09-17 14:39 UTC, YuriSilenok commented
Нарушены [требования именования веток](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/branches.md). Головная ветка не соответсвует требованиям.

2020-09-17 14:39 UTC, YuriSilenok commented
Нарушены [требования именования веток](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/branches.md). Головная ветка не соответсвует требованиям.

2020-09-17 14:42 UTC, ifuwmnn approved these changes

2020-09-17 15:13 UTC, YuriSilenok reviewed
Отчет выглядит верно, давайте попробуем автоматизировать.

2020-09-17 15:38 UTC, MyachevM commented
> 
> 
> Нарушены [требования именования веток](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/branches.md). Головная ветка не соответсвует требованиям.

Немного не понимаю

2020-09-17 15:59 UTC, YuriSilenok commented
> > Нарушены [требования именования веток](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/branches.md). Головная ветка не соответствует требованиям.
> 
> Немного не понимаю

Расскажите подробнее, что непонятно, что бы я мог сформировать более детальное сообщение

2020-09-17 16:17 UTC, Alphavite51 commented on Docs/UT-Deleted-CTeacher/REPORT.md
>  | R1 | task-1281-1 | Удаление сведений в пустой таблице преподавателей | Таблица преподавателей пуста | FirstName = "Садовская", SecondName = "Ольга", Patronymic = "Борисовна", academicDegree = "Канд
academic Degree не должно начинаться с "C"? и во всех остальных "academic..."

2020-09-17 16:17 UTC, Alphavite51 requested changes
"C" забыли

2020-09-17 16:29 UTC, MyachevM commented
> 
> 
> > > Нарушены [требования именования веток](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/branches.md). Головная ветка не соответствует требованиям.
> > 
> > 
> > Немного не понимаю
> 
> Расскажите подробнее, что непонятно, что бы я мог сформировать более детальное сообщение

Что не так в наименовании ветки ?

2020-09-17 16:31 UTC, MyachevM commented on Docs/UT-Deleted-CTeacher/REPORT.md
>  | R1 | task-1281-1 | Удаление сведений в пустой таблице преподавателей | Таблица преподавателей пуста | FirstName = "Садовская", SecondName = "Ольга", Patronymic = "Борисовна", academicDegree = "Канд
> 
> 
> academic Degree не должно начинаться с "C"? и во всех остальных "academic..."

Нет, не должно
Это свойство, определяющее преподавателя

2020-09-17 17:28 UTC, YuriSilenok commented
> > 
> > 
> > > > Нарушены [требования именования веток](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/branches.md). Головная ветка не соответствует требованиям.
> > > 
> > > 
> > > Немного не понимаю
> > 
> > Расскажите подробнее, что непонятно, что бы я мог сформировать более детальное сообщение
> 
> Что не так в наименовании ветки ?

Нарушены требования, ссылку смотрели?

2020-09-18 12:13 UTC, MyachevM commented
> 
> 
> > > > > Нарушены [требования именования веток](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/branches.md). Головная ветка не соответствует требованиям.
> > > > 
> > > > 
> > > > Немного не понимаю
> > > 
> > > 
> > > Расскажите подробнее, что непонятно, что бы я мог сформировать более детальное сообщение
> > 
> > 
> > Что не так в наименовании ветки ?
> 
> Нарушены требования, ссылку смотрели?

Да, смотрел ссылку. Переименую ветку

2020-09-20 08:38 UTC, closed without merging