Удаление лишних проверок в файле CAcademicLoad.cs
Students-of-the-city-of-Kostroma/Student-timetable pull request #1324
Opened 2020-08-03 11:29 UTC by Alphavite51

2020-08-03 19:07 UTC, Alphavite51 commented
Нужен ревью @ssas18 @NesgovorovVS @MyachevM @JennyShel18 @badsster @NordScandinavian @ifuwmnn @ZhizhikinIvan, пожалуйста

2020-08-04 05:03 UTC, YuriSilenok commented
Пожалуйста, добавьте описание к этой задаче

2020-08-04 08:21 UTC, YuriSilenok requested changes
Я не увидел что бы проблемы была устранена.
@ssas18  могли бы подтвердить это?

2020-08-04 13:22 UTC, Alphavite51 commented
> Я не увидел что бы проблемы быдла устранена.
> @ssas18  могли бы подтвердить это? 

А какая была проблема? Мне сказали что есть лишняя проверка

2020-08-04 13:28 UTC, ssas18 requested changes
Проблема излишней проверки не была устранена

2020-08-04 14:49 UTC, Alphavite51 commented
> Проблема излишней проверки не была устранена 

А то, что я удалил обязательно в коде или можно тоже убрать?

2020-08-04 15:51 UTC, ssas18 commented
> > Проблема излишней проверки не была устранена
> 
> А то, что я удалил обязательно в коде или можно тоже убрать?

Ну я думаю что обязательно, т.к оно обрабатывает непредвиденную ошибку и приложение не выключается, а выдаёт исключение

2020-08-05 05:03 UTC, YuriSilenok commented
Пожалуйста, добавьте описание к этой задаче

2020-08-05 20:48 UTC, YuriSilenok commented
Я вижу вы справились с настройкой git, поздравляю, но об этом так же нужно описывать туда, где эта проблема решалась, что бы люди не думали что вы оставили эту проблему не решенной.

2020-08-06 06:02 UTC, Alphavite51 commented
> Я вижу вы справились с настройкой git, поздравляю, но об этом так же нужно описывать туда, где эта проблема решалась, что бы люди не думали что вы оставили эту проблему не решенной. 

Забыл отписать что проверку сделал, извиняюсь

2020-08-06 06:12 UTC, ssas18 requested changes
В #1312  было указано что лишняя проверка есть в методе update класса, а ты исправляешь приведение типов в методе delete

2020-08-06 08:41 UTC, YuriSilenok commented
> > Я вижу вы справились с настройкой git, поздравляю, но об этом так же нужно описывать туда, где эта проблема решалась, что бы люди не думали что вы оставили эту проблему не решенной. 
> 
> Забыл отписать что проверку сделал, извиняюсь 

Нужно повторно запрашивать проверку того человека, который нашёл вам ошибку, возможно он до провери, а ещё именно он может подтвердить что вы правильно исправили замечания

2020-08-06 17:31 UTC, ssas18 requested changes
Я думаю стоит вернуть try catch

2020-08-06 20:14 UTC, YuriSilenok commented
> Я думаю стоит вернуть try catch

Думаю в этом может помочь команда `git revert`

2020-08-07 09:48 UTC, ssas18 requested changes
Есть какой-то смысл это менять?

2020-08-07 09:48 UTC, ssas18 commented on LibOfTimetableOfClasses/CAcademicLoad.cs
> -                Debug.WriteLine(ex.Message);
В чем причина замены Message на Source

2020-08-07 10:11 UTC, Alphavite51 reviewed
Посмотрите пожалуйста фаил репозитория, кажется в нем так и прописано

2020-08-07 10:11 UTC, Alphavite51 commented on LibOfTimetableOfClasses/CAcademicLoad.cs
> -                Debug.WriteLine(ex.Message);
А разве в оригинальном фаиле не так прописано?(Source)

2020-08-07 10:11 UTC, Alphavite51 commented on LibOfTimetableOfClasses/CAcademicLoad.cs
> -                Debug.WriteLine(ex.Message);
я просто выкачал репозиторий и заново с ним работал, ничего кроме как удаления " if (mAcademic.Group == null)
return false; " и восстановления try catch не делал, тоесть это я не изменял

2020-08-08 06:55 UTC, ssas18 commented
> Посмотрите пожалуйста фаил репозитория, кажется в нем так и прописано

Да, в файле с репозитория стоит Source, но я не знаю что делать в данном случае, дождемся Юрия Викторовича

2020-08-08 13:58 UTC, YuriSilenok commented
Постараюсь вечером посмотреть откуда эти изменения.

2020-08-08 17:02 UTC, Alphavite51 commented
> Постараюсь вечером посмотреть откуда эти изменения. 

Я таких изменений не делал

2020-08-08 17:43 UTC, YuriSilenok commented
Возможно это результат глобального рефакторинга, но я ещё не смотрел.

сб, 8 авг. 2020 г., 20:02 АлександрСоколов <notifications@github.com>:

> Постараюсь вечером посмотреть откуда эти изменения.
>
> Я таких изменений не делал
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1324#issuecomment-670951078>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADROXL4OYKDCDU44L2P7QK3R7WALXANCNFSM4PTHZE4Q>
> .
>

2020-08-10 14:01 UTC, YuriSilenok commented
Этот фрагмент кода с обработкой исключений в вашей ветке много раз переделывался. Давайте поступим немного не правильно. Вы удаляет ветку, создаёте её снова из ветки dev, вносите нужные измени и мы уже закончим с этой задачей.

2020-08-10 14:02 UTC, YuriSilenok requested changes
Этот фрагмент кода с обработкой исключений в вашей ветке много раз переделывался. Давайте поступим немного не правильно. Вы удаляет ветку, создаёте её снова из ветки dev, вносите нужные измени и мы уже закончим с этой задачей.

2020-08-10 17:04 UTC, closed without merging