Исправление сбоев в автотестах в файле UT_Delete_CInstitute
Students-of-the-city-of-Kostroma/Student-timetable pull request #1329
Opened 2020-08-22 09:11 UTC by NordScandinavian

Исправление автотестов задачи #1095

2020-08-23 11:22 UTC, ssas18 requested changes
У каждого условия должен быть свой порядковый номер
![image](https://user-images.githubusercontent.com/47377817/90977156-e07fc800-e54b-11ea-89b5-2fcc59e43378.png)
здесь должно быть еще 2 столбца:
![image](https://user-images.githubusercontent.com/47377817/90977182-1755de00-e54c-11ea-8f63-97c6b98883fd.png)
 номер теста и предварительное условие

2020-08-24 10:30 UTC, MyachevM requested changes
На графе не проставлены регионы

2020-08-24 13:24 UTC, Alphavite51 reviewed
Почему не обозначены маршруты?

2020-08-24 13:24 UTC, Alphavite51 commented on UnitTestOfTimetableOfClasses/UT_Delete_CInstitute.cs
> +            MTeacher mTeacher = new MTeacher("Юрий", "Лустгартен", "Леонидович", "КН", "Доц", "ФАСТ", "Пн, Чт", "ПТ", "СБ, ВС");
Нужен ли капс в "ПТ, СБ, ВС" если да то почему не все "Пн, Чт" 
если это дни недели, то где еще два?

2020-08-26 16:00 UTC, ssas18 requested changes
> Принято регионы располагать так, чтобы регины с меньшим номером располагались ближе к 
> начальной вершине.


Тоже думаю стоит соблюсти

2020-08-31 13:04 UTC, ssas18 approved these changes, later dismissed

2020-09-01 12:01 UTC, ifuwmnn requested changes, later dismissed
В Azure фейлится тест 617_1 
![image](https://user-images.githubusercontent.com/47635280/91848974-fb48ef80-ec63-11ea-9ca9-27f43fab71ae.png)

2020-09-01 17:39 UTC, ifuwmnn approved these changes

2020-09-03 07:47 UTC, MyachevM submitted a review, later dismissed

2020-09-03 08:09 UTC, Alphavite51 approved these changes

2020-09-03 16:01 UTC, YuriSilenok commented
Ого, аж 4 положительных проверки. Скоро проверю.

2020-09-04 07:50 UTC, YuriSilenok requested changes
![image](https://user-images.githubusercontent.com/14871471/92213516-5a914480-ee9c-11ea-862c-b8d5edb90c15.png)
Получается что если условие 4 не выполнено, то происходит выход из цикла?

2020-09-09 12:35 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1342', '#1322', '#1294', '#1228', '#1217']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-10 11:37 UTC, Heriuple reviewed
Требуется дополнить или изменить граф, поскольку из поинтов 5,6,7 по графу нельзя выйти в следующую итерацию цикла.

2020-09-10 11:39 UTC, Heriuple requested changes
Выше комментарий

2020-09-11 19:37 UTC, NordScandinavian commented
> ![image](https://user-images.githubusercontent.com/14871471/92213516-5a914480-ee9c-11ea-862c-b8d5edb90c15.png)
> Получается что если условие 4 не выполнено, то происходит выход из цикла?

Получается, что из пункта 12 мы должны выходить в пункт 2?

2020-09-11 19:38 UTC, NordScandinavian commented
> Требуется дополнить или изменить граф, поскольку из поинтов 5,6,7 по графу нельзя выйти в следующую итерацию цикла.

А куда тогда мы должны выйти?

2020-09-11 21:15 UTC, Heriuple commented
В поинт 2, как минимум чтобы выйти в следующую итерацию цикла, как в поинте 4. Они же равнозначны, по коду. (не получилось с телефона ответом на комментарий сделать, извините)

2020-09-13 18:48 UTC, NordScandinavian commented
> В поинт 2, как минимум чтобы выйти в следующую итерацию цикла, как в поинте 4. Они же равнозначны, по коду. (не получилось с телефона ответом на комментарий сделать, извините)

То есть каждый из пунктов 4,5,6,7 сначала выходит в 2, и только в 12, я правильно понял?

2020-09-14 18:50 UTC, NordScandinavian commented
@YuriSilenok, я в замешательстве,
не могли бы Вы помочь и разрешить ситуацию?

2020-09-14 19:02 UTC, YuriSilenok reviewed
Вам нужно выполнить пошаговое выполнение программы, тогда вы увидите, откуда и куда выполняются переходы.

2020-09-15 10:33 UTC, Alphavite51 requested changes
Разве могут быть маршруты которые на 1 пункт отличаются друг от друга

2020-09-15 11:02 UTC, YuriSilenok commented
> Разве могут быть маршруты которые на 1 пункт отличаются друг от друга

Возможно вы имеете ввиду вершины 4,5,6,7. Они реализуют составное условие. На первом курсе Вам должны были рассказывать как работет оператор &&  в языке C#. Если первое условие не выполнено, остальные условия не будут проверяться.

2020-09-15 19:04 UTC, ifuwmnn requested changes
@NordScandinavian У тебя пошагово проверяется условие в пунктах 4, 5, 6, 7. Проверка может оборваться на любом из них, если это произойдёт, то мы должны вернуться в ПУНКТ 2 из прерванного пункта, а по твоей схеме мы можем вернутся только из пункта 4, и если зафейлятся пункты 5, 6, 7 мы выходим из цикла, а не возвращаемся в него. В общем убирай стрелочки соединяющие 4, 5, 6, 7 с 12, и соединяй 5, 6, 7 со 2.

2020-09-16 20:26 UTC, Heriuple reviewed
Пока не буду ставить апрув, дождусь ещё людей. Каких-то грубых вещей не увидел, но меня смущает одно: допустим у нас несколько Rows и мы не находим сразу нужную для удаления, насколько важно, сколько итераций в цикле мы сделали? И имеет ли смысл как-то обозначать их в Маршрутах на основании графа? Если да, то не представляю как это сделать, поэтому жду ещё одного человека, который скажет, что истинно, а что ложно в моих и Артёмовых суждениях. А и ещё одно, что тоже смущает. Если мы выходим из returne true, то мы не будем задевать внутренний цикл, а сразу выйдем из метода, по идее.(То бишь, в R6 идёт из 10 поинта сразу в 14).

2020-09-17 06:54 UTC, YuriSilenok commented
> насколько важно, сколько итераций в цикле мы сделали?

Важно что пройдены все вершины в пути хотя бы один раз и ни разу не пройдены вершины, которых нет в пути. Внес уточнение в [документацию](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/commit/9f023327f68537a2785183688d9e9ac9555a96c0).

2020-09-17 06:56 UTC, YuriSilenok commented
> И имеет ли смысл как-то обозначать их в Маршрутах на основании графа?

Нет, не имеет смысла, так как маршрут составляется на основании региона, который можно запетлять и не нарушить ни одного правила. Таким образом, отображение петель не несет полезной информации и перегружают отчет текстом.

2020-09-17 07:03 UTC, YuriSilenok commented
> Если мы выходим из returne true, то мы не будем задевать внутренний цикл, а сразу выйдем из метода, по идее.(То бишь, в R6 идёт из 10 поинта сразу в 14).

Да, это так, и в этом случае мы получает [изолированные вершины](https://ru.wikipedia.org/wiki/%D0%92%D0%B5%D1%80%D1%88%D0%B8%D0%BD%D0%B0_(%D1%82%D0%B5%D0%BE%D1%80%D0%B8%D1%8F_%D0%B3%D1%80%D0%B0%D1%84%D0%BE%D0%B2)#%D0%A2%D0%B8%D0%BF%D1%8B_%D0%B2%D0%B5%D1%80%D1%88%D0%B8%D0%BD). На рисунке это будет выглядеть не очень красиво. Если хочется сделать все идеально, то лучше не нумеровать недостижимые фигурные скобки.

2020-09-17 12:52 UTC, ifuwmnn approved these changes, later dismissed

2020-09-17 13:36 UTC, MyachevM requested changes
В маршруте R6, идёт переход из 5 поинта сразу в 7
А разве он не должен сначала попасть в 6 поинт ?

2020-09-17 13:40 UTC, YuriSilenok commented
> В маршруте R6, идёт переход из 5 поинта сразу в 7
> А разве он не должен сначала попасть в 6 поинт ?

Очень ценное замечание, именно о таких, внимательных, проверках я и говорил когда-то в чате.

2020-09-17 21:39 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1322']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-18 05:30 UTC, YuriSilenok commented
Нарушены [требования именования веток](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/branches.md#issue-d). Головная ветка task-1095 не соответствует требованиям.

2020-09-18 06:51 UTC, YuriSilenok commented
Нарушены [требования именования веток](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/branches.md#issue-d). Головная ветка task-1095 не соответствует требованиям.

2020-09-18 06:53 UTC, YuriSilenok requested changes

2020-09-18 06:53 UTC, YuriSilenok commented on LibOfTimetableOfClasses/CUniversity.cs
> +                Unique = true
Как эти изменения связаны с текущей задачей?

2020-09-18 06:53 UTC, YuriSilenok commented on LibOfTimetableOfClasses/LibOfTimetableOfClasses.csproj
> +    <UseVSHostingProcess>true</UseVSHostingProcess>
Зачем были добавлены эти изменения?

2020-09-18 06:53 UTC, YuriSilenok commented on TimetableOfClasses/TimetableOfClasses.csproj
> +    <UseVSHostingProcess>true</UseVSHostingProcess>
Зачем были добавлены эти изменения?

2020-09-18 06:53 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Delete_CInstitute.cs
> +            MTeacher mTeacher = new MTeacher("Юрий", "Лустгартен", "Леонидович", "КН", "Доц", "ФАСТ", "Пн, Чт", "ПТ", "СБ, ВС");
Нет проверки предварительного условия

2020-09-18 06:53 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UnitTestOfTimetableOfClasses.csproj
> +    <UseVSHostingProcess>true</UseVSHostingProcess>
Зачем были добавлены эти изменения?

2020-09-18 12:08 UTC, Alphavite51 requested changes
в R4 b R5 тоже самое

2020-09-18 12:08 UTC, Alphavite51 commented on Docs/UT_Delete_CInstitute/REPORT.md
> +|R3|617_3|Удалить несуществующее полное название института в  таблице| FullName = "Институт Автоматизированных Систем и Технологий" ShortName = "ФАСТ" Director = "Лустгартен Юрий Леонидович" VUS = "К
FullName Институт(Й) Систем(Й) и технологий(Й) удалить что в скобках

2020-09-20 11:22 UTC, ifuwmnn commented on Docs/UT_Delete_CInstitute/REPORT.md
> +|R3|617_3|Удалить несуществующее полное название института в  таблице| FullName = "Институт Автоматизированных Систем и Технологий" ShortName = "ФАСТ" Director = "Лустгартен Юрий Леонидович" VUS = "К
А в чём ошибка, разве эти й не обеспечивают прохождение по 3 региону?

2020-09-20 11:48 UTC, ifuwmnn reviewed
Как уже написал Юрий Викторович, нужно добавить проверку того, что данные действительно занеслись в таблицы mTeacher и I_IInstitute, + почему нет остальных тестов?

2020-09-21 06:13 UTC, closed without merging