отделение инициализация данных RefData из ее конструктора
Students-of-the-city-of-Kostroma/Student-timetable pull request #1331
Opened 2020-08-24 13:12 UTC by Alphavite51

#1323

2020-08-24 13:28 UTC, ssas18 requested changes
Имеется несколько конфликтов которые нужно решить перед мержем 
![image](https://user-images.githubusercontent.com/47377817/91050044-c4048e00-e626-11ea-8811-f66e7538b6e7.png)

2020-08-24 13:44 UTC, closed without merging

2020-08-27 13:48 UTC, Alphavite51 commented
Ветка смержена, можете продолжать работу.

2020-08-28 11:04 UTC, YuriSilenok commented
сами себе написали, а подумать?

2020-08-28 13:48 UTC, Alphavite51 commented
@ssas18 , @JennyShel18 , @MyachevM , @ifuwmnn , @NordScandinavian , @NesgovorovVS , @ZhizhikinIvan , @Heriuple @VinogradovAlexandr781227 , @badsster , Ветка смержена, можете продолжать работу, вам нужно мержить dev в ваши "заблокированные" ветки!