Отделение инициализации данных RefData из ее конструктора
Students-of-the-city-of-Kostroma/Student-timetable pull request #1332
Opened 2020-08-24 13:48 UTC by Alphavite51

#1323

2020-08-25 10:48 UTC, YuriSilenok requested changes
Молодец, убрали несколько пробелов.

2020-08-25 14:04 UTC, closed without merging

2020-08-27 13:48 UTC, Alphavite51 commented
Ветка смержена, можете начинать работу.

2020-08-28 11:05 UTC, YuriSilenok commented
опять сам себе

2020-08-28 13:48 UTC, Alphavite51 commented
@ssas18 , @JennyShel18 , @MyachevM , @ifuwmnn , @NordScandinavian , @NesgovorovVS , @ZhizhikinIvan , @Heriuple @VinogradovAlexandr781227 , @badsster , Ветка смержена, можете продолжать работу, вам нужно мержить dev в ваши "заблокированные" ветки!