Исправление сбоев в автотестах в файле UT_Update_CUniversity
Students-of-the-city-of-Kostroma/Student-timetable pull request #1333
Opened 2020-08-25 09:55 UTC by NordScandinavian

#1088

2020-08-26 15:58 UTC, ssas18 submitted a review, later dismissed

2020-08-28 07:43 UTC, NordScandinavian commented
Прошу не закрывать задачу по не активности, жду проверки команды.

2020-08-28 10:47 UTC, MyachevM submitted a review, later dismissed

2020-08-28 11:28 UTC, YuriSilenok commented
> Прошу не закрывать задачу по не активности, жду проверки команды.

Пока вы ждете одобрения членов команды, займитесь проверкой работ присланных Вам на проверку

2020-09-01 11:54 UTC, ifuwmnn submitted a review, later dismissed
Azure показывает, что фэйлятся тесты 497_3, 497_7 
![image](https://user-images.githubusercontent.com/47635280/91847016-02233280-ec63-11ea-8c82-622bb0ff79bc.png)

2020-09-01 12:33 UTC, ifuwmnn submitted a review, later dismissed

2020-09-04 07:41 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1342', '#1322', '#1309', '#1295', '#1294', '#1228', '#1217']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-07 16:01 UTC, Alphavite51 requested changes
У вас есть непроверенные запросы ['#1341']Пожалуйста, выполните проверку этого запроса.

2020-09-09 12:32 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1342', '#1322', '#1294', '#1228', '#1217']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-10 08:35 UTC, Alphavite51 approved these changes

2020-09-10 11:27 UTC, Heriuple submitted a review, later dismissed
Ошибок, не считая опечаток не было выявлено.

2020-09-10 12:33 UTC, YuriSilenok commented
> Ошибок, не считая опечаток не было выявлено.

Не стесняйтесь, сообщите об ошибках.

2020-09-10 16:42 UTC, Alphavite51 requested changes
Пару букв добавить

2020-09-10 16:42 UTC, Alphavite51 commented on Docs/UT_Update_CUniversity/REPORT.md
> +|R1|497_1|Изменить сведения в путой таблице| Таблица институтов пуста | INN = "4401006211", ShortName = "КГТУ", FullName =  ActualAdres = "Костромской Государственный Технический Университет", LegalA
в пуСтой

2020-09-10 16:42 UTC, Alphavite51 commented on Docs/UT_Update_CUniversity/REPORT.md
> +|R2|497_2|Изменить несуществующий унивеситет|INN = "4401006211", ShortName = "КГТУ", FullName =  ActualAdres = "Костромской Государственный Технический Университет", LegalAdres = "156005, Костромская
унивеРситет

2020-09-10 16:42 UTC, Alphavite51 commented on Docs/UT_Update_CUniversity/REPORT.md
> +|R2|497_2|Изменить несуществующий унивеситет|INN = "4401006211", ShortName = "КГТУ", FullName =  ActualAdres = "Костромской Государственный Технический Университет", LegalAdres = "156005, Костромская
город точно Костромушка, не уверен что я правильно замечание делаю, но все-же

2020-09-11 20:05 UTC, NordScandinavian commented on Docs/UT_Update_CUniversity/REPORT.md
> +|R2|497_2|Изменить несуществующий унивеситет|INN = "4401006211", ShortName = "КГТУ", FullName =  ActualAdres = "Костромской Государственный Технический Университет", LegalAdres = "156005, Костромская
> город точно Костромушка, не уверен что я правильно замечание делаю, но все-же

Поправил, но идея теста особо не поменялась. Считаю этот комментарий излишним.

2020-09-11 20:05 UTC, NordScandinavian commented on Docs/UT_Update_CUniversity/REPORT.md
> +|R1|497_1|Изменить сведения в путой таблице| Таблица институтов пуста | INN = "4401006211", ShortName = "КГТУ", FullName =  ActualAdres = "Костромской Государственный Технический Университет", LegalA
Спасибо, поправил

2020-09-11 20:05 UTC, NordScandinavian commented on Docs/UT_Update_CUniversity/REPORT.md
> +|R2|497_2|Изменить несуществующий унивеситет|INN = "4401006211", ShortName = "КГТУ", FullName =  ActualAdres = "Костромской Государственный Технический Университет", LegalAdres = "156005, Костромская
Спасибо, поправил

2020-09-15 10:26 UTC, YuriSilenok reviewed
Приведите пример, когда возможен переход 10-12

2020-09-15 10:26 UTC, YuriSilenok commented on Docs/UT_Update_CUniversity/REPORT.md
> +![alt text](GRAPH.PNG "Тестируемый метод")
На графе не хватает 16 вершины

2020-09-15 18:54 UTC, ifuwmnn commented on Docs/UT_Update_CUniversity/REPORT.md
> +![alt text](GRAPH.PNG "Тестируемый метод")
> На графе не хватает 16 вершины

Вроде на графе есть вершина 16, разве нет? 
![image](https://user-images.githubusercontent.com/47635280/93252362-0a6c8900-f79e-11ea-8ab3-79c24f4cbb51.png)

2020-09-15 19:34 UTC, YuriSilenok commented on Docs/UT_Update_CUniversity/REPORT.md
> +![alt text](GRAPH.PNG "Тестируемый метод")
Ах, она спрятана в середине.
Обычно не рисуют так сложно графы. 
Их стараются сделать более линейными.
В презентации к лекции показан такой способ.

2020-09-15 19:35 UTC, YuriSilenok commented
> Приведите пример, когда возможен переход 10-12

Жду пример

2020-09-15 20:26 UTC, Heriuple reviewed
Не знаю, насколько это существенно, но в пути R4 он разве не должен из 14 сразу идти в пункт 16?
насколько я понимаю, его выбрасывает раньше чем он успеет достичь внешнего false?

2020-09-15 20:28 UTC, YuriSilenok commented
> Не знаю, насколько это существенно, но в пути R4 он разве не должен из 14 сразу идти в пункт 16?
> насколько я понимаю, его выбрасывает раньше чем он успеет достичь внешнего false?

R4 - это не путь, а регион.

2020-09-15 20:29 UTC, YuriSilenok commented
> Не знаю, насколько это существенно, но в пути R4 он разве не должен из 14 сразу идти в пункт 16?
> насколько я понимаю, его выбрасывает раньше чем он успеет достичь внешнего false?

2020-09-15 20:30 UTC, YuriSilenok commented
Случайно закрыл.

2020-09-16 14:02 UTC, NordScandinavian commented
> > Приведите пример, когда возможен переход 10-12
> 
> Жду пример

![image](https://user-images.githubusercontent.com/47521360/93347930-4ce5a280-f83e-11ea-9fc7-e1b9584e23d4.png)
Если у данных тестов я поменяю маршрут местами, то проблема решится?

2020-09-16 14:07 UTC, YuriSilenok commented
> Если у данных тестов я поменяю маршрут местами, то проблема решится?

Ничего не изменится.
так что там с переходом 10-12, как вы его получили?

2020-09-18 05:20 UTC, NordScandinavian commented
> > Если у данных тестов я поменяю маршрут местами, то проблема решится?
> 
> Ничего не изменится.
> так что там с переходом 10-12, как вы его получили?

Пример привести не могу, но разве это не такая же проверка, как и остальные?

2020-09-18 09:40 UTC, YuriSilenok commented
> > > Если у данных тестов я поменяю маршрут местами, то проблема решится?
> > 
> > 
> > Ничего не изменится.
> > так что там с переходом 10-12, как вы его получили?
> 
> Пример привести не могу, но разве это не такая же проверка, как и остальные?

Не понимаю о какой проверке вы говорите, вот вы заявили, что возможен переход из 10 в 12, объясните как вы это определили?

2020-09-18 18:48 UTC, YuriSilenok commented
- CAcademicDegreeМетка тестируемого класса не найдена. Ожидается одна из следующих меток:

- MAcademicDegreeМетка тестируемого класса не найдена. Ожидается одна из следующих меток:

- CAcademicLoadМетка тестируемого класса не найдена. Ожидается одна из следующих меток:

- MAcademicLoadМетка тестируемого класса не найдена. Ожидается одна из следующих меток:

- CAuditorМетка тестируемого класса не найдена. Ожидается одна из следующих меток:

- MAuditorМетка тестируемого класса не найдена. Ожидается одна из следующих меток:

- CDirectionOfPreparationМетка тестируемого класса не найдена. Ожидается одна из следующих меток:

- MDirectionOfPreparationМетка тестируемого класса не найдена. Ожидается одна из следующих меток:

- CDisciplineМетка тестируемого класса не найдена. Ожидается одна из следующих меток:

- MDisciplineМетка тестируемого класса не найдена. Ожидается одна из следующих меток:

- CEnclosuresМетка тестируемого класса не найдена. Ожидается одна из следующих меток:

- MEnclosuresМетка тестируемого класса не найдена. Ожидается одна из следующих меток:

- CGroupМетка тестируемого класса не найдена. Ожидается одна из следующих меток:

- MGroupМетка тестируемого класса не найдена. Ожидается одна из следующих меток:

- CHEIМетка тестируемого класса не найдена. Ожидается одна из следующих меток:

- MHEIМетка тестируемого класса не найдена. Ожидается одна из следующих меток:

- CInstituteМетка тестируемого класса не найдена. Ожидается одна из следующих меток:

- MInstituteМетка тестируемого класса не найдена. Ожидается одна из следующих меток:

- CStudyWeekМетка тестируемого класса не найдена. Ожидается одна из следующих меток:

- MStudyWeekМетка тестируемого класса не найдена. Ожидается одна из следующих меток:

- CTeacherМетка тестируемого класса не найдена. Ожидается одна из следующих меток:

- MTeacherМетка тестируемого класса не найдена. Ожидается одна из следующих меток:

- CTitleМетка тестируемого класса не найдена. Ожидается одна из следующих меток:

- MTitleМетка тестируемого класса не найдена. Ожидается одна из следующих меток:

- CTrainingProfilesМетка тестируемого класса не найдена. Ожидается одна из следующих меток:

- MTrainingProfilesМетка тестируемого класса не найдена. Ожидается одна из следующих меток:

- CTypesOfOccupationsМетка тестируемого класса не найдена. Ожидается одна из следующих меток:

- MTypesOfOccupationsМетка тестируемого класса не найдена. Ожидается одна из следующих меток:

- CUniversityМетка тестируемого класса не найдена. Ожидается одна из следующих меток:

- MUniversity

2020-09-18 18:49 UTC, YuriSilenok commented
Метка тестируемого класса не найдена. Ожидается одна из следующих меток:
- CAcademicDegree
- MAcademicDegree
- CAcademicLoad
- MAcademicLoad
- CAuditor
- MAuditor
- CDirectionOfPreparation
- MDirectionOfPreparation
- CDiscipline
- MDiscipline
- CEnclosures
- MEnclosures
- CGroup
- MGroup
- CHEI
- MHEI
- CInstitute
- MInstitute
- CStudyWeek
- MStudyWeek
- CTeacher
- MTeacher
- CTitle
- MTitle
- CTrainingProfiles
- MTrainingProfiles
- CTypesOfOccupations
- MTypesOfOccupations
- CUniversity
- MUniversity

2020-09-18 18:56 UTC, YuriSilenok commented
В месте с метко `Unit test` необходимо указать одну из меток приведенных ниже.
|Контроллер|Модель|
|---|---|
|CAcademicDegree|MAcademicDegree|
|CAcademicLoad|MAcademicLoad|
|CAuditor|MAuditor|
|CDirectionOfPreparation|MDirectionOfPreparation|
|CDiscipline|MDiscipline|
|CEnclosures|MEnclosures|
|CGroup|MGroup|
|CHEI|MHEI|
|CInstitute|MInstitute|
|CStudyWeek|MStudyWeek|
|CTeacher|MTeacher|
|CTitle|MTitle|
|CTrainingProfiles|MTrainingProfiles|
|CTypesOfOccupations|MTypesOfOccupations|
|CUniversity|MUniversity|

2020-09-21 05:59 UTC, closed without merging