Исправление сбоев в автотестах расположенных в файле UT_Insert_CTeacher
Students-of-the-city-of-Kostroma/Student-timetable pull request #1335
Opened 2020-08-25 16:21 UTC by NordScandinavian

#1032

2020-08-26 15:57 UTC, ssas18 requested changes
> Первый регион принято указывать на внешней области графа
Это не критично, но я думаю стоит это соблюсти

2020-08-27 06:24 UTC, YuriSilenok commented
> > Первый регион принято указывать на внешней области графа
> 
> Это не критично, но я думаю стоит это соблюсти

- это прописано в требованиях
- если следовать требованиям, то будет несколько косвенных признаков, что вы правильно выделяете маршруты.

2020-08-29 10:44 UTC, ssas18 approved these changes

2020-09-01 11:50 UTC, ifuwmnn requested changes, later dismissed
У тебя вроде тесты 246_1, 246_2, 246_4, 246_5, 246_6 фейлятся 
![image](https://user-images.githubusercontent.com/47635280/91848634-6e9e3180-ec63-11ea-87ea-22037d1430e3.png)
![image](https://user-images.githubusercontent.com/47635280/91848706-870e4c00-ec63-11ea-9b3f-d97872c3e136.png)

2020-09-01 12:32 UTC, ifuwmnn approved these changes, later dismissed

2020-09-02 08:26 UTC, YuriSilenok requested changes
Что значит некорректные данные, как понять какое ограничение у вас проверяется?

2020-09-02 08:26 UTC, YuriSilenok commented on Docs/UT_Insert_CTeacher/REPORT.md
> +|R2|246_2|Добавить корректные данные преподавателя в существующую таблицу преподавателей| "Киприна", "Людмила", "Юрьевна", "Кандидат наук", "Доцент", "ФАСТ", "Пн, Вт", "Ср, Чт, Пт", "Воскресенье" | "
Кто-то разбирался что значат эти предварительные условия?

2020-09-02 12:18 UTC, NordScandinavian commented on Docs/UT_Insert_CTeacher/REPORT.md
> +|R2|246_2|Добавить корректные данные преподавателя в существующую таблицу преподавателей| "Киприна", "Людмила", "Юрьевна", "Кандидат наук", "Доцент", "ФАСТ", "Пн, Вт", "Ср, Чт, Пт", "Воскресенье" | "
Введённое значение на корректность по правилам, описанным в классе со свойствами преподавателя
Здесь было изменено значение поля "Выходной" с корректного "Воскресенье" на некорректное "воскресенье",
Одно из условий проверяет первую букву на заглавность.
![image](https://user-images.githubusercontent.com/47521360/91979907-264c4580-ed2f-11ea-831a-90bf6fc58440.png)
![image](https://user-images.githubusercontent.com/47521360/91980166-8511bf00-ed2f-11ea-84b4-167c6eb2f76e.png)

2020-09-04 08:21 UTC, MyachevM approved these changes

2020-09-04 09:50 UTC, YuriSilenok commented on Docs/UT_Insert_CTeacher/REPORT.md
> +|R2|246_2|Добавить корректные данные преподавателя в существующую таблицу преподавателей| "Киприна", "Людмила", "Юрьевна", "Кандидат наук", "Доцент", "ФАСТ", "Пн, Вт", "Ср, Чт, Пт", "Воскресенье" | "
А причем тут класс MTeacher? вы ведь тестируете метод Insert класса CTeacher

2020-09-07 13:26 UTC, MyachevM approved these changes
Я наверное соглашусь с Артёмом про некорректные данные, поэтому Approve

2020-09-07 14:44 UTC, YuriSilenok commented
> Я наверное соглашусь с Артёмом про некорректные данные, поэтому Approve

Так а что значит некорректные данные? почему апрув, понять не могу.
Это выглядит как на форме регистрации ввести корректный возраст, а если пользователь ошибся, ему пишется, возраст некорректен, но ни кто ему не говорит что возврат должен быть 23+

2020-09-07 18:40 UTC, NordScandinavian commented on Docs/UT_Insert_CTeacher/REPORT.md
> +|R2|246_2|Добавить корректные данные преподавателя в существующую таблицу преподавателей| "Киприна", "Людмила", "Юрьевна", "Кандидат наук", "Доцент", "ФАСТ", "Пн, Вт", "Ср, Чт, Пт", "Воскресенье" | "
Присвоение свойств в классе CTeacher происходит из другого класса, MTeacher. От туда и берутся ограничения на ввод.
Вероятно, я что-то не понимаю, прошу объяснить.
![image](https://user-images.githubusercontent.com/47521360/92411977-bc7ad400-f152-11ea-97b9-199d1d991a14.png)

2020-09-07 18:44 UTC, NordScandinavian commented
> > Я наверное соглашусь с Артёмом про некорректные данные, поэтому Approve
> 
> Так а что значит некорректные данные? почему апрув, понять не могу.
> Это выглядит как на форме регистрации ввести корректный возраст, а если пользователь ошибся, ему пишется, возраст некорректен, но ни кто ему не говорит что возврат должен быть 23+

Вы предлагаете сделать тесты на прохождение по каждой из проверок, а не в целом?

2020-09-08 18:00 UTC, ssas18 reviewed
Для чего тут ревью?

2020-09-08 18:01 UTC, ssas18 requested changes
для чего тут ревью?

2020-09-09 11:36 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1342', '#1322', '#1294', '#1228', '#1217']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-09 11:36 UTC, YuriSilenok commented
У вас есть непроверенные запросы []. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-09 12:18 UTC, MyachevM commented
> 
> 
> > Я наверное соглашусь с Артёмом про некорректные данные, поэтому Approve
> 
> Так а что значит некорректные данные? почему апрув, понять не могу.
> Это выглядит как на форме регистрации ввести корректный возраст, а если пользователь ошибся, ему пишется, возраст некорректен, но ни кто ему не говорит что возврат должен быть 23+

Возможно, как мне кажется, некорректность данных означает, к примеру, пропущенную букву в Фамилии преподавателя, либо же, не до конца введённые ФИО.

2020-09-09 12:30 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1342', '#1322', '#1294', '#1228', '#1217']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-09 18:43 UTC, YuriSilenok commented
> > 
> > 
> > > Я наверное соглашусь с Артёмом про некорректные данные, поэтому Approve
> > 
> > Так а что значит некорректные данные? почему апрув, понять не могу.
> > Это выглядит как на форме регистрации ввести корректный возраст, а если пользователь ошибся, ему пишется, возраст некорректен, но ни кто ему не говорит что возврат должен быть 23+
> 
> Возможно, как мне кажется, некорректность данных означает, к примеру, пропущенную букву в Фамилии преподавателя, либо же, не до конца введённые ФИО.

Таких ограничений нет. Вы значение какие ограничения проверяются в тестируем ом методе?

2020-09-10 08:41 UTC, ifuwmnn reviewed
Юрий Викторович уже описал ошибки.

2020-09-10 08:45 UTC, YuriSilenok commented
> Юрий Викторович уже описал ошибки.

Да вроде не описал.
Но суть в том, что если возникают ошибки при создании экземпляра класса модели (класс начинается с M), то вы попали в ограничение модели, а не в ограничение контроллера. 
Есть две группы ограничений контроллера:
- реляционных связей
- уникальности значений

Вот от них и пляшите.

2020-09-11 09:48 UTC, MyachevM requested changes
Непонятная ситуация с R1: добавление некорректных данных

2020-09-13 07:25 UTC, YuriSilenok requested changes

2020-09-13 07:25 UTC, YuriSilenok commented on Docs/UT_Insert_CTeacher/REPORT.md
> +|R1|246_2| Добавить преподавателя с некорректным ученым званием | "Киприна", "Людмила", "Юрьевна", "Кандидат наук", "Доцент", "ФАСТ", "Пн, Вт", "Ср, Чт, Пт", "Воскресенье" | "Киприна", "Людмила", "Юр
что значит `некорректным ученым званием` я как тестировщик не знаю, сколько таких правил существует, подходящих под невалидные данные?

2020-09-14 18:48 UTC, NordScandinavian commented on Docs/UT_Insert_CTeacher/REPORT.md
> +|R1|246_2| Добавить преподавателя с некорректным ученым званием | "Киприна", "Людмила", "Юрьевна", "Кандидат наук", "Доцент", "ФАСТ", "Пн, Вт", "Ср, Чт, Пт", "Воскресенье" | "Киприна", "Людмила", "Юр
> что значит `некорректным ученым званием` я как тестировщик не знаю, сколько таких правил существует, подходящих под невалидные данные?

Прошу прощения, неправильно выразился. Не `некорректным ученым званием` а `несуществующим `

2020-09-15 10:33 UTC, YuriSilenok reviewed
Как Вы определяете какой регион соответсвует какому маршруту?

2020-09-15 18:43 UTC, ifuwmnn reviewed
Я возможно скажу глупость, но по идее для каждого теста должен быть свой регион, и их видимо должно быть больше чем 2.

2020-09-15 19:31 UTC, YuriSilenok commented
> Я возможно скажу глупость, но по идее для каждого теста должен быть свой регион, и их видимо должно быть больше чем 2.

На оборот, для каждого региона 1 и более тестов, причем некоторые тесты могут быть недостижимыми.

2020-09-15 20:09 UTC, Heriuple reviewed
Боюсь, что подсказать что именно делать не смогу, ибо не понял в чем может быть проблема.(поэтому ни реквест, ни апрув делать не буду). Может быть не хватает ещё больше тестовых сценариев чтобы покрыть все строки добавляемые? И ещё вопрос, может всё таки существующего преподавателя в 246_3?

2020-09-16 13:55 UTC, NordScandinavian commented
> Как Вы определяете какой регион соответсвует какому тесту?

У меня 2 маршрута, один выходит в true, другой в false. И, соответственно, для каждого из этих маршрутов я описываю сценарии, при которых возможно прохождение этих маршрутов

2020-09-16 14:03 UTC, YuriSilenok commented
> > Как Вы определяете какой регион соответсвует какому тесту?
> 
> У меня 2 маршрута, один выходит в true, другой в false. И, соответственно, для каждого из этих маршрутов я описываю сценарии, при которых возможно прохождение этих маршрутов

Да, похоже это я запутался, так как у вас идут сначала негативные тесты.
Вопрос вот в чем, вот идея теста `Добавление несуществующего преподавателя`  добавление идет в таблице преподавателей. У вас получился преподаватель Шредингера. Он существует, потому что он указан во входных параметрах и не существует, потому что идея теста такая.

2020-09-18 05:18 UTC, NordScandinavian commented
> > > Как Вы определяете какой регион соответсвует какому тесту?
> > 
> > 
> > У меня 2 маршрута, один выходит в true, другой в false. И, соответственно, для каждого из этих маршрутов я описываю сценарии, при которых возможно прохождение этих маршрутов
> 
> Да, похоже это я запутался, так как у вас идут сначала негативные тесты.
> Вопрос вот в чем, вот идея теста `Добавление несуществующего преподавателя` добавление идет в таблице преподавателей. У вас получился преподаватель Шредингера. Он существует, потому что он указан во входных параметрах и не существует, потому что идея теста такая.

То есть изменение входных данных на пустую таблицу исправвит ошибку?

2020-09-18 09:38 UTC, YuriSilenok commented
> > > > Как Вы определяете какой регион соответсвует какому тесту?
> > > 
> > > 
> > > У меня 2 маршрута, один выходит в true, другой в false. И, соответственно, для каждого из этих маршрутов я описываю сценарии, при которых возможно прохождение этих маршрутов
> > 
> > 
> > Да, похоже это я запутался, так как у вас идут сначала негативные тесты.
> > Вопрос вот в чем, вот идея теста `Добавление несуществующего преподавателя` добавление идет в таблице преподавателей. У вас получился преподаватель Шредингера. Он существует, потому что он указан во входных параметрах и не существует, потому что идея теста такая.
> 
> То есть изменение входных данных на пустую таблицу исправвит ошибку?

Звучит ужасно, давайте вы сделаете исправление, а мы посмотрим, что вы имели ввиду на практике. Может быть коллеги помогут разобраться.

2020-09-21 05:09 UTC, YuriSilenok commented
Нарушены [требования именования веток](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/branches.md#issue-d). Головная ветка task-1032 не соответствует требованиям.

2020-09-21 05:09 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1355']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-21 05:09 UTC, YuriSilenok commented
Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/labels.md) для метки `Unit test`

2020-09-21 05:10 UTC, YuriSilenok commented
Нарушены [требования именования веток](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/branches.md#issue-d). Головная ветка task-1032 не соответствует требованиям.

2020-09-21 05:11 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1355']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-21 05:11 UTC, YuriSilenok commented
Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/labels.md) для метки `Unit test`

2020-09-21 05:11 UTC, YuriSilenok commented
Нарушены [требования именования веток](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/branches.md#issue-d). Головная ветка task-1032 не соответствует требованиям.

2020-09-21 05:11 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1355']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-21 05:11 UTC, YuriSilenok commented
Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/labels.md) для метки `Unit test`

2020-09-21 05:21 UTC, closed without merging

2020-09-21 18:08 UTC, MyachevM commented
Мне точно нужно проверить задачу ? Она находится в закрытых

2020-09-21 18:28 UTC, YuriSilenok commented
> Мне точно нужно проверить задачу ? Она находится в закрытых

нет, по идее и отображаться в списке не должна, как вы на нее вышли?