Отделение инициализации RefData от ее конструктора
Students-of-the-city-of-Kostroma/Student-timetable pull request #1336
Opened 2020-08-26 11:00 UTC by Alphavite51

#1323

2020-08-26 11:11 UTC, Alphavite51 commented
нужен ревью @ssas18 , @MyachevM , @NesgovorovVS , @NordScandinavian , @badsster , @JennyShel18 , @Heriuple , @ifuwmnn

2020-08-26 11:13 UTC, ssas18 requested changes
Заполни ассигн, лейбл и так далее

2020-08-26 11:15 UTC, ifuwmnn approved these changes

2020-08-26 11:16 UTC, Alphavite51 commented
> Заполни ассигн, лейбл и так далее

Сделал

2020-08-26 11:20 UTC, ssas18 approved these changes

2020-08-26 15:00 UTC, MyachevM approved these changes

2020-08-27 06:23 UTC, YuriSilenok approved these changes
Можете мержить.
Желательно отписать во все задачи которые заблокированы вашей задачей, что можно продолжать. Список таких задач можно просмотреть в истории комментариев вашей задачи. Так как люди сообщая в своих задачах что они не могу выполнять свою задачу ссылались на вашу задачу. Сообщите им что они должны получить обновления из ветки dev.

2020-08-27 13:45 UTC, merged

2020-08-28 13:49 UTC, Alphavite51 commented
@ssas18 , @JennyShel18 , @MyachevM , @ifuwmnn , @NordScandinavian , @NesgovorovVS , @ZhizhikinIvan , @Heriuple @VinogradovAlexandr781227 , @badsster , Ветка смержена, можете продолжать работу, вам нужно мержить dev в ваши "заблокированные" ветки!

2020-09-13 00:24 UTC, YuriSilenok commented
После того, как преподаватель провел положительную проверку запроса #1336, Вы должны смержить запрос. После этого перевесить основную задачу #1323 на преподавателя.