Добавил расписание для студентов на форму "расписание"
Students-of-the-city-of-Kostroma/Student-timetable pull request #1338
Opened 2020-08-29 13:53 UTC by ZhizhikinIvan

https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/1326

2020-08-31 13:09 UTC, ssas18 requested changes
Ветка в которую мержишь должна быть dev, надо добавить проверяющих в запрос и у тебя имеется мерж конфликт

2020-09-06 07:51 UTC, MyachevM requested changes
В проверяющих нужно добавить всех членов команды.
Решить merge-conflict.

2020-09-06 14:31 UTC, ZhizhikinIvan commented
@MyachevM В данный момент, как раз работаю над решением конфликта.

2020-09-09 11:33 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1342', '#1335', '#1333', '#1329', '#1322', '#1294', '#1217']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-09 11:33 UTC, YuriSilenok commented
У вас есть непроверенные запросы []. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-09 12:27 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1342', '#1335', '#1333', '#1329', '#1322', '#1294', '#1217']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-15 05:44 UTC, YuriSilenok commented
Вы ведь понимаете, что данные должны будут браться из таблиц, а не быть зафиксированы кодом?

2020-09-16 21:31 UTC, ZhizhikinIvan commented
> Вы ведь понимаете, что данные будут браться из таблиц, а не зафиксированы кодом?

Юрий Викторович, я надеюсь, что я правильно понял и вас, и само условие задачи. 
Ведь необходимо сделать так, что бы институт, направление подготовки и группа, а затем и само расписание должны подгружаться из RefData? Верно? 
Но перед этим недостающие данные должны быть туда занесены.

Если всё так, то я допустил ошибку, подумав, что данные в списках (институт, направление подготовки и группа), должны уже находиться в форме. Данную ошибку буду править.

А и ещё один вопрос, в RefData список институтов представлен таким образом (скрин ниже)?

![image](https://user-images.githubusercontent.com/47943099/93393981-1e86b800-f87c-11ea-906c-b7d53005523b.png)

2020-09-17 07:09 UTC, YuriSilenok commented
> > Вы ведь понимаете, что данные будут браться из таблиц, а не зафиксированы кодом?
> 
> Юрий Викторович, я надеюсь, что я правильно понял и вас, и само условие задачи.
> Ведь необходимо сделать так, что бы институт, направление подготовки и группа, а затем и само расписание должны подгружаться из RefData? Верно?
> Но перед этим недостающие данные должны быть туда занесены.
> 
> Если всё так, то я допустил ошибку, подумав, что данные в списках (институт, направление подготовки и группа), должны уже находиться в форме. Данную ошибку буду править.
> 
> А и ещё один вопрос, в RefData список институтов представлен таким образом (скрин ниже)?
> 
> ![image](https://user-images.githubusercontent.com/47943099/93393981-1e86b800-f87c-11ea-906c-b7d53005523b.png)

Да, все верно, на текущий момент, загрузка этих данных выключена, есть метод Init в RefData, который за это отвечает. Но возможности его использовать сейчас нет, так как часть создаваемых данных, не проходят проверку на уровне моделей. Вы можете сделать кнопку в меню главной формы, с текстом `Загрузить тестовые данные`, которая вызовет соответствующий метод. Думаю при нажатии этой кнопки вы словите исключение, по которому будет понятно, в какой момент какие данные заносились не верно.

2020-09-17 18:33 UTC, ZhizhikinIvan commented
Юрий Викторович, на какой форме делать кнопку "загрузить тестовые данные"?
Если делать на форме "Start", то я не знаю, как передать refData на форму "Timetable".
Не могли бы вы мне немного подсказать?

2020-09-17 19:46 UTC, ZhizhikinIvan commented
Юрий Викторович, подскажите пожалуйста, как можно исправить ошибку с ветками, которая возникла у меня в задаче?

2020-09-17 21:15 UTC, YuriSilenok commented
![image](https://user-images.githubusercontent.com/14871471/93528972-db901780-f943-11ea-8546-452fbfa2cf33.png)
![image](https://user-images.githubusercontent.com/14871471/93529035-f06cab00-f943-11ea-85dc-f1d403c92715.png)
Если вы пускали ветку из dev, то все будет без конфликтов

2020-09-17 21:20 UTC, ZhizhikinIvan commented
@YuriSilenok Спасибо.

2020-09-19 19:36 UTC, ZhizhikinIvan commented
Юрий Викторович, является ли моей задачей приведение RefData к нормальному, пригодному для дальнейшего использования виду? Это необходимо сделать, потому что, имеющиеся у нас тестовые данные, некорректны и дальнейшее их использование проблематично.
Возможно ли вывести эту задачу отдельно, так как там достаточно большой объём работ?

2020-09-20 18:25 UTC, ZhizhikinIvan commented
@YuriSilenok Юрий Викторович, в задании сказано: `"После выбора института, поле "Выберите направление подготовки" должно стать доступным и содержать значения соответствующие моему институту."` 
Не могли бы вы объяснить, как определить направление подготовки для конкретного института?

2020-09-20 18:52 UTC, YuriSilenok commented
> @YuriSilenok Юрий Викторович, является ли моей задачей приведение RefData к нормальному, пригодному для дальнейшего использования виду? Это необходимо сделать, потому что, имеющиеся у нас тестовые данные, некорректны и дальнейшее их использование проблематично.
> Возможно ли вывести эту задачу отдельно, так как там достаточно большой объём работ?

Думаю ы хотели бы использовать тестовые данные, но не можете из-за их некорректности.
Если у вас имеются свободные лабораторки, Вы можете поднять на себя эту задачу, только загрузка данных должна производится из меню главной формы. При нажатии на кнопку, старая рефдата должна удалиться, а новая погрузиться, для этого есть соответствующие методы.

2020-09-21 19:35 UTC, ZhizhikinIvan commented
@YuriSilenok 

Юрий Викторович, на данный момент сделано:
1. В CDirectionOfPreparation и MDirectionOfPreparation добавлено поле InstituteShortName для связи с Institute.
2. В RefData добавлена связь между Institute и DirectionOfPreparation.
3. Исправлены некоторые ошибки в RefData. Некоторые связи в RefData временно закомментированы, что бы не мешали загрузке.
4. На форму Start добавлена кнопка "Загрузка тестовых данных" из RefData.
5. На форму Timetable добавлены выпадающие списки и сделано заполнение списка Институтов.
6. Поправлены формы AddDirectionOfPreparation и DirectionOfPreparation, что бы проект собирался без ошибок.

Далее планирую сделать:
1. Для перезагрузки RefData, при нажатии на кнопку "Загрузка тестовых данных", думаю добавить в класс RefData 2 метода:
 а) первый метод - проверки, был ли выполнен метод InitData() (вероятно буду проверять каждую таблицу на число записей, если число записей равно 0, то InitData не выполнялась);
 б) второй метод - очистки данных во всех таблицах. 
2. Доделать загрузку списков данных для направлений подготовки и групп.
3. Сделать отображение расписания (пока не знаю как).

Вопросы:
1. Возможно ли в рамках этой задачи, окончательно исправить RefData, и будет ли это засчитано за недостающую лабораторную? Мне нужно исправление RefData в рамках этой задачи и не очень удобно выполнять это в рамках отдельной ветки, как положено по требованиям.
2. На форме AddDirectionOfPreparation добавлен текстовый блок для отображения и кнопка выбора института, но функционал выбора института не реализован. Следует ли мне реализовать это?

2020-09-21 20:13 UTC, YuriSilenok commented
> 1. а) первый метод - проверки, был ли выполнен метод InitData() (вероятно буду проверять каждую таблицу на число записей, если число записей равно 0, то InitData не выполнялась);

там есть метод удаления данных, ничего не случится если на чистой рефдате вызвать этот метод, он отработает быстро

2020-09-21 20:13 UTC, YuriSilenok commented
> 1. Возможно ли в рамках этой задачи, окончательно исправить RefData, и будет ли это засчитано за недостающую лабораторную?

можно, будет

2020-09-21 20:14 UTC, YuriSilenok commented
> 2\. На форме AddDirectionOfPreparation добавлен текстовый блок для отображения и кнопка выбора института, но функционал выбора института не реализован. Следует ли мне реализовать это?

Кажется там должен быть выпадающий список

2020-09-21 20:15 UTC, YuriSilenok commented
> 2\. На форме AddDirectionOfPreparation добавлен текстовый блок для отображения и кнопка выбора института, но функционал выбора института не реализован. Следует ли мне реализовать это?

да, посмотрите как сделано в других местах, там переиспользована форма добавления сущности.

2020-09-21 20:18 UTC, YuriSilenok commented
> 3\. Подскажите пожалуйста, как определить, в какой аудитории и в какое время должно проходить занятие для какой-то группы, что бы это отобразить в самом расписании?

Судя по имеющимся контроллерам, нет такой сущности, которая хранила бы сведения об одном занятии. значит ее нужно создать.

2020-09-22 17:37 UTC, ZhizhikinIvan commented
@YuriSilenok 
>там есть метод удаления данных, ничего не случится если на чистой рефдате вызвать этот метод, он отработает быстро

Если вы имеете ввиду RefData, то в ней нет метода удаления данных. Если вы говорите про метод Delete в каждой таблице, то да, этот метод планировал использовать.

2020-09-22 18:00 UTC, YuriSilenok commented
Разобрался.
Все дело в том, что когда то этот метод существовал в [таком](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/16144b5a6d773c6f659e27bb1a7cb57c0e3ce1c8/LibOfTimetableOfClasses/RefData.cs) виде.
Можете написать свой или воспользоваться частью кода из этой версии.

2020-09-22 18:07 UTC, ZhizhikinIvan commented
Спасибо.

2020-09-23 20:26 UTC, ZhizhikinIvan commented
На текущий момент сделано:
1. Доработана RefData. Исправлен метод InitData, сначала загружаются справочники, потом основные данные. Данные дополнены. Загрузка RefData происходит успешно.
2. В RefData добавлен метод очистки контроллеров. Тоже работает.
3. Исправлена проверка данных в моделях, исправлены ошибки в контроллерах, мешающие загрузке тестовых данных.
4. В приложении добавлена кнопка загрузки данных из RefData. При нажатии на кнопку контроллеры сначала очищаются.

Далее планирую сделать:
1. Доделать загрузку списков данных для направлений подготовки и групп.
2. Реализовать выбор института на форме AddDirectionOfPreparation.
3. Сделать отображение расписания (пока не знаю как).


Прощу зачесть одну лабораторную, так как RefData доведена до рабочего состояния и наполнена правильными данными.

2020-09-24 07:17 UTC, YuriSilenok requested changes
Проверил только часть работы, есть много вопросов.

2020-09-24 07:17 UTC, YuriSilenok commented on LibOfTimetableOfClasses/MAcademicLoad.cs
> +        /// Строка должна быть: не-null, не более 25 символов, содержать только А-Я,а-я, цифры, не пустой, начинаться с заглавной
Почему в дисциплине могу быть цифры?

2020-09-24 07:17 UTC, YuriSilenok commented on LibOfTimetableOfClasses/MAcademicLoad.cs
> +                if (value.Length > 45) throw new Exception("Кол-во символов превышает 45");
Изменить в комментариях  к свойству сведения о длине строки

2020-09-24 07:17 UTC, YuriSilenok commented on LibOfTimetableOfClasses/MAcademicLoad.cs
> +                if (value.Length > 110) throw new Exception("Кол-во символов не превышает 107");
"Кол-во символов не превышает 107" а в условии 110

2020-09-24 07:48 UTC, ZhizhikinIvan commented on LibOfTimetableOfClasses/MAcademicLoad.cs
> +        /// Строка должна быть: не-null, не более 25 символов, содержать только А-Я,а-я, цифры, не пустой, начинаться с заглавной
Я минимально исправлял существующие данные в RefData, добиваясь безошибочной загрузки данных.
В InitAcademicLoad() есть нагрузка с дисциплиной "3Д-моделирование". Причем название я исправил, первоначально было "3D-моделирование". Я решил исключить английские буквы.
Дисциплину "WEB-программирование", я тоже заменил на "ВЕБ-программирование".

2020-09-24 07:50 UTC, ZhizhikinIvan commented on LibOfTimetableOfClasses/MAcademicLoad.cs
> +                if (value.Length > 45) throw new Exception("Кол-во символов превышает 45");
Да, поправил.

2020-09-24 07:50 UTC, ZhizhikinIvan commented on LibOfTimetableOfClasses/MAcademicLoad.cs
> +                if (value.Length > 110) throw new Exception("Кол-во символов не превышает 107");
Тоже поправил.

2020-09-24 08:00 UTC, YuriSilenok commented
вы пишите что исправили, а коммиты где?

2020-09-24 08:01 UTC, ZhizhikinIvan commented on LibOfTimetableOfClasses/MAcademicLoad.cs
> +                if (value.Length > 110) throw new Exception("Кол-во символов не превышает 107");
Видимо из-за того, что предыдущий мерж находится у вас на ревью, я не могу закомитить исправления.

![image](https://user-images.githubusercontent.com/47943099/94117666-33071980-fe55-11ea-9672-af10dd55dbec.png)

2020-09-24 08:01 UTC, YuriSilenok commented on LibOfTimetableOfClasses/MAcademicLoad.cs
> +        /// Строка должна быть: не-null, не более 25 символов, содержать только А-Я,а-я, цифры, не пустой, начинаться с заглавной
принято.

2020-09-24 08:34 UTC, YuriSilenok commented on LibOfTimetableOfClasses/CAcademicLoad.cs
> +                //Unique = true  // не может быть уникальным!!!
не очень хорошо так делать.
Вы по сути начали обсуждение в комментариях к методу.
Если считаете что нужно удалить уникальность у группы, то просто это сделайте.
Возникнут вопросы, мы это обсудим в комментариях к коду.

2020-09-24 08:34 UTC, YuriSilenok commented on LibOfTimetableOfClasses/CAcademicLoad.cs
> +                    && (string)this.Rows[i]["KindOfLesson"] == mAcademicLoad.Occupation)
я думаю нам не хватает первичного ключа.
Думаю у нагрузки, как у документа, должен быть свой номер, как у приказов.

2020-09-24 08:34 UTC, YuriSilenok commented on LibOfTimetableOfClasses/MAcademicLoad.cs
> +                if (value.Length > 110) throw new Exception("Кол-во символов не превышает 107");
- всегда делайте полный скрин окна
- я устал объяснять, что если ветка в удаленном репозитории будет иметь коммиты которых у вас нет в локальном репозитории, то вы не сможете оправить свои изменения, вам нужно сначала получить коммиты из удаленного репозитория.
![image](https://user-images.githubusercontent.com/14871471/94119338-6f3b7980-fe57-11ea-8b36-c1d76cfd694e.png)
переведите то, что написано желтым.

2020-09-24 10:43 UTC, ZhizhikinIvan commented on LibOfTimetableOfClasses/CAcademicLoad.cs
> +                    && (string)this.Rows[i]["KindOfLesson"] == mAcademicLoad.Occupation)
Я думал, что проектирование БД не являлось моей задачей. Я исправлял явные ошибки, мешающие мне.

2020-09-24 10:46 UTC, ZhizhikinIvan commented on LibOfTimetableOfClasses/CAcademicLoad.cs
> +                //Unique = true  // не может быть уникальным!!!
Удалил

2020-09-24 10:47 UTC, YuriSilenok commented on LibOfTimetableOfClasses/CAcademicLoad.cs
> +                    && (string)this.Rows[i]["KindOfLesson"] == mAcademicLoad.Occupation)
Ну допустим. посмотрим что из этого получится.

2020-09-24 10:48 UTC, YuriSilenok commented on LibOfTimetableOfClasses/CAcademicLoad.cs
> +                //Unique = true  // не может быть уникальным!!!
сначала публикуете изменения, а потом пишете комментарий, потому что для меня сейчас до сих пор ничего не удалено

2020-09-24 10:53 UTC, ZhizhikinIvan commented on LibOfTimetableOfClasses/MAcademicLoad.cs
> +                if (value.Length > 110) throw new Exception("Кол-во символов не превышает 107");
Юрий Викторович, git pull выполнен первой командой, но ошибка осталась.

![image](https://user-images.githubusercontent.com/47943099/94136215-44f4b680-fe6d-11ea-8c8a-4f4d53df142d.png)

2020-09-24 11:00 UTC, YuriSilenok commented on LibOfTimetableOfClasses/MAcademicLoad.cs
> +                if (value.Length > 110) throw new Exception("Кол-во символов не превышает 107");
как только вы получаете такую ошибку, выполняйте еще раз команду `git pull` если напишет что все обновлена, тогда есть проблема и будем разбираться. а сейчас есть хорошая вероятность того, что после команды git pull и git push произошли изменения в удаленном репозитории

2020-09-24 11:12 UTC, ZhizhikinIvan commented on LibOfTimetableOfClasses/MAcademicLoad.cs
> +                if (value.Length > 110) throw new Exception("Кол-во символов не превышает 107");
![image](https://user-images.githubusercontent.com/47943099/94137711-88e8bb00-fe6f-11ea-8a68-35c1e0612f39.png)
Сделал 2 раза git pull, какие-то изменения пришли, но ошибка всё равно есть.

![image](https://user-images.githubusercontent.com/47943099/94137905-e1b85380-fe6f-11ea-969b-493e136b6b1d.png)
Сделал git pull ещё 2 раза (подчёркнуто), но не помогло.

2020-09-24 11:15 UTC, ZhizhikinIvan commented on LibOfTimetableOfClasses/CAcademicLoad.cs
> +                    && (string)this.Rows[i]["KindOfLesson"] == mAcademicLoad.Occupation)
>Думаю у нагрузки, как у документа, должен быть свой номер, как у приказов.

Что вы имеете ввиду под "приказами"?
Поле "номер" добавить не сложно, только вопрос в том, какого типа оно должно быть: строка или число (думаю что скорее всего строка)?

2020-09-24 11:17 UTC, YuriSilenok commented on LibOfTimetableOfClasses/MAcademicLoad.cs
> +                if (value.Length > 110) throw new Exception("Кол-во символов не превышает 107");
ну допустим, давайте разбираться.
покажите скрин окна на gitk команду

2020-09-24 11:26 UTC, YuriSilenok commented on LibOfTimetableOfClasses/CAcademicLoad.cs
> +                    && (string)this.Rows[i]["KindOfLesson"] == mAcademicLoad.Occupation)
я имею ввиду что нагрузка составляется каждый год, и когда вам понадобится составить вторую нагрузку, данные из первой нагрузки будут мешать составлять вторую нагрузку.

2020-09-24 11:28 UTC, ZhizhikinIvan commented on LibOfTimetableOfClasses/MAcademicLoad.cs
> +                if (value.Length > 110) throw new Exception("Кол-во символов не превышает 107");
![image](https://user-images.githubusercontent.com/47943099/94139323-21803a80-fe72-11ea-8e7e-940e5c70c9fb.png)

2020-09-24 11:32 UTC, YuriSilenok commented on LibOfTimetableOfClasses/MAcademicLoad.cs
> +                if (value.Length > 110) throw new Exception("Кол-во символов не превышает 107");
все, я понял.
по какой-то причине у вас локальная ветка task-1326 не привязана к удаленной ветке, об этом вам сообщается когда вы выполняете команду git pull. такое часто бывает когда вы создаете ветку локально.
Что вам нужно сделать
```
git branch --set-upstream-to=origin/task-1326 task-1326
git pull
```
возможны конфликты, но вряд ли. Если будут, решите их, скорее всего в пользу ветки dev
потом пробуйте git push

2020-09-24 11:43 UTC, YuriSilenok commented
ага, вижу что получилось.

2020-09-24 11:44 UTC, ZhizhikinIvan commented
Да, получилось. Спасибо.

2020-09-25 19:50 UTC, ZhizhikinIvan commented
@YuriSilenok 
Реализовывал работу ComboBox, выбирающих "институт", "нагрузку" и "группу". 

Есть проблема с доступность ComboBox (можно выбирать группу, когда этого не должно быть), для которой пока не нашёл решение.

2020-09-26 12:01 UTC, YuriSilenok commented
Хорошо, проблему самостоятельно решите?

2020-09-26 17:57 UTC, ZhizhikinIvan commented
@YuriSilenok 
Разобрался с проблемой. Надо было вместо события SelectedIndexChanget использовать событие SelectionChangeCommitted.

Далее буду думать над реализацией отображения расписания.

2020-09-26 18:01 UTC, YuriSilenok commented
Смотрите в сторону табличных контейнеров разметки

2020-09-26 18:04 UTC, ZhizhikinIvan commented
>Смотрите в сторону табличных контейнеров разметки

Я ещё окончательно не разобрался в взаимосвязях данных и какие данные нужны для отображения.

2020-09-26 18:07 UTC, YuriSilenok commented
Выглядеть должно как на сайте КГУ.

2020-09-28 18:04 UTC, ZhizhikinIvan commented
@YuriSilenok 
Я закомитил реализацию выбора института на форме AddDirectionOfPreparation и поправил некоторые ошибки в RefData.

У меня есть некоторые вопросы по расписанию:
Каким образом должна быть организованна связь между "Дисциплиной", "Аудиторией", "Днём" и "Временем проведения занятия" для группы?

Если лекция или практика для каждой группы всегда проводятся в одном и том же месте, то можно ссылку на "Аудиторию" добавить в CAcademicLoad. И туда же добавить "День недели" и "Время проведения занятия".

Или же должна быть отдельная сущность, хранящая "День недели", "Время", "Аудиторию" и ссылку на CAcademicLoad?

Или же расписание должно формироваться автоматически? Но тогда мне непонятны правила, по которым это должно происходить.

2020-09-29 07:08 UTC, YuriSilenok commented
> Каким образом должна быть организованна связь между "Дисциплиной", "Аудиторией", "Днём" и "Временем проведения занятия" для группы?

у вас должна быть таблица в которую вы заносите эти данные, пусть будет называется как `расписание`. у нее должны быть реляционные связи. мы не будем думать о нормализации, не та дисциплина.

2020-09-29 07:10 UTC, YuriSilenok commented
> Если лекция или практика, для каждой группы, всегда проводятся в одном и том же месте, то можно ссылку на "Аудиторию" добавить в CAcademicLoad.

Это отдельная функциональность, преподаватели подают сведения о том, в каких аудиториях они могли бы проводить свою дисциплину. не будем учитывать это в данной юзер стори

2020-09-29 07:12 UTC, YuriSilenok commented
> в CAcademicLoad. И туда же добавить "День недели" и "Время проведения занятия".

думаю в системе должна существовать таблица с учебным временем, она ляжет в основу ветки на форму, которая будет заполняться.

2020-09-29 07:14 UTC, YuriSilenok commented
> Или же расписание должно формироваться автоматически?

расписание будет формироваться вручную, это первый этап автоматизации. потом будет сделан помощник, который подсказывает, куда можно поставить пару, а куда нельзя. третьим этапом будет функция автоматической расстановки расписания.

2020-09-29 17:46 UTC, YuriSilenok requested changes
Нарушены [требования именования веток](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/branches.md#issue-d). Головная ветка task-1326 не соответствует требованиям.

2020-09-29 17:46 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1358', '#1355']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-29 17:48 UTC, YuriSilenok commented
Нарушены [требования именования веток](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/branches.md#issue-d). Головная ветка task-1326 не соответствует требованиям.

2020-09-29 17:55 UTC, YuriSilenok commented
Нарушены [требования именования веток](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/branches.md#issue-d). Головная ветка task-1326 не соответствует требованиям.

2020-09-29 17:55 UTC, closed without merging

2020-09-29 17:59 UTC, ZhizhikinIvan commented
@YuriSilenok Юрий Викторович, что бы переоткрыть задачу мне необходимо сделать так, что бы ветка соответствовала требованиям. Не могли бы вы подсказать, как это сделать?

2020-09-29 20:53 UTC, YuriSilenok commented
все ответы по git есть в чате

2020-09-29 21:25 UTC, ZhizhikinIvan commented
@YuriSilenok 
Не смог найти информацию в чате, так как с момента обсуждения прошло прилично времени, поэтому полез в гугл.

Вот что нашёл:
>git branch -m `имя новой ветки`
>git push origin : `имя старой ветки`
>git push --set-upstream origin `имя новой ветки`

2020-09-29 21:40 UTC, YuriSilenok commented
жаль что вы не разобрались в значениях этих команд до конца.
давайте учиться задавать вопросы, спросите у коллег, как они это делали