Исправил опечатки, которые увидел
Students-of-the-city-of-Kostroma/Student-timetable pull request #1341
Opened 2020-08-30 21:56 UTC by NesgovorovVS

#1340

2020-09-02 09:15 UTC, YuriSilenok reviewed
@Students-of-the-city-of-Kostroma/17-elite 
Пожалуйста, выполните внесите свой редакционный вклад в это.
Проверьте на предмет ошибок.

2020-09-02 09:36 UTC, Alphavite51 requested changes
несколько слов написаны не верно

2020-09-02 09:36 UTC, Alphavite51 commented on README.md
>  - Студент создает ветку имя которой соответвует описанному выше шаблону, где номер в имени ветки это номер задачи
имя которой "СоответСТвует"

2020-09-02 09:36 UTC, Alphavite51 commented on README.md
> +- Студент реализует задачу в ветку и запрашивает запрос на слияние. При это имя запроса должно соответсвовать шаблону "WIP: ИмяЗадачиДляКоторойВыполняетсяЗапрос",  а описание должно содержать текст "
имя запроса должно "СоответсТвовать"

2020-09-02 09:36 UTC, Alphavite51 commented on README.md
>  # Ответсвенность
ОтветсТвенность

2020-09-02 09:36 UTC, Alphavite51 commented on README.md
> +- Ни на кого неназначеные открытые задачи без меток состояния выплнения - эти задачи формируют список задач из которого участник проекта может взять на исполнение.
без меток состояния "выпОлнения"

2020-09-02 09:36 UTC, Alphavite51 commented on README.md
> +- Задача имеет исполнителя и помечена меткой Doing - это значит, что к исполнению этой задачи уже приступили. Если нет активности в течении недели, то у задачи будет снята метка Doing и выставлена ме
в течениЕ недели

2020-09-02 09:36 UTC, Alphavite51 commented on README.md
> +Создаются исполнителем задач с целью предоставления работы на проверку, после которой последует слияние ветки которая сдержит изменение кода в ветку Testing. Запрос на слияние должен иметь исполнител
после которой последует слияние ветки "запятая" которая...

2020-09-02 09:36 UTC, Alphavite51 commented on README.md
>  - Model - (MVC) Задача на разработку кода организуюший хранение данных. Если упомянут класс, который начинается с большой буквы M, например, MGroup, то задача должна быть помечена меткой Model.
на разработку кода "организуюЩий"

2020-09-02 11:48 UTC, Alphavite51 requested changes
3 строчка опыт работы с репОзиторием.
12 строчка соответствующим номеру задачи по Шаблону
21 Ни на кого неназначеные (раздельно)
32 задача на устранения несоотвеТСТВИЯ, и заявленной с 2 "Н" , что значит в баге "всегода" (Все в 32 строке)
45 тестовых сцеНАриев
68 обязательный (без В)
85 указывает статус (без Т на конце)

2020-09-02 11:49 UTC, Alphavite51 reviewed
написал по строкам потому что не могу выделить некоторые из них, да и так думаю вам легче будет исправить зная номера строк

2020-09-03 09:38 UTC, NesgovorovVS commented
> 3 строчка опыт работы с репОзиторием.
> 12 строчка соответствующим номеру задачи по Шаблону
> 21 Ни на кого неназначеные (раздельно)
> 32 задача на устранения несоотвеТСТВИЯ, и заявленной с 2 "Н" , что значит в баге "всегода" (Все в 32 строке)
> 45 тестовых сцеНАриев
> 68 обязательный (без В)
> 85 указывает статус (без Т на конце)

исправил ошибки, в 21 строке неназначенные пишется слитно, но увидел другую ошибку, что с одной "н" было написано

2020-09-03 16:07 UTC, YuriSilenok commented
Если все исправили, то запросите у человека повторную проверку. Он будет знать, что пора перепроверить и подтвердить что все исправлено.

2020-09-04 06:41 UTC, ssas18 approved these changes, later dismissed
Не силен в поисках опечаток, на мой взгляд все верно

2020-09-04 08:49 UTC, YuriSilenok commented
> Не силен в поисках опечаток, на мой взгляд все верно

А вдруг Вы знаете правило, на которое здесь ошибка.

2020-09-04 08:50 UTC, YuriSilenok commented
> > 3 строчка опыт работы с репОзиторием.
> > 12 строчка соответствующим номеру задачи по Шаблону
> > 21 Ни на кого неназначеные (раздельно)
> > 32 задача на устранения несоотвеТСТВИЯ, и заявленной с 2 "Н" , что значит в баге "всегода" (Все в 32 строке)
> > 45 тестовых сцеНАриев
> > 68 обязательный (без В)
> > 85 указывает статус (без Т на конце)
> 
> исправил ошибки, в 21 строке неназначенные пишется слитно, но увидел другую ошибку, что с одной "н" было написано

исправляйте все что найдете.

2020-09-06 05:53 UTC, ssas18 approved these changes, later dismissed

2020-09-06 07:49 UTC, MyachevM submitted a review, later dismissed

2020-09-06 09:36 UTC, ifuwmnn submitted a review, later dismissed

2020-09-07 05:43 UTC, Alphavite51 approved these changes
Посмотрите

2020-09-07 05:45 UTC, YuriSilenok commented
> Посмотрите

Кому вы пишите?

2020-09-07 14:03 UTC, Alphavite51 commented on README.md
>  * Исчезновение вертикального скролла для таблцы Преподаватели
таблИцы

2020-09-07 14:03 UTC, Alphavite51 requested changes
Исправьте пожалуйста

2020-09-07 14:06 UTC, NesgovorovVS commented
> Исправьте пожалуйста

Исправил)

2020-09-07 14:11 UTC, Alphavite51 approved these changes

2020-09-07 14:20 UTC, JennyShel18 approved these changes

2020-09-07 16:04 UTC, Alphavite51 requested changes
У вас есть непроверенные запросы ['#1342', '#1335', '#1333', '#1329', '#1322', '#1294', '#1217']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-07 17:09 UTC, ssas18 approved these changes

2020-09-07 17:19 UTC, MyachevM approved these changes

2020-09-07 17:42 UTC, NordScandinavian approved these changes

2020-09-07 20:15 UTC, VinogradovAlexandr781227 approved these changes
Ошибок, правила на которые я знаю не нашел

2020-09-08 04:22 UTC, YuriSilenok commented
> У вас есть непроверенные запросы ['#1342', '#1335', '#1333', '#1329', '#1322', '#1294', '#1217']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

Зачем это здесь?

2020-09-08 04:45 UTC, YuriSilenok approved these changes

2020-09-08 11:52 UTC, ifuwmnn approved these changes

2020-09-08 12:19 UTC, Alphavite51 approved these changes

2020-09-08 12:58 UTC, merged

2020-09-15 17:27 UTC, NesgovorovVS commented
@YuriSilenok , прошу отметить эту задачу в журнале.

2020-09-15 17:37 UTC, YuriSilenok commented
Это НЕ задача

2020-09-15 18:57 UTC, NesgovorovVS commented
> Это НЕ задача

а где можно найти ваши слова про то, что это можно зачесть как задачу, если мне удастся, чтобы было 5 проверок?

2020-09-15 18:58 UTC, NesgovorovVS commented
> Это НЕ задача

понял свою ошибку, напишу в задачу

2020-09-15 18:59 UTC, NesgovorovVS commented
> > Это НЕ задача
> 
> понял свою ошибку, извиняюсь