Разработал функцию корректировки норм учебной нагрузки для сотрудников вуза
Students-of-the-city-of-Kostroma/Student-timetable pull request #1342
Opened 2020-09-02 07:26 UTC by Heriuple

Добавил изменения в формы: Стартовая, преподаватели, ученое звание. В форме стартовая, изменил название справочника преподаватели на сотрудники, в форме преподаватели изменил название формы на сотрудники и добавил графу должность (в дальнейшем добавлю поле для выбора должности в форму добавления преподавателя). В форму ученое звание добавил поля для ввода минимального и максимального кол-ва часов. Всё это пока не имеет функционала, ждет подтверждения, о том, правильно ли понял задачу.

2020-09-04 06:48 UTC, ssas18 reviewed
Первый раз сталкиваюсь с таким запросом на проверку и пока не понимаю что и как проверять, Юрий Викторович вроде как обещал документ для такого типа запросов, после его появления обязательно проверю твой запрос

2020-09-04 08:14 UTC, MyachevM reviewed
Я честно говоря соглашусь с @ssas18, так как тоже не имею пока понятия, как проверять такие запросы

2020-09-05 13:32 UTC, ifuwmnn reviewed
Поддержу коллег, пока не понятно как оценивать данные запросы.

2020-09-05 17:50 UTC, YuriSilenok commented
Поднял задачу #1344, по её завершению будет понятно как проверять работу и что вообще из себя представляет user story.

2020-09-09 11:30 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1335', '#1333', '#1329', '#1309', '#1295', '#1294', '#1217']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-09 11:30 UTC, YuriSilenok commented
У вас есть непроверенные запросы []. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-09 12:10 UTC, YuriSilenok requested changes
@Students-of-the-city-of-Kostroma/elite 
Давайте начнем проверять со здравого смысла.
Вот сказано что часы зависят от должности, а должность невозможно указать
![image](https://user-images.githubusercontent.com/14871471/92596511-95d1b000-f2ae-11ea-8b7b-6e3adeb3c3ff.png)

2020-09-09 12:10 UTC, YuriSilenok commented on TimetableOfClasses/Teachers.cs
> +        }
Зачем?

2020-09-09 12:24 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1335', '#1333', '#1329', '#1309', '#1295', '#1294', '#1217']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-10 10:39 UTC, Heriuple commented on TimetableOfClasses/Teachers.cs
> +        }
Я так и указал, что в дальнейшем буду добавлять отдельное поле для должности. В течение дня внесу изменения.

2020-09-10 12:25 UTC, YuriSilenok commented on TimetableOfClasses/Teachers.cs
> +        }
Да, простите, не увидел сразу, тогда запросите проверку, когда вы посчитаете что все готово.

2020-09-11 20:07 UTC, NordScandinavian requested changes
Согласен с Юрием Викторовичем.

2020-09-14 18:51 UTC, NordScandinavian requested changes
Согласен с Юрием Викторовичем.

2020-09-15 10:36 UTC, YuriSilenok commented
> Согласен с Юрием Викторовичем.

С чем Вы тут согласны, нет цитат, Вас не просиил проверять, а Вы спамите.

2020-09-22 07:25 UTC, closed without merging