Добавил описание жизненного цикла для задачи
Students-of-the-city-of-Kostroma/Student-timetable pull request #1353
Opened 2020-09-11 09:31 UTC by YuriSilenok

closed #1352

2020-09-11 13:34 UTC, Alphavite51 approved these changes, later dismissed

2020-09-11 15:45 UTC, NesgovorovVS requested changes

2020-09-11 15:45 UTC, NesgovorovVS commented on Docs/Life-cycle.md
> +- - Если проверяюший указал на проблему, то после устранения проблемы, необходимо повторно запросить у проверяющего проверку.
*проверяюЩий

2020-09-11 17:08 UTC, NesgovorovVS requested changes

2020-09-11 17:08 UTC, NesgovorovVS commented on Docs/Life-cycle.md
> +- На внесение любых изменений в репозитории создается задача (issue) соответсвующая требованиям (здесь будет ссылка на требования)[].
могу ошибаться, но в 3,4,5 строке перед соответствующая ставится ","

2020-09-13 19:23 UTC, NesgovorovVS approved these changes

2020-09-13 19:23 UTC, NesgovorovVS approved these changes, later dismissed

2020-09-17 08:25 UTC, YuriSilenok commented
Добавленная ссылка в документе начнет работать, после мержа с веткой dev.

2020-09-17 12:44 UTC, ifuwmnn approved these changes

2020-09-17 14:43 UTC, merged