Исправление сбоев в автотестах расположенных в файле UT-Deleted-CTeacher
Students-of-the-city-of-Kostroma/Student-timetable pull request #1355
Opened 2020-09-20 08:52 UTC by MyachevM

#1281

2020-09-20 11:12 UTC, ifuwmnn submitted a review, later dismissed

2020-09-20 17:25 UTC, YuriSilenok commented
Основная задача #1281 назначена на преподавателя. Это значит вы не можете вести дальнейшую активность по этой задаче.

2020-09-20 17:59 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1335', '#1333', '#1329']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-20 17:59 UTC, YuriSilenok commented
Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/labels.md) для метки `Unit test`

2020-09-20 17:59 UTC, YuriSilenok commented
Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/labels.md) для метки `Unit test`

2020-09-20 17:59 UTC, YuriSilenok commented
Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/labels.md) для метки `Unit test`

2020-09-20 17:59 UTC, YuriSilenok commented
Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/labels.md) для метки `Unit test`

2020-09-20 17:59 UTC, YuriSilenok commented
Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/labels.md) для метки `Unit test`

2020-09-20 17:59 UTC, YuriSilenok commented
Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/labels.md) для метки `Unit test`

2020-09-20 17:59 UTC, YuriSilenok commented
Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/labels.md) для метки `Unit test`

2020-09-20 17:59 UTC, YuriSilenok commented
Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/labels.md) для метки `Unit test`

2020-09-21 18:26 UTC, YuriSilenok requested changes
Файл `Docs/UT-Deleted-CTeacher/CODE.jpg` не соответствует требованиям. Нарушены требования именования папок или файлов к [белому ящику](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/White-box/README.md) или [модульным тестам](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Unit-test/README.md).

2020-09-21 18:26 UTC, YuriSilenok commented
Не найдены сопутствующие метки для `Unit test`. Нарушены[требования](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/labels.md) для меток.

2020-09-22 11:17 UTC, YuriSilenok requested changes
Файл `Docs/UT-Deleted-CTeacher/CODE.jpg` не соответствует требованиям. Нарушены требования именования папок или файлов к [белому ящику](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/White-box/README.md) или [модульным тестам](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Unit-test/README.md).

2020-09-22 11:17 UTC, YuriSilenok commented
Не найдены сопутствующие метки для `Unit test`. Нарушены [требования](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/labels.md) для меток.

2020-09-22 11:30 UTC, YuriSilenok requested changes
Файл `Docs/UT-Deleted-CTeacher/code.png` не соответствует требованиям. Нарушены требования именования папок или файлов к [белому ящику](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/White-box/README.md) или [модульным тестам](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Unit-test/README.md).

2020-09-22 11:30 UTC, YuriSilenok commented
Не найдены сопутствующие метки для `Unit test`. Нарушены [требования](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/labels.md) для меток.

2020-09-22 14:40 UTC, ifuwmnn reviewed
Исправь имя папки 
![image](https://user-images.githubusercontent.com/47635280/93897272-8e70c480-fcfa-11ea-89db-40e97d1631d5.png)
![image](https://user-images.githubusercontent.com/47635280/93897379-ac3e2980-fcfa-11ea-89f8-a2eabd0d04ee.png)

2020-09-22 14:44 UTC, ifuwmnn commented
> Исправь имя папки
> ![image](https://user-images.githubusercontent.com/47635280/93897272-8e70c480-fcfa-11ea-89db-40e97d1631d5.png)
> ![image](https://user-images.githubusercontent.com/47635280/93897379-ac3e2980-fcfa-11ea-89f8-a2eabd0d04ee.png)

Не туда посмотрел, написал чушь

2020-09-22 15:38 UTC, YuriSilenok commented
> > Исправь имя папки
> > ![image](https://user-images.githubusercontent.com/47635280/93897272-8e70c480-fcfa-11ea-89db-40e97d1631d5.png)
> > ![image](https://user-images.githubusercontent.com/47635280/93897379-ac3e2980-fcfa-11ea-89f8-a2eabd0d04ee.png)
> 
> Не туда посмотрел, написал чушь

в этом есть истина, отчеты к тестам переезжают в папку с тестами

2020-09-23 17:12 UTC, MyachevM commented
> 
> 
> Исправь имя папки
> ![image](https://user-images.githubusercontent.com/47635280/93897272-8e70c480-fcfa-11ea-89db-40e97d1631d5.png)
> ![image](https://user-images.githubusercontent.com/47635280/93897379-ac3e2980-fcfa-11ea-89f8-a2eabd0d04ee.png)

Такая папка уже вроде есть в файлах проекта
Туда закидывать отчёт и скрины кода и графа ?

2020-09-23 17:16 UTC, YuriSilenok commented
> > Исправь имя папки
> > ![image](https://user-images.githubusercontent.com/47635280/93897272-8e70c480-fcfa-11ea-89db-40e97d1631d5.png)
> > ![image](https://user-images.githubusercontent.com/47635280/93897379-ac3e2980-fcfa-11ea-89f8-a2eabd0d04ee.png)
> 
> Такая папка уже вроде есть в файлах проекта
> Туда закидывать отчёт и скрины кода и графа ?

понять не могу, почему вы выделили только часть пути, папку верхнего уровня?
Напишите пожалуйста путь, куда вы собираетесь перемещать свои отчеты
@NesgovorovVS, пожалуйста, проконтролируйте.

2020-09-24 10:10 UTC, NordScandinavian requested changes
Требования по белому ящику выполнены частично. 
Переименуй папку по требованиям.

2020-09-24 12:29 UTC, YuriSilenok requested changes
Файл `Docs/UT-Deleted-CTeacher/code.png` не соответствует требованиям. Нарушены требования именования папок или файлов к [белому ящику](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/White-box/README.md) или [модульным тестам](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Unit-test/README.md).

2020-09-24 12:30 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1360', '#1358', '#1357', '#1356']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-24 12:30 UTC, YuriSilenok commented
Не найдены сопутствующие метки для `Unit test`. Нарушены [требования](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/labels.md) для меток.

2020-09-24 17:40 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1360']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-24 17:40 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1358', '#1357', '#1356']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-24 17:40 UTC, YuriSilenok commented
Не найдены сопутствующие метки для `Unit test`. Нарушены [требования](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/labels.md) для меток.

2020-09-24 17:45 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1360']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-24 17:45 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1358', '#1357', '#1356']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-24 17:45 UTC, YuriSilenok commented
Не найдены сопутствующие метки для `Unit test`. Нарушены [требования](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/labels.md) для меток.

2020-09-24 18:01 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1360']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-24 18:01 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1358', '#1357', '#1356']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-27 18:51 UTC, YuriSilenok reviewed
![image](https://user-images.githubusercontent.com/14871471/94373063-77bbda80-010b-11eb-8207-77c0ef070d13.png)
У вас многовато пятых вершин.
Вот их этой пятой вершины вы попадаете в 6 вершину? 
Вы сможете это воспроизвести в VS?

2020-09-27 19:17 UTC, MyachevM commented
> 
> 
> ![image](https://user-images.githubusercontent.com/14871471/94373063-77bbda80-010b-11eb-8207-77c0ef070d13.png)
> У вас многовато пятых вершин.
> Вот их этой пятой вершины вы попадаете в 6 вершину?
> Вы сможете это воспроизвести в VS?

Да, попадаю в шестую от пятой которую вы обвели красным кругом

2020-09-27 19:21 UTC, YuriSilenok commented
могли бы предоставить скрины или видео пошаговой отладки где вы попадаете из 5 вершины, обведенной красным, в вершину 6?

2020-09-27 20:07 UTC, MyachevM commented
> 
> 
> могли бы предоставить скрины или видео пошаговой отладки где вы попадаете из 5 вершины, обведенной красным, в вершину 6?

да, смогу, но только уже завтра

2020-09-28 19:43 UTC, badsster commented
![IMG_20200928_224048](https://user-images.githubusercontent.com/47521045/94478374-dea8c480-01db-11eb-96ff-78607e5ffaa4.png)
Не могу найти папку с файлами для проверки отчёта UT_Deleted_CTeacher

2020-09-28 19:59 UTC, badsster commented
Нашла в папке с Unit тестами, прошу прощения. Тоже не понимаю, как их 5 мы попадаем в 6. Думаю, что если выполняется 5, то мы попадаем в 8. Но не уверена. Тоже мы хотелось понять этот момент.

2020-09-30 08:31 UTC, YuriSilenok requested changes
Файл `UnitTestOfTimetableOfClasses/UT_Delete_CTeacher.cs` не соответствует требованиям. Нарушены требования именования папок или файлов к [белому ящику](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/White-box/README.md) или [модульным тестам](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Unit-test/README.md).

2020-09-30 08:31 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1361']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-30 08:31 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1363']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-02 08:14 UTC, YuriSilenok requested changes
Файл `UnitTestOfTimetableOfClasses/CTeacher/Delete/UT_Delete_CTeacher.cs` не соответствует требованиям. Нарушены требования именования папок или файлов к [белому ящику](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/White-box/README.md) или [модульным тестам](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Unit-test/README.md).

2020-10-03 13:21 UTC, YuriSilenok requested changes
Файл `UnitTestOfTimetableOfClasses/CTeacher/Delete/UT_Delete_CTeacher.cs` не соответствует требованиям. Нарушены требования именования папок или файлов к [белому ящику](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/White-box/README.md) или [модульным тестам](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Unit-test/README.md).

2020-10-03 13:27 UTC, YuriSilenok requested changes
Файл `UnitTestOfTimetableOfClasses/CTeacher/Delete/UT_Delete_CTeacher.cs` не соответствует требованиям. Нарушены требования именования папок или файлов к [белому ящику](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/White-box/README.md) или [модульным тестам](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Unit-test/README.md).

2020-10-03 20:28 UTC, YuriSilenok commented
Я начинаю тестировать новый функционал скрипта на вашем запросе.

2020-10-03 20:39 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UT_Delete_CTeacher.cs
> +        [TestMethod]
ожидается начало комментария `/// <summary>` или конец класса

2020-10-03 20:53 UTC, YuriSilenok commented
Нарушены [требования именования веток](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/branches.md#issue-d). Созданная ветка 1355 была удалена.

2020-10-04 17:06 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UT_Delete_CTeacher.cs
> +        [TestMethod]
Ожидается начало комментария `/// <summary>` или конец класса

2020-10-05 13:36 UTC, YuriSilenok requested changes
Файл `UnitTestOfTimetableOfClasses/CTeacher/Delete/UT_Delete_CTeacher.cs` не соответствует требованиям. Нарушены требования именования папок или файлов к [белому ящику](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/White-box/README.md) или [модульным тестам](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Unit-test/README.md).

2020-10-05 13:36 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1366']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-05 14:23 UTC, ifuwmnn requested changes
Я полностью не уверен, но видимо ошибка с именованием кроется где-то здесь.  
![image](https://user-images.githubusercontent.com/47635280/95091106-b1ee3300-072e-11eb-8d0e-abd40eea6a9c.png)
![image](https://user-images.githubusercontent.com/47635280/95091299-f24db100-072e-11eb-8d0e-bbe2b796a665.png)

2020-10-05 14:30 UTC, YuriSilenok requested changes
Файл `UnitTestOfTimetableOfClasses/UT_Delete_CTeacher.cs` не соответствует требованиям. Нарушены требования именования папок или файлов к [белому ящику](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/White-box/README.md) или [модульным тестам](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Unit-test/README.md).

2020-10-05 14:50 UTC, YuriSilenok commented
> Файл `UnitTestOfTimetableOfClasses/UT_Delete_CTeacher.cs` не соответствует требованиям. Нарушены требования именования папок или файлов к [белому ящику](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/White-box/README.md) или [модульным тестам](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Unit-test/README.md).

Видимо нужно поправить что бы игнорировались проверки для полностью удаленных файлов, если такое возможно.

2020-10-05 14:59 UTC, YuriSilenok requested changes
Файл `UnitTestOfTimetableOfClasses/UT_Delete_CTeacher.cs` не соответствует требованиям. Нарушены требования именования папок или файлов к [белому ящику](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/White-box/README.md) или [модульным тестам](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Unit-test/README.md).

2020-10-05 14:59 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +        [TestMethod]
Ожидается начало комментария `/// <summary>` или конец класса

2020-10-05 14:59 UTC, YuriSilenok commented
Проверку поправил

2020-10-05 15:01 UTC, YuriSilenok requested changes
Файл `UnitTestOfTimetableOfClasses/UT_Delete_CTeacher.cs` не соответствует требованиям. Нарушены требования именования папок или файлов к [белому ящику](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/White-box/README.md) или [модульным тестам](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Unit-test/README.md).

2020-10-05 15:01 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +        [TestMethod]
Ожидается начало комментария `/// <summary>` или конец класса

2020-10-05 15:07 UTC, YuriSilenok requested changes
Файл `UnitTestOfTimetableOfClasses/UT_Delete_CTeacher.cs` не соответствует требованиям. Нарушены требования именования папок или файлов к [белому ящику](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/White-box/README.md) или [модульным тестам](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Unit-test/README.md).

2020-10-05 15:07 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +        [TestMethod]
Ожидается начало комментария `/// <summary>` или конец класса

2020-10-05 15:08 UTC, ifuwmnn requested changes
У тебя не правильно оформлено написание, что тестируется  
У тебя так 
![image](https://user-images.githubusercontent.com/47635280/95096811-6c813400-0735-11eb-87f3-5ec124cde7d2.png) 
А должно быть так  
        
![image](https://user-images.githubusercontent.com/47635280/95097262-f29d7a80-0735-11eb-934d-6f82209223c4.png)

2020-10-05 15:54 UTC, YuriSilenok commented
Продолжаю проверку скрипта

2020-10-05 15:55 UTC, YuriSilenok requested changes
Файл `UnitTestOfTimetableOfClasses/UT_Delete_CTeacher.cs` не соответствует требованиям. Нарушены требования именования папок или файлов к [белому ящику](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/White-box/README.md) или [модульным тестам](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Unit-test/README.md).

2020-10-05 18:34 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +        [TestMethod]
Ожидается начало комментария `/// <summary>` или конец класса

2020-10-05 18:34 UTC, YuriSilenok commented
Нет обработчика для файла UnitTestOfTimetableOfClasses/CTeacher/Delete/whiteBox.md

2020-10-05 19:29 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +        [TestMethod]
Ожидается начало комментария `/// <summary>` или конец класса

2020-10-05 19:29 UTC, YuriSilenok commented
Нет обработчика для файла UnitTestOfTimetableOfClasses/CTeacher/Delete/whiteBox.md

2020-10-05 19:37 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +        [TestMethod]              /// <summary>
Ожидается начало комментария `/// <summary>` или конец класса

2020-10-05 19:37 UTC, YuriSilenok commented
Нет обработчика для файла UnitTestOfTimetableOfClasses/CTeacher/Delete/whiteBox.md

2020-10-06 13:12 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +        [TestMethod]              /// <summary>
@MyachevM где Вы нашли такой вариант расположения комментариев?
Думаю мне стоит добавить ссылку в сообщение на то, как это делается.

2020-10-06 14:08 UTC, MyachevM commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +        [TestMethod]              /// <summary>
> 
> 
> @MyachevM где Вы нашли такой вариант расположения комментариев?
> Думаю мне стоит добавить ссылку в сообщение на то, как это делается.

в требованиях увидел эту информацию про комментарии 
подумал стоит попробовать написать комментарии таким образом

2020-10-06 14:56 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +        [TestMethod]              /// <summary>
А как на счет погуглить?

2020-10-06 15:48 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +        [TestMethod]
Ожидается [начало комментария](https://habr.com/ru/post/41514/) `/// <summary>` или конец класса

2020-10-06 15:48 UTC, YuriSilenok commented
Нет обработчика для файла `UnitTestOfTimetableOfClasses/CTeacher/Delete/whiteBox.md`

2020-10-07 14:49 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1368', '#1367', '#1360']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-07 14:49 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +    /// <summary>
В файле `UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs` после строки `    [TestClass]` ожидается любое из списка`[' {4}public class UT_((I|U|D)С)|(AcademicDegree|AcademicLoad|Auditor|DirectionOfPreparation|Discipline|Enclosures|Group|HEI|Institute|StudyWeek|Teacher|Title|TrainingProfiles|TypesOfOccupations|University)', ' {4}public class UT_M|(AcademicDegree|AcademicLoad|Auditor|DirectionOfPreparation|Discipline|Enclosures|Group|HEI|Institute|StudyWeek|Teacher|Title|TrainingProfiles|TypesOfOccupations|University)']`

2020-10-07 15:10 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +    /// <summary>
В файле `UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs` после строки `{` ожидается любое из списка`[' {4}\\[TestClass\\]']`

2020-10-07 15:22 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +    /// <summary>
В файле `UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs` после строки `` ожидается любое из списка`['$', 'namespace UnitTestOfTimetableOfClasses']`

2020-10-07 15:27 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +    /// <summary>
В файле `UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs` после строки `` ожидается любое из списка`['(\\ufeff){,1}using [\\w+\\.]+;', '$']`

2020-10-07 15:33 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +    /// <summary>
В файле `UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs` после строки `    public class UT_DСTeacher                    ` ожидается любое из списка`[' {4}\\{']`

2020-10-07 15:40 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +        [TestMethod]
Ожидается [начало комментария](https://habr.com/ru/post/41514/) `/// <summary>` или конец класса

2020-10-07 21:09 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +        [TestMethod]
к полям так же нужны комментарии

2020-10-08 15:49 UTC, ifuwmnn requested changes
У тебя так 
![image](https://user-images.githubusercontent.com/47635280/95482292-a3a25000-0996-11eb-9fd6-7637c2fb1ebc.png)
а должно быть так 
![image](https://user-images.githubusercontent.com/47635280/95482552-f2e88080-0996-11eb-800c-3bb6e262763c.png)
(код со второго скрина никак не относится к твоей задаче)

2020-10-08 16:18 UTC, YuriSilenok commented
к полю refData так же должен быть комментарий

2020-10-08 18:24 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1366']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-08 18:24 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +        /// Удаление сведений в пустой таблице преподавателей
В файле `UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs` после строки `        /// <summary>` ожидается любое из списка`[' {8}///[\\w+\\.]+', ' {8}/// </summary>']`

2020-10-08 18:24 UTC, YuriSilenok commented
Неизвестный файл `UnitTestOfTimetableOfClasses/CTeacher/Delete/whiteBox.md`

2020-10-08 18:25 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +        /// Удаление сведений в пустой таблице преподавателей
так, что-то тут не так, смотрю

2020-10-08 18:29 UTC, YuriSilenok commented
> Неизвестный файл `UnitTestOfTimetableOfClasses/CTeacher/Delete/whiteBox.md`

с виду тут все верно, буду смотреть на это

2020-10-08 18:30 UTC, MyachevM commented
> У тебя так
> ![image](https://user-images.githubusercontent.com/47635280/95482292-a3a25000-0996-11eb-9fd6-7637c2fb1ebc.png)
> а должно быть так
> ![image](https://user-images.githubusercontent.com/47635280/95482552-f2e88080-0996-11eb-800c-3bb6e262763c.png)
> (код со второго скрина никак не относится к твоей задаче)

![image](https://user-images.githubusercontent.com/47633738/95499142-82992980-09ad-11eb-8e43-e68ed47a29e1.png)

2020-10-08 19:02 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1366']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-08 19:18 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1366']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-08 19:27 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1366']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-08 19:35 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1366']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-08 19:36 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1366']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-08 19:59 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1366']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-08 19:59 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +        [TestMethod]
В файле `UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs` после строки `        /// </summary>` ожидается любое из списка`[' {8}///[\\w+ \\.]+', ' {8}/// </summary>']`

2020-10-08 19:59 UTC, YuriSilenok commented
Неизвестный файл `UnitTestOfTimetableOfClasses/CTeacher/Delete/whiteBox.md`

2020-10-08 20:06 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1366']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-08 20:12 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1366']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-08 20:17 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +        [TestMethod]
В файле `UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs` после строки `        /// </summary>` ожидается любое из списка`['\\[TestMethod\\]']`

2020-10-08 20:17 UTC, YuriSilenok commented
Неизвестный файл `UnitTestOfTimetableOfClasses/CTeacher/Delete/whiteBox.md`

2020-10-08 20:18 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1366']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-08 20:18 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +        {
В файле `UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs` после строки `        public void DCTeacher_1()` ожидается любое из списка`[' {12}\\{']`

2020-10-08 20:18 UTC, YuriSilenok commented
Неизвестный файл `UnitTestOfTimetableOfClasses/CTeacher/Delete/whiteBox.md`

2020-10-08 20:31 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1366']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-08 20:31 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +        }
В файле `UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs` после строки `            Assert.AreEqual(refData.CTeacher.Delete(tcher), false, "Преподаватель был удалён, не смотря на то, что таблица преподавателей пуста");` ожидается любое из списка`[' {12}.*', ' {8}\\}$']`

2020-10-09 07:51 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1366']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-09 08:00 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +        }
В файле `UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs` после строки `            Assert.AreEqual(refData.CTeacher.Delete(tcher), false, "Преподаватель был удалён, не смотря на то, что таблица преподавателей пуста");` ожидается любое из списка`[' {12}.*', ' {8}\\}$']`

2020-10-09 08:01 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +        }
у вас пробел после фигурной скобки в 19 строке.

2020-10-09 10:56 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +        {
После строки `        public void DCTeacher_1()` ожидается любое из списка`[' {8}\\{$']`

2020-10-09 18:08 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +        {
Вы знаете в чем проблема?

2020-10-10 18:53 UTC, MyachevM commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +        {
> Вы знаете в чем проблема?

Честно говоря не понимаю, так как у меня стоит открывающая скобка как и положено
а комментарий к методу есть и находится на своём месте где и должен быть

2020-10-10 19:10 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +        {
![image](https://user-images.githubusercontent.com/14871471/95663153-51ebf800-0b45-11eb-9af2-c1f78061b4f8.png)
Проблема в этих пробелах.

2020-10-11 09:26 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1361', '#1358', '#1357', '#1356']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-11 09:26 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +namespace UnitTestOfTimetableOfClasses
После строки `` ожидается любое из списка`['$', 'namespace UnitTestOfTimetableOfClasses\\.CTeacher\\.Delete$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-10-11 18:41 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1364']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-11 18:41 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +namespace UnitTestOfTimetableOfClasses
После строки `using Microsoft.VisualStudio.TestTools.UnitTesting;` ожидается любое из списка`['(\\ufeff){,1}using [\\w+\\.]+;$', '$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-10-11 18:58 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +namespace UnitTestOfTimetableOfClasses
После строки `` ожидается любое из списка`['$', 'namespace UnitTestOfTimetableOfClasses\\.CTeacher\\.Delete$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-10-12 20:03 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1366']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-12 20:03 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +namespace UnitTestOfTimetableOfClasses
После строки `` ожидается любое из списка`['$', 'namespace UnitTestOfTimetableOfClasses\\.CTeacher\\.Delete$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-10-13 19:02 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +namespace UnitTestOfTimetableOfClasses
После строки `` ожидается любое из списка`['$', 'namespace UnitTestOfTimetableOfClasses\\.CTeacher\\.Delete$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-10-14 13:26 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +        /// <summary>
После строки `{` ожидается любое из списка`[' {4}\\[TestClass\\]$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-10-14 13:31 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +        /// <summary>
После строки `    {` ожидается любое из списка`[' {8}readonly RefData refData = new RefData\\(\\);$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-10-14 17:56 UTC, MyachevM commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +        /// <summary>
Не понимаю почему комментарий не проходит
Если я поставлю ниже рефдаты комментарий, он сошлётся на строку после Рефдаты

2020-10-15 14:01 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +/// <summary>
После строки `{` ожидается любое из списка`[' {4}\\[TestClass\\]$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-10-15 15:46 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1371']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-15 15:48 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1371']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-15 15:51 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1371']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-15 16:02 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1371']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-15 16:07 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1371']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-15 16:07 UTC, YuriSilenok commented
Проблема в файле UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs. 
После строки `{` ожидается любое из списка`[' {4}/// <summary>$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-10-15 16:38 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1371']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-15 16:38 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +    /// <summary>
После строки `    {` ожидается любое из списка`[' {8}readonly RefData refData = new RefData\\(\\);$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-10-15 16:39 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +    /// <summary>
Здесь что-то пошло не так

2020-10-15 16:43 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1371']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-15 16:56 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1371']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-15 17:10 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1371']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-15 17:10 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +    /// <summary>
После строки `    {` ожидается любое из списка`[' {8}/// <summary>$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-10-15 17:18 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1371']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-15 17:18 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +    /// <summary>
После строки `    {` (номер строки 5) ожидается любое из списка`[' {8}/// <summary>$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-10-15 17:22 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1371']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-15 17:36 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +    /// <summary>
После строки `    {` (номер строки 5) ожидается любое из списка`[' {8}/// <summary>$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-10-15 17:41 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1371']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-15 17:41 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +    /// <summary>
После строки `    {` (номер строки 10) ожидается любое из списка`[' {8}/// <summary>$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-10-15 18:39 UTC, badsster submitted a review, later dismissed
![image](https://user-images.githubusercontent.com/47521045/96171410-8a1c7d80-0f2d-11eb-8929-4bcaa048ecb8.png)
Этот файл так и должен быть удален?

2020-10-15 21:11 UTC, MyachevM commented
> ![image](https://user-images.githubusercontent.com/47521045/96171410-8a1c7d80-0f2d-11eb-8929-4bcaa048ecb8.png)
> Этот файл так и должен быть удален?

Да

2020-10-16 11:49 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1361']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-16 11:49 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +    /// <summary>
После строки `    {` (номер строки 10) ожидается любое из списка`[' {8}/// <summary>$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-10-16 18:51 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1361']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-16 18:51 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +    /// <summary>
После строки `    {` (номер строки 10) ожидается любое из списка`[' {8}/// <summary>$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-10-17 18:26 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1358', '#1357', '#1356']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-17 18:26 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +/// <summary>
После строки `{` (номер строки 4) ожидается любое из списка`[' {4}/// <summary>$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-10-19 10:53 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1364']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-19 10:53 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +        [TestMethod]
После строки `        /// </summary>` (номер строки 17) ожидается любое из списка`[' {8}\\[TestMethod\\]$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-10-19 11:02 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +            /// <summary>
Ожидается [начало комментария](https://habr.com/ru/post/41514/) `/// <summary>` или конец класса

2020-10-19 11:06 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +        [TestMethod]
После строки `        /// </summary>` (номер строки 17) ожидается любое из списка`[' {8}\\[TestMethod\\]$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-10-19 23:59 UTC, ifuwmnn reviewed
![image](https://user-images.githubusercontent.com/47635280/96524166-2a510a00-1280-11eb-8fdd-a5a6c758e4b5.png)
тут точно ничего не пропущено?

2020-10-20 15:36 UTC, MyachevM commented
> ![image](https://user-images.githubusercontent.com/47635280/96524166-2a510a00-1280-11eb-8fdd-a5a6c758e4b5.png)
> тут точно ничего не пропущено?



> ![image](https://user-images.githubusercontent.com/47635280/96524166-2a510a00-1280-11eb-8fdd-a5a6c758e4b5.png)
> тут точно ничего не пропущено?

не уверен
возможно мне кажется в конце названия класса нужно ()

2020-10-21 16:58 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +            /// <summary>
Ожидается [начало комментария](https://habr.com/ru/post/41514/) `/// <summary>` или конец класса

2020-10-22 18:09 UTC, YuriSilenok commented
На текущий момент у вас комментарии с неправильным сдвигом.

2020-10-22 18:25 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +        [TestMethod]
После строки `        /// </summary>` (номер строки 17) ожидается любое из списка`[' {8}\\[TestMethod\\]$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-10-22 18:44 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +        /// <summary> /// Удаление сведений в пустой таблице преподавателей /// </summary>
Ожидается [начало комментария](https://habr.com/ru/post/41514/) `/// <summary>` или конец класса

2020-10-22 18:46 UTC, YuriSilenok commented
Разберитесь с синтаксисом, наугад жизни не хватит.

2020-10-22 18:59 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +    public class UT_DСTeacher
После строки `        /// <summary>` (номер строки 15) ожидается любое из списка`[' {8}/// </summary>$', ' {8}///[\\w+ \\.]+']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-10-22 19:03 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +        [TestMethod]
После строки `        /// </summary>` (номер строки 17) ожидается любое из списка`[' {8}\\[TestMethod\\]$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-10-22 19:05 UTC, YuriSilenok commented
следите за пробелами в конце строки, их не должно быть.

2020-10-22 19:09 UTC, MyachevM commented
> следите за пробелами в конце строки, их не должно быть.

В том то и дело, что их там нету

2020-10-22 19:11 UTC, YuriSilenok commented
> > следите за пробелами в конце строки, их не должно быть.
> 
> В том то и дело, что их там нету

а если найду?
![image](https://user-images.githubusercontent.com/14871471/96918787-8059c380-14b3-11eb-858d-e43f7f0f8e4b.png)

2020-10-22 19:23 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +        [TestMethod]
После строки `        /// </summary>` (номер строки 27) ожидается любое из списка`[' {8}\\[TestMethod\\]$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-10-22 19:27 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +        {
После строки `        public void DCTeacher_2()` (номер строки 29) ожидается любое из списка`[' {8}\\{$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-10-22 19:35 UTC, YuriSilenok requested changes
Проблема в файле UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs. 
 После строки `        {` (номер строки 30) ожидается любое из списка`[' {12}.*', ' {8}\\}$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-10-22 19:39 UTC, YuriSilenok commented
Поняли в чем проблема?

2020-10-22 19:40 UTC, MyachevM commented
> Поняли в чем проблема?

в пробелах ?

2020-10-22 19:43 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +        }
Ожидается [начало комментария](https://habr.com/ru/post/41514/) `/// <summary>` или конец класса

2020-10-22 19:49 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +        }
я посмотрю в чем проблема, мне не очевидна проблема в этом месте.

2020-10-22 19:52 UTC, MyachevM commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
> +        }
> Ожидается [начало комментария](https://habr.com/ru/post/41514/) `/// <summary>` или конец класса

а вот здесь непонятно как то
если смотреть по требованиям, комментарий причины сбоя присутствует внутри метода
а /// <summary> здесь вставлять некуда
на пробелы также всё проверено в этом месте

2020-10-22 20:30 UTC, YuriSilenok commented
Похоже первичная проверка кода пройдена.

2020-10-23 06:01 UTC, NordScandinavian approved these changes, later dismissed

2020-10-23 06:17 UTC, YuriSilenok requested changes
Автотесты не запускаются

2020-10-23 08:52 UTC, MyachevM commented
> Автотесты не запускаются

![image](https://user-images.githubusercontent.com/47633738/96977806-3eb63080-1526-11eb-9a28-6e4f43fc7a56.png)

2020-10-23 08:53 UTC, MyachevM commented
> > Автотесты не запускаются
> 
> ![image](https://user-images.githubusercontent.com/47633738/96977806-3eb63080-1526-11eb-9a28-6e4f43fc7a56.png)

Азура пишет что файл с автотестами вообще не найден

2020-10-23 09:04 UTC, YuriSilenok commented
Это вопрос или утверждение?

2020-10-23 09:05 UTC, MyachevM commented
> Это вопрос или утверждение?

Утверждение
А потом я понял, что Азура ссылается на файл Юнит Теста со старым названием

2020-10-24 17:20 UTC, ZhizhikinIvan submitted a review, later dismissed
В процессе проверки отчёта по "белому ящику", нашёл 2 неточности.
1. Порядковый номер на разметке кода, начинается с 0 (см. рекомендацию):
![image](https://user-images.githubusercontent.com/47943099/97087821-8d062500-1635-11eb-90a7-1c6e16ca8bc9.png)

У вас же выглядит так:
![image](https://user-images.githubusercontent.com/47943099/97087758-149f6400-1635-11eb-8306-f6ae23e8ff5a.png)

Ну и из-за этой неточности, граф у вас тоже не совсем верен.

Должно быть так: 
![image](https://user-images.githubusercontent.com/47943099/97087884-f84ff700-1635-11eb-9713-ccd00140b321.png)


У вас так:
![image](https://user-images.githubusercontent.com/47943099/97087871-e2423680-1635-11eb-8f08-1032c125b1f1.png)

P.S. Cлинкуйте задачу.
![image](https://user-images.githubusercontent.com/47943099/97087942-47962780-1636-11eb-87a7-84d5115c555a.png)

2020-10-25 18:00 UTC, ifuwmnn reviewed
Недочёты по белому ящику исправлены, теперь нужно что-то решать с тем, что azure не видит автотесты.

2020-10-26 12:22 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1371']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-26 12:22 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1372']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-26 12:32 UTC, MyachevM commented
> Недочёты по белому ящику исправлены, теперь нужно что-то решать с тем, что azure не видит автотесты.

Проблема решена !

2020-10-26 13:30 UTC, YuriSilenok reviewed
Прежде чем закончить проверку, я хотел бы увидеть проверку от @NesgovorovVS 
Он занимается переездом проекта под новую структуру и его тщательная проверка здесь нужна.

2020-10-27 17:18 UTC, NesgovorovVS approved these changes, later dismissed
Тесты добавлены верно. Тесты проходят.

2020-10-27 17:18 UTC, NesgovorovVS commented
> Тесты добавлены верно. Тесты проходят.

Структура верная.

2020-10-27 17:19 UTC, NesgovorovVS commented
> Прежде чем закончить проверку, я хотел бы увидеть проверку от @NesgovorovVS
> Он занимается переездом проекта под новую структуру и его тщательная проверка здесь нужна.

Добавил проверку.

2020-10-27 18:53 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1357']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-27 18:53 UTC, YuriSilenok commented
Неизвестный файл `UnitTestOfTimetableOfClasses/UnitTestOfTimetableOfClasses.csproj`

2020-10-30 18:45 UTC, ifuwmnn approved these changes

2020-10-31 20:05 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1371', '#1357']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-31 20:05 UTC, YuriSilenok commented
Неизвестный файл `UnitTestOfTimetableOfClasses/UnitTestOfTimetableOfClasses.csproj`

2020-11-01 10:35 UTC, NesgovorovVS approved these changes

2020-11-01 10:54 UTC, YuriSilenok requested changes
@NesgovorovVS 
Пожалуйста, делайте проверки не только через githab, делайте это через VS.
Обратите внимание что в самой VS еще существуют сведения о файле, местоположение которого ссылается на несуществующий файл
![image](https://user-images.githubusercontent.com/14871471/97800845-8be28280-1c49-11eb-840d-6b902aeb5ade.png)
Кроме этого я не увидел в проекте каталогов, которые повторяли бы пространство имен. Фактически этого файла `CTeacher\Delete\UnitTest.cs` нет в проекте.

2020-11-01 11:33 UTC, MyachevM commented
> @NesgovorovVS
> Пожалуйста, делайте проверки не только через githab, делайте это через VS.
> Обратите внимание что в самой VS еще существуют сведения о файле, местоположение которого ссылается на несуществующий файл
> ![image](https://user-images.githubusercontent.com/14871471/97800845-8be28280-1c49-11eb-840d-6b902aeb5ade.png)
> Кроме этого я не увидел в проекте каталогов, которые повторяли бы пространство имен. Фактически этого файла `CTeacher\Delete\UnitTest.cs` нет в проекте.

![5fB1k36sssQ](https://user-images.githubusercontent.com/47633738/97801625-25f8f980-1c4f-11eb-904b-ed5bbcab6b69.jpg)
как то странно
у меня всё в порядке
но я ещё не вливал изменения в dev, если вдруг что

2020-11-01 11:35 UTC, YuriSilenok commented
dev тут не причем, я смотрел в ветке issue-1281, сейчас перепроверю и пришлю полный скрин

2020-11-01 11:39 UTC, YuriSilenok commented
да, у меня была старая версия проекта, смотрю последнюю

2020-11-01 11:40 UTC, YuriSilenok commented
похоже что VS меня подвела в плане получения последний изменений из ветки.

2020-11-01 11:40 UTC, YuriSilenok approved these changes

2020-11-01 11:57 UTC, merged