Исправление сбоев в автотестах расположенных в файле UT_Delete_CGroup
Students-of-the-city-of-Kostroma/Student-timetable pull request #1360
Opened 2020-09-22 14:49 UTC by NesgovorovVS

#1065

2020-09-22 14:51 UTC, YuriSilenok commented
Не найдены сопутствующие метки для `Unit test`. Нарушены [требования](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/labels.md) для меток.

2020-09-22 14:51 UTC, YuriSilenok requested changes
Файл `Docs/UT_Delete_CGroup/CODE.png` не соответствует требованиям. Нарушены требования именования папок или файлов к [белому ящику](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/White-box/README.md) или [модульным тестам](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Unit-test/README.md).

2020-09-22 14:52 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1355']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-22 14:52 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1358', '#1357', '#1356']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-22 14:52 UTC, YuriSilenok commented
Не найдены сопутствующие метки для `Unit test`. Нарушены [требования](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/labels.md) для меток.

2020-09-22 15:01 UTC, YuriSilenok requested changes
Файл `Docs/UT_Delete_CGroup/CODE.png` не соответствует требованиям. Нарушены требования именования папок или файлов к [белому ящику](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/White-box/README.md) или [модульным тестам](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Unit-test/README.md).

2020-09-22 15:01 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1355']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-22 15:02 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1358', '#1357', '#1356']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-22 15:02 UTC, YuriSilenok commented
Не найдены сопутствующие метки для `Unit test`. Нарушены [требования](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/labels.md) для меток.

2020-09-22 17:14 UTC, YuriSilenok requested changes
![image](https://user-images.githubusercontent.com/14871471/93915117-33e26300-fd10-11ea-9faf-89aec0ad1c6a.png)

2020-09-24 10:07 UTC, NordScandinavian requested changes
Пока что, проверять нечего, жду обновлений

2020-09-24 10:32 UTC, YuriSilenok commented
> Пока что, проверять нечего, жду обновлений

каких обновлений?

2020-09-25 08:56 UTC, MyachevM requested changes
Переместить папку CGroup в UnitTestOfTimetableOfClasses и создать новую метку CGroup

2020-09-27 17:28 UTC, ifuwmnn requested changes
У тебя не хватает региона, где this.Rows.Count было бы равно 0. Если я ничего не путаю.
![image](https://user-images.githubusercontent.com/47635280/94371537-f6127f80-00ff-11eb-8da5-b5e5f5b271bb.png)

2020-09-27 20:29 UTC, YuriSilenok requested changes
Файл `UnitTestOfTimetableOfClasses/CGroup/Delete/CODE.png` не соответствует требованиям. Нарушены требования именования папок или файлов к [белому ящику](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/White-box/README.md) или [модульным тестам](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Unit-test/README.md).

2020-09-27 20:30 UTC, NesgovorovVS commented
Извиняюсь заранее за то, что запросил проверку, сейчас исправлю ещё регион

2020-09-27 20:30 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1358', '#1357', '#1356', '#1355']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-07 13:46 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1366', '#1361', '#1358', '#1357', '#1356', '#1355']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-07 13:46 UTC, YuriSilenok commented
Нет обработчика для файла `UnitTestOfTimetableOfClasses/CGroup/Delete/CODE.png`

2020-10-07 13:46 UTC, YuriSilenok commented
Нет обработчика для файла `UnitTestOfTimetableOfClasses/CGroup/Delete/GRAPH.PNG`

2020-10-07 13:46 UTC, YuriSilenok commented
Нет обработчика для файла `UnitTestOfTimetableOfClasses/CGroup/Delete/whiteBox.md`

2020-10-07 13:46 UTC, YuriSilenok commented
В файле `UnitTestOfTimetableOfClasses/UT_Delete_CGroup.cs` после строки `namespace UnitTestOfTimetableOfClasses` ожидается любое из списка`['(\\ufeff){,1}using [\\w+\\.]+;', '$']`

2020-10-07 14:26 UTC, YuriSilenok commented
> В файле `UnitTestOfTimetableOfClasses/UT_Delete_CGroup.cs` после строки `namespace UnitTestOfTimetableOfClasses` ожидается любое из списка`['(\\ufeff){,1}using [\\w+\\.]+;', '$']`

На самом деле проблема в том, что после конструкции using должен идти разделитель в виде пустой строки. В данном случая после строки `using LibOfTimetableOfClasses;` должен идти этот разделитель.

2020-10-07 14:27 UTC, YuriSilenok commented
> Нет обработчика для файла

Это значит что обнаружен неизвестный файл, проверьте требования к именованию файлов

2020-10-07 14:57 UTC, MyachevM requested changes
1. На графе не расставлены регионы
2. Test-ID в сценариях, скорее всего неверные
3. Также непонятная ситуация с R2, скорее всего надо сделать R2а и R2b, раз у региона есть разветвление

2020-10-07 17:48 UTC, NordScandinavian requested changes
Согласен с предыдущим комментатором, жду обновлений.

2020-10-13 20:50 UTC, badsster requested changes
![image](https://user-images.githubusercontent.com/47521045/95914741-d55c5200-0dae-11eb-9be4-379fa9dff939.png)
Удалён отчет . Не могу полностью оценить работу

2020-10-22 19:07 UTC, ZhizhikinIvan requested changes
В whitebox.md не корректно отображается таблица "Тестовые сценарии". Поправьте.
![image](https://user-images.githubusercontent.com/47943099/96917830-06750a80-14b2-11eb-981d-f7e6b52609d7.png)

2020-11-05 21:52 UTC, NesgovorovVS commented
Приболел. Временно отстранился от работы. Через 2 дня вернусь к таскам.

2021-05-19 07:04 UTC, closed without merging