Разработала методические рекомендации к составлению пользовательской истории
Students-of-the-city-of-Kostroma/Student-timetable pull request #1361
Opened 2020-09-24 10:57 UTC by badsster

#1344
 [Документ](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/issue-1344/Docs/Contributers/user_story.md )

2020-09-26 14:01 UTC, YuriSilenok commented
Нам нужно созвонится для обсуждения этого документа

2020-09-26 14:25 UTC, badsster commented
> Нам нужно созвонится для обсуждения этого документа

@YuriSilenok добрый вечер, Юрий Викторович . Когда и где вы хотите это сделать?

2020-09-26 14:27 UTC, YuriSilenok commented
По будням с 9 до 18, я ссылку пришлю. Предложите день и время.

2020-09-26 14:37 UTC, badsster commented
> По будням с 9 до 18, я ссылку пришлю. Предложите день и время.

Я могу в любой из дней после занятий в университете. Но вторник из-за занятий военной кафедры у нас как учебный выходной, поэтому может быть в этот день? 
Если мы будем созваниваться всей группой нужно и их мнение, когда удобно им.

2020-09-26 14:39 UTC, YuriSilenok commented
Мы будем обсуждать с Вами документ, остальные могут участвовать по желанию. Давайте во вторник в 9:00 я создам мероприятие в календаре.

2020-09-26 14:57 UTC, YuriSilenok commented
Отправил приглашение к мероприятию в календаре, там же ссылка

2020-09-26 15:03 UTC, badsster commented
> Отправил приглашение к мероприятию в календаре, там же ссылка

Приглашение получила. Спасибо.

2020-09-27 18:54 UTC, YuriSilenok commented
Вы закончили работу на задачей?

2020-09-27 20:10 UTC, badsster commented
> Вы закончили работу на заботу?

Здравствуйте. Думаю, что да. Весь материал, что требовалось в документе я написала. Больше не знаю, что добавить.

2020-09-27 20:12 UTC, YuriSilenok commented
а почему меня в проверяющих не указали?

2020-09-27 20:15 UTC, badsster commented
> а почему меня в проверяющих не указали?

Сейчас указала. Спасибо, что подсказали.

2020-09-27 20:16 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1358', '#1357', '#1356', '#1355']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-29 17:59 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1358', '#1355']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-29 17:59 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1363']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-29 18:10 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1358', '#1355']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-29 18:10 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1363']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-29 18:10 UTC, YuriSilenok commented
Классифицирующая метка не найдена. Нарушены [требования](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/labels.md) для меток.

2020-09-30 01:01 UTC, badsster commented
- Добавила метку Documentation;
- Исправила требования к заголовкам, добавила идентификатор;
- Добавила отсылки на метки;
- Составила критерии приемлемости каждого пункта;
- Изменила описание ЖЦ ПО и документов;
- Добавила файлы EXAMPLE.png и SAMPLE.png с изображением иерархии создания документов и шаблон User Story.

Приступлю к проверке других запросов позже. Надеюсь на Вашу проверку. И обязательно задавайте вопросы, если что-то не понятно.

2020-09-30 07:08 UTC, YuriSilenok commented
> Надеюсь на Вашу проверку. И обязательно задавайте вопросы, если что-то не понятно.

Для того, что бы запросить повторную проверку, нужно нажать на вот эту кнопку
![image](https://user-images.githubusercontent.com/14871471/94653864-e7e18080-0304-11eb-8a0e-be7068b04551.png)

2020-09-30 07:15 UTC, YuriSilenok commented
> Классифицирующая метка не найдена. Нарушены [требования](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/labels.md) для меток.

думаю сейчас не продет проверка по меткам, я пока подумаю как решить эту проблему, нужно придумать какая метка будет означать разработку методических рекомендаций и как она будет проверяться.

2020-09-30 07:22 UTC, badsster commented
> > Классифицирующая метка не найдена. Нарушены [требования](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/labels.md) для меток.
> 
> думаю сейчас не продет проверка по меткам, я пока подумаю как решить эту проблему, нужно придумать какая метка будет означать методы рекомендаций и как она будет проверяться.

Кроме метки Documentation я не знала, что можно ещё поставить в методические рекомендации ,поэтому добавила её. Надеюсь Вы сможете придумать какая метка будет за это отвечать. Жду Вашего решения.

2020-09-30 07:27 UTC, YuriSilenok commented
Так как это документация, то да, метка документации справедливо стоит, но это документация о документации или методическая документация, то думаю можно создать метку Methodological, как вы на это смотрите?

2020-09-30 07:32 UTC, badsster commented
> Так как это документация, то да, метка документации стоит, но это документация о документации или методическая документация, то думаю можно создать метку Методологические, как вы на это смотрите?

Перевод этого слова как раз подходит к таким типам задач. Думаю да, можно создать метку с таким названием.

2020-09-30 08:32 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1358', '#1355']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-30 08:32 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1363']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-09-30 08:32 UTC, YuriSilenok commented
Не найдены сопутствующие метки для `Documentation`. Нарушены [требования](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/labels.md) для меток.

2020-09-30 08:51 UTC, YuriSilenok commented
> Не найдены сопутствующие метки для `Documentation`. Нарушены [требования](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/labels.md) для меток.

Обновил требования

2020-09-30 19:57 UTC, badsster commented
> > Не найдены сопутствующие метки для `Documentation`. Нарушены [требования](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/labels.md) для меток.
> 
> Обновил требования

Юрий Викторович, подскажите, а мне в labels самой составить метку Methodological или оставить как есть ? Просто я её не нашла

2020-09-30 19:59 UTC, YuriSilenok commented
Создайте её самостоятельно и назначте на запрос

2020-10-01 20:57 UTC, badsster commented
@YuriSilenok хочу внести поправки в файл labels.md. В dev не могу так как она защищенная , создавать новую ветку? Или не вносить изменения? 
![image](https://user-images.githubusercontent.com/47521045/94862582-e10c5800-0441-11eb-9113-c3c8c6211a77.png)

2020-10-01 21:17 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1358', '#1355']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-01 21:18 UTC, YuriSilenok commented
Все правки в дев у нас через отдельные ветки.

2020-10-01 21:31 UTC, badsster commented
> Все правки в дев у нас через отдельные ветки.

Подскажите, пожалуйста, какую ветку создать мне, чтобы добавить изменения?

2020-10-01 21:34 UTC, YuriSilenok commented
Есть задача #1347, вы можете в рамках её сделать нужные правки.

2020-10-02 08:12 UTC, MyachevM approved these changes, later dismissed

2020-10-04 15:33 UTC, badsster commented
> У вас есть непроверенные запросы ['#1358', '#1355']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

Добрый вечер, Юрий Викторович. Хотелось бы уточнить по поводу проверок запросов, потому что я этого еще не делала.
Вы мне показывали приложение Github Desktop, когда мы обсуждали, что мне делать в моей задаче. Я его скачала, указала путь репозитория и у меня вопрос. Как мне выполнить проверку через эту программу? 

Например,ветка проверки issue-1095. Я указываю репозиторий, дальше ветку, внизу краткое и полное описание и нажимаю кнопку commit. В данном случае у меня будет отмечен запрос как проверенный или нет?
![image](https://user-images.githubusercontent.com/47521045/95019790-0da5b700-0670-11eb-8a31-d312adb15a97.png)

2020-10-04 16:11 UTC, YuriSilenok commented
Коммит это просто фиксация изменений, что бы запросить проверку нужно в этом запросе, об этом я уже писал [здесь](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1361#issuecomment-701203558)

2020-10-05 00:51 UTC, badsster commented
> Коммит это просто фиксация изменений, что бы запросить проверку нужно в этом запросе нажать на кнопочку с двумя круговыми стрелками, об этом я уже писал [здесь](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1361#issuecomment-701203558)

Про проверку своего запроса я поняла, что нужно нажать на этот значок стрелочек для повторной проверки. Но у меня в моем документе нет изменений.
Я хочу проверить #1355 #1358 и чтобы у моего никнейма стояли значки либо галочка, либо +/- , как в моей задаче. Как это сделать, подскажите, пожалуйста. 
![image](https://user-images.githubusercontent.com/47521045/95031303-ee357b00-06bd-11eb-90bf-e0febf6d0898.png)

2020-10-05 06:13 UTC, YuriSilenok commented
![image](https://user-images.githubusercontent.com/14871471/95045549-efc96800-06ea-11eb-978f-5aefde62ef29.png)
![image](https://user-images.githubusercontent.com/14871471/95045586-02dc3800-06eb-11eb-8396-8f4b0abe0846.png)

2020-10-05 14:36 UTC, YuriSilenok requested changes
Провел рецензирование.

2020-10-05 14:36 UTC, YuriSilenok commented on Docs/Contributers/UserStory/README.md
> +- Начало заголовка: имя существительное;
Кажется раньше вы описывали что заголовок содержит действие.

2020-10-05 14:36 UTC, YuriSilenok commented on Docs/Contributers/DocStyle/README.md
> +- Язык документа Русский. В документе может использоваться английский язык, в случае, если нужно указать сущность или понятие/аббревиатуру.
Вынес общие требования к документам в отдельный файл

2020-10-05 14:36 UTC, YuriSilenok commented on Docs/Contributers/UserStory/README.md
> +`ЗДЕСЬ ДОЛЖНА БЫТЬ ССЫЛКА НА ОБРАЗЕЦ ПОЛЬЗОВАТЕЛЬСКОЙ ИСТОРИИ`
В место картинки сделать ссылку на образец. Соответственно нужно будет создать документ, образец пользовательской истории за номером `0` и описать ее на свободную тему, так что бы она максимально покрывала представленные здесь требования. Лучше конечно найти какую-нибудь пользовательскую историю и перевести ее в текстовый формат `md`.

2020-10-05 14:39 UTC, YuriSilenok commented on Docs/Contributers/UserStory/README.md
> +- Описание одного теста состоит из одного предложения;
Я не уверен что это будет в виде одного предложения. Тестовый сценарий имеет много атрибутов, в том числе шаги выполнения, они точно не вмещаются в одно предложение, жду образца.

2020-10-06 19:37 UTC, badsster commented on Docs/Contributers/UserStory/README.md
> +- Начало заголовка: имя существительное;
Убрала этот пункт, так как нельзя указать конкретно с чего начинается заголовок. Оставила 2 пункт, а остальные требования есть в документе выше. Пока не знаю, что еще можно добавить.

2020-10-06 19:37 UTC, badsster commented on Docs/Contributers/DocStyle/README.md
> +- Язык документа Русский. В документе может использоваться английский язык, в случае, если нужно указать сущность или понятие/аббревиатуру.
Немного изменила данные документ. Исправила опечатки.

2020-10-06 19:40 UTC, badsster commented on Docs/Contributers/UserStory/README.md
> +`ЗДЕСЬ ДОЛЖНА БЫТЬ ССЫЛКА НА ОБРАЗЕЦ ПОЛЬЗОВАТЕЛЬСКОЙ ИСТОРИИ`
Хотела бы узнать по какому пути мне делать образец. 
Правильно ли я понимаю, что образец сделать по этому пути /Docs/Technical/UserStories/Story-0/READMY.md  ?
Или создать образец в /Docs/Contributers/UserStory/Story-0/READMY.md ?

2020-10-06 20:01 UTC, badsster commented on Docs/Contributers/UserStory/README.md
> +- Описание одного теста состоит из одного предложения;
Тестирование;

- Начало тестового сценария: Тестовый сценарий-"Порядковый номер теста";
- После нумерации теста и знака двоеточие идет заголовок теста с маленькой буквы;
- Описание одного теста состоит из последовательности шагов выполнения проверки;
- Количество тест-кейсов не менее трех.

Изменила описание тестирования. Такой шаблон тестового сценария будет приемлемым?

Пример:
Тестовый сценарий 1: проверка функциональности входа.
1. Проверьте работу при вводе правильного имени пользователя и пароля.
2: Проверьте операцию, если введены неверные имя пользователя и пароль.
3: Проверьте операцию, если имя пользователя пусто и нажата кнопка входа.

2020-10-07 19:41 UTC, YuriSilenok commented on Docs/Contributers/UserStory/README.md
> +`ЗДЕСЬ ДОЛЖНА БЫТЬ ССЫЛКА НА ОБРАЗЕЦ ПОЛЬЗОВАТЕЛЬСКОЙ ИСТОРИИ`
Да, давайте так, выглядит логично.

2020-10-07 21:04 UTC, YuriSilenok commented on Docs/Contributers/UserStory/README.md
> +- Описание одного теста состоит из одного предложения;
> Пример:
Тестовый сценарий 1: проверка функциональности входа:

> Проверьте работу при вводе правильного имени пользователя и пароля.
Проверьте операцию, если введены неверные имя пользователя и пароль.
Проверьте операцию, если имя пользователя пусто и нажата кнопка входа.

Проблема только в шагах. В них нужно писать не то, что нужно проверить, а что сделать над системой. а вот после всех шагов пишется что мы ожидаем, это и будет проверка.

Например:
Сценарий 1: Агрессивный ордер в регулярной торговле торгуется не вставая на книжку.
1. Послать пассивный ордер с ценой продажи 100 и объемом 1000
2. Послать агрессивный ордер с ценой покупки 100 и объемом 1000
Ожидаемый результат: Пользователь получает два сообщения о торговле на весь объем ордеров. Сообщения о том, что агрессивный ордер попал на книжку не приходит.

Относительно интерфейса, нужно описывать что пользователь должен вводить, что бы достичь какого-т результата.

2020-10-08 18:47 UTC, badsster commented on Docs/Contributers/UserStory/README.md
> +`ЗДЕСЬ ДОЛЖНА БЫТЬ ССЫЛКА НА ОБРАЗЕЦ ПОЛЬЗОВАТЕЛЬСКОЙ ИСТОРИИ`
> Да, давайте так, выглядит логично.

Юрий Викторович, не поняла какой вариант мне взять?
1 вариант)/Docs/Technical/UserStories/Story-0/READMY.md 
2 вариант)/Docs/Contributers/UserStory/Story-0/READMY.md

2020-10-08 20:07 UTC, badsster commented on Docs/Contributers/UserStory/README.md
> +- Описание одного теста состоит из одного предложения;
Изменила описание блока тестирования.

Тестирование;
- Начало тестового сценария: Сценарий-"Порядковый номер теста";
- После нумерации теста и знака двоеточие идет заголовок с заглавной буквы;
- Описание одного сценария состоит из последовательности шагов, что нужно сделать с системой;
- После всех шагов мы описываем "Ожидаемый результат", который и будет являться проверкой тестов;
- Количество тест-кейсов не менее трех.

2020-10-08 21:38 UTC, badsster commented on Docs/Contributers/UserStory/README.md
> +`ЗДЕСЬ ДОЛЖНА БЫТЬ ССЫЛКА НА ОБРАЗЕЦ ПОЛЬЗОВАТЕЛЬСКОЙ ИСТОРИИ`
Создала документ по первому варианту.
Если неправильно, то перенесу.
[Образец](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/issue-1344/Docs/Technical/UserStories/Story-0/READMY.md)

2020-10-09 18:15 UTC, YuriSilenok commented
Работа готова для проверки?

2020-10-09 18:21 UTC, badsster commented
> Работа готова для проверки?

Да, впринципе готова. Если будут какие-то погрешности, то я исправлю.

2020-10-09 18:23 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1368', '#1367', '#1366', '#1360', '#1358', '#1357', '#1356', '#1355']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-09 18:23 UTC, YuriSilenok commented
Неизвестный файл `Docs/Contributers/DocStyle/README.md`

2020-10-09 18:53 UTC, YuriSilenok commented
У вас большая очередь в запросах, посмотрите их?

2020-10-09 20:15 UTC, badsster commented
> У вас большая очередь в запросах, посмотрите их?

Сейчас пока не могу, как буду иметь возможность работать за компьютером, возьмусь за проверку.

2020-10-11 18:37 UTC, MyachevM approved these changes, later dismissed

2020-10-12 16:08 UTC, ifuwmnn approved these changes, later dismissed

2020-10-13 14:48 UTC, ZhizhikinIvan submitted a review, later dismissed

2020-10-13 21:24 UTC, badsster commented
> У вас большая очередь в запросах, посмотрите их?

Проверила запросы.

2020-10-13 21:26 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1364', '#1355']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-13 21:26 UTC, YuriSilenok commented
Неизвестный файл `Docs/Technical/UserStories/Story-0/READMY.md`

2020-10-15 18:18 UTC, badsster commented
> Неизвестный файл `Docs/Technical/UserStories/Story-0/READMY.md`

Данный файл это образец пользовательской истории, которую Вы попросили создать. Поэтому я расположила его по этому пути Student-timetable/Docs/Technical/UserStories/Story-0/READMY.md

Мне изменить путь?

2020-10-15 18:40 UTC, YuriSilenok commented
У вас есть непроверенные запросы ['#1371']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-15 18:40 UTC, YuriSilenok commented
Неизвестный файл `Docs/Technical/UserStories/Story-0/READMY.md`

2020-10-16 00:00 UTC, YuriSilenok commented
Неизвестный файл `Docs/Technical/UserStories/Story-0/READMY.md`

2020-10-16 00:00 UTC, YuriSilenok commented
Неизвестный файл `Docs/Technical/UserStories/Story-0/READMY.md`

2020-10-16 00:00 UTC, YuriSilenok commented
Неизвестный файл `Docs/Technical/UserStories/Story-0/READMY.md`

2020-10-16 00:00 UTC, badsster commented
> Неизвестный файл `Docs/Technical/UserStories/Story-0/READMY.md`

Запрос #1371 проверила. Еще раз хотелось бы уточнить по поводу образца , может я его располагаю не по тому пути?
Я его взяла как  нулевую историю и поэтому расположила Docs/Technical/UserStories/Story-0/READMY.md. Правильно ли это? Или образец нужно расположить в другом месте?

2020-10-17 18:22 UTC, MyachevM approved these changes

2020-10-18 11:35 UTC, ZhizhikinIvan approved these changes

2020-10-18 18:33 UTC, NordScandinavian approved these changes

2020-10-19 23:49 UTC, ifuwmnn approved these changes

2020-10-22 18:14 UTC, YuriSilenok approved these changes

2020-10-22 18:15 UTC, YuriSilenok commented
@badsster Дальше знаете что делать?

2020-10-23 01:39 UTC, badsster commented
> @badsster Дальше знаете что делать?

Добрый день, Юрий Викторович. Лучше уточню, чтобы не ошибиться. Нужно нажать на кнопку Merge pull request и перевесить на Вас основной таск #1344 ?

2020-10-23 05:46 UTC, YuriSilenok commented
> > @badsster Дальше знаете что делать?
> 
> Добрый день, Юрий Викторович. Лучше уточню, чтобы не ошибиться. Нужно нажать на кнопку Merge pull request и перевесить на Вас основной таск #1344 ?

да

2020-10-23 09:31 UTC, merged