Разработал историю функции корректировки учебной нагрузки для студентов вуза
Students-of-the-city-of-Kostroma/Student-timetable pull request #1363
Opened 2020-09-29 14:08 UTC by VinogradovAlexandr781227

#1346

2020-09-30 20:36 UTC, YuriSilenok requested changes
Нарушены [требования именования веток](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/branches.md#issue-d). Слияние в ветку master возможно только из ветки dev.

2020-09-30 20:36 UTC, closed without merging

2020-09-30 20:36 UTC, YuriSilenok commented
Классифицирующая метка не найдена. Нарушены [требования](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/labels.md) для меток.

2020-10-02 08:11 UTC, MyachevM reviewed
Задача находится в закрытых

2020-10-02 08:37 UTC, YuriSilenok commented
> Задача находится в закрытых

да, это ложное срабатывание, внесу дополнительное условие

2020-10-02 08:38 UTC, YuriSilenok commented
хотя нет, все хорошо, на момент вашего запроса на проверку, этот запрос еще был открыт.