Разработал и автоматизировал сценарии тестирования метода Insert (Model model) сущности Нагрузка
Students-of-the-city-of-Kostroma/Student-timetable pull request #1367
Opened 2020-10-05 18:58 UTC by NesgovorovVS

2020-10-05 19:00 UTC, YuriSilenok commented
Не найдены сопутствующие метки для `Unit test`. Нарушены [требования](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/labels.md) для меток.

2020-10-07 14:00 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1366', '#1361', '#1358', '#1357', '#1356', '#1355']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-07 14:00 UTC, YuriSilenok commented
Не найдены сопутствующие метки для `Unit test`. Нарушены [требования](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/labels.md) для меток.

2020-10-07 14:00 UTC, YuriSilenok commented
Нет обработчика для файла `UnitTestOfTimetableOfClasses/CAcademicLoad/Insert/CODE.png`

2020-10-07 14:01 UTC, YuriSilenok commented
Нет обработчика для файла `UnitTestOfTimetableOfClasses/CAcademicLoad/Insert/GRAPH.PNG`

2020-10-07 14:01 UTC, YuriSilenok commented
Нет обработчика для файла `UnitTestOfTimetableOfClasses/CAcademicLoad/Insert/whitebox.md`

2020-10-07 14:01 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Insert_CAdemicLoad.cs
> +    public class UT_Insert_CAcademicLoad
В файле `UnitTestOfTimetableOfClasses/UT_Insert_CAdemicLoad.cs` после строки `    public class UT_Insert_CAcademicLoad` ожидается любое из списка`[' {4}public class UT_((I|U|D)С)|(AcademicDegree|AcademicLoad|Auditor|DirectionOfPreparation|Discipline|Enclosures|Group|HEI|Institute|StudyWeek|Teacher|Title|TrainingProfiles|TypesOfOccupations|University)', ' {4}public class UT_M|(AcademicDegree|AcademicLoad|Auditor|DirectionOfPreparation|Discipline|Enclosures|Group|HEI|Institute|StudyWeek|Teacher|Title|TrainingProfiles|TypesOfOccupations|University)']`

2020-10-07 14:01 UTC, YuriSilenok commented
Нет обработчика для файла `UnitTestOfTimetableOfClasses/UnitTestOfTimetableOfClasses.csproj`

2020-10-07 14:56 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/UT_Insert_CAdemicLoad.cs
> +    public class UT_Insert_CAcademicLoad
Требования для имени класса [здесь](/Docs/Unit-test/README.md)

2020-10-07 15:01 UTC, MyachevM requested changes
1. Нет описания к задаче
2. На графе не расставлены регионы
3. Некорректный вид тестовых сценариев

2020-10-07 17:47 UTC, NordScandinavian requested changes
Согласен с предыдущим комментатором, нового ничего на проверку не появилось.

2020-10-08 11:14 UTC, YuriSilenok commented
> Нет обработчика для файла `UnitTestOfTimetableOfClasses/UnitTestOfTimetableOfClasses.csproj`

Добавил игнорирование этого файла

2020-10-08 16:02 UTC, ifuwmnn reviewed
Коллега выше уже описал ошибки.

2020-10-13 20:41 UTC, badsster requested changes
Новых изменений на проверку нет.

2020-10-17 15:50 UTC, YuriSilenok commented
Описание запроса должно содержать сведения о том, какую задачу он закрывает в случае мержа

2020-11-08 16:57 UTC, NesgovorovVS commented
Приболел. Завтра займусь задачей.

2020-11-13 09:39 UTC, NesgovorovVS commented
> Приболел. Завтра займусь задачей.

Чуть дольше чем ожидалось. Завтра вечером приступлю снова ко всем задачам.

2021-05-19 07:04 UTC, closed without merging