Разработка сценариев для автотестов расположенных в файле UT_Insert_CUniversity
Students-of-the-city-of-Kostroma/Student-timetable pull request #1368
Opened 2020-10-05 19:02 UTC by NesgovorovVS

2020-10-05 19:02 UTC, YuriSilenok commented
Не найдены сопутствующие метки для `Unit test`. Нарушены [требования](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/labels.md) для меток.

2020-10-07 13:52 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1366', '#1361', '#1358', '#1357', '#1356', '#1355']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-07 13:52 UTC, YuriSilenok commented
Не найдены сопутствующие метки для `Unit test`. Нарушены [требования](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/labels.md) для меток.

2020-10-07 13:52 UTC, YuriSilenok commented
Нет обработчика для файла `UnitTestOfTimetableOfClasses/CUniversity/Insert/CODE.png`

2020-10-07 13:52 UTC, YuriSilenok commented
Нет обработчика для файла `UnitTestOfTimetableOfClasses/CUniversity/Insert/GRAPH.PNG`

2020-10-07 13:52 UTC, YuriSilenok commented
Нет обработчика для файла `UnitTestOfTimetableOfClasses/CUniversity/Insert/whitebox.md`

2020-10-07 15:06 UTC, MyachevM requested changes
1. Нет описания к задаче
2. На графе не расставлены регионы
3. Скорее всего некорректные номера Test-ID
4. В сценариях, в R2, R3, R4, R5, R6, значение столбца Ожидаемый Результат находится в значении столбца Входные Параметры

2020-10-07 17:46 UTC, NordScandinavian requested changes
Согласен с предыдущим комментатором.

2020-10-08 16:00 UTC, ifuwmnn requested changes
Выше коллега уже описал ошибки, могу добавить, что недостаточно просто написать валидные данные, нужно писать конкретные значения в столбцах предварительное условие и входные параметры

2020-10-13 20:26 UTC, badsster commented
![image](https://user-images.githubusercontent.com/47521045/95912113-0b97d280-0dab-11eb-8f2e-bc0c9f514ac5.png)
Управляющий граф у меня не отображается в самом отчете.  Похоже он удален . А так согласна с замечаниями коллег.

2020-10-13 20:35 UTC, badsster requested changes
Review changes

2020-10-15 18:54 UTC, ZhizhikinIvan reviewed
Граф всё ещё не отображается в whitebox.md.
В остальном согласен с коллегами.

2021-05-19 07:04 UTC, closed without merging