Реструктуризация проекта UnitTestOfTimetableOfClasses
Students-of-the-city-of-Kostroma/Student-timetable pull request #1371
Opened 2020-10-15 15:38 UTC by NesgovorovVS

#1354

2020-10-15 15:40 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1366', '#1364', '#1361', '#1358', '#1357', '#1356', '#1355']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-15 15:40 UTC, YuriSilenok commented
Метка определяющая тип задачи не найдена. Нарушены [требования](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/labels.md) для меток.

2020-10-15 15:40 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CAcademicDegree/Delete/UnitTest.cs
>  namespace UnitTestOfTimetableOfClasses
После строки `` ожидается любое из списка`['$', 'namespace UnitTestOfTimetableOfClasses\\.CAcademicDegree\\.Delete$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-10-15 15:40 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CAcademicDegree/Insert/UnitTest.cs
>  namespace UnitTestOfTimetableOfClasses
После строки `` ожидается любое из списка`['$', 'namespace UnitTestOfTimetableOfClasses\\.CAcademicDegree\\.Insert$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-10-15 15:41 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CAcademicDegree/Update/UnitTest.cs
>  namespace UnitTestOfTimetableOfClasses
После строки `` ожидается любое из списка`['$', 'namespace UnitTestOfTimetableOfClasses\\.CAcademicDegree\\.Update$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-10-15 15:41 UTC, YuriSilenok commented
Неизвестный файл `UnitTestOfTimetableOfClasses/CAcademicLoad/Update/CODE.PNG`

2020-10-15 23:36 UTC, badsster requested changes
![image](https://user-images.githubusercontent.com/47521045/96196563-573baf00-0f58-11eb-8cc3-07a0a88578f3.png)
Добавь, пожалуйста, метки и связь с запросом

2020-10-16 11:46 UTC, MyachevM approved these changes
мне кажется здесь нужна только метка рефакторинга, поэтому апрув

2020-10-18 11:03 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1366', '#1364', '#1361', '#1358', '#1357', '#1356', '#1355']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-18 11:03 UTC, YuriSilenok commented
Метка определяющая тип задачи не найдена. Нарушены [требования](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/labels.md) для меток.

2020-10-18 11:03 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CAcademicDegree/Delete/UnitTest.cs
>  namespace UnitTestOfTimetableOfClasses
После строки `` (номер строки 2) ожидается любое из списка`['$', 'namespace UnitTestOfTimetableOfClasses\\.CAcademicDegree\\.Delete$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-10-18 11:03 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CAcademicDegree/Insert/UnitTest.cs
>  namespace UnitTestOfTimetableOfClasses
После строки `` (номер строки 2) ожидается любое из списка`['$', 'namespace UnitTestOfTimetableOfClasses\\.CAcademicDegree\\.Insert$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-10-18 11:03 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CAcademicDegree/Update/UnitTest.cs
>  namespace UnitTestOfTimetableOfClasses
После строки `` (номер строки 2) ожидается любое из списка`['$', 'namespace UnitTestOfTimetableOfClasses\\.CAcademicDegree\\.Update$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-10-18 11:03 UTC, YuriSilenok commented
Неизвестный файл `UnitTestOfTimetableOfClasses/CAcademicLoad/Update/CODE.PNG`

2020-10-22 05:15 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1364', '#1361', '#1358', '#1357', '#1356', '#1355']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-22 05:15 UTC, YuriSilenok commented
Метка определяющая тип задачи не найдена. Нарушены [требования](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/labels.md) для меток.

2020-10-22 05:15 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CAcademicDegree/Delete/UnitTest.cs
>  namespace UnitTestOfTimetableOfClasses
После строки `` (номер строки 2) ожидается любое из списка`['$', 'namespace UnitTestOfTimetableOfClasses\\.CAcademicDegree\\.Delete$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-10-22 05:15 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CAcademicDegree/Insert/UnitTest.cs
>  namespace UnitTestOfTimetableOfClasses
После строки `` (номер строки 2) ожидается любое из списка`['$', 'namespace UnitTestOfTimetableOfClasses\\.CAcademicDegree\\.Insert$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-10-22 05:15 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CAcademicDegree/Update/UnitTest.cs
>  namespace UnitTestOfTimetableOfClasses
После строки `` (номер строки 2) ожидается любое из списка`['$', 'namespace UnitTestOfTimetableOfClasses\\.CAcademicDegree\\.Update$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-10-22 05:15 UTC, YuriSilenok commented
Неизвестный файл `UnitTestOfTimetableOfClasses/CAcademicLoad/Update/CODE.PNG`

2020-10-23 06:00 UTC, NordScandinavian requested changes
Ничего нового не добавилось, жду изменений

2020-10-23 06:08 UTC, YuriSilenok approved these changes

2020-10-23 06:20 UTC, YuriSilenok requested changes
Проверьте, что перенесенные юнит тесты могут выполняться.

2020-10-23 20:23 UTC, ZhizhikinIvan requested changes
Жду обновлений, как и другие коллеги.

2020-10-25 08:30 UTC, NesgovorovVS commented
> Проверьте, что перенесенные юнит тесты могут выполняться.

они не смогут выполняться, т.к не смогут быть добавлены в проект из-за одинаковых названий "UnitTest.cs"

2020-10-26 12:24 UTC, MyachevM requested changes
Жду обновлений

2020-10-28 10:10 UTC, NesgovorovVS commented
> Проверьте, что перенесенные юнит тесты могут выполняться.

Перенесенные тесты выполняются

2020-10-28 10:11 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1372', '#1364', '#1358', '#1357', '#1356']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-10-28 10:11 UTC, YuriSilenok commented
Метка определяющая тип задачи не найдена. Нарушены [требования](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/labels.md) для меток.

2020-10-28 10:11 UTC, YuriSilenok commented
Неизвестный файл `Docs/Unit-test/README.md`

2020-11-01 09:35 UTC, ifuwmnn approved these changes

2020-11-01 09:47 UTC, MyachevM approved these changes
![image](https://user-images.githubusercontent.com/47633738/97798520-de1aa800-1c37-11eb-9a4b-3a4073ff2afe.png)
Папки с тестами созданы верно
Перенесённые тесты выполняются

2020-11-01 11:12 UTC, YuriSilenok requested changes
У вас есть непроверенные запросы ['#1372', '#1364', '#1358', '#1357', '#1356']. Пожалуйста, выполните проверку этих запросов и после этого повторно запросите проверку своего запроса

2020-11-01 11:12 UTC, YuriSilenok commented
Метка определяющая тип задачи не найдена. Нарушены [требования](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/labels.md) для меток.

2020-11-01 11:12 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `Docs/Unit-test/README.md`

2020-11-01 11:13 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CAcademicDegree/Delete/UnitTest.cs
>      [TestClass]
После строки `{` (номер строки 4) ожидается любое из списка`[' {4}/// <summary>$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-11-01 11:13 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CAcademicDegree/Delete/UnitTest.cs`

2020-11-01 11:13 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CAcademicDegree/Insert/UnitTest.cs
>      [TestClass]
После строки `{` (номер строки 4) ожидается любое из списка`[' {4}/// <summary>$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-11-01 11:13 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CAcademicDegree/Insert/UnitTest.cs`

2020-11-01 11:13 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CAcademicDegree/Update/UnitTest.cs
>      [TestClass]
После строки `{` (номер строки 4) ожидается любое из списка`[' {4}/// <summary>$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-11-01 11:13 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CAcademicDegree/Update/UnitTest.cs`

2020-11-01 11:13 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CAcademicLoad/Update/CODE.PNG`

2020-11-01 11:13 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CAcademicLoad/Update/GRAPH.PNG`

2020-11-01 11:13 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CAcademicLoad/Update/UnitTest.cs
>      [TestClass]
После строки `{` (номер строки 5) ожидается любое из списка`[' {4}/// <summary>$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-11-01 11:13 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CAcademicLoad/Update/UnitTest.cs`

2020-11-01 11:13 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CAcademicLoad/Update/whitebox.md`

2020-11-01 11:13 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CAuditor/Insert/UnitTest.cs
> +namespace UnitTestOfTimetableOfClasses.Auditor.Insert
После строки `` (номер строки 3) ожидается любое из списка`['$', 'namespace UnitTestOfTimetableOfClasses\\.CAuditor\\.Insert$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-11-01 11:13 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CAuditor/Insert/UnitTest.cs`

2020-11-01 11:13 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CDirectionOfPreparation/Delete/UnitTest.cs
>      [TestClass]
После строки `{` (номер строки 4) ожидается любое из списка`[' {4}/// <summary>$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-11-01 11:13 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CDirectionOfPreparation/Delete/UnitTest.cs`

2020-11-01 11:13 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CEnclosures/Delete/UnitTest.cs
>      [TestClass]
После строки `{` (номер строки 4) ожидается любое из списка`[' {4}/// <summary>$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-11-01 11:13 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CEnclosures/Delete/UnitTest.cs`

2020-11-01 11:13 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CEnclosures/Delete/code.JPG`

2020-11-01 11:13 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CEnclosures/Delete/graph.JPG`

2020-11-01 11:13 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CEnclosures/Delete/whitebox.md`

2020-11-01 11:13 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CEnclosures/Insert/UnitTest.cs
>      [TestClass]
После строки `{` (номер строки 4) ожидается любое из списка`[' {4}/// <summary>$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-11-01 11:13 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CEnclosures/Insert/UnitTest.cs`

2020-11-01 11:13 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CEnclosures/Update/UnitTest.cs
> +namespace UnitTestOfTimetableOfClasses.CEnclosurse.Update
После строки `` (номер строки 3) ожидается любое из списка`['$', 'namespace UnitTestOfTimetableOfClasses\\.CEnclosures\\.Update$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-11-01 11:13 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CEnclosures/Update/UnitTest.cs`

2020-11-01 11:13 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CGroup/Delete/UnitTest.cs
> +namespace UnitTestOfTimetableOfClasses.CGroup.Delete
После строки `using LibOfTimetableOfClasses;` (номер строки 2) ожидается любое из списка`['(\\ufeff){,1}using [\\w+\\.]+;$', '$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-11-01 11:13 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CGroup/Delete/UnitTest.cs`

2020-11-01 11:13 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CGroup/Insert/CODE.PNG`

2020-11-01 11:13 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CGroup/Insert/GRAPH.PNG`

2020-11-01 11:13 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CGroup/Insert/UnitTest.cs
>      [TestClass]
После строки `{` (номер строки 5) ожидается любое из списка`[' {4}/// <summary>$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-11-01 11:13 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CGroup/Insert/UnitTest.cs`

2020-11-01 11:13 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CGroup/UPDATE/CODE.PNG`

2020-11-01 11:13 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CGroup/UPDATE/GRAPH.PNG`

2020-11-01 11:13 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CGroup/UPDATE/UnitTest.cs
> +namespace UnitTestOfTimetableOfClasses.CGroup.Update
После строки `` (номер строки 3) ожидается любое из списка`['$', 'namespace UnitTestOfTimetableOfClasses\\.CGroup\\.UPDATE$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-11-01 11:13 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CGroup/UPDATE/UnitTest.cs`

2020-11-01 11:13 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CGroup/UPDATE/whitebox.md`

2020-11-01 11:13 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CInstitute/Delete/UnitTest.cs
>      [TestClass]
После строки `{` (номер строки 6) ожидается любое из списка`[' {4}/// <summary>$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-11-01 11:13 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CInstitute/Delete/UnitTest.cs`

2020-11-01 11:13 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CInstitute/Insert/UnitTest.cs
>      [TestClass]
После строки `{` (номер строки 6) ожидается любое из списка`[' {4}/// <summary>$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-11-01 11:13 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CInstitute/Insert/UnitTest.cs`

2020-11-01 11:13 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CInstitute/Update/UnitTest.cs
>      [TestClass]
После строки `{` (номер строки 4) ожидается любое из списка`[' {4}/// <summary>$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-11-01 11:13 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CInstitute/Update/UnitTest.cs`

2020-11-01 11:13 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs
>      [TestClass]
После строки `{` (номер строки 4) ожидается любое из списка`[' {4}/// <summary>$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-11-01 11:13 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CTeacher/Delete/UnitTest.cs`

2020-11-01 11:13 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Insert/UnitTest.cs
>      [TestClass]
После строки `{` (номер строки 5) ожидается любое из списка`[' {4}/// <summary>$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-11-01 11:13 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CTeacher/Insert/UnitTest.cs`

2020-11-01 11:13 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CTeacher/Update/CODE.PNG`

2020-11-01 11:13 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CTeacher/Update/GRAPH.PNG`

2020-11-01 11:13 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTeacher/Update/UnitTest.cs
>      [TestClass]
После строки `{` (номер строки 5) ожидается любое из списка`[' {4}/// <summary>$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-11-01 11:13 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CTeacher/Update/UnitTest.cs`

2020-11-01 11:13 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CTeacher/Update/whitebox.md`

2020-11-01 11:13 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTitle/Delete/UnitTest.cs
>      [TestClass]
После строки `{` (номер строки 5) ожидается любое из списка`[' {4}/// <summary>$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-11-01 11:13 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CTitle/Delete/UnitTest.cs`

2020-11-01 11:13 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CTitle/Insert/CODE.PNG`

2020-11-01 11:13 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CTitle/Insert/GRAPH.PNG`

2020-11-01 11:13 UTC, YuriSilenok requested changes
Проблема в файле UnitTestOfTimetableOfClasses/CTitle/Insert/UnitTest.cs. 
 После строки `{` (номер строки 4) ожидается любое из списка`[' {4}/// <summary>$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-11-01 11:13 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CTitle/Insert/UnitTest.cs`

2020-11-01 11:13 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CTitle/Insert/whitebox.md`

2020-11-01 11:14 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTitle/Update/UnitTest.cs
>      [TestClass]
После строки `{` (номер строки 4) ожидается любое из списка`[' {4}/// <summary>$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-11-01 11:14 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CTitle/Update/UnitTest.cs`

2020-11-01 11:14 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTrainingProfile/Delete/UnitTest.cs
>  	[TestClass]
После строки `{` (номер строки 4) ожидается любое из списка`[' {4}/// <summary>$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-11-01 11:14 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CTrainingProfile/Delete/UnitTest.cs`

2020-11-01 11:14 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTypesOfOccupation/Delete/UnitTest.cs
> +namespace UnitTestOfTimetableOfClasses.TypesOfOccupations.Delete
После строки `` (номер строки 2) ожидается любое из списка`['$', 'namespace UnitTestOfTimetableOfClasses\\.CTypesOfOccupation\\.Delete$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-11-01 11:14 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CTypesOfOccupation/Delete/UnitTest.cs`

2020-11-01 11:14 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTypesOfOccupation/Insert/UnitTest.cs
>  namespace UnitTestOfTimetableOfClasses
После строки `` (номер строки 2) ожидается любое из списка`['$', 'namespace UnitTestOfTimetableOfClasses\\.CTypesOfOccupation\\.Insert$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-11-01 11:14 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CTypesOfOccupation/Insert/UnitTest.cs`

2020-11-01 11:14 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTypesOfOccupation/Update/UnitTest.cs
>      [TestClass]
После строки `{` (номер строки 4) ожидается любое из списка`[' {4}/// <summary>$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-11-01 11:14 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CTypesOfOccupation/Update/UnitTest.cs`

2020-11-01 11:14 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CUniversity/Delete/UnitTest.cs
>  namespace UnitTestOfTimetableOfClasses
После строки `` (номер строки 2) ожидается любое из списка`['$', 'namespace UnitTestOfTimetableOfClasses\\.CUniversity\\.Delete$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-11-01 11:14 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CUniversity/Delete/UnitTest.cs`

2020-11-01 11:14 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CUniversity/Insert/UnitTest.cs
>  namespace UnitTestOfTimetableOfClasses
После строки `` (номер строки 3) ожидается любое из списка`['$', 'namespace UnitTestOfTimetableOfClasses\\.CUniversity\\.Insert$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-11-01 11:14 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CUniversity/Insert/UnitTest.cs`

2020-11-01 11:14 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CUniversity/Update/UnitTest.cs
>  namespace UnitTestOfTimetableOfClasses
После строки `` (номер строки 3) ожидается любое из списка`['$', 'namespace UnitTestOfTimetableOfClasses\\.CUniversity\\.Update$']` Нарушено [требование](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/blob/dev/Docs/Code-review/README.md) для кода.

2020-11-01 11:14 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/CUniversity/Update/UnitTest.cs`

2020-11-01 11:14 UTC, YuriSilenok commented
Обнаружены неизвестные файлы:
- `UnitTestOfTimetableOfClasses/UnitTestOfTimetableOfClasses.csproj`

2020-11-01 11:15 UTC, YuriSilenok reviewed
Есть ошибки в путях, а что у нас с моделями?

2020-11-01 11:55 UTC, NesgovorovVS commented
> Есть ошибки в путях, а что у нас с моделями?
> ![image](https://user-images.githubusercontent.com/14871471/97801363-3f00ab00-1c4d-11eb-90c9-6cfa11e14064.png)

а вот я сам не знаю, что с моделями, про них в документации ни слова

2020-11-01 12:43 UTC, YuriSilenok commented
создал [задачу](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/1374) на уточнение требований к тестам для моделей.

2020-11-08 16:57 UTC, NesgovorovVS commented
https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1367#issuecomment-723635061

2020-11-27 21:12 UTC, NesgovorovVS commented
Завтра залью новые изменения на гит. В связи с новыми требованиями.

2021-05-19 07:04 UTC, closed without merging