Добавил описание понятия "веха"
Students-of-the-city-of-Kostroma/Student-timetable pull request #1432
Opened 2021-05-23 17:38 UTC by Danil-Prokofiev

-Добавил описание понятию _вехи_ в файле 'issues.md' в каталоге 'Student-timetable/Docs/'.
-Добавил ссылку на сайт с полной информацией о _вехах_ 
-Добавил ссылку на сайт с описание создания _вехи_

2021-05-26 12:51 UTC, YuriSilenok requested changes

2021-05-26 12:51 UTC, YuriSilenok commented on Docs/issues.md
> +-Список открытых и закрытых 'issues' и 'pull request'’ов, связанных с вехой
немного не правильно использован синтаксис для ненумерованного списка

2021-05-26 12:51 UTC, YuriSilenok commented on Docs/issues.md
> +-Список открытых и закрытых 'issues' и 'pull request'’ов, связанных с вехой
если хотите что-то выделить, то лучше использовать `
ознакомьтесь с синтаксисом [здесь](https://guides.github.com/features/mastering-markdown/)

2021-05-26 17:00 UTC, Danil-Prokofiev commented on Docs/issues.md
> +-Список открытых и закрытых 'issues' и 'pull request'’ов, связанных с вехой
Изменил синтаксис ненумерованного списка согласно Mastering Markdown. Ссылка на коммит: https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1432/commits/a481032a9c2c4e1734b53bb0edb16f94e41c92ed

2021-05-26 18:59 UTC, YuriSilenok requested changes
Так же хотелось видеть разъяснения по поводу того, как использовать вехи. Нужно расписать как они используются для обозначения спринтов, что нужно писать в описание вехи. Для этого я рекомендую заглянуть в закрытые вехи этого проекта.

2021-05-26 18:59 UTC, YuriSilenok commented on Docs/issues.md
> +Когда вы создаете веху, вы можете ее «связать» с 'issues' и 'pull request'’ами.
пожалуйста, для выделения слов используйте символ `, так принято во все документации. Эти требования так же перечислены в [документации проекта](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/tree/dev/Docs/Contributers/DocStyle).

2021-05-27 07:10 UTC, YuriSilenok requested changes
в целом хорошо, осталось исправить указанные опечатки

2021-05-27 07:10 UTC, YuriSilenok commented on Docs/issues.md
> +Вехи можно использовать для отслеживания прогресса в работе над несколькими `issues` или `pull requests`’ами в репозитории.
Лишний апостроф перед `ами в репозитории.`

2021-05-27 07:10 UTC, YuriSilenok commented on Docs/issues.md
> +Когда вы создаете веху, вы можете ее «связать» с `issues` и `pull request`’ами.
Лишний апостроф перед `ами.`

2021-05-27 07:10 UTC, YuriSilenok commented on Docs/issues.md
> +* Количество открытых и закрытых `issues` и `pull request`’ов, связанных с вехой
’ов, связанных с вехой

2021-05-27 07:10 UTC, YuriSilenok commented on Docs/issues.md
> +* Список открытых и закрытых `issues` и `pull request`’ов, связанных с вехой
’ов, связанных с вехой

2021-05-27 10:13 UTC, YuriSilenok requested changes

2021-05-27 10:13 UTC, YuriSilenok commented on Docs/issues.md
> +> О том как создать веху можно узнать [здесь](https://docs.github.com/en/github/managing-your-work-on-github/tracking-the-progress-of-your-work-with-milestones/creating-and-editing-milestones-for-iss
символ `>` используется для цитирования. здесь вы не цитируете, а предлагаете некоторый набор полезных ссылок.

2021-05-27 15:05 UTC, YuriSilenok approved these changes

2021-05-27 15:06 UTC, merged