Dev
Students-of-the-city-of-Kostroma/Student-timetable pull request #1441
Opened 2021-05-25 12:35 UTC by HappyRogue36

Правка вида модульных тестов

2021-05-25 13:55 UTC, YuriSilenok requested changes
Исправьте пространства имён у тестовых классов.

2021-05-25 17:00 UTC, HappyRogue36 commented
Исправил ошибку.

2021-05-26 13:28 UTC, YuriSilenok requested changes

2021-05-26 13:28 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/MAcademicDegree/UnitTest.cs
> +using LibOfTimetableOfClasses;
Причина по которой были перемешаны эти подключения

2021-05-26 13:28 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/MAcademicDegree/UnitTest.cs
> +
почему была добавлена эта пустая строка?

2021-05-26 13:28 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/MAuditor/UnitTest.cs
> +                Assert.AreEqual(typeof(string), T_Auditor.Building.GetType(), "Ожидался тип поля ushort");
почему был сменен регистр буквы?

2021-05-26 13:28 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/MTrainingProfile/UnitTest.cs
> +               MTrainingProfile mTrainingProfile = new MTrainingProfile("Информациооные системы и технологии", "ИС", "40454");
что тут с отступом?

2021-05-26 14:29 UTC, HappyRogue36 commented on UnitTestOfTimetableOfClasses/MAcademicDegree/UnitTest.cs
> +
Во время исправлений с проблем с пространством имён добавил, забыл убрать.

2021-05-26 14:29 UTC, HappyRogue36 commented on UnitTestOfTimetableOfClasses/MAuditor/UnitTest.cs
> +                Assert.AreEqual(typeof(string), T_Auditor.Building.GetType(), "Ожидался тип поля ushort");
Даже не трогал эту строчку кода.

2021-05-26 14:30 UTC, HappyRogue36 commented on UnitTestOfTimetableOfClasses/MTrainingProfile/UnitTest.cs
> +               MTrainingProfile mTrainingProfile = new MTrainingProfile("Информациооные системы и технологии", "ИС", "40454");
Вот это уже мой косяк.

2021-05-26 14:31 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/MAuditor/UnitTest.cs
> +                Assert.AreEqual(typeof(string), T_Auditor.Building.GetType(), "Ожидался тип поля ushort");
Тогда верните в исходное состояние, сами просмотрите изменения в этом запросе

2021-05-26 14:34 UTC, YuriSilenok commented
конфликт связанный с настройками проекта я разрешил

2021-05-26 14:51 UTC, HappyRogue36 commented
Получается, всё?

2021-05-26 15:02 UTC, YuriSilenok commented
Нужно убрать лишние изменения

2021-05-26 15:19 UTC, HappyRogue36 commented
Внёс изменения.

2021-05-26 15:48 UTC, HappyRogue36 commented
Теперь точно всё поправил.

2021-05-26 16:27 UTC, merged