Правка Insert
Students-of-the-city-of-Kostroma/Student-timetable pull request #1453
Opened 2021-05-26 21:33 UTC by xShende

Для файлов Insert созданы папки с юниттестами Insert`ов

2021-05-27 05:34 UTC, YuriSilenok requested changes
Не изменены пространства имен

2021-05-28 12:16 UTC, YuriSilenok commented
укажите ссылку на задачу

2021-05-28 12:56 UTC, xShende commented
> укажите ссылку на задачу

В ВК выдавали задачу мне(Гречухин Дмитрий/Дмитрий Романов, Артемию, Вите и Егору) с сортировкой файлов по папкам

2021-05-28 20:55 UTC, YuriSilenok reviewed
решите конфликт

2021-05-28 21:29 UTC, YuriSilenok requested changes
имена папок не соответствуют требованиям

2021-05-28 22:13 UTC, xShende commented
> имена папок не соответствуют требованиям

У меня задание было с сортировкой файлов UT_Insert. Папки называются UT_Insert, как указано в требованиях. Что, собственно, не так?

2021-05-29 05:52 UTC, YuriSilenok commented
> > имена папок не соответствуют требованиям
> 
> У меня задание было с сортировкой файлов UT_Insert. Папки называются UT_Insert, как указано в требованиях. Что, собственно, не так?

не так то, что имя папок не соответствует требованиям, об этом я уже написал.
В соответствии с какими требованиями вы выполняли свою работу, покажите где в ваших требованиях указано как нужно именовать файлы.

2021-05-29 07:48 UTC, xShende commented
> > > имена папок не соответствуют требованиям
> > 
> > 
> > У меня задание было с сортировкой файлов UT_Insert. Папки называются UT_Insert, как указано в требованиях. Что, собственно, не так?
> 
> не так то, что имя папок не соответствует требованиям, об этом я уже написал.
> В соответствии с какими требованиями вы выполняли свою работу, покажите где в ваших требованиях указано как нужно именовать файлы.

Переименовал.

2021-05-29 07:56 UTC, YuriSilenok commented
у вас конфликты

2021-05-29 08:00 UTC, YuriSilenok requested changes
это что ща файл был добавлен в репозиторий?
- UnitTestOfTimetableOfClasses/CTeacher/Delete/Thumbs.db

2021-05-29 08:00 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CTitle/Insert/UnitTest.cs.cs
> +        public void CTitle_1()
Имя теста не соответствует требованиям, проверьте все остальные тесты

2021-05-29 09:13 UTC, xShende commented on UnitTestOfTimetableOfClasses/CTitle/Insert/UnitTest.cs.cs
> +        public void CTitle_1()
Переименовал имена тестов, а вот UnitTestOfTimetableOfClasses/CTeacher/Delete/Thumbs.db это я не знаю, что за файл, ибо в обозревателе решений его нет, и добавлял его не я, хотя почему-то с моим коммитом он добавился.

2021-05-29 09:16 UTC, YuriSilenok commented
у вас конфликт

2021-05-29 14:19 UTC, xShende commented
> у вас конфликт

Дак это не мои файлы, в конфликте ему не нравятся файлы с UT_Delete и UT_Update - которыми занимался Егор Поселёнов и Виктор Степанов. В моих файлах(Insert) нет конфликтов.

2021-05-29 14:25 UTC, YuriSilenok commented
> > у вас конфликт
> 
> Дак это не мои файлы, в конфликте ему не нравятся файлы с UT_Delete и UT_Update - которыми занимался Егор Поселёнов и Виктор Степанов. В моих файлах(Insert) нет конфликтов.

проблема и не в этих файлах, а в `UnitTestOfTimetableOfClasses/UnitTestOfTimetableOfClasses.csproj`

2021-05-29 14:33 UTC, YuriSilenok requested changes
Куда делись эти файлы*

- UnitTestOfTimetableOfClasses/UT_CTeacher/Delete/UnitTest.cs
- UnitTestOfTimetableOfClasses/UT_CTeacher/UT_Delete/code.png
- UnitTestOfTimetableOfClasses/UT_CTeacher/UT_Delete/graph.png
UnitTestOfTimetableOfClasses/UT_CTeacher/UT_Delete/whiteBox.md

2021-05-29 14:36 UTC, YuriSilenok commented
> Куда делись эти файлы*
> 
> * UnitTestOfTimetableOfClasses/UT_CTeacher/Delete/UnitTest.cs
> * UnitTestOfTimetableOfClasses/UT_CTeacher/UT_Delete/code.png
> * UnitTestOfTimetableOfClasses/UT_CTeacher/UT_Delete/graph.png
>   UnitTestOfTimetableOfClasses/UT_CTeacher/UT_Delete/whiteBox.md

Я их нашел

2021-05-29 14:53 UTC, YuriSilenok requested changes
почему вы коммитите все без разбора, почему снова появился этот файл в репозитории?
`UnitTestOfTimetableOfClasses/CTeacher/Delete/Thumbs.db`

2021-05-29 15:04 UTC, YuriSilenok commented
я все еще жду когда вы решите конфликты

2021-05-29 15:06 UTC, YuriSilenok requested changes
сами проверьте что вы коммитите, это что за файл?
`UnitTestOfTimetableOfClasses/CTeacher/Delete/Thumbs.db`

2021-05-29 15:15 UTC, xShende commented
> сами проверьте что вы коммитите, это что за файл?
> `UnitTestOfTimetableOfClasses/CTeacher/Delete/Thumbs.db`

Это я вернул ту папку, которая добавилась с каким-то из коммитов(как Артемий сказал, то это папка девочки, которой он помогал с ЛР04)

2021-05-29 18:34 UTC, YuriSilenok commented
сделайте все как надо, потом напишите письмо что готово к проверке

2021-06-01 13:10 UTC, closed without merging