коммит на изменение структуры класса Controller
Students-of-the-city-of-Kostroma/Student-timetable pull request #146
Opened 2019-03-07 20:11 UTC by Proffet78

2019-03-08 18:58 UTC, YuriSilenok commented
В какую ветку и почему вы хотите слить свои изменения?

2019-03-10 20:12 UTC, Proffet78 commented
Здравствуйте.
В ветку Testing, не доглядел. Исправил.
Спасибо.

2019-03-12 10:20 UTC, YuriSilenok commented
Кто является ответственным в запросах на слияние и почему?

2019-03-12 10:31 UTC, Proffet78 commented
Здравствуйте.

Я думаю, что преподаватель или владелец проекта. Инициатором слияния в данном случае являюсь я, а вы являетесь ответственным в запросах на слияние. В конечном итоге Владелец проекта принимает решение о принятии изменений, либо об их отклонении.

Спасибо.

2019-03-19 19:54 UTC, YuriSilenok requested changes
Исправить замечание

2019-03-19 19:54 UTC, YuriSilenok commented on LibOfTimetableOfClasses/Controller.cs
> +            DataTable table = new DataTable(tableName);
DateTable это родитель класса Controller.
Это значит что Вам в конструкторе не нужно создавать экземпляр класса DateTable.
Это значит что table это и есть создаваемый объект.
Это значит что в место переменной table нужно использовать слово this.
Попробуйте в этом разобраться.

2019-03-26 08:48 UTC, Proffet78 commented
Здравствуйте!

Исправил!

Спасибо,

2019-04-03 07:33 UTC, Proffet78 commented
Здравствуйте!
Вы можете объяснить мне, что у меня не правильно сделано?
Спасибо.

2019-04-03 09:24 UTC, YuriSilenok commented
Почему Вы решили что у Вас не правильно сделано?
Вы в последний раз написали что исправили, после этого я еще ничего Вам не писал.

2019-04-23 17:27 UTC, closed without merging