Создание формы Department (#133)
Students-of-the-city-of-Kostroma/Student-timetable pull request #148
Opened 2019-03-08 16:23 UTC by VinogradovAlexandr781227

2019-03-08 19:44 UTC, YuriSilenok requested changes
Чем руководствовались при выборе ветки в которую будете заливать свои изменения?

2019-03-08 20:18 UTC, VinogradovAlexandr781227 commented
Здравствуйте. Не доглядел. Перепутал

2019-03-09 11:13 UTC, YuriSilenok commented
Приступайте к решению конфликта

2019-03-09 11:14 UTC, YuriSilenok approved these changes

2019-04-23 17:26 UTC, closed without merging