Создать форму Профили подготовки
Students-of-the-city-of-Kostroma/Student-timetable pull request #149
Opened 2019-03-08 21:06 UTC by KudelinRoman

задача [#129](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/129)

2019-03-11 13:24 UTC, YuriSilenok requested changes
Не настроены отступы.

2019-03-11 22:06 UTC, KudelinRoman commented
Здравствуйте, я настроил отступы.

2019-03-15 11:53 UTC, YuriSilenok requested changes
Проверить во всех измененных файлах.

2019-03-15 11:53 UTC, YuriSilenok commented on TimetableOfClasses/Start.Designer.cs
> +            this.menuStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
Здесь вы заменили табуляцию на пробелы. Исправить на табуляцию.

2019-04-01 13:50 UTC, YuriSilenok requested changes

2019-04-01 13:50 UTC, YuriSilenok commented on TimetableOfClasses/TrainingProfiles.Designer.cs
> +            base.Dispose(disposing);
Этот класс содержит в качестве отступов пробелы.

2019-04-02 20:31 UTC, KudelinRoman commented
Здравствуйте, я исправил пробелы на табуляцию в классе.
Спасибо.

2019-04-03 16:21 UTC, YuriSilenok submitted a review, later dismissed

2019-04-03 16:21 UTC, YuriSilenok commented on TimetableOfClasses/TrainingProfiles.cs
> +        }
В этом файле не верные отступы.

2019-04-08 19:55 UTC, KudelinRoman commented
Здравствуйте,  мне приступать к разрешению конфликтов?
Спасибо.

2019-04-12 20:14 UTC, KudelinRoman commented on TimetableOfClasses/TrainingProfiles.cs
> +        }
Здравствуйте, я исправил отступы. Мне приступать к разрешению конфликтов?
Спасибо.

2019-04-23 19:38 UTC, YuriSilenok commented
Закрыто и зачтено. эта задача реализуется повторно другой командой.

2019-04-23 19:38 UTC, closed without merging