Убрал одинаковый метод в отдельный класс
Students-of-the-city-of-Kostroma/Student-timetable pull request #1531
Opened 2021-06-13 09:21 UTC by Daniil34525

Добавил класс, в который положил повторяющийся в нескольких местах метод и убрал его из мест, где он содержался раньше.

2021-06-13 12:59 UTC, YuriSilenok requested changes

2021-06-13 12:59 UTC, YuriSilenok commented on TimetableOfClasses/DG_ColumnHeaderMouseClick.cs
> +}
Это что?

2021-06-14 08:03 UTC, Daniil34525 commented on TimetableOfClasses/DG_ColumnHeaderMouseClick.cs
> +}
Случайно добавил класс.

2021-06-14 08:17 UTC, YuriSilenok commented on TimetableOfClasses/DG_ColumnHeaderMouseClick.cs
> +}
Нужно убрать лишнее

2021-06-15 06:21 UTC, YuriSilenok requested changes

2021-06-15 06:21 UTC, YuriSilenok commented on TimetableOfClasses/DG_ColumnHeaderMouseClick1.cs
> +	public class DG_ColumnHeaderMouseClick1
Название класса не должно указывать на метод из-за которого оно делалось. Когда вы делали ЛР с наследованием геометрических фигур, вы же класс наследник не называли как площадь, а давали более осмысленное название.

2021-06-17 06:59 UTC, YuriSilenok commented
1. Вам нужно создать `Компонент` 
2. в него вам нужно будет перетащить `DataGridView`. 
3. В код этого компонента нужно будет перенести задублированный метод
4. В коде дизайнера подписаться на событие на исполнение задублированного кода
5. В коде дизайнере формах где используется задублированный код нужно поменять `DataGridView` на созданный компонент
![image](https://user-images.githubusercontent.com/14871471/122346759-fda9db00-cf51-11eb-9117-72390c0970a5.png)
Если возникнут трудности, пишите в этом запросе, я помогу, задача у Вас не тривиальная.

2021-06-17 08:57 UTC, Daniil34525 commented
Не понимаю как выполнить 5 пункт, как поменять DataGridView на созданный компонент. Ведь если я поменяю компонент DG который там уже есть, получается мне надо копировать все методы. Или я где-то кнопку не увидел?
![image](https://user-images.githubusercontent.com/84543667/122365190-22f31500-cf63-11eb-98fb-0c05d1b06b6a.png)

2021-06-17 08:59 UTC, YuriSilenok commented
у каждой формы есть файл дизайнер с кодом, которым собственно и накидываются все элементы, тебе нужно заменить там классы. визуально ничего не должно поменяться и ошибок не должно появиться. найди файл с дизанер

2021-06-17 09:19 UTC, Daniil34525 commented
Я так понял что нужно здесь поменять, только я не понимаю что и на что заменять.
![image](https://user-images.githubusercontent.com/84543667/122368589-24720c80-cf66-11eb-871c-846268df0c9d.png)

2021-06-17 09:26 UTC, Daniil34525 commented
Нашел только этот метод, но он отвечает за двойной клик, и вроде как за другое
![image](https://user-images.githubusercontent.com/84543667/122369795-30120300-cf67-11eb-9c77-ce484c9cc42c.png)

2021-06-17 09:31 UTC, YuriSilenok commented
![image](https://user-images.githubusercontent.com/14871471/122370618-de1dad00-cf67-11eb-9588-33ae47ae4af2.png)
вот это поле нужно инициализировать.

2021-06-17 09:44 UTC, Daniil34525 commented
А как если дизайнер не видит компонент
![image](https://user-images.githubusercontent.com/84543667/122372720-9566f380-cf69-11eb-852c-9041d3e19932.png)
Или я не так понял?

2021-06-17 09:47 UTC, YuriSilenok commented
найдите место где объявляется этот датагрид

2021-06-17 09:47 UTC, Daniil34525 commented
Или приравнять к значениям из другого класса

2021-06-17 09:48 UTC, Daniil34525 commented
Здесь. Назвал так же как и было
![image](https://user-images.githubusercontent.com/84543667/122373533-3a81cc00-cf6a-11eb-9b2f-947ecc5dd1b8.png)

2021-06-17 09:49 UTC, YuriSilenok commented
нет, это компонент, а надо в дизайнере формы найти

2021-06-17 09:50 UTC, Daniil34525 commented
![image](https://user-images.githubusercontent.com/84543667/122373981-a2381700-cf6a-11eb-85c4-6d01f63b4950.png)

2021-06-17 09:53 UTC, Daniil34525 commented
Все равно не доходит как использовать метод другого класса

2021-06-17 09:54 UTC, YuriSilenok commented
![image](https://user-images.githubusercontent.com/14871471/122374633-35714c80-cf6b-11eb-88cf-335068b08ef9.png)

2021-06-17 09:56 UTC, YuriSilenok commented
![image](https://user-images.githubusercontent.com/14871471/122374840-605ba080-cf6b-11eb-94dc-5f80e74bee87.png)

2021-06-17 10:10 UTC, Daniil34525 commented
А что с этим делать?

2021-06-17 10:12 UTC, Daniil34525 commented
На втором скрине DG создается как название, а на первом как объект

2021-06-17 10:14 UTC, Daniil34525 commented
Мне надо заменить выполнение одного метода на выполнение того же метода только в компоненте.
Мне же не нужно создавать другой объект?

2021-06-17 10:18 UTC, YuriSilenok commented
> Мне надо заменить выполнение одного метода на выполнение того же метода только в компоненте.

да

> Мне же не нужно создавать другой объект?

не понял вопроса

2021-06-17 13:46 UTC, Daniil34525 commented
Как я создам выполнение другого метода в дизайнере?

2021-06-17 17:44 UTC, YuriSilenok commented
> Как я могу создать выполнение другого метода в дизайнере?

если речь идет о дизайнере формы, то вам не нужно там привязывать задублированный метод, наоборот, привязку нужно убрать, так как она есть в вашем компоненте.

2021-06-17 19:49 UTC, YuriSilenok commented
я стесняюсь спросить, а где в описании ссылка на задачу, которую вы делаете?

2021-06-21 05:13 UTC, closed without merging