Update UnitTest.cs
Students-of-the-city-of-Kostroma/Student-timetable pull request #1532
Opened 2021-06-13 15:30 UTC by yungkrevetka

#1516 - Исправление дублирующегося кода

2021-06-13 18:23 UTC, YuriSilenok requested changes
Почему был исправлен код не указанный как дублирующий в задаче?

2021-06-13 18:25 UTC, YuriSilenok requested changes
Почему был исправлен код не указанный как дублирующий в задаче?

2021-06-14 17:43 UTC, YuriSilenok requested changes
вы не избавились от дублирующего кода

2021-06-15 12:16 UTC, YuriSilenok requested changes

2021-06-15 12:16 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CEnclosures/Update/UnitTest.cs
> +            }
зачем этот костыль?

2021-06-15 18:49 UTC, yungkrevetka commented on UnitTestOfTimetableOfClasses/CEnclosures/Update/UnitTest.cs
> +            }
По другому не работает(

2021-06-17 06:23 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CEnclosures/Update/UnitTest.cs
> +            }
оно прекрасно может работать и без этого костыля

2021-06-17 06:24 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CEnclosures/Update/UnitTest.cs
> +        bool PhoneDouble = false;
эти костыли тут не нужны

2021-06-17 09:29 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CEnclosures/Update/UnitTest.cs
> +        bool PhoneDouble;
эти поля вообще не нужны, это необоснованные костыли, можно обойтись без этих флагов

2021-06-17 09:42 UTC, YuriSilenok commented
я бы ожидал что вы исправите только конкретный дублированный код, другие проверки, которые вы перенесли в общий метод вызывают сомнения. По сути, этот метод является прекондишеном для теста. 
![image](https://user-images.githubusercontent.com/14871471/122372586-7700f800-cf69-11eb-8014-3ef095741ddc.png)

2021-06-17 10:05 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CEnclosures/Update/UnitTest.cs
> +            MUniversity university = new MUniversity("4401026216", "МГУ", "Московский Государственный Университет", "156005, Московская область, г. Москва, ул. Дзержинского, 17", "156005, Московская
У вас есть повторяющийся код, почему?
![image](https://user-images.githubusercontent.com/14871471/122376297-b250f600-cf6c-11eb-8d43-3ae436052dde.png)

2021-06-17 10:09 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CEnclosures/Update/UnitTest.cs
> -            MUniversity university = new MUniversity("4401026216", "МГУ", "Московский Государственный Университет", "156005, Московская область, г. Москва, ул. Дзержинского, 17", "156005, Московская
почему вы это удалили?

2021-06-17 11:09 UTC, yungkrevetka commented on UnitTestOfTimetableOfClasses/CEnclosures/Update/UnitTest.cs
> -            MUniversity university = new MUniversity("4401026216", "МГУ", "Московский Государственный Университет", "156005, Московская область, г. Москва, ул. Дзержинского, 17", "156005, Московская
Теперь опять не работает

2021-06-17 11:11 UTC, YuriSilenok commented on UnitTestOfTimetableOfClasses/CEnclosures/Update/UnitTest.cs
> -            MUniversity university = new MUniversity("4401026216", "МГУ", "Московский Государственный Университет", "156005, Московская область, г. Москва, ул. Дзержинского, 17", "156005, Московская
Если ты в Е корпусе, найди меня в коворкинге с ноутбуком до 15 часов я смогу тебе показать все пальцем

2021-06-19 05:13 UTC, closed without merging