#1515 Fix 'Duplicate Code' issue in multiple files
Students-of-the-city-of-Kostroma/Student-timetable pull request #1533
Opened 2021-06-14 14:24 UTC by TumelliYN

Ready

2021-06-14 17:58 UTC, YuriSilenok requested changes
в соответствии с новым стандартом C# правильнее инициализацию данных проводить через фигурные скобки. Кроме этого я не увидел причины по которой вы выполнили преобразование
`typeof(int)` -> `Type.GetType("System.Int32")`
как называется тот способ, которым вы воспользовались для устранения дублирующего кода?

2021-06-15 10:48 UTC, TumelliYN commented
«правильнее инициализацию данных проводить через фигурные скобки.»
По моему мнению именно это и послужило вызову ошибки. Причиной данного преобразование стала ошибка повтора инициализации, поэтому я решил упростить инициализацию, этот способ называется  «упрощение».
  
>Понедельник, 14 июня 2021, 20:58 +03:00 от Юрий Силенок ***@***.***>:
> 
> 
>@YuriSilenok requested changes on this pull request.
>в соответствии с новым стандартом C# правильнее инициализацию данных проводить через фигурные скобки. Кроме этого я не увидел причины по которой вы выполнили преобразование
>typeof(int) -> Type.GetType("System.Int32")
>как называется тот способ, которым вы воспользовались для устранения дублирующего кода?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
 
 
--
дима чугунов
 

2021-06-15 10:52 UTC, TumelliYN commented
«правильнее инициализацию данных проводить через фигурные скобки.»
По моему мнению именно это и послужило вызову ошибки дублирования кода. Причиной данного преобразование стала ошибка повтора инициализации, поэтому я решил упростить инициализацию, этот способ называется «Равносильное преобразование алгоритмов».
>Понедельник, 14 июня 2021, 20:58 +03:00 от Юрий Силенок ***@***.***>:
> 
> 
>@YuriSilenok requested changes on this pull request.
>в соответствии с новым стандартом C# правильнее инициализацию данных проводить через фигурные скобки. Кроме этого я не увидел причины по которой вы выполнили преобразование
>typeof(int) -> Type.GetType("System.Int32")
>как называется тот способ, которым вы воспользовались для устранения дублирующего кода?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
дима чугунов
 

2021-06-15 10:59 UTC, YuriSilenok commented
В соответствии с какими рекомендациями вы провели "упрощение"?

2021-06-15 11:03 UTC, YuriSilenok commented
Какие способы устранения проблемы вы рассматривали?

2021-06-15 11:20 UTC, TumelliYN commented
Так же пытался сгруппировать дублирующие части в один метод, потом думал, что эти два метода находиться в подклассах и пытался их вынести в супер класс, как описывается в инструкции способа «Подтягивание поля» , и так же показался уместным способ « Шаблона формы» , но получился токо последний способ.
  
>Вторник, 15 июня 2021, 14:03 +03:00 от Юрий Силенок ***@***.***>:
> 
> 
>Какие способы устранения проблемы вы рассматривали?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
дима чугунов
 

2021-06-15 12:06 UTC, YuriSilenok commented
> «Подтягивание поля»

так, а почему подтягивание поля не получилось?

2021-06-15 12:07 UTC, YuriSilenok commented
и я ожидаю увидеть в описании запроса ссылку на issue

2021-06-15 12:23 UTC, TumelliYN commented
Отредактировал запроc, добавив ссылку на issues.

  
>Вторник, 15 июня 2021, 15:07 +03:00 от Юрий Силенок ***@***.***>:
> 
> 
>и я ожидаю увидеть в описании запроса ссылку на issue
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
дима чугунов
 

2021-06-15 12:27 UTC, TumelliYN commented
Не прошел проверку гита, выглядело вот так,  сделал просто добавление столбцов, а не повторное добавление, ну мыслил так по крайней мере,   Потом попробовал  преобразование алгоритмов и чудо гит сказал верно.
 

  
>Вторник, 15 июня 2021, 15:06 +03:00 от Юрий Силенок ***@***.***>:
> 
> 
>«Подтягивание поля»
так, а почему подтягивание поля не получилось?
—
You are receiving this because you authored the thread.
Reply to this email directly,  view it on GitHub , or  unsubscribe .
 
 
--
дима чугунов
 

2021-06-15 12:40 UTC, TumelliYN commented
Скорее всего данный способ не подходит сюда, либо мой решение по этому способу не конечное щас залью на гит еще одну попытку фикса.

  
>Вторник, 15 июня 2021, 15:26 +03:00 от дима чугунов ***@***.***>:
> 
>Не прошел проверку гита, выглядело вот так,  сделал просто добавление столбцов, а не повторное добавление, ну мыслил так по крайней мере,   Потом попробовал  преобразование алгоритмов и чудо гит сказал верно.
> 
>
> 
>>Вторник, 15 июня 2021, 15:06 +03:00 от Юрий Силенок < ***@***.*** >:
>> 
>> 
>>«Подтягивание поля»
>так, а почему подтягивание поля не получилось?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
> 
> 
>--
>дима чугунов
>  
 
 
--
дима чугунов
 

2021-06-15 13:08 UTC, YuriSilenok commented
я бы рекомендовал обратить внимание на этот запрос https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/1535, в нем реализуется решение, которое можно будет применить и у Вас.

2021-06-15 13:28 UTC, TumelliYN commented
А чем плох мой метод?

2021-06-15 13:34 UTC, YuriSilenok commented on LibOfTimetableOfClasses/CCourseSchedule.cs
> +            idColumn = CAcademicLoad.InpId(idColumn);
представим что вы разработчик, какой логикой вы будете руководствоваться чтобы найти нужный метод InpId?

2021-06-15 13:36 UTC, TumelliYN commented on LibOfTimetableOfClasses/CCourseSchedule.cs
> +            idColumn = CAcademicLoad.InpId(idColumn);
Ну это да... А можно как-то обойти создание отдельного класса?

2021-06-15 13:37 UTC, YuriSilenok commented on LibOfTimetableOfClasses/CCourseSchedule.cs
> +            idColumn = CAcademicLoad.InpId(idColumn);
а чем вас пугает отдельный класс?

2021-06-15 14:22 UTC, TumelliYN commented on LibOfTimetableOfClasses/CCourseSchedule.cs
> +            idColumn = CAcademicLoad.InpId(idColumn);
Отдельный класс, больше ошибок...

2021-06-15 16:02 UTC, TumelliYN commented
Добавил отдельный класс, вроде, работает)

2021-06-17 07:00 UTC, YuriSilenok commented on LibOfTimetableOfClasses/CCourseSchedule.cs
> +            idColumn = CAcademicLoad.InpId(idColumn);
плохой программист - больше ошибок

2021-06-17 07:03 UTC, YuriSilenok commented on LibOfTimetableOfClasses/ColumnGenerator.cs
> +        }
Это не должен быть статический метод, тут должен быть конструктор, а этот класс должен наследоваться. И класс у вас создает первичный ключ, а не просто любой столбец, названия должны быть более осмысленные.

2021-06-17 07:10 UTC, TumelliYN commented on LibOfTimetableOfClasses/ColumnGenerator.cs
> +        }
Понял, сейчас поправлю.

2021-06-17 07:31 UTC, YuriSilenok commented
чет вы тут накосячили с мержами

2021-06-17 07:31 UTC, TumelliYN commented
Да я вижу, а как это поправить?

2021-06-17 07:32 UTC, YuriSilenok commented
> Да я вижу, а как это поправить?

git revert

2021-06-17 07:42 UTC, TumelliYN commented
Что-то у меня не получается `revert`
![image](https://user-images.githubusercontent.com/81413377/122353368-a8bd9300-cf58-11eb-8739-83e53ba60abd.png)

2021-06-17 07:55 UTC, YuriSilenok commented
все равно 11 файлов

2021-06-17 08:05 UTC, TumelliYN commented
Что-то я вообще не понимаю, как это править..

2021-06-17 08:05 UTC, TumelliYN commented
Я не могу сделать реверт `merge`

2021-06-17 08:07 UTC, YuriSilenok commented
тогда попробуй сделать новую ветку от нужного коммита

2021-06-17 08:23 UTC, TumelliYN commented
А не подскажете, как коммит с другой ветки закинуть сюда?

2021-06-17 08:26 UTC, YuriSilenok commented
> А не подскажете, как коммит с другой ветки закинуть сюда?

git cherry-pick

2021-06-17 08:26 UTC, YuriSilenok commented
может просто званого?
Ты с какой группы?

2021-06-17 08:27 UTC, TumelliYN commented
![image](https://user-images.githubusercontent.com/81413377/122360354-048b1a80-cf5f-11eb-962f-fa2c3e19f50c.png)

2021-06-17 08:28 UTC, TumelliYN commented
Такс, а что делать теперь?

2021-06-17 08:29 UTC, YuriSilenok commented
я сейчас буду простые задания не для ИС выдавать, советую взять, а твой репозиторий удалить и сделать новую вилку, а сложную задачу с себя снять

2021-06-17 08:30 UTC, TumelliYN commented
Понял.

2021-06-17 08:32 UTC, closed without merging