Update MInstitute.cs
Students-of-the-city-of-Kostroma/Student-timetable pull request #1534
Opened 2021-06-14 19:08 UTC by DreAMer2308

#1510 Fix 'Complex Method' issue in LibOfTimetableOfClasses\MInstitute.cs

2021-06-15 12:08 UTC, YuriSilenok requested changes
Вы уменьшили количество информации в случае возникновения ошибки, не надо так.

2021-06-15 13:02 UTC, DreAMer2308 commented
Обновил информацию в случае возникновения ошибки

2021-06-15 13:04 UTC, YuriSilenok commented on LibOfTimetableOfClasses/MInstitute.cs
> +                    throw new Exception("Некорректная длина поля");
а здесь почему два сообщения заменены на одно?

2021-06-15 13:06 UTC, DreAMer2308 commented on LibOfTimetableOfClasses/MInstitute.cs
> +                    throw new Exception("Некорректная длина поля");
А их разве нельзя внести под одну интерпретацию?

2021-06-15 13:10 UTC, YuriSilenok commented on LibOfTimetableOfClasses/MInstitute.cs
> +                    throw new Exception("Некорректная длина поля");
> А их разве нельзя внести под одну интерпретацию?

чисто техническим можно, но пользователи глупенькие, им нужно конкретизировать. Вы боретесь не с сообщениями, а с сложным методом. Вы изучили способы устранения этой проблемы?

2021-06-15 14:52 UTC, DreAMer2308 commented
Поправил.

2021-06-16 12:39 UTC, DreAMer2308 commented
Поправил.

2021-06-17 06:08 UTC, YuriSilenok approved these changes

2021-06-17 06:08 UTC, merged