Устранен баг программы при удалении дисциплины в пустой таблице "дисциплина"
Students-of-the-city-of-Kostroma/Student-timetable pull request #156
Opened 2019-03-11 13:02 UTC by Proffet78

#142

2019-03-13 03:47 UTC, YuriSilenok commented
Вы проблему не решили, а проигнорировали.
Отлов исключений это всегда трудоемкая операция для ПО.

2019-03-20 19:38 UTC, YuriSilenok requested changes
Вы проблему не решили, а проигнорировали.
Отлов исключений это всегда трудоемкая операция для ПО.
Устраните причину бага.

2019-03-26 09:02 UTC, Proffet78 commented
Здравствуйте!

Устранил причину бага!

Спасибо!

2019-03-26 19:35 UTC, merged

2019-03-26 19:57 UTC, Proffet78 commented
Здравствуйте! 
Я тут, что-то сделал, не могли бы вы мне помочь вернуть все обратно?
Спасибо

2019-03-26 20:11 UTC, Proffet78 commented
Здравствуйте! 
Моя ошибка в том,что я сам объединил и закрыл ветку! Хотя не имел на это право.
Что мне теперь делать?
Спасибо

2019-04-03 14:19 UTC, YuriSilenok commented
После того как Вы откатите изменения в ветке тестинг для этой ветки нужно будет выполнить команду rebase относительно ветки Testing