Форма институты создана
Students-of-the-city-of-Kostroma/Student-timetable pull request #158
Opened 2019-03-17 15:45 UTC by MaximTrapeznikov

[#137](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/137)

2019-04-01 13:17 UTC, YuriSilenok submitted a review, later dismissed

2019-04-01 13:18 UTC, YuriSilenok commented
@MaximTrapeznikov По коду замечаний нет.
Вам необходимо решить мержконфликт.

2019-05-07 15:37 UTC, MaximTrapeznikov commented
Здраствуйте, Юрий Викторович.  

Столкнулся с такой ситуацией, решил доделать 3 лабораторную работу, там был не разрешен мержконфликт. Сейчас захожу, он  разрешен   и закрыт, но работа не защитана.

Что делать в данной ситуации?

Спасибо.

2019-05-07 15:45 UTC, YuriSilenok commented
Переткрыл запрос на слияние.

2019-05-07 15:49 UTC, YuriSilenok commented
Добавил служебный файл

2019-05-07 15:51 UTC, YuriSilenok approved these changes

2019-05-07 15:57 UTC, YuriSilenok commented
Обратите внимание что проект не компилируется.

2019-05-07 15:57 UTC, YuriSilenok requested changes
Обратите внимание что проект не компилируется.

2019-05-07 16:14 UTC, YuriSilenok commented
Я бы ожидал что Вы сначало испрвите ошибки недающие компилировать проект, а после решать мержконфликт.

2019-05-07 16:16 UTC, YuriSilenok commented
Ваша ветка содержит синтаксические ошибки. Не забудте получить изменения командой git pull

2019-05-15 03:09 UTC, YuriSilenok commented
Вы задачу планируете доделывать?

2019-05-19 10:04 UTC, MaximTrapeznikov commented
Здравствуйте, Юрий Викторович.
Я решил мержконфлик раньше чем исправил синтаксические ошибки 
Когда решал мержконфликт я немного накосячил.
Нашел свою ошибку в TimetableOfClasses/TimetableOfClasses.csproj 
"Скриншот куска кода "
![image](https://user-images.githubusercontent.com/46522172/57980644-964d9400-7a36-11e9-9edc-fe7aaf4d7135.png)
Помогите пожалуйста. 
Как мне это всё исправить?
Спасибо.

2019-05-19 10:22 UTC, YuriSilenok commented
Вам нуднр исправить и залить коммит, это должно отобразиться в запросе и пройти автотесты

2019-06-19 17:13 UTC, YuriSilenok commented
закрыто по не активности

2019-06-19 17:13 UTC, closed without merging