Создана форма Направления подготовки
Students-of-the-city-of-Kostroma/Student-timetable pull request #188
Opened 2019-03-25 20:16 UTC by AlexandraKv

#178

2019-03-26 07:00 UTC, YuriSilenok requested changes
у Вас не настроены отступы в VS.
Пожалуйста, найдите соответствующее письмо, выполните настройку и замените все отступы.

2019-03-26 07:44 UTC, AlexandraKv commented
Здравствуйте, я изменила настройки табуляции в VS, но на Githab ничего не
изменилось.

Спасибо.
Квашонкина Александра.
17-ИДбо-3а.

вт, 26 мар. 2019 г. в 10:00, Юрий Силенок <notifications@github.com>:

> *@YuriSilenok* requested changes on this pull request.
>
> у Вас не настроены отступы в VS.
> Пожалуйста, найдите соответствующее письмо, выполните настройку и замените
> все отступы.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/188#pullrequestreview-218717147>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AtbNgmJcPMoWhnPPlQsGbszZH99pU-myks5vacWFgaJpZM4cJBlu>
> .
>

2019-03-28 12:02 UTC, YuriSilenok requested changes
1. Отступы
2. Добавить вызов формы в меню

2019-04-19 10:58 UTC, YuriSilenok submitted a review, later dismissed

2019-04-25 12:07 UTC, YuriSilenok submitted a review, later dismissed

2019-04-25 12:25 UTC, YuriSilenok approved these changes

2019-04-25 12:25 UTC, merged