Update README.md
Students-of-the-city-of-Kostroma/Student-timetable pull request #295
Opened 2019-04-08 12:02 UTC by YuriSilenok

2019-04-10 06:44 UTC, Parallusion reviewed
Ok

2019-04-10 06:46 UTC, Parallusion requested changes
It's not ok.

2019-04-10 06:46 UTC, Parallusion reviewed
Maybe ok.

2019-04-10 06:47 UTC, Parallusion approved these changes
MIsha Bobylev.

2019-04-10 06:48 UTC, Parallusion requested changes
Zhiba.

2019-04-10 06:52 UTC, closed without merging

2020-06-26 05:11 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-26 05:11 UTC, YuriSilenok commented
Пожалуйста, добавьте метки в вашу задачу

2020-06-27 05:10 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-27 05:10 UTC, YuriSilenok commented
Пожалуйста, добавьте метки в вашу задачу

2020-06-28 05:10 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-28 05:10 UTC, YuriSilenok commented
Пожалуйста, добавьте метки в вашу задачу

2020-06-29 05:10 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-29 05:10 UTC, YuriSilenok commented
Пожалуйста, добавьте метки в вашу задачу

2020-06-30 05:09 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-30 05:09 UTC, YuriSilenok commented
Пожалуйста, добавьте метки в вашу задачу

2020-07-01 05:10 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-01 05:10 UTC, YuriSilenok commented
Пожалуйста, добавьте метки в вашу задачу

2020-07-02 05:09 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-02 05:09 UTC, YuriSilenok commented
Пожалуйста, добавьте метки в вашу задачу

2020-07-03 05:08 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-03 05:08 UTC, YuriSilenok commented
Пожалуйста, добавьте метки в вашу задачу

2020-07-03 13:20 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-03 13:20 UTC, YuriSilenok commented
Пожалуйста, добавьте метки в вашу задачу

2020-07-04 05:06 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-04 05:06 UTC, YuriSilenok commented
Пожалуйста, добавьте метки в вашу задачу

2020-07-05 05:06 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-05 05:06 UTC, YuriSilenok commented
Пожалуйста, добавьте метки в вашу задачу

2020-07-06 05:06 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 05:06 UTC, YuriSilenok commented
Пожалуйста, добавьте метки в вашу задачу