Исправлен баг открытия одновременно двух форм Ученые степени
Students-of-the-city-of-Kostroma/Student-timetable pull request #489
Opened 2019-04-25 22:14 UTC by FvckNeighbors

#301

2019-04-26 09:06 UTC, YuriSilenok commented
На кого задача назвначена? кто за нее ответсвенный?

2019-04-26 09:14 UTC, FvckNeighbors commented
Я ответственный за задачу. Повесил ее на себя

2019-04-26 11:37 UTC, PopovMilan approved these changes

2019-04-26 11:46 UTC, PopovMilan requested changes
Баг устранен

2019-04-26 11:46 UTC, PopovMilan approved these changes
Баг устранен

2019-04-26 11:54 UTC, merged

2019-04-26 17:00 UTC, YuriSilenok commented
Почему вы мержите в ветку первого спринта?

2020-06-26 05:09 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-06-27 05:09 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-06-28 05:08 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-06-29 05:09 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-06-30 05:08 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-07-01 05:09 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-07-02 05:08 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-07-03 05:07 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-07-03 13:19 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-07-04 05:05 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-07-05 05:05 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-07-06 05:05 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-07-06 13:05 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-07-06 14:25 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-07-06 15:29 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-07-06 15:51 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-07-07 05:05 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-07-08 05:05 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-07-09 05:05 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-07-10 05:05 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-07-11 05:05 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу

2020-07-11 06:19 UTC, YuriSilenok commented
Пожалуйста, добавьте ответсвенного на эту задачу