Задача реализована
Students-of-the-city-of-Kostroma/Student-timetable pull request #64
Opened 2019-02-18 15:46 UTC by Chippa99fm

Метод реализован

2019-02-18 19:00 UTC, YuriSilenok commented on LibOfTimetableOfClasses/CDiscipline.cs
> +                            table.Rows[i]["ID"] = mDiscipline.Id;
Есть ли смысл в перезаписывании ID если он заведомо совпадает?

2019-02-18 19:02 UTC, Chippa99fm commented on LibOfTimetableOfClasses/CDiscipline.cs
> +                            table.Rows[i]["ID"] = mDiscipline.Id;
Здравстуйте.

Сейчас исправлю!

2019-02-19 08:08 UTC, YuriSilenok requested changes
Здравствуйте.
Вы выполнили автоматические тесты?
Спасибо.

2019-02-19 11:25 UTC, Chippa99fm commented
> Здравствуйте.
> Вы выполнили автоматические тесты?
> Спасибо.

 Здравствуйте.
Да, я выполнил автоматические тесты и они были успешно пройдены.
Спасибо.

2019-02-19 11:25 UTC, merged

2019-02-19 11:40 UTC, YuriSilenok commented
Что Вы сделали 15 минут назад?

2019-02-19 11:44 UTC, Chippa99fm commented
Здравстуйте.

Я случайно нажал на какую-то кнопочку, т.к. увидел от вас запрос, который
будет изображён в прикреплённом файле.

Спасибо


вт, 19 февр. 2019 г. в 14:40, Юрий Силенок <notifications@github.com>:

> Что Вы сделали 15 минут назад?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/64#issuecomment-465097054>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AtIM6d0ukFNzXDWEKj_2LgY-dgxlESCGks5vO-KmgaJpZM4bBJJN>
> .
>

2019-02-19 11:45 UTC, YuriSilenok commented
Я никакого файла не увижу, так как вы ответили письмом на гитхаб, а он не принимает прикрепленные фалйы, только текст.
Напишите в комменатрий на гитхабе.

2019-02-19 11:52 UTC, Chippa99fm commented
> Я никакого файла не увижу, так как вы ответили письмом на гитхаб, а он не принимает прикрепленные фалйы, только текст.
> Напишите в комменатрий на гитхабе.

Здравствуйте.

Вот этот файл из прошлого комментария.

И как я понял только что, 15 минут назад я случайно объеденил свою ветку task-36 и ветку Testing.

Это очень плохо?
![default](https://user-images.githubusercontent.com/47320297/53013033-be3c5400-3455-11e9-9678-f95464c75a6a.PNG)

2019-02-19 11:56 UTC, YuriSilenok commented
Вам повезло, туда не попало ничего того что могло поломать что-то у других.
Будьте внимательнее. 
Пойду закрою задачу.

2019-02-19 11:56 UTC, YuriSilenok commented
А нет, задачу не закрыть, там еще двоечник висит. 
В комментариях отпишу к задаче.

2019-02-19 11:58 UTC, Chippa99fm commented
> Вам повезло, туда не попало ничего того что могло поломать что-то у других.
> Будьте внимательнее.
> Пойду закрою задачу.

Здравствуйте.

Впредь буду внимательней смотреть, куда нажимаю мышкой.

Если задачу не закрыть ,это значит, что моя лабороторная не будет засчитана ?

Спасибо.