Method Insert
Students-of-the-city-of-Kostroma/Student-timetable pull request #65
Opened 2019-02-18 15:46 UTC by SamuraSwordS

Метод реализован.

2019-02-18 18:44 UTC, YuriSilenok requested changes
Здравствуйте.
Вас не смутил тот факт, что есть синтаксические ошибки?

2019-02-18 19:17 UTC, SamuraSwordS commented
> Здравствуйте.
> Вас не смутил тот факт, что есть синтаксические ошибки?

Здравствуйте.
Предупреждения исправлены.

2019-02-19 07:54 UTC, YuriSilenok requested changes
Здравствуйте.
Вообще я вопрос задавал, а Вы приступили к действиям.
Хорошо что не сделали лишнего. Вы исправили второй недочет на который я хотел обратить внимание позже.
Задам вопрос еще раз.
Вы автоматические тесты запускали?
Спасибо.

2019-02-19 08:45 UTC, SamuraSwordS commented
Здравствуйте. 
Да, тесты прошли успешно.

2019-02-19 09:52 UTC, YuriSilenok commented
У меня есть сомнения на этот счет.
Пожалуйста, больше не перевешивайте запрос на меня.
Пожалуйста, предоставьте скрин на котором было бы видно все окно VS.
Проверьте что бы у вас отображалась информация в следующих блоках.
![image](https://user-images.githubusercontent.com/14871471/53005797-02732880-3445-11e9-90e2-8b433ea6dcff.png)

2019-02-19 11:18 UTC, SamuraSwordS commented
Прошу, всё сделал, как вы и просили.
![image](https://user-images.githubusercontent.com/47320646/53011272-158bf580-3451-11e9-9527-51fcc794896b.png)

2019-02-19 11:42 UTC, SamuraSwordS commented
Заметил недочёт , который я допустил, который видимо вы имели в виду

2019-02-19 11:46 UTC, SamuraSwordS commented
Исправлено.
Повторный тест:
![image](https://user-images.githubusercontent.com/47320646/53012829-2ccce200-3455-11e9-892c-adad86602d0c.png)

2019-02-19 11:49 UTC, YuriSilenok commented
А покажите мне свойства библиотеки
![image](https://user-images.githubusercontent.com/14871471/53012988-977e1d80-3455-11e9-9a72-804619237d66.png)

2019-02-19 11:53 UTC, SamuraSwordS commented
Пожалуйста
![image](https://user-images.githubusercontent.com/47320646/53013128-065b7680-3456-11e9-9a95-5038c618365a.png)

2019-02-19 12:04 UTC, YuriSilenok commented
Очень странно.
У меня ругается на синтаксические ошибки.
Мы когда-то вводили фичи языка, но потом от них отказались, и на старых фрймворках они не должны работать. Есть ли у Вас возможность предоставить мне удаленный доступ. Хочу сам пару минут посмотреть каким образом у вас это работает. Предпочтительнее TeamViewer.
![image](https://user-images.githubusercontent.com/14871471/53013699-774f5e00-3457-11e9-8df0-bfed2b095b9a.png)

2019-02-19 12:11 UTC, SamuraSwordS commented
Я, конечно , могу установить TeamViewer.
Но никаких манипуляций в данном месте, что скриншоте , я не проводил.

2019-02-19 12:13 UTC, YuriSilenok commented
TeamViewer можно запускать без установки
Дела в недоверии, а в непонимании и поиске истины.

2019-02-19 12:16 UTC, SamuraSwordS commented
Id и пароль написать сюда , в комментарий ?

2019-02-19 12:18 UTC, YuriSilenok commented
Добрый день.

На почту.
Не нужно светить эту информацию, даже если она временная.

Спасибо

*Yuri Silenok* | QA Analyst, Consolidated FT team | *Exactpro*


BUILD SOFTWARE TO TEST SOFTWARE


*D*&*M:* +7 953 665 79 34 | *W: *exactpro.com
*Follow us:* LinkedIn
<https://www.linkedin.com/company/exactpro-systems-llc/>| Twitter
<https://twitter.com/exactpro>| Facebook
<https://www.facebook.com/exactpro/>| Instagram
<https://instagram.com/exactpro>| Youtube
<https://www.youtube.com/channel/UCFF2_9hAmg4YwEBohNYRsdg>

Exactpro приглашает на практику студентов ИТ-специальностей по направлениям
тестирование, разработка программного обеспечения, системное
администрирование.

Во время практики вы узнаете, как мы тестируем программное обеспечение
мировых финансовых организаций и разрабатываем инструменты для
тестирования, поработаете в команде профессионалов и получите возможность
поучаствовать в реальных проектных задачах.

Мы ждем ваше резюме на cv@exactpro.com с пометкой "прохождение практики" и
указанием интересующего вас направления.
Уточнить мое расписание Вы можете в этом
<https://calendar.google.com/calendar?cid=eXVyaS5zaWxlbm9rQGdtYWlsLmNvbQ>
календаре


вт, 19 февр. 2019 г. в 15:16, Сергей Дремченко <notifications@github.com>:

> Id и пароль написать сюда , в комментарий ?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/65#issuecomment-465106846>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AOLrr4V4lSnKwxTPUP8tQiQwmM5qTj1dks5vO-skgaJpZM4bBJJu>
> .
>

2019-02-19 12:40 UTC, YuriSilenok commented
Я понял в чем дело.
C# поддерживающий такой синтаксис поставляется со студией, а не с фреймворком, я повысил требования к проекту, а сам не обновился.

2019-02-19 12:41 UTC, SamuraSwordS commented
Моя работа окончена ?

2019-02-19 12:54 UTC, YuriSilenok approved these changes
Да, конечно.
Я отлучался, сейчас закончу с Вами.

2019-02-19 12:54 UTC, merged