Добавил описания
Students-of-the-city-of-Kostroma/Student-timetable pull request #793
Opened 2019-05-21 14:55 UTC by Chippa99fm

#763

2019-05-21 14:57 UTC, YuriSilenok commented
Учтите что именно названия запросов на слияние пойдет в список измнений на релиз. Создавайте заголовки не менее подробные чем для задач.

2019-05-21 14:58 UTC, YuriSilenok commented on LibOfTimetableOfClasses/CUniversity.cs
> +
Для публичного конструктора нет описания

2019-05-21 14:59 UTC, YuriSilenok reviewed
Не все публичные конструкции имеют комментарии

2019-05-21 14:59 UTC, YuriSilenok commented on LibOfTimetableOfClasses/CUniversity.cs
>  {
Публичный класс не имеет описания

2019-05-21 15:01 UTC, YuriSilenok commented
Почему у пользователя сделавший этот коммит не настроен user.name и user.email ?

2019-05-21 15:02 UTC, YuriSilenok requested changes
Почему у пользователя сделавший этот коммит не настроен user.name и user.email ?

2019-05-21 16:31 UTC, YuriSilenok submitted a review, later dismissed
/// <summary>
		/// Метод удаления 
		/// </summary>
		/// <param name="model"></param>
		/// <returns></returns>


По мне это отписка какая-то.
- Должно быть что-то типа, удаляет из таблицы экземпляр если совпадает атрибут такой-то
- где описание входноего параметра `/// <param name="model"> тут должно быть описание</param>`

		/// <summary>
		/// Ввод ИНН
		/// </summary>

В свойста вы не вводите а читаете или записываете, а вводите в графическом интерфейсе в тектовые поля. И почему тогда только ввод? получить значение из свойства нельзя?

2019-05-21 16:46 UTC, YuriSilenok commented
Здравсвуйте @Chippa99fm 

Знаете, хотелось бы искре верить в то, что при поиске информации Вам не встретятся ответы которые содеражат столько же полезной информации.
@map82top Я больше не буду смотреть на этот запрос, оставляю проверку на Вас.

Спасибо,
Юрий

2019-05-23 19:16 UTC, map82top approved these changes

2019-05-23 19:17 UTC, merged