Создал справочник "Учебная неделя"
Students-of-the-city-of-Kostroma/Student-timetable pull request #823
Opened 2019-05-22 12:42 UTC by DemiKor

…/issues/798
Создал:
1.  модель учебной недели
1.  контроллер для учебной недели
1.  представление учебной недели на котором располагаются:
   1. Таблица со столбцами:
      1. Номер
      1. Наименование
   1. Кнопки:
      1. Удалить
      1. Изменить
      1. Добавить

2019-05-29 12:38 UTC, YuriSilenok requested changes
- в некоторых файлах произошла замена табуляции на пробелы. У Вас настроены отступы? жду исправлдений.
- вам предстоит еще решить мержконфликт, учтите что файл и класс Controllers должен быть переименован в RefData
- по мимо этого было сделано больше чем просилось в таске.

2019-05-29 17:42 UTC, DemiKor commented
*табуляция была исправлена
*можно поподробнее о решении мержконфликта?

2019-05-29 17:50 UTC, DemiKor commented
* Исправлена табуляция
* Можете рассказать подробнее о решении мержконфликта?

2019-06-02 11:34 UTC, YuriSilenok commented
я частично помог решить конфликт. Остался небольшой конфликт.

2019-06-02 11:35 UTC, YuriSilenok commented
Сбои в автотестах, сейчас это нормально.

2019-06-02 11:37 UTC, YuriSilenok requested changes
Необходимо решить конфликт

2019-06-04 15:21 UTC, YuriSilenok requested changes
Обратите на замечания

2019-06-04 15:21 UTC, YuriSilenok commented on LibOfTimetableOfClasses/Controllers.cs
> +	public class Controllers
Почему появился этот класс Controllers?

2019-06-04 15:21 UTC, YuriSilenok commented on LibOfTimetableOfClasses/RefData.cs
> +
Кажется вы решали конфликты не очень задумываясь о необходимости обоих вариантов.

2019-06-04 15:21 UTC, YuriSilenok commented on TimetableOfClasses/Program.cs
> +            Application.Run(new Start());
Почему здесь пробелы появились?

2019-06-04 15:21 UTC, YuriSilenok commented on TimetableOfClasses/RefData.cs
> +		public static CTeacher CTeacher = new CTeacher();
Почему вы решили что этот файл должен существовать?

2019-06-06 22:19 UTC, DemiKor commented on LibOfTimetableOfClasses/Controllers.cs
> +	public class Controllers
Не знаю, с этим классом много багов в гите у меня было, он не удалялся, не пушился и т.п.

2019-06-06 22:23 UTC, DemiKor commented on LibOfTimetableOfClasses/RefData.cs
> +
Не понял сути комментария
Различия в одной добавленной строке по сути, разве нет?

2019-06-06 22:23 UTC, DemiKor commented on TimetableOfClasses/Program.cs
> +            Application.Run(new Start());
Возможно случайно таб нажал и не заметил

2019-06-06 22:29 UTC, DemiKor commented on TimetableOfClasses/RefData.cs
> +		public static CTeacher CTeacher = new CTeacher();
На моей памяти этот файл существовал до того, как я стянул в новую ветку проект
У себя я его пару раз переименовывал только

2019-06-07 07:24 UTC, YuriSilenok commented on TimetableOfClasses/RefData.cs
> +		public static CTeacher CTeacher = new CTeacher();
Есть общие части проекта, которые изменяются не только Вами.
Если что-то было изменено не Вами, это не значит что нужно вернуть как было у Вас.
Этот файл в основном проекте уже не должен существовать.
[вторым](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/823/commits/5283288cbb8b225f40b7bdc16a1b0019de52b34e#diff-1cbaac6f9f81a1eccf7a9d5a9b13344d) коммитом Вы добавили файл RefData в основной проект. Могу предположить что вы скопировали проект, возмно что бы устранить какие-то сбои.
Пожалуйста, сделайте правильно.

2019-06-07 07:25 UTC, YuriSilenok commented on TimetableOfClasses/Program.cs
> +            Application.Run(new Start());
восстановите.

2019-06-07 07:27 UTC, YuriSilenok commented on LibOfTimetableOfClasses/RefData.cs
> +
а как на счет 4 удаленных строк?
либо вы втсавили файлы из какого-то старого проекта или у вас не правильно настроены отступы. Склоняюсь к первому варианту.

2019-06-07 07:31 UTC, YuriSilenok commented on LibOfTimetableOfClasses/Controllers.cs
> +	public class Controllers
багов - путаете теримины, скорее вы говорите об ошибках.
он не удалялся, не пушился и т.п. - какова причина, к кому Вы обратились за помощью?

2019-06-09 15:58 UTC, DemiKor commented on LibOfTimetableOfClasses/RefData.cs
> +
2 строки из 4 были просто переписаны
а еще 2 заглушки не известно для чего вообще созданы

2019-06-09 16:02 UTC, DemiKor commented on LibOfTimetableOfClasses/Controllers.cs
> +	public class Controllers
Удалил файл

2019-06-09 16:02 UTC, DemiKor commented on TimetableOfClasses/RefData.cs
> +		public static CTeacher CTeacher = new CTeacher();
Удалил файл

2019-06-09 16:04 UTC, DemiKor commented on TimetableOfClasses/Program.cs
> +            Application.Run(new Start());
исправил

2019-06-11 17:15 UTC, YuriSilenok commented on LibOfTimetableOfClasses/RefData.cs
> +
`#pragma warning disable` это не заглушка. Если есть сомнения о предназначении фрагменте кода, нужно спросить. Удалять в таких ситуациях, плохая идея.

25 и 26 строка все еще имеет в качестве отсупов пробелы.

2019-06-11 17:15 UTC, YuriSilenok commented on TimetableOfClasses/StudyWeek.Designer.cs
> +}
Этот файл содержит в качестве отступов пробелы.

2019-06-19 17:21 UTC, YuriSilenok commented
запрос закрыт по не активности

2019-06-19 17:21 UTC, closed without merging

2020-06-25 13:10 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-26 05:07 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-27 05:07 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-28 05:06 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-29 05:07 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-06-30 05:06 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-01 05:07 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-02 05:06 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-03 05:05 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-03 13:17 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-04 05:04 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-05 05:04 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 05:04 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 13:03 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 14:23 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 15:25 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 15:28 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-06 15:50 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-07 05:04 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-08 05:04 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-09 05:03 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-10 05:04 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-11 05:04 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче

2020-07-11 06:18 UTC, YuriSilenok commented
Пожалуйста, добавьте веху к этой задаче