Создал форму Добавить дисциплину
Students-of-the-city-of-Kostroma/Student-timetable pull request #87
Opened 2019-02-20 22:12 UTC by Rogachev99

Задача #77 
Добавленная ветка: task-77

2019-02-21 10:51 UTC, YuriSilenok requested changes

2019-02-21 10:51 UTC, YuriSilenok commented on TimetableOfClasses/Discipline.Designer.cs
> +			this.DG_Disc = new System.Windows.Forms.DataGridView();
Этот файл был изменен так как у Вас в качестве отступов настроена табуляция.
Из-за этого этот файл сильно модифицировался. Вам необходимо либо заменить табуляцию на пробелы в этом файле, либо из ветки Testing скачать этот файл и аккуратно внести исправления, либо изменить настройки отступа. Сейчас идет голосование, которое будет завершено на лекции и объявлены результаты. По результатам которого я попрошу всех настроить VS. На данный момент результаты [такие](https://docs.google.com/forms/d/1cAezDFcZ4kQB7IBKY1VJKu-KnPkpBI_MjXQkX7NPDMg/edit#responses).

2019-02-21 11:28 UTC, Rogachev99 commented on TimetableOfClasses/Discipline.Designer.cs
> +			this.DG_Disc = new System.Windows.Forms.DataGridView();
В локальной ветке исправил. Как мне лучше внести изменения: создать новый коммит и залить в удаленную ветку, или исправить прошлый коммит и так же залить в свою ветку?

2019-02-21 12:26 UTC, YuriSilenok commented on TimetableOfClasses/Discipline.Designer.cs
> +			this.DG_Disc = new System.Windows.Forms.DataGridView();
Вы делаете новый коммит и заливаете изменения на удалённый репозиторий, а гитхаб покажет разницу между ветками.

2019-02-22 20:40 UTC, YuriSilenok commented
Смогу проверить только завтра

2019-02-23 08:59 UTC, YuriSilenok approved these changes
Замечаний нет.

2019-02-23 08:59 UTC, merged