Исправлены сбои в автоматических тестах
Students-of-the-city-of-Kostroma/Student-timetable pull request #913
Opened 2019-05-25 22:22 UTC by MaximTrapeznikov

Список тестов
Task_420_3
Task_420_4
Task_420_5
Task_420_6
Task_421_1
Task_421_2
Task_421_3
Task_421_4
Task_485_1
Task_485_2
[task-867](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/867)

2019-05-26 06:42 UTC, YuriSilenok requested changes
Здравствуйте.
- Для тестирования необходимо использовать существующие источники данных, то есть класс Controllers и либо использовать DataSet или использовать ссылки на экземпляры контроллеров. Иначе вы теряете реляционные связи между таблицами.
- Название переменных должны быть более осмысленны. y это недопустимое значение для переменной в этом контексте.

Спасибо

2019-05-26 15:00 UTC, MaximTrapeznikov commented
Здраствуйте, @YuriSilenok .

Можно узнать по подробнее как это сделать?

Полскажите пожалуйста, чем вызвано данное исключение?
![image](https://user-images.githubusercontent.com/46522172/58383480-0da79880-7fe0-11e9-8d84-31ad93a00487.png)


Спасибо.

2019-05-30 13:29 UTC, YuriSilenok commented
Обратите на класс Controllers. В нем есть все источники данных. Я упоминал в прошлом сообщении о том как правильно использовать источники данных.

2019-06-05 06:34 UTC, YuriSilenok commented
задача закрыта по не активности

2019-06-05 06:34 UTC, closed without merging