Исправлены сбои в автоматических тестах
Students-of-the-city-of-Kostroma/Student-timetable pull request #916
Opened 2019-05-25 22:50 UTC by MaximTrapeznikov

Список тестов

Task_335_4
Task_335_5
Task_337_1
Task_337_2
Task_337_3
Task_337_4
Task_339_1
Task_339_2
Task_420_1
Task_420_2
[task-866](https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/issues/866)

2019-05-26 06:38 UTC, YuriSilenok requested changes
Здравствуйте.
- Для тестирования необходимо использовать существующие источники данных, то есть класс Controllers и либо использовать DataSet или использовать ссылки на экземпляры контроллеров. Иначе вы теряете реляционные связи между таблицами.
- Название переменных должны быть более осмысленны. y это недопустимое значение для переменной в этом контексте.

Спасибо

2019-05-28 13:14 UTC, MaximTrapeznikov commented
Здраствуйте, @YuriSilenok .

Можно узнать по подробнее как это сделать?

Полскажите пожалуйста, чем вызвано данное исключение?
image

Спасибо.

2019-05-30 17:08 UTC, YuriSilenok commented
https://github.com/Students-of-the-city-of-Kostroma/Student-timetable/pull/913#issuecomment-497329498

2019-06-05 06:34 UTC, YuriSilenok commented
задача закрыта по не активности

2019-06-05 06:34 UTC, closed without merging