Создал форму "Параметры". Вкладка День.
Students-of-the-city-of-Kostroma/Student-timetable pull request #985
Opened 2019-06-01 13:22 UTC by DenisSavelev

#517

2019-06-02 11:40 UTC, YuriSilenok requested changes
Поясните что было подключено к проекту?

2019-06-02 11:40 UTC, YuriSilenok commented on TimetableOfClasses/TimetableOfClasses.csproj
>      <Reference Include="System" />
Зачем это подключено?

2019-06-02 11:40 UTC, YuriSilenok commented on TimetableOfClasses/TimetableOfClasses.csproj
>      <Reference Include="System.Xml.Linq" />
Зачем это подключено?

2019-06-02 11:40 UTC, YuriSilenok commented on TimetableOfClasses/TimetableOfClasses.csproj
> +    <Reference Include="WindowsFormsIntegration" />
Зачем это подключено?

2019-06-02 12:29 UTC, DenisSavelev commented on TimetableOfClasses/TimetableOfClasses.csproj
>      <Reference Include="System" />
Не знаю, возможно автоматически подключилось при создание элементов на форме

2019-06-02 12:54 UTC, DenisSavelev commented on TimetableOfClasses/TimetableOfClasses.csproj
>      <Reference Include="System" />
Возможно это связано с обновлениями пакетов, так как выскочила вот эта ошибка
![image](https://user-images.githubusercontent.com/47320542/58761588-bb6df680-854e-11e9-9f65-387c3a545790.png)

2019-06-02 12:57 UTC, DenisSavelev commented on TimetableOfClasses/TimetableOfClasses.csproj
>      <Reference Include="System" />
Возможно связано с обновлениями пакетов, так как при работе возникла вот эта ошибка 
![image](https://user-images.githubusercontent.com/47320542/58761615-130c6200-854f-11e9-9241-1345c2f7ff5f.png)

2019-06-02 15:30 UTC, YuriSilenok commented
Попробуйте вручную вычистить все лишнее

2019-06-03 15:51 UTC, DenisSavelev commented
> Попробуйте вручную вычистить все лишнее

Вычистил

2019-06-04 19:05 UTC, YuriSilenok approved these changes
Конфликтов на данный момент нет, мержите.

2019-06-04 19:06 UTC, merged

2019-06-04 19:07 UTC, YuriSilenok commented
ветку удалить

2019-06-04 19:08 UTC, YuriSilenok commented
и задачу перевесить

2019-06-04 19:13 UTC, DenisSavelev commented
> и задачу перевесить

Перевесил